<?php

namespace raingarden\rg_content\rg_poems\rg_g_to_m;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Introduction to the Book of Stuff##/h2>##/li>
		##li class='poem line'>everything is stuff##/li>
		##li class='poem line'>a world of stuff##/li>
		##li class='poem line'>energy is stuff, intangibles are stuff##/li>
		##li class='poem line'>and every kind of stuff has its own stuff##/li>
		##li class='poem line'>in fact, some of it carries so much stuff##/li>
		##li class='poem line'>that it is iconic, more than stuff##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>let me give you an example:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when we use the word 'woman'##/li>
		##li class='poem line'>it comes with a load of stuff##/li>
		##li class='poem line'>girl##/li>
		##li class='poem line'>female##/li>
		##li class='poem line'>person##/li>
		##li class='poem line'>lady##/li>
		##li class='poem line'>mother##/li>
		##li class='poem line'>daughter##/li>
		##li class='poem line'>sister##/li>
		##li class='poem line'>bubby##/li>
		##li class='poem line'>auntie##/li>
		##li class='poem line'>and this is just the beginning.##/li>
		##li class='poem line'>breast##/li>
		##li class='poem line'>vagina##/li>
		##li class='poem line'>baby##/li>
		##li class='poem line'>are all words that are part of the stuff of 'woman'##/li>
		##li class='poem line'>you may argue (rightly) that a woman should not be thought a thing##/li>
		##li class='poem line'>and therefore you can argue (wrongly) that a woman is not stuff##/li>
		##li class='poem line'>a woman is stuff because humans are objects, objects are things,##/li>
		##li class='poem line'>things are stuff##/li>
		##li class='poem line'>people and stuff, you know.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why did i choose the word 'woman' for my exploration of stuff?##/li>
		##li class='poem line'>because i know that it's controversial##/li>
		##li class='poem line'>i could have used 'man'##/li>
		##li class='poem line'>boy##/li>
		##li class='poem line'>male##/li>
		##li class='poem line'>guy##/li>
		##li class='poem line'>father##/li>
		##li class='poem line'>brother##/li>
		##li class='poem line'>son##/li>
		##li class='poem line'>zaidy##/li>
		##li class='poem line'>uncle##/li>
		##li class='poem line'>testicle##/li>
		##li class='poem line'>penis##/li>
		##li class='poem line'>baby?##/li>
		##li class='poem line'>for some reason, me being a man##/li>
		##li class='poem line'>this choice of word as illustration##/li>
		##li class='poem line'>is not controversial##/li>
		##li class='poem line'>but conversations about women##/li>
		##li class='poem line'>when indulged in by men##/li>
		##li class='poem line'>are reckoned full of stuff##/li>
		##li class='poem line'>and that stuff,##/li>
		##li class='poem line'>sexism##/li>
		##li class='poem line'>chauvinism##/li>
		##li class='poem line'>domination##/li>
		##li class='poem line'>violence##/li>
		##li class='poem line'>victimization##/li>
		##li class='poem line'>has stuff of its own##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why should my use of these words##/li>
		##li class='poem line'>carry so much stuff?##/li>
		##li class='poem line'>because our brains are made of interesting stuff##/li>
		##li class='poem line'>we have a lot of neurons##/li>
		##li class='poem line'>axons##/li>
		##li class='poem line'>synapses##/li>
		##li class='poem line'>glials##/li>
		##li class='poem line'>blood vessels##/li>
		##li class='poem line'>in our cortexes, each with many##/li>
		##li class='poem line'>connections##/li>
		##li class='poem line'>linkages##/li>
		##li class='poem line'>neighbours##/li>
		##li class='poem line'>allies##/li>
		##li class='poem line'>we can put a lot of stuff together##/li>
		##li class='poem line'>with our collections of stuff##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what does all this have to do with me?##/li>
		##li class='poem line'>i have my stuff##/li>
		##li class='poem line'>problems##/li>
		##li class='poem line'>issues##/li>
		##li class='poem line'>demands##/li>
		##li class='poem line'>that all require my attention##/li>
		##li class='poem line'>in my poems, i deal with various##/li>
		##li class='poem line'>ideas##/li>
		##li class='poem line'>concepts##/li>
		##li class='poem line'>philosophies##/li>
		##li class='poem line'>issues##/li>
		##li class='poem line'>as well as##/li>
		##li class='poem line'>personal stuff##/li>
		##li class='poem line'>humourous stuff##/li>
		##li class='poem line'>love stuff##/li>
		##li class='poem line'>sexual stuff##/li>
		##li class='poem line'>therefore, in my poems##/li>
		##li class='poem line'>you will also be dealing with stuff##/li>
		##li class='poem line'>i hope my stuff has some correlation with your stuff##/li>
		##li class='poem line'>if it doesn't, my stuff will be boring##/li>
		##li class='poem line'>many apologies##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the following poems##/li>
		##li class='poem line'>all deal with stuff -##/li>
		##li class='poem line'>an incredible collection of stuff.##/li>
		##li class='poem line'>one item will lead to another item##/li>
		##li class='poem line'>i will call it wikipoetica##/li>
		##li class='poem line'>you may add your own stuff##/li>
		##li class='poem line'>to my stuff##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there are three ways (that i can think of)##/li>
		##li class='poem line'>to start this chain##/li>
		##li class='poem line'>me##/li>
		##li class='poem line'>mind##/li>
		##li class='poem line'>universe##/li>
		##li class='poem line'>why these three?##/li>
		##li class='poem line'>because each is one half of an essential dichotomy##/li>
		##li class='poem line'>that we all know and understand##/li>
		##li class='poem line'>me and mind are different facets##/li>
		##li class='poem line'>of the same thing##/li>
		##li class='poem line'>and each can be used as the opposite of universe##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the elimination round:##/li>
		##li class='poem line'>do i carry the universe in my mind?##/li>
		##li class='poem line'>does the universe contain my mind?##/li>
		##li class='poem line'>am i part of the universe?##/li>
		##li class='poem line'>is the universe part of me?##/li>
		##li class='poem line'>is my mind greater than me?##/li>
		##li class='poem line'>or do I contain my mind?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it's a tie!##/li>
		##li class='poem line'>the judges are unanimous##/li>
		##li class='poem line'>in not being able to decide##/li>
		##li class='poem line'>solipsism notwithstanding##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i will start my examination of stuff##/li>
		##li class='poem line'>in three places##/li>
		##li class='poem line'>the stuff of me##/li>
		##li class='poem line'>the stuff of mind##/li>
		##li class='poem line'>the stuff of the universe##/li>
		##li class='poem line'>i hope this is acceptable ##/li>
		##li class='poem line'>now please move along##/li>
		##li class='poem line'>there's lots of stuff to do##/li>
	##/ul>
##/article>";