<?php

namespace raingarden\rg_content\rg_poems\rg_g_to_m;
$the_html = "##article##article class='poem'>
    ##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Lattice##/h2>##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>  is a lattice##/li>
		##li class='poem line'>of molecules and light##/li>
		##li class='poem line'>it is a mathematical precision##/li>
		##li class='poem line'>  recordable##/li>
		##li class='poem line'>if we only had the means##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>  could be stored##/li>
		##li class='poem line'>in the memory##/li>
		##li class='poem line'>of a machine large enough##/li>
		##li class='poem line'>  to be a god ##/li>
		##li class='poem line'>    precipitating##/li>
		##li class='poem line'>  a Transition of State.##/li>
		##li class='poem line'>    triggering##/li>
		##li class='poem line'>  a nanoslide of water##/li>
		##li class='poem line'>  a picotaste of sugar##/li>
		##li class='poem line'>  a femtojerk pulse##/li>
		##li class='poem line'>      a candy-bowl of blood to spill its sweet liqueur##/li>
		##li class='poem line'>love is no easy matter##/li>
		##li class='poem line'>but from one mind to another##/li>
		##li class='poem line'>let me tell you##/li>
		##li class='poem line'>one who has known it can discern it's shimmering shape##/li>
		##li class='poem line'>with the shuttered eye of intuition##/li>
		##li class='poem line'>can know it's cuttlefish colour##/li>
		##li class='poem line'>with the grasping hand of inspiration##/li>
		##li class='poem line'>and can trace the angleless flow of its time ##/li>
		##li class='poem line'>with greedy imagination##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>      theoretically##/li>
		##li class='poem line'>  can be described##/li>
		##li class='poem line'>  investigated##/li>
		##li class='poem line'>     and saved for later##/li>
		##li class='poem line'>and as such##/li>
		##li class='poem line'>it exists apart from the head that holds it##/li>
		##li class='poem line'>if my head were detached##/li>
		##li class='poem line'>tomorrow, or Tuesday##/li>
		##li class='poem line'>my love would still exist##/li>
		##li class='poem line'>  (trees do make a sound)##/li>
		##li class='poem line'>rain would pass through it##/li>
		##li class='poem line'>and change nothing but everything##/li>
		##li class='poem line'>as it dripped down the collars##/li>
		##li class='poem line'>of the cursed##/li>
		##li class='poem line'>who swim in the river of fog##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>  could wander forever##/li>
		##li class='poem line'>being the account of all my earthly desire##/li>
		##li class='poem line'>  a balloon freed from the child's hand##/li>
		##li class='poem line'>where do those balloons go##/li>
		##li class='poem line'>when their helium brains have leaked out?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am not great##/li>
		##li class='poem line'>i have bits and pieces i would exchange for lottery prizes##/li>
		##li class='poem line'>some would have me worship me ##/li>
		##li class='poem line'>sit in the pews of my heart##/li>
		##li class='poem line'>exclaim accidentally on purpose##/li>
		##li class='poem line'>that all of me is perfect##/li>
		##li class='poem line'>i can't do that##/li>
		##li class='poem line'>i would expand to fill my world##/li>
		##li class='poem line'>the puffer fish deadly at the core##/li>
		##li class='poem line'>aren't i big enough already?##/li>
		##li class='poem line'>what have i been telling you all this time?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>on the milk-crate which serves as my altar##/li>
		##li class='poem line'>i have##/li>
		##li class='poem line'>a stone-chipped arrowhead of once upon a time##/li>
		##li class='poem line'>a flaming votive candle of exactly now##/li>
		##li class='poem line'>the smoke of my cow-dung fire##/li>
		##li class='poem line'>will stink up your hair for weeks##/li>
		##li class='poem line'>actually, that's incense, some people don't like it,##/li>
		##li class='poem line'>burning somewhere in a place we haven't reached yet##/li>
		##li class='poem line'>i like to drop loonies in the lap of a golden buddha##/li>
		##li class='poem line'>who sits under the dust of shed skin on my shelf##/li>
		##li class='poem line'>if i say the words just right, everything will be perfect:##/li>
		##li class='poem line'>My Love##/li>
		##li class='poem line'>has a great big hole in the middle##/li>
		##li class='poem line'>(it is NOT a donut)##/li>
		##li class='poem line'>that you could blow smoke rings through##/li>
		##li class='poem line'>plasmafied particles of vegetable love##/li>
		##li class='poem line'>have you ever seen two clouds come together?##/li>
		##li class='poem line'>stupid question, of course you have##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>if you wish to gaze upon the radiance of my shell##/li>
		##li class='poem line'>who am i to say no?##/li>
		##li class='poem line'>i've waited uncontrollable moments to strip myself bare##/li>
		##li class='poem line'>press my flat feet into the giving sand of mama beach##/li>
		##li class='poem line'>and if you must feast on the photons that reflect from my european flanks##/li>
		##li class='poem line'>i don't care, do what you will##/li>
		##li class='poem line'>photons belong to everybody##/li>
		##li class='poem line'>and my imperfect perfections are as much your property as mine##/li>
		##li class='poem line'>i know your eyes bother you##/li>
		##li class='poem line'>that you can feel the sand under your lids##/li>
		##li class='poem line'>and i would never do you the harm##/li>
		##li class='poem line'>of pretending to know what you are, or how you define##/li>
		##li class='poem line'>  your pain##/li>
		##li class='poem line'>but within the limits of my intuition##/li>
		##li class='poem line'>(yes, that intuition)##/li>
		##li class='poem line'>are the pillars of sympathy and understanding##/li>
		##li class='poem line'>that have bred me apart from the rest of you monkeys##/li>
		##li class='poem line'>when you tell me your pain##/li>
		##li class='poem line'>evil pokes my ass with dull claws##/li>
		##li class='poem line'>till i feel you being born##/li>
		##li class='poem line'>in the shadowed cave of my gut##/li>
		##li class='poem line'>and like the cat with the bassoon would tell you##/li>
		##li class='poem line'>we can all blow the low note##/li>
		##li class='poem line'>and hear each other sublime in the halls of the temple##/li>
		##li class='poem line'>	my temple is a beach at sunset##/li>
		##li class='poem line'>and i can hear your low note from a mile away##/li>
		##li class='poem line'>so if my beige skin must be yours for a second or two##/li>
		##li class='poem line'>don't pretend you weren't looking, you'll only hurt my feelings##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>(aside)##/li>
		##li class='poem line'>so to backtrack a minute##/li>
		##li class='poem line'>there are three evils that i know of##/li>
		##li class='poem line'>make that four, one of them comes in two flavours##/li>
		##li class='poem line'>the first is one we can eat for breakfast##/li>
		##li class='poem line'>the desire to make everything flat##/li>
		##li class='poem line'>the dark purpose of erosion, of perfect order##/li>
		##li class='poem line'>the next is the evil of an afternoon snack##/li>
		##li class='poem line'>to put a spoon in my smooth jell-o##/li>
		##li class='poem line'>and make the world lumpy, with no hint of sanity##/li>
		##li class='poem line'>the last is the twain##/li>
		##li class='poem line'>to love suffering, one's own or another's##/li>
		##li class='poem line'>to make suffering where there is none##/li>
		##li class='poem line'>the other last is the twain##/li>
		##li class='poem line'>to pass the meme of fun falsely:##/li>
		##li class='poem line'>i have been a prisoner of flesh and the weakness of ambition##/li>
		##li class='poem line'>(are you only just reading this now?)##/li>
		##li class='poem line'>i came late to the table, when i was starving already##/li>
		##li class='poem line'>never shop when you're hungry, you'll buy cupcakes and fish sticks##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is not in my power to remake you##/li>
		##li class='poem line'>perhaps i will never save your life##/li>
		##li class='poem line'>but i can describe it in such detail, can you?##/li>
		##li class='poem line'>i only say the things no one else wants to say##/li>
		##li class='poem line'>no thanks needed, just doing my job##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>(thus endeth the aside##/li>
		##li class='poem line'>the jester has poked holes in the bag covering my head##/li>
		##li class='poem line'>i must thank him one day)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>coda:##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>  is a bell whose ringing##/li>
		##li class='poem line'>  continues long##/li>
		##li class='poem line'>  after Quasimodo has left the building##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>  is the bank account##/li>
		##li class='poem line'>  that still gathers interest##/li>
		##li class='poem line'>  after the books have gone to dust##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>  is a perfume whose rosy scent##/li>
		##li class='poem line'>  hangs in the air##/li>
		##li class='poem line'>  after the lap-dance is over##/li>
		##li class='poem line'>	forgive me, i didn't mean to say that##/li>
	##/ul>
##/article>";