<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Compulsion##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about deconstruction##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>since this is a poem about deconstruction##/li>
		##li class='poem line'>it stands to reason that we must deconstruct something##/li>
		##li class='poem line'>this means we will take it apart##/li>
		##li class='poem line'>and consider the pieces##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>no, it doesn't##/li>
		##li class='poem line'>the act of deconstruction is not destruction##/li>
		##li class='poem line'>when we dismantle a poem, the poem remains##/li>
		##li class='poem line'>it is not destroyed##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>deconstruction means##/li>
		##li class='poem line'>we can dismantle from within the structure##/li>
		##li class='poem line'>and use the tools we are given##/li>
		##li class='poem line'>or we can dismantle from without the structure##/li>
		##li class='poem line'>and use our own tools##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>no, it doesn't##/li>
		##li class='poem line'>those are assumptions##/li>
		##li class='poem line'>we can dismantle a structure##/li>
		##li class='poem line'>with x-rays##/li>
		##li class='poem line'>leave it intact and respected##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now we have performed##/li>
		##li class='poem line'>a limited act of deconstruction##/li>
		##li class='poem line'>do not pretend you know what i'm talking about##/li>
		##li class='poem line'>i wrote the above##/li>
		##li class='poem line'>and i do not pretend i know what i'm talking about##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we call the above deconstruction##/li>
		##li class='poem line'>because it is the job of the deconstructionist##/li>
		##li class='poem line'>to dissect the metaphysics of a work or an idea##/li>
		##li class='poem line'>and thereby reveal the false binaries and assumptions##/li>
		##li class='poem line'>that lie at the heart of tradition##/li>
		##li class='poem line'>the false assumption here##/li>
		##li class='poem line'>is that we can ever state##/li>
		##li class='poem line'>in a poem##/li>
		##li class='poem line'>what the source of the poem is##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in fact, deconstruction has come to mean more than this##/li>
		##li class='poem line'>it means the dismantling of the psychology##/li>
		##li class='poem line'>surrounding a work or an idea##/li>
		##li class='poem line'>so that we can see what makes it tick##/li>
		##li class='poem line'>in the act of deconstruction##/li>
		##li class='poem line'>is an act of reconstruction##/li>
		##li class='poem line'>that is, if we care that anybody hears us talk about it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why should we do this?##/li>
		##li class='poem line'>the answer is surprisingly simple##/li>
		##li class='poem line'>because it is fun##/li>
		##li class='poem line'>it satisfies the endless curiousity##/li>
		##li class='poem line'>that sets us apart from the rest of the monkeys##/li>
		##li class='poem line'>and allows us to build poems##/li>
		##li class='poem line'>better##/li>
		##li class='poem line'>bigger##/li>
		##li class='poem line'>smarter##/li>
		##li class='poem line'>and with more permanence##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>poems take up no room##/li>
		##li class='poem line'>we can never have too many##/li>
		##li class='poem line'>but when we have as many as we do##/li>
		##li class='poem line'>we must decide which ones##/li>
		##li class='poem line'>are worth teaching to our little monkeys##/li>
		##li class='poem line'>to do this##/li>
		##li class='poem line'>we must discuss the poems##/li>
		##li class='poem line'>we must dismantle the intangible##/li>
		##li class='poem line'>see what makes it tick##/li>
		##li class='poem line'>decide whether it is a leaky roof##/li>
		##li class='poem line'>or a sound foundation##/li>
		##li class='poem line'>and pass it on or not##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem for you to deconstruct##/li>
		##li class='poem line'>and for you to decide the merits of##/li>
		##li class='poem line'>you will probably not pass it on to your little monkeys##/li>
		##li class='poem line'>but you will pass on the strings of the intangible##/li>
		##li class='poem line'>which it has poured through you##/li>
		##li class='poem line'>one way or another##/li>
		##li class='poem line'>good luck with that, monkey##/li>
	##/ul>
##/article>";