<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Daydream##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about poetry##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why is this a poem?##/li>
		##li class='poem line'>because poems about poetry should be poems##/li>
		##li class='poem line'>and not non-poems##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what is the poem about poetry?##/li>
		##li class='poem line'>this is##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>let there be a colon:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the author of the poem is i##/li>
		##li class='poem line'>(say hello, i)##/li>
		##li class='poem line'>HELLO!##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am writing a poem about i##/li>
		##li class='poem line'>this is established##/li>
		##li class='poem line'>when does the poem start?##/li>
		##li class='poem line'>it has, literally##/li>
		##li class='poem line'>it does now, here, figuratively##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what is a poem, that we should write a poem about it?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in the first place, it is and this is##/li>
		##li class='poem line'>a collection of words##/li>
		##li class='poem line'>in which form is of importance##/li>
		##li class='poem line'>must the words have substance?##/li>
		##li class='poem line'>this is debatable##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>ok, the debate is over##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the words must have meaning##/li>
		##li class='poem line'>if this, the poem about poems, has no words with meaning##/li>
		##li class='poem line'>it is boring##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>is it boring?##/li>
		##li class='poem line'>this is the question i ask myself##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what about poems that have no meaning?##/li>
		##li class='poem line'>they mean nothing, nothing having a meaning##/li>
		##li class='poem line'>by it's absence##/li>
		##li class='poem line'>they are boring##/li>
		##li class='poem line'>that is why the debate is over##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what if the meaning is obscure?##/li>
		##li class='poem line'>this is permitted##/li>
		##li class='poem line'>if there is no need of meaning##/li>
		##li class='poem line'>for it to be a poem that is boring##/li>
		##li class='poem line'>there is no objection to obscurity##/li>
		##li class='poem line'>for a poem which may or may not##/li>
		##li class='poem line'>be boring##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>perhaps the words are not boring##/li>
		##li class='poem line'>(the plumage of blue and yellow sparrows dancing their finality in swirling rythms of cake)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>is the section of the poem about poems that deals with obscurity##/li>
		##li class='poem line'>boring?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is not up to i (me)##/li>
		##li class='poem line'>the author of the poem which is a collection of words##/li>
		##li class='poem line'>about poetry in terms of boringness##/li>
		##li class='poem line'>is not qualified to judge##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that is a lie##/li>
		##li class='poem line'>i am always judging:##/li>
		##li class='poem line'>poetry with no meaning is boring##/li>
		##li class='poem line'>poetry with no contemplatable meaning is boring##/li>
		##li class='poem line'>what is not boring?##/li>
		##li class='poem line'>a poem with meaning may be boring##/li>
		##li class='poem line'>a poem with meaning may be not boring##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a poem about poetry may be boring, but you are still reading it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a poem which makes the complicated simple is interesting##/li>
		##li class='poem line'>a poem which makes the simple complicated is boring##/li>
		##li class='poem line'>this is the pronouncement of me, the author of the poem##/li>
		##li class='poem line'>the entire poem is an excuse to make this point##/li>
		##li class='poem line'>i apologize##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is the end of the poem##/li>
	##/ul>
##/article>";