<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Instruction Manual##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about how to read poems##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the way to read a poem##/li>
		##li class='poem line'>about deconstruction##/li>
		##li class='poem line'>is through an act of deconstruction##/li>
		##li class='poem line'>i have demonstrated this process##/li>
		##li class='poem line'>in other poems about deconstruction##/li>
		##li class='poem line'>now i will make my instructions##/li>
		##li class='poem line'>explicit##/li>
		##li class='poem line'>then you will know what you are ignoring##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>first##/li>
		##li class='poem line'>deconstruct the title##/li>
		##li class='poem line'>the title is obliquely referential##/li>
		##li class='poem line'>but is in most cases a joke##/li>
		##li class='poem line'>perhaps not a ha ha joke##/li>
		##li class='poem line'>but an Existential Humour Club type joke##/li>
		##li class='poem line'>(see appropriate poem)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>second##/li>
		##li class='poem line'>deconstruct the first line##/li>
		##li class='poem line'>it won't be hard - it only means what it says##/li>
		##li class='poem line'>but it is a warning/hint/signpost##/li>
		##li class='poem line'>it tells you what is ahead##/li>
		##li class='poem line'>that this poem will be part of a series##/li>
		##li class='poem line'>that will attempt to tie knots in your mind##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>third##/li>
		##li class='poem line'>deconstruct the second line##/li>
		##li class='poem line'>it won't be hard either##/li>
		##li class='poem line'>it is the headline to the poem##/li>
		##li class='poem line'>it telegraphs the meaning##/li>
		##li class='poem line'>it is the last clue you get##/li>
		##li class='poem line'>but be warned, it may be a head fake##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fourth##/li>
		##li class='poem line'>read the body of the poem##/li>
		##li class='poem line'>i can't help you much with this one now##/li>
		##li class='poem line'>some of the poems are serious##/li>
		##li class='poem line'>others are not##/li>
		##li class='poem line'>it's up to you to decide##/li>
		##li class='poem line'>each poem analyzes something to do##/li>
		##li class='poem line'>with the act of poetry##/li>
		##li class='poem line'>and what meaning i can derive from it##/li>
		##li class='poem line'>i am The Midnight Deconstructionist##/li>
		##li class='poem line'>and I am dismantling myself##/li>
		##li class='poem line'>for your benefit##/li>
		##li class='poem line'>and not merely for money and fame##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>you will notice##/li>
		##li class='poem line'>that there are themes and even phrases##/li>
		##li class='poem line'>that are common to two or more poems##/li>
		##li class='poem line'>other than the first line##/li>
		##li class='poem line'>this is deliberate##/li>
		##li class='poem line'>it serves to tie the poems together##/li>
		##li class='poem line'>the overlap is both deliberate##/li>
		##li class='poem line'>and a result of my (literally)##/li>
		##li class='poem line'>obsessive thinking##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>those are the general instructions##/li>
		##li class='poem line'>now a brief history##/li>
		##li class='poem line'>deconstruction##/li>
		##li class='poem line'>is the act of close reading##/li>
		##li class='poem line'>such that##/li>
		##li class='poem line'>the parts of the text##/li>
		##li class='poem line'>(we are talking about text, after all)##/li>
		##li class='poem line'>are individually dismantled##/li>
		##li class='poem line'>examined and interpreted##/li>
		##li class='poem line'>every drop of significance##/li>
		##li class='poem line'>every iota of meaning##/li>
		##li class='poem line'>is to be drawn from each word##/li>
		##li class='poem line'>the word is the basic block##/li>
		##li class='poem line'>there is nothing to be drawn from letters##/li>
		##li class='poem line'>letters are merely squiggles##/li>
		##li class='poem line'>with traditional intent##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>deconstruction was never really invented##/li>
		##li class='poem line'>it grew out of a form of criticism##/li>
		##li class='poem line'>called New Criticism##/li>
		##li class='poem line'>which was not new at all##/li>
		##li class='poem line'>and is even less so now##/li>
		##li class='poem line'>it purports to ignore##/li>
		##li class='poem line'>the circumstances of writing##/li>
		##li class='poem line'>and assign meaning only to the text##/li>
		##li class='poem line'>it often celebrates form over content##/li>
		##li class='poem line'>this is why deconstruction is superior -##/li>
		##li class='poem line'>because it emphasizes the whole enchilada##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is also related##/li>
		##li class='poem line'>to the scientific methods##/li>
		##li class='poem line'>of reduction##/li>
		##li class='poem line'>	the splitting of a problem into sub-problems##/li>
		##li class='poem line'>	to make understanding the whole easier##/li>
		##li class='poem line'>and emergence##/li>
		##li class='poem line'>	the interpretation of sub-problems##/li>
		##li class='poem line'>	to make conclusions about the whole##/li>
		##li class='poem line'>i use the terms loosely##/li>
		##li class='poem line'>as befits a poet##/li>
		##li class='poem line'>analyze that, and you have hooks in my eyes##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this series is complete as it is##/li>
		##li class='poem line'>but it is not finished##/li>
		##li class='poem line'>as long as i write##/li>
		##li class='poem line'>i will find new aspects of myself##/li>
		##li class='poem line'>and my writing##/li>
		##li class='poem line'>which deserve further analysis##/li>
		##li class='poem line'>it will never be finished##/li>
		##li class='poem line'>until i am finished##/li>
		##li class='poem line'>and the Ride of the Midnight Deconstructionist##/li>
		##li class='poem line'>ends with the horse's death##/li>
		##li class='poem line'>and even then##/li>
		##li class='poem line'>i may live on##/li>
		##li class='poem line'>in the flogging that will ensue##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>finally##/li>
		##li class='poem line'>i wish you to also notice##/li>
		##li class='poem line'>what i'm sure you've already noticed##/li>
		##li class='poem line'>that this is the final poem in the series##/li>
		##li class='poem line'>and it's too late now##/li>
		##li class='poem line'>this is mean of me##/li>
		##li class='poem line'>and representative of poetic analysis##/li>
		##li class='poem line'>it is a comment on the obscurantist nature##/li>
		##li class='poem line'>of poetry criticism##/li>
		##li class='poem line'>i have been no help at all##/li>
		##li class='poem line'>however##/li>
		##li class='poem line'>you have my permission##/li>
		##li class='poem line'>to go back to the beginning##/li>
		##li class='poem line'>and start over##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>let me give you a hand:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about you starting over##/li>
	##/ul>
##/article>";