<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Navel##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the Deconstructionist##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why does the deconstructionist write poetry when essays are usually best-read in prose?##/li>
		##li class='poem line'>why does he insist on the form least suited to success?##/li>
		##li class='poem line'>why does he refuse to adapt to the demands of his own limited market?##/li>
		##li class='poem line'>why does he speak of himself in the third person when everyone knows it's him?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>ok, i won't speak of myself in the third person##/li>
		##li class='poem line'>I am the Midnight Deconstructionist##/li>
		##li class='poem line'>and i am a poet##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>look at me##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>do i not look poetic?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>things about me:##/li>
		##li class='poem line'>i am very slow to anger##/li>
		##li class='poem line'>i am very easy to make laugh##/li>
		##li class='poem line'>i don`t care about a lot of things that i should care about (money above all)##/li>
		##li class='poem line'>i believe in love, peace, liberty and art##/li>
		##li class='poem line'>i think in words, lots of words, freakin` words all over the place##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it would be easy to say##/li>
		##li class='poem line'>that i did not choose this life##/li>
		##li class='poem line'>that it chose me.##/li>
		##li class='poem line'>as i've stated elsewhere##/li>
		##li class='poem line'>things don't choose##/li>
		##li class='poem line'>they are chosen##/li>
		##li class='poem line'>i chose this life##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>still,##/li>
		##li class='poem line'>i have tried everything i could##/li>
		##li class='poem line'>to not be a poet##/li>
		##li class='poem line'>and again and again, this is where i end up##/li>
		##li class='poem line'>i have tried, without success##/li>
		##li class='poem line'>to be another form of artist##/li>
		##li class='poem line'>another form of technician##/li>
		##li class='poem line'>another form of professional##/li>
		##li class='poem line'>and all i can say is##/li>
		##li class='poem line'>splat##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>some people think in pictures##/li>
		##li class='poem line'>(at least, they say they do, i have my doubts)##/li>
		##li class='poem line'>i see pictures all the time##/li>
		##li class='poem line'>they always illustrate things i end up describing##/li>
		##li class='poem line'>in words, lovely words##/li>
		##li class='poem line'>but not just any words##/li>
		##li class='poem line'>there is an art to putting words down##/li>
		##li class='poem line'>or reciting them aloud -##/li>
		##li class='poem line'>to elevate speech and text##/li>
		##li class='poem line'>from the mundane##/li>
		##li class='poem line'>requires an attachment to the aesthetic:##/li>
		##li class='poem line'>what is oft referred to as##/li>
		##li class='poem line'>literature (pronounced LI-tri-chur).##/li>
		##li class='poem line'>i have this attachment##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i have written one-and-a-half novels##/li>
		##li class='poem line'>i have written perhaps a hundred essays##/li>
		##li class='poem line'>i am attached to their stories, their content##/li>
		##li class='poem line'>but i am not attached to their words##/li>
		##li class='poem line'>they are not poetry, which is why people will like them##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we have no word, oddly enough##/li>
		##li class='poem line'>to describe the what of speech and text##/li>
		##li class='poem line'>that is the magic heart of what we do##/li>
		##li class='poem line'>we borrow from song:##/li>
		##li class='poem line'>rhythm, cadence, music##/li>
		##li class='poem line'>we borrow from the tactile:##/li>
		##li class='poem line'>smooth, flowing, textured##/li>
		##li class='poem line'>we borrow from math:##/li>
		##li class='poem line'>elliptical, circular, linear##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in poetry we sometimes speak of scansion##/li>
		##li class='poem line'>it is a made-up word that misses the point##/li>
		##li class='poem line'>made-up words should never miss the point##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the first job of poetry, therefore,##/li>
		##li class='poem line'>is to find a way to speak of itself##/li>
		##li class='poem line'>when you can adequately describe what you do##/li>
		##li class='poem line'>you are a poet##/li>
		##li class='poem line'>until then, you are just poetic##/li>
		##li class='poem line'>this is a pronouncement, rather than a rule##/li>
		##li class='poem line'>and as such, is wrong##/li>
		##li class='poem line'>too bad, one of the things i don`t care about##/li>
		##li class='poem line'>is whether this is right or wrong,##/li>
		##li class='poem line'>it`s poetry, and rightness or wrongness belong to science##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i attempt, when writing poetry##/li>
		##li class='poem line'>to speak poetically##/li>
		##li class='poem line'>i am unfashionable that way##/li>
		##li class='poem line'>and as noted above,##/li>
		##li class='poem line'>i am unwilling to adapt to fashion##/li>
		##li class='poem line'>as a result, i am unpopular with editors##/li>
		##li class='poem line'>i am frequently rejected, and dejected##/li>
		##li class='poem line'>this means nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>some people say##/li>
		##li class='poem line'>that the words flow through them##/li>
		##li class='poem line'>this is another clich&eacute; too often repeated##/li>
		##li class='poem line'>i create the juxtaposition of words##/li>
		##li class='poem line'>they flow from a space inside me##/li>
		##li class='poem line'>where the Five Domains meet:##/li>
		##li class='poem line'>world##/li>
		##li class='poem line'>intellect##/li>
		##li class='poem line'>emotion##/li>
		##li class='poem line'>spirit##/li>
		##li class='poem line'>body##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for some people, when these things coalesce##/li>
		##li class='poem line'>it`s time to cook a chicken##/li>
		##li class='poem line'>when they coalesce in me##/li>
		##li class='poem line'>i must write, and usually poetry##/li>
		##li class='poem line'>and often of a self-revelatory nature##/li>
		##li class='poem line'>it often strikes me late at night##/li>
		##li class='poem line'>when i wish i was sleeping (it`s 12:36 right now)##/li>
		##li class='poem line'>this is why I call myself##/li>
		##li class='poem line'>the Midnight Deconstructionist##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>your soul##/li>
		##li class='poem line'>and your words##/li>
		##li class='poem line'>are two things you can give away##/li>
		##li class='poem line'>and still keep.##/li>
		##li class='poem line'>these words contain a piece of my soul##/li>
		##li class='poem line'>that intangible creation of the dangerous fact##/li>
		##li class='poem line'>that we are more than the sum of our parts##/li>
		##li class='poem line'>the soul of a poet##/li>
		##li class='poem line'>is the interface of the elements##/li>
		##li class='poem line'>i feel the silk of wind in my pores##/li>
		##li class='poem line'>i feel the tug of tides in my blood##/li>
		##li class='poem line'>i feel the growth of the tree of life in my hands##/li>
		##li class='poem line'>i burn with the knowledge of my fate##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>therefore##/li>
		##li class='poem line'>no matter how i twist and turn##/li>
		##li class='poem line'>how i attempt to shake from myself##/li>
		##li class='poem line'>the clinging droplets of heaven##/li>
		##li class='poem line'>i am a poet##/li>
		##li class='poem line'>it is my task##/li>
		##li class='poem line'>my duty##/li>
		##li class='poem line'>to return poetry to the world##/li>
		##li class='poem line'>feed the aching hunger of the masses##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for i am the Midnight Deconstructionist##/li>
		##li class='poem line'>coming soon, to the meeting of the Five Domains##/li>
		##li class='poem line'>that is you.##/li>
	##/ul>
##/article>";