<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Riddle##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the structure of a poem##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>no it's not##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all the poems in this series##/li>
		##li class='poem line'>assume a structure##/li>
		##li class='poem line'>	(assume means more than one thing)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all the poems in this series##/li>
		##li class='poem line'>therefore assume a centre##/li>
		##li class='poem line'>the centre of a series of poems about poetry and poets##/li>
		##li class='poem line'>is the assumption##/li>
		##li class='poem line'>that poetry is a metaphysical act##/li>
		##li class='poem line'>(metaphysics being the science of being and knowing)##/li>
		##li class='poem line'>or perhaps##/li>
		##li class='poem line'>a poemetaphysical act##/li>
		##li class='poem line'>(poemetaphysics being the poetry of being and knowing)##/li>
		##li class='poem line'>and that poetry is valid##/li>
		##li class='poem line'>the centre of the series of poems is poetry##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the structure of this poem##/li>
		##li class='poem line'>which is about structure##/li>
		##li class='poem line'>is not the structure of this poem##/li>
		##li class='poem line'>that is another poem that is not this one##/li>
		##li class='poem line'>but shares with this one the structure of the series##/li>
		##li class='poem line'>which is about the structure of poetry and poets##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>are we clear?##/li>
		##li class='poem line'>no we are not##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why are we not clear?##/li>
		##li class='poem line'>because we know##/li>
		##li class='poem line'>that the centre of a series about poetry and poets##/li>
		##li class='poem line'>should be the poem##/li>
		##li class='poem line'>but by definition##/li>
		##li class='poem line'>there is no such thing as a common structure in poetry##/li>
		##li class='poem line'>the centre##/li>
		##li class='poem line'>is not the centre##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>no, this is a lie##/li>
		##li class='poem line'>(what is a lie?##/li>
		##li class='poem line'>			oh don't play that game with me)##/li>
		##li class='poem line'>the centre is an inviolate centre##/li>
		##li class='poem line'>but because i am using poetry##/li>
		##li class='poem line'>to deconstruct poetry##/li>
		##li class='poem line'>the centre is double##/li>
		##li class='poem line'>the poem##/li>
		##li class='poem line'>is an inviolate thing##/li>
		##li class='poem line'>and therefore outside of the structure##/li>
		##li class='poem line'>yet, because this is a poem##/li>
		##li class='poem line'>the structure still has an internal centre##/li>
		##li class='poem line'>there are two centres to the structure##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in fact, this also is a lie##/li>
		##li class='poem line'>there are three centres to this poem##/li>
		##li class='poem line'>the third centre is the centre of meaning##/li>
		##li class='poem line'>meaning is a structure##/li>
		##li class='poem line'>like structure is a structure##/li>
		##li class='poem line'>they are integrated, but each have a centre##/li>
		##li class='poem line'>the central meaning here##/li>
		##li class='poem line'>is that poetry is us##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>no, that's a lie##/li>
		##li class='poem line'>poetry is not us##/li>
		##li class='poem line'>poetry is me##/li>
		##li class='poem line'>this is how i think##/li>
		##li class='poem line'>this is how you think of me##/li>
		##li class='poem line'>i am the centre##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there are now four centres##/li>
		##li class='poem line'>and each one supports the metastructure##/li>
		##li class='poem line'>if you remove any of these centres##/li>
		##li class='poem line'>the structure will collapse##/li>
		##li class='poem line'>there will be no act of poetry##/li>
		##li class='poem line'>there will be no poet##/li>
		##li class='poem line'>there will be no meaning##/li>
		##li class='poem line'>there will be no structure##/li>
		##li class='poem line'>there will be no poemetaphysics##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>(that is, no theory of the being and knowing of poetry##/li>
		##li class='poem line'>poetry bes, sometimes##/li>
		##li class='poem line'>this is why my deconstruction of my poetic motives##/li>
		##li class='poem line'>is valid, sue me if you don't like it)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the four centres##/li>
		##li class='poem line'>add up to five centres##/li>
		##li class='poem line'>this is embarrassing##/li>
		##li class='poem line'>in fact, the fifth centre##/li>
		##li class='poem line'>the knowing and being of poetry##/li>
		##li class='poem line'>is not a centre of this poem##/li>
		##li class='poem line'>it is a result of the addition of the other four##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>at one time##/li>
		##li class='poem line'>poetry itself was the centre##/li>
		##li class='poem line'>(this is a different use of the word centre)##/li>
		##li class='poem line'>it is no longer a centre##/li>
		##li class='poem line'>the centre was the reader##/li>
		##li class='poem line'>the reader has collapsed in our age##/li>
		##li class='poem line'>the structure has collapsed with the reader##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is the single most important post-modern poem##/li>
		##li class='poem line'>ever written##/li>
		##li class='poem line'>it restores the centre##/li>
		##li class='poem line'>which is not the centre##/li>
		##li class='poem line'>but upon which is built the structure##/li>
		##li class='poem line'>which has six centres##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>you##/li>
		##li class='poem line'>my love##/li>
		##li class='poem line'>are the centre##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about you##/li>
	##/ul>
##/article>";