<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Misery##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about poetry's place among the arts##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there are only seven fundamental arts##/li>
		##li class='poem line'>are you ready for this?##/li>
		##li class='poem line'>pictures##/li>
		##li class='poem line'>sculptures##/li>
		##li class='poem line'>music##/li>
		##li class='poem line'>cooking##/li>
		##li class='poem line'>dance##/li>
		##li class='poem line'>acting##/li>
		##li class='poem line'>and##/li>
		##li class='poem line'>words##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we may remake this list as follows:##/li>
		##li class='poem line'>two dimensional visual art##/li>
		##li class='poem line'>three-dimensional visual/tactile art##/li>
		##li class='poem line'>sonic art##/li>
		##li class='poem line'>delicious art##/li>
		##li class='poem line'>movement art##/li>
		##li class='poem line'>portrayal art##/li>
		##li class='poem line'>	and##/li>
		##li class='poem line'>linguistic art##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all the other arts##/li>
		##li class='poem line'>from opera to film to tying wombats to flagpoles##/li>
		##li class='poem line'>are only variations on these##/li>
		##li class='poem line'>perhaps the most important of the hybrids##/li>
		##li class='poem line'>is theatre and its many avatars##/li>
		##li class='poem line'>we do not dishonour it with the name hybrid##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all of these fundamental forms##/li>
		##li class='poem line'>come in many flavours##/li>
		##li class='poem line'>pictures are as varied as the artists who make them##/li>
		##li class='poem line'>we all have our own dances##/li>
		##li class='poem line'>we hum our own songs##/li>
		##li class='poem line'>we make our own flavours##/li>
		##li class='poem line'>words are no different##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>story##/li>
		##li class='poem line'>dialogue##/li>
		##li class='poem line'>essay##/li>
		##li class='poem line'>these are the favoured children of the art form##/li>
		##li class='poem line'>and here i am, a poet##/li>
		##li class='poem line'>wearing the shabby shoes##/li>
		##li class='poem line'>poetry has fallen on hard times##/li>
		##li class='poem line'>it is the unloved poor relation##/li>
		##li class='poem line'>in the family of the arts##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>musicians brag about music##/li>
		##li class='poem line'>cooks brag about cooking##/li>
		##li class='poem line'>visual artists brag about visual art##/li>
		##li class='poem line'>dancers brag about dancing##/li>
		##li class='poem line'>who brags about poetry?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the art of words is as ancient as language##/li>
		##li class='poem line'>at one time, poetry and storytelling##/li>
		##li class='poem line'>were best friends##/li>
		##li class='poem line'>those who could read and write##/li>
		##li class='poem line'>keep the histories and account the days of life##/li>
		##li class='poem line'>were elevated above their peers##/li>
		##li class='poem line'>stood at the right hand of power##/li>
		##li class='poem line'>were the stars of the communal house##/li>
		##li class='poem line'>i would say##/li>
		##li class='poem line'>we've lost it.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why should this be so?##/li>
		##li class='poem line'>poetry, after all, is the fundamental form##/li>
		##li class='poem line'>of this fundamental form##/li>
		##li class='poem line'>stories must be poetic to be interesting##/li>
		##li class='poem line'>plays must use poetry to be compelling##/li>
		##li class='poem line'>an essay must use an elevated rhetorical style##/li>
		##li class='poem line'>poetry is in all of these##/li>
		##li class='poem line'>yet poetry is shunned##/li>
		##li class='poem line'>we must ask##/li>
		##li class='poem line'>why should this be so?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the answer##/li>
		##li class='poem line'>lies less with the poet##/li>
		##li class='poem line'>than with the audience##/li>
		##li class='poem line'>in the days of Christendom, long that they were##/li>
		##li class='poem line'>the poetry of the pulpit was prime##/li>
		##li class='poem line'>the church knew how##/li>
		##li class='poem line'>to put on a big show##/li>
		##li class='poem line'>candles and gold##/li>
		##li class='poem line'>the body and the blood##/li>
		##li class='poem line'>the sermon and the scripture##/li>
		##li class='poem line'>it is no accident##/li>
		##li class='poem line'>that the bible is written in verse##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in Shakespeare's day##/li>
		##li class='poem line'>the poem was still beloved of the masses and kings##/li>
		##li class='poem line'>but began to wane nonetheless##/li>
		##li class='poem line'>simple recitation##/li>
		##li class='poem line'>had come to pale in comparison##/li>
		##li class='poem line'>to the hybrids: song and theatre##/li>
		##li class='poem line'>those minstrels, they knew how##/li>
		##li class='poem line'>to put on a big show##/li>
		##li class='poem line'>and the big show##/li>
		##li class='poem line'>was full of meaning##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in our day, words envelope us##/li>
		##li class='poem line'>tv, film, newspaper##/li>
		##li class='poem line'>there are more words than ever##/li>
		##li class='poem line'>but there is less poetry than ever##/li>
		##li class='poem line'>poets do not know how##/li>
		##li class='poem line'>to put on a big show##/li>
		##li class='poem line'>and the big shows have moved on##/li>
		##li class='poem line'>we care more about the bigness##/li>
		##li class='poem line'>than the meaning##/li>
		##li class='poem line'>the vacuous has triumphed at last##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and that, my friends##/li>
		##li class='poem line'>is the reason for the plight of the poet##/li>
		##li class='poem line'>for the art of the wordsmith##/li>
		##li class='poem line'>is the art of meaning##/li>
		##li class='poem line'>and without meaning##/li>
		##li class='poem line'>poetry has come to mean nothing##/li>
		##li class='poem line'>and nobody can care about nothing##/li>
		##li class='poem line'>poets, in their desperation##/li>
		##li class='poem line'>speak only to poets##/li>
		##li class='poem line'>and the poets, in their desperation to be heard##/li>
		##li class='poem line'>are not listening to each other##/li>
		##li class='poem line'>you, the audience##/li>
		##li class='poem line'>are as full of the art of words##/li>
		##li class='poem line'>as humans are, in our world##/li>
		##li class='poem line'>you love the word, elevate the word##/li>
		##li class='poem line'>but you do not spread the word -##/li>
		##li class='poem line'>the gospel of the word##/li>
		##li class='poem line'>the word of the gospel##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i therefore command##/li>
		##li class='poem line'>that the poet remember##/li>
		##li class='poem line'>that the art of words is meaning##/li>
		##li class='poem line'>and that we learn##/li>
		##li class='poem line'>to put on a big show##/li>
		##li class='poem line'>thus will we rehabilitate our art##/li>
		##li class='poem line'>raise the art of words##/li>
		##li class='poem line'>from the pit of disdain##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i hereby announce##/li>
		##li class='poem line'>the dawn of a new hybrid##/li>
		##li class='poem line'>the poetry of the big show##/li>
		##li class='poem line'>i will blow something up##/li>
		##li class='poem line'>and write my words##/li>
		##li class='poem line'>on the ball of flames##/li>
		##li class='poem line'>i will dive from a roof##/li>
		##li class='poem line'>and write my words##/li>
		##li class='poem line'>on my pathway through the air##/li>
		##li class='poem line'>i will remind you of all you have forgotten##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for even now##/li>
		##li class='poem line'>there are no masters of the word##/li>
		##li class='poem line'>and the poet##/li>
		##li class='poem line'>is the highest of its slaves##/li>
	##/ul>
##/article>";