<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>dum dum chicken##/h2>##/li>
		##li class='poem line'>dum dum chick##/li>
		##li class='poem line'>dum chick##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>dum chick##/li>
		##li class='poem line'>dum dum chick##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now clap your hands and stamp your feet##/li>
		##li class='poem line'>wiggle and jiggle to the crazy beat##/li>
		##li class='poem line'>come and take a ride with me##/li>
		##li class='poem line'>and let's go see what we can see##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we went for a visit with Farmer Brown##/li>
		##li class='poem line'>when we got there he was getting down##/li>
		##li class='poem line'>with a barnyard full of his rappin' crew##/li>
		##li class='poem line'>he said 'hey there, we were waiting for you##/li>
		##li class='poem line'>let me introduce you all around##/li>
		##li class='poem line'>we'll start with the creatures underground'##/li>
		##li class='poem line'>so mr mole came into the light##/li>
		##li class='poem line'>and he said, 'glad to meet you but it's too darn bright##/li>
		##li class='poem line'>I prefer to hide out in my hole##/li>
		##li class='poem line'>remember me I'm mr mole'##/li>
		##li class='poem line'>he made this little digging sound##/li>
		##li class='poem line'>as he burrowed down into his mound##/li>
		##li class='poem line'>it went##/li>
		##li class='poem line'>dig dig scoop##/li>
		##li class='poem line'>dig dig scoop##/li>
		##li class='poem line'>and it made the chicken want to fly the coop##/li>
		##li class='poem line'>he was a##/li>
		##li class='poem line'>dum dum chicken ##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>then we went for a ride on a big black cow##/li>
		##li class='poem line'>I'd like to do it again right now##/li>
		##li class='poem line'>we rode and sang and the cow said, 'moo,##/li>
		##li class='poem line'>do you think this is all that I can do?'##/li>
		##li class='poem line'>we stopped for lunch, and we ate our cheese##/li>
		##li class='poem line'>with pickles and honey from the honey bees##/li>
		##li class='poem line'>the cow stoop up and said 'watch me now,##/li>
		##li class='poem line'>I'm the world's only singing, dancing cow'##/li>
		##li class='poem line'>she danced so high and she danced so long##/li>
		##li class='poem line'>I ran out of room in this short song##/li>
		##li class='poem line'>she went##/li>
		##li class='poem line'>moo moo clomp##/li>
		##li class='poem line'>moo moo clomp##/li>
		##li class='poem line'>it made that chicken just want to stomp##/li>
		##li class='poem line'>it was a dum dum chicken##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>dum dum chicken (wooh!)##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when we got back Farmer Brown said 'yo,##/li>
		##li class='poem line'>it's almost time for you to go,##/li>
		##li class='poem line'>but there's still a lot for you to see##/li>
		##li class='poem line'>next time you come and visit me.##/li>
		##li class='poem line'>There's the horse of course##/li>
		##li class='poem line'>and a couple ducks##/li>
		##li class='poem line'>a tractor and two old pickup trucks##/li>
		##li class='poem line'>a pig, a weasel, and Uncle Fred##/li>
		##li class='poem line'>who sleeps in the barn on the old straw bed.##/li>
		##li class='poem line'>There's all sorts of things that you can see##/li>
		##li class='poem line'>but there's one that's as best as best can be##/li>
		##li class='poem line'>with scratchin' and struttin' and pluckin' and pickin'##/li>
		##li class='poem line'>there's only one and he's the ##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>alive and well and hiphophippin'##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>a dum dum chicken##/li>
		##li class='poem line'>just watch him go, now watch him fly##/li>
		##li class='poem line'>he can jump halfway to the big blue sky##/li>
		##li class='poem line'>he can break a beat, he can crack an egg##/li>
		##li class='poem line'>he can balance and spin on a single leg##/li>
		##li class='poem line'>he goes scratch scratch scratch##/li>
		##li class='poem line'>cock a doodle doo##/li>
		##li class='poem line'>and now he wants to dance with you.'##/li>
		##li class='poem line'>so clap your hands and stamp your feet##/li>
		##li class='poem line'>wiggle and jiggle to the crazy beat##/li>
		##li class='poem line'>it's time for kicks, it's time for kickin'##/li>
		##li class='poem line'>it's time to do the##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>dum dum chicken ##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>time to do the dum dum chicken##/li>
		##li class='poem line'>dum dum chicken##/li>
		##li class='poem line'>dum##/li>
	##/ul>
##/article>";