<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Erection##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the sources of poetry##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>some would say##/li>
		##li class='poem line'>(and they would be wrong)##/li>
		##li class='poem line'>that the source of poetry is angst##/li>
		##li class='poem line'>others would say##/li>
		##li class='poem line'>(and they would be wrong)##/li>
		##li class='poem line'>that the source of poetry is suffering##/li>
		##li class='poem line'>still more would say##/li>
		##li class='poem line'>(and, yes, they would be wrong)##/li>
		##li class='poem line'>that the source of poetry is meaninglessness##/li>
		##li class='poem line'>yet still more would say##/li>
		##li class='poem line'>(and they would be wrongest of all)##/li>
		##li class='poem line'>that the source of poetry is form##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in fact, it doesn't matter what you say##/li>
		##li class='poem line'>on this topic of topics (or metatopic, if you will)##/li>
		##li class='poem line'>you would be wrong##/li>
		##li class='poem line'>that is because there is no source for poetry##/li>
		##li class='poem line'>other than the machine of time, space and thought##/li>
		##li class='poem line'>driven by the fuel of energy##/li>
		##li class='poem line'>through the engine of matter##/li>
		##li class='poem line'>producing the intangible##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am a conduit##/li>
		##li class='poem line'>a be-funnelled tube##/li>
		##li class='poem line'>through which the strings of the intangible##/li>
		##li class='poem line'>(yes, Virginia, that is a paradox)##/li>
		##li class='poem line'>are poured##/li>
		##li class='poem line'>at one end are the warp of the vacuum and the woof of the real##/li>
		##li class='poem line'>they pass through the various holes and receptors##/li>
		##li class='poem line'>that make up me##/li>
		##li class='poem line'>they percolate and mix in the various churns and algorithms##/li>
		##li class='poem line'>that make up me##/li>
		##li class='poem line'>they are transformed and output through the various digits and communicators##/li>
		##li class='poem line'>that make up me##/li>
		##li class='poem line'>and thus a poem is born##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the source is everything##/li>
		##li class='poem line'>the source, at least in my eccentricity##/li>
		##li class='poem line'>is never nothing##/li>
		##li class='poem line'>some would say that the author is dead##/li>
		##li class='poem line'>that all a writer is is a blender##/li>
		##li class='poem line'>i am not dead##/li>
		##li class='poem line'>i am a unique filter##/li>
		##li class='poem line'>and a blender, for which i never apologize##/li>
		##li class='poem line'>the claim that the author is dead##/li>
		##li class='poem line'>is no more than a weak insult##/li>
		##li class='poem line'>delivered by a non-poet##/li>
		##li class='poem line'>who does not truly understand what it means##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to create##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to be the first in the universe##/li>
		##li class='poem line'>to translate what is##/li>
		##li class='poem line'>into what is now##/li>
		##li class='poem line'>i am doing this even as i speak##/li>
		##li class='poem line'>and will do it again in the very-off-chance##/li>
		##li class='poem line'>that anyone will ever hear me read this##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the reason everybody is wrong##/li>
		##li class='poem line'>is that critics speak in absolutes##/li>
		##li class='poem line'>there are only three absolutes##/li>
		##li class='poem line'>you##/li>
		##li class='poem line'>and##/li>
		##li class='poem line'>me##/li>
		##li class='poem line'>and##/li>
		##li class='poem line'>everything else##/li>
		##li class='poem line'>the source of poetry##/li>
		##li class='poem line'>is you##/li>
		##li class='poem line'>and##/li>
		##li class='poem line'>me##/li>
		##li class='poem line'>and##/li>
		##li class='poem line'>everything else##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>of those three##/li>
		##li class='poem line'>the only ones that matter##/li>
		##li class='poem line'>are all of them##/li>
		##li class='poem line'>why?##/li>
		##li class='poem line'>because they all have meaning##/li>
		##li class='poem line'>and meaning is the blood of poetry##/li>
		##li class='poem line'>this is my credo##/li>
		##li class='poem line'>tattoo it on the inside of your eyelid##/li>
		##li class='poem line'>and you will never cease to amaze yourself##/li>
		##li class='poem line'>i am the funnel##/li>
		##li class='poem line'>i am the Midnight Deconstructionist##/li>
		##li class='poem line'>you are turning me on##/li>
		##li class='poem line'>and i have no reason to lie to you##/li>
	##/ul>
##/article>";