<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Diagnosis##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem now##/li>
		##li class='poem line'>it is still a poem##/li>
		##li class='poem line'>it is a poem about the Deconstructionist's effort to record and analyze time##/li>
		##li class='poem line'>as a function of poetry##/li>
		##li class='poem line'>and poetry##/li>
		##li class='poem line'>as a function of time##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>an oblique:##/li>
		##li class='poem line'>my i##/li>
		##li class='poem line'>is located behind my eyes##/li>
		##li class='poem line'>i have two eyes##/li>
		##li class='poem line'>not just for stereoscopy##/li>
		##li class='poem line'>but one for each brain##/li>
		##li class='poem line'>i have an i/2 for each brain##/li>
		##li class='poem line'>a left i##/li>
		##li class='poem line'>a right i##/li>
		##li class='poem line'>let me introduce you##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am the left i.  i am logical, linear and sensible.  i think in such a way that the necessities of life are taken care of.  i provide the outline to the essay of life.  to me, time is a river.  it flows from the past to the future, and i stand on the bank, in the present, my hook in the water, and never touch the same river twice.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am the right i##/li>
		##li class='poem line'>i like stuff##/li>
		##li class='poem line'>intangibles, shiny things and##/li>
		##li class='poem line'>	i may not believe in god##/li>
		##li class='poem line'>	i just hope he/she/it/they believe in me##/li>
		##li class='poem line'>to me, time is a river that flows from infinity to infinity##/li>
		##li class='poem line'>and i swim in its current, and never touch the same river twice##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the operative##/li>
		##li class='poem line'>is of course##/li>
		##li class='poem line'>that i never touch the same river twice##/li>
		##li class='poem line'>humans have debated this sentence for thousands of years##/li>
		##li class='poem line'>my i's have no trouble with it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>my left i##/li>
		##li class='poem line'>sees the river, and knows that it follows the same path##/li>
		##li class='poem line'>but contains different water each moment##/li>
		##li class='poem line'>by definition##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>my right i##/li>
		##li class='poem line'>sees the river, and knows that it is a symbol##/li>
		##li class='poem line'>both of the infinite and of constant change##/li>
		##li class='poem line'>by intuition##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>an anoblique:##/li>
		##li class='poem line'>this started out as a poem##/li>
		##li class='poem line'>it is still a poem##/li>
		##li class='poem line'>yet, like my i's##/li>
		##li class='poem line'>it sees itself as a work-in-progress##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that was the right i speaking##/li>
		##li class='poem line'>the left i knows that there is no poem that can see itself##/li>
		##li class='poem line'>even as a work-in-progress##/li>
		##li class='poem line'>however, the right i knows that time##/li>
		##li class='poem line'>as we understand it##/li>
		##li class='poem line'>only exists for conscious beings##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but there is more than one kind of time##/li>
		##li class='poem line'>there is time that measures change##/li>
		##li class='poem line'>and there is the time of the i##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the left##/li>
		##li class='poem line'>knows that the time of the i##/li>
		##li class='poem line'>is an illusion##/li>
		##li class='poem line'>but he cherishes this illusion##/li>
		##li class='poem line'>because he knows that it is crucial##/li>
		##li class='poem line'>to the functioning of the right i##/li>
		##li class='poem line'>(they love each other)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when the two i's get together##/li>
		##li class='poem line'>they become synergistic##/li>
		##li class='poem line'>nature knowed good##/li>
		##li class='poem line'>what nature was doing##/li>
		##li class='poem line'>when it made two i's##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when time is flowing smoothly##/li>
		##li class='poem line'>for the synergized i's##/li>
		##li class='poem line'>a poem is created##/li>
		##li class='poem line'>all forms of zany antics ensue##/li>
		##li class='poem line'>like this##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>at this very moment##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>at this very moment##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>at this very moment##/li>
		##li class='poem line'>time is flowing perfectly for the Deconstructionist##/li>
		##li class='poem line'>my i's are clear##/li>
		##li class='poem line'>this poem is emerging##/li>
		##li class='poem line'>from the synergistic##/li>
		##li class='poem line'>workings##/li>
		##li class='poem line'>of the two i's##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there are only two times in the Deconstructionist's life##/li>
		##li class='poem line'>when time flows perfectly##/li>
		##li class='poem line'>and the two i's are working perfectly##/li>
		##li class='poem line'>one is fucking my love##/li>
		##li class='poem line'>one is writing, my love##/li>
		##li class='poem line'>excuse the vulgarity, i wished to emphasize the physicality of the act##/li>
		##li class='poem line'>lest you believe##/li>
		##li class='poem line'>that i don't live in the physical world##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a poem is a little river of words##/li>
		##li class='poem line'>it has a beginning somewhere##/li>
		##li class='poem line'>yet from the vantage point of any particular point##/li>
		##li class='poem line'>seems to flow from unknown-where (my i's)##/li>
		##li class='poem line'>to other-where (your i's)##/li>
		##li class='poem line'>you stand on the bank##/li>
		##li class='poem line'>or swim in the current##/li>
		##li class='poem line'>as your i's see fit##/li>
		##li class='poem line'>and the flow of ideas##/li>
		##li class='poem line'>continues unabated##/li>
		##li class='poem line'>the poem, when written##/li>
		##li class='poem line'>has a beginning##/li>
		##li class='poem line'>but it doesn't begin your thoughts##/li>
		##li class='poem line'>it joins them like a tributary##/li>
		##li class='poem line'>and it has an end##/li>
		##li class='poem line'>but your thoughts continue##/li>
		##li class='poem line'>like a river that forks off##/li>
		##li class='poem line'>leaving a brook to one side##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this poem, therefore##/li>
		##li class='poem line'>is a flow in time##/li>
		##li class='poem line'>it started out with##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>but it is not the same poem it was##/li>
		##li class='poem line'>when it said nothing yet##/li>
		##li class='poem line'>the only poem that existed at that moment##/li>
		##li class='poem line'>was in your own mind, and in your own time##/li>
		##li class='poem line'>which is not the time of this writing##/li>
		##li class='poem line'>you are swimming in/standing by##/li>
		##li class='poem line'>the same river/poem/time##/li>
		##li class='poem line'>but it is not the same river/poem/time##/li>
		##li class='poem line'>it is a river of you##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the only times##/li>
		##li class='poem line'>in other words##/li>
		##li class='poem line'>when my i's feel perfect##/li>
		##li class='poem line'>is when i'm fucking my love##/li>
		##li class='poem line'>or##/li>
		##li class='poem line'>when this is a poem##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>(and, adds the right i##/li>
		##li class='poem line'>i love you)##/li>
	##/ul>
##/article>";