<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Fear part 2##/h2>##/li>
		##li class='poem line'>1.##/li>
		##li class='poem line'>two creatures live in me##/li>
		##li class='poem line'>lodged in my soul##/li>
		##li class='poem line'>like a virus in the spine:##/li>
		##li class='poem line'>herpes of the mind##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a darkened box##/li>
		##li class='poem line'>sets fire the tinder##/li>
		##li class='poem line'>in my reptilian core##/li>
		##li class='poem line'>i  know how a lizard feels poured in concrete##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the other##/li>
		##li class='poem line'>binds me to the intangible##/li>
		##li class='poem line'>i am a victim of nothing##/li>
		##li class='poem line'>a sensual, palpable, nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>2.##/li>
		##li class='poem line'>the idea of my death##/li>
		##li class='poem line'>doesn't disturb me##/li>
		##li class='poem line'>a short passage from here to not##/li>
		##li class='poem line'>how could i care?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i could flee from life.##/li>
		##li class='poem line'>find a desert island##/li>
		##li class='poem line'>a last remnant, final##/li>
		##li class='poem line'>a dot on the barren horizon##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but my island is here##/li>
		##li class='poem line'>between chair and table##/li>
		##li class='poem line'>i serve myself dinner##/li>
		##li class='poem line'>reheat coffee##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>3. ##/li>
		##li class='poem line'>i was king for ten minutes##/li>
		##li class='poem line'>and no one knew but me##/li>
		##li class='poem line'>i was a pauper without a song##/li>
		##li class='poem line'>and the crowds closed around me##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for a brief time##/li>
		##li class='poem line'>all the signs were pointing my way##/li>
		##li class='poem line'>saying here's the guy##/li>
		##li class='poem line'>he has a voice, you know##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the wind has long since changed##/li>
		##li class='poem line'>i'm back in my chair##/li>
		##li class='poem line'>still, I wouldn't trade my ten minutes##/li>
		##li class='poem line'>for another night of leftovers##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>4.##/li>
		##li class='poem line'>ok, i woke up this morning##/li>
		##li class='poem line'>chose a head for the day##/li>
		##li class='poem line'>actually, it chose me##/li>
		##li class='poem line'>but that's a clich&eacute;, and i was avoiding it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this head is uncombed, unshaven##/li>
		##li class='poem line'>that's good enough, i don't##/li>
		##li class='poem line'>look at myself in mirrors##/li>
		##li class='poem line'>why bring up issues?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the sleeping dog##/li>
		##li class='poem line'>at the foot of the stairs##/li>
		##li class='poem line'>bit me on the ass yesterday##/li>
		##li class='poem line'>today i step over without waking him##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>5.##/li>
		##li class='poem line'>i sort of wanted to cry##/li>
		##li class='poem line'>lock myself in my room##/li>
		##li class='poem line'>and not be a man##/li>
		##li class='poem line'>for a few precious minutes##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i didn't do it##/li>
		##li class='poem line'>why bother?##/li>
		##li class='poem line'>crying alone tugs on no heartstrings##/li>
		##li class='poem line'>but your own##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>instead, i turned my attention##/li>
		##li class='poem line'>toward the screen of my tv##/li>
		##li class='poem line'>there is nothing like nothing##/li>
		##li class='poem line'>to make you feel nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>6.##/li>
		##li class='poem line'>i have broken with myself##/li>
		##li class='poem line'>i no longer wish to be part of me##/li>
		##li class='poem line'>my philosophies have changed##/li>
		##li class='poem line'>and i'm become irrelevant##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it would be easy now##/li>
		##li class='poem line'>to say i don't know who i am##/li>
		##li class='poem line'>but the problem is##/li>
		##li class='poem line'>i do##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i know exactly who i am##/li>
		##li class='poem line'>i'm the guy##/li>
		##li class='poem line'>who knows##/li>
		##li class='poem line'>he has broken with himself##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>7.##/li>
		##li class='poem line'>fear is in the mind##/li>
		##li class='poem line'>the future##/li>
		##li class='poem line'>stretching out unending##/li>
	##/ul>
##/article>";