<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Freedom##/h2>##/li>
		##li class='poem line'>I##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>of all the arguments that exist##/li>
		##li class='poem line'>in favour of freedom##/li>
		##li class='poem line'>none is so perfect as this:##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>cannot explain the human mind.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is a good argument##/li>
		##li class='poem line'>being exactly as the same##/li>
		##li class='poem line'>as the one about God:##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>cannot explain the human mind.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in fact, it is the only argument##/li>
		##li class='poem line'>that is ever possible##/li>
		##li class='poem line'>in support of the soul:##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>cannot explain the human mind.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>Kant was wrong##/li>
		##li class='poem line'>there are not three meaningful questions##/li>
		##li class='poem line'>there is only one:##/li>
		##li class='poem line'>can the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>explain the human mind?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>II##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>if God exists##/li>
		##li class='poem line'>then a soul is possible##/li>
		##li class='poem line'>if a soul is possible##/li>
		##li class='poem line'>then freedom is plausible##/li>
		##li class='poem line'>if freedom is plausible##/li>
		##li class='poem line'>then God can exist##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the questions become one:##/li>
		##li class='poem line'>is an immortal God free to do##/li>
		##li class='poem line'>whatever He wishes?##/li>
		##li class='poem line'>can he transcend causality##/li>
		##li class='poem line'>to pick a purely random number?##/li>
		##li class='poem line'>and are we made in that image?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so the questions become one:##/li>
		##li class='poem line'>is an immortal human free to do##/li>
		##li class='poem line'>whatever it wishes?##/li>
		##li class='poem line'>can it transcend causality##/li>
		##li class='poem line'>to pick a purely random number?##/li>
		##li class='poem line'>could we create a God in that image?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>if humans exist##/li>
		##li class='poem line'>then mortality is possible##/li>
		##li class='poem line'>if mortality is possible##/li>
		##li class='poem line'>then freedom is implausible##/li>
		##li class='poem line'>if freedom is implausible##/li>
		##li class='poem line'>then how can God exist?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>III##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a soul##/li>
		##li class='poem line'>would have to be free##/li>
		##li class='poem line'>it could not be tied##/li>
		##li class='poem line'>to the hardware of humanity##/li>
		##li class='poem line'>or it would wear the chains##/li>
		##li class='poem line'>of history##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a God##/li>
		##li class='poem line'>would have to be free##/li>
		##li class='poem line'>it could not be tied##/li>
		##li class='poem line'>to the hardware of the universe##/li>
		##li class='poem line'>or it would wear the chains##/li>
		##li class='poem line'>of causality##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>therefore, a God and a soul##/li>
		##li class='poem line'>must share an essential quality##/li>
		##li class='poem line'>they are almost identical##/li>
		##li class='poem line'>not being stuff##/li>
		##li class='poem line'>and having no history##/li>
		##li class='poem line'>they would have no beginning or end##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a soul and a God##/li>
		##li class='poem line'>would be immortal##/li>
		##li class='poem line'>and not being contained in time##/li>
		##li class='poem line'>could no more be contained in space##/li>
		##li class='poem line'>they would both##/li>
		##li class='poem line'>be infinite##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>being infinite##/li>
		##li class='poem line'>they would both fill infinity and eternity##/li>
		##li class='poem line'>having no beginning or end##/li>
		##li class='poem line'>they would needs fill each other##/li>
		##li class='poem line'>having no space or time##/li>
		##li class='poem line'>they would needs be the same##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>therefore, a God and a soul##/li>
		##li class='poem line'>must share an essential quality##/li>
		##li class='poem line'>they are identical##/li>
		##li class='poem line'>not being stuff##/li>
		##li class='poem line'>and having no history##/li>
		##li class='poem line'>they would be indistinguishable##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a soul and a God##/li>
		##li class='poem line'>would have to be free##/li>
		##li class='poem line'>and not being contained in anything##/li>
		##li class='poem line'>or wearing any chains##/li>
		##li class='poem line'>they would not only be free##/li>
		##li class='poem line'>they would be freedom##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>being freedom##/li>
		##li class='poem line'>a God and a soul##/li>
		##li class='poem line'>are an identity##/li>
		##li class='poem line'>not being stuff##/li>
		##li class='poem line'>and having no history##/li>
		##li class='poem line'>they would not be##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>IV##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the question becomes##/li>
		##li class='poem line'>can the GodSoulFreedom##/li>
		##li class='poem line'>inhabit a human mind?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to know this##/li>
		##li class='poem line'>we must know one thing:##/li>
		##li class='poem line'>is a mind infinite?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to answer that##/li>
		##li class='poem line'>we must know something more:##/li>
		##li class='poem line'>can the infinite achieve limits?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to understand that##/li>
		##li class='poem line'>we must turn further inward:##/li>
		##li class='poem line'>am I capable of the infinite?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to achieve understanding##/li>
		##li class='poem line'>we must ask ourselves##/li>
		##li class='poem line'>if I am capable, must I not already be?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the question becomes##/li>
		##li class='poem line'>can a human mind##/li>
		##li class='poem line'>inhabit the GodSoulFreedom?##/li>
		
		##li class='poem line'>V##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>ok, so now we are faced with the inevitable##/li>
		##li class='poem line'>for the mind to be free##/li>
		##li class='poem line'>the mind must be part of the identity##/li>
		##li class='poem line'>MindGodSoulFreedom##/li>
		##li class='poem line'>we are back where we started:##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>cannot explain the human mind.##/li>
		
		##li class='poem line'>VI##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a strange wind fell##/li>
		##li class='poem line'>from the face of the northern slope##/li>
		##li class='poem line'>chaos in motion, ecstatic##/li>
		##li class='poem line'>rushing down the frozen rock##/li>
		##li class='poem line'>to pile wickedly against##/li>
		##li class='poem line'>a cornice rotten with sun##/li>
		##li class='poem line'>which, with a painless groan##/li>
		##li class='poem line'>unbecame.##/li>
		##li class='poem line'>there were no witnesses -##/li>
		##li class='poem line'>there are never any witnesses.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the question becomes##/li>
		##li class='poem line'>can a mind choose a random number?##/li>
		
		
		
		##li class='poem line'>it is the unity of this opposition##/li>
		##li class='poem line'>which ties together the metaphysical##/li>
		##li class='poem line'>Kant's three questions##/li>
		##li class='poem line'>because they are answered identically##/li>
		##li class='poem line'>are all the same question##/li>
		##li class='poem line'>asked in three different ways:##/li>
		##li class='poem line'>what three positive single-digit numbers##/li>
		##li class='poem line'>taken together add up to three?##/li>
		
		##li class='poem line'>VII##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there was a time##/li>
		##li class='poem line'>before Freud poked holes in the balloon##/li>
		##li class='poem line'>when the mind was pure mystery##/li>
		##li class='poem line'>an aether in the wind##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there was a time##/li>
		##li class='poem line'>when mechanics were of Newton##/li>
		##li class='poem line'>and bodies reacted to bodies##/li>
		##li class='poem line'>as substance to substance##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there was a time##/li>
		##li class='poem line'>when the physical world broke down##/li>
		##li class='poem line'>and Einstein, Bohr and Heisenberg##/li>
		##li class='poem line'>showed us there is no substance##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is a now##/li>
		##li class='poem line'>when the only way to understand##/li>
		##li class='poem line'>is to re-embrace the mystery of mind##/li>
		##li class='poem line'>a wind in the aether##/li>
		
		##li class='poem line'>VIII##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>freedom##/li>
		##li class='poem line'>is the right of quanta##/li>
		##li class='poem line'>to behave unpredictably##/li>
		##li class='poem line'>and even that##/li>
		##li class='poem line'>wears the chains of the physical##/li>
		##li class='poem line'>some would say##/li>
		##li class='poem line'>because we are ignorant of the truth##/li>
		##li class='poem line'>that there is no truth##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>truth##/li>
		##li class='poem line'>is a light##/li>
		##li class='poem line'>that beckons from the horizon##/li>
		##li class='poem line'>always the horizon, only the horizon##/li>
		##li class='poem line'>but understanding is the earth##/li>
		##li class='poem line'>we cross on our way there##/li>
		##li class='poem line'>leaving civilization in our wake##/li>
		##li class='poem line'>wherein dwells the desire - freedom##/li>
		
		##li class='poem line'>IX##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is only one thing##/li>
		##li class='poem line'>that thing is everything##/li>
		##li class='poem line'>there is no I, there is no not-I##/li>
		##li class='poem line'>this is an illusion##/li>
		##li class='poem line'>caused by the grossness of senses##/li>
		##li class='poem line'>and the weakness of identity##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we imagine borders##/li>
		##li class='poem line'>where there are none##/li>
		##li class='poem line'>and bodies##/li>
		##li class='poem line'>and think, 'where am I?'##/li>
		##li class='poem line'>pointing to a third eye##/li>
		##li class='poem line'>and finding this inadequate##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that question means all##/li>
		##li class='poem line'>more than 'what' or 'why?'##/li>
		##li class='poem line'>but we hate the answer##/li>
		##li class='poem line'>because the answer##/li>
		##li class='poem line'>is##/li>
		##li class='poem line'>here##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we don't like being here##/li>
		##li class='poem line'>being##/li>
		##li class='poem line'>here##/li>
		##li class='poem line'>we don't like being not infinite##/li>
		##li class='poem line'>being##/li>
		##li class='poem line'>not infinite##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the good news##/li>
		##li class='poem line'>is that we are infinite##/li>
		##li class='poem line'>I is not-I##/li>
		##li class='poem line'>and the illusion##/li>
		##li class='poem line'>of I-ness and not-I-etude##/li>
		##li class='poem line'>is merely useful##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the unquiet soul##/li>
		##li class='poem line'>is disturbed by what is##/li>
		##li class='poem line'>and what is not##/li>
		##li class='poem line'>i don't understand that##/li>
		##li class='poem line'>what i am not##/li>
		##li class='poem line'>is not not-I##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>not-I##/li>
		##li class='poem line'>is just the limit of illusion##/li>
		##li class='poem line'>and the illusion##/li>
		##li class='poem line'>is the limit of I##/li>
		##li class='poem line'>i am infinite##/li>
		##li class='poem line'>but i am not God##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>how do i know this?##/li>
		##li class='poem line'>because if i was God##/li>
		##li class='poem line'>i would choose not to be##/li>
		##li class='poem line'>which would make me not-God##/li>
		##li class='poem line'>it is simply a reflection##/li>
		##li class='poem line'>of my comfortable illusion##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the myriad myriads##/li>
		##li class='poem line'>that comprise the illusion of me##/li>
		##li class='poem line'>combine and uncombine and recombine##/li>
		##li class='poem line'>with the rest of the not-me##/li>
		##li class='poem line'>which i perceive##/li>
		##li class='poem line'>as the illusion of not-I##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the unquiet soul##/li>
		##li class='poem line'>is disturbed by what is##/li>
		##li class='poem line'>and what is not##/li>
		##li class='poem line'>i don't understand that##/li>
		##li class='poem line'>the proof of I-not-I##/li>
		##li class='poem line'>is love##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>X##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i will never choose a random number##/li>
		##li class='poem line'>i will always have reasons for every choice##/li>
		##li class='poem line'>and my reasons will have reasons##/li>
		##li class='poem line'>and they will, and so on##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but the chains of causality##/li>
		##li class='poem line'>are light upon my neck##/li>
		##li class='poem line'>because i cherish my illusion##/li>
		##li class='poem line'>this body, this world##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this not-thing##/li>
		##li class='poem line'>i call my mind##/li>
		##li class='poem line'>wears the same chains##/li>
		##li class='poem line'>as Newton, Einstein, Bohr and Heisenberg##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i will never choose a random number##/li>
		##li class='poem line'>i will never be a random number##/li>
		##li class='poem line'>my illusions will have illusions##/li>
		##li class='poem line'>and i will love you for it##/li>
		
		##li class='poem line'>XI##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i need not believe in God##/li>
		##li class='poem line'>who believes in I-not-I##/li>
		##li class='poem line'>or perhaps##/li>
		##li class='poem line'>they are the same thing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i need not believe in a soul##/li>
		##li class='poem line'>who believes in I-not-I##/li>
		##li class='poem line'>or perhaps##/li>
		##li class='poem line'>they are the same thing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i need not believe in freedom##/li>
		##li class='poem line'>who believes in I-not-I##/li>
		##li class='poem line'>or perhaps##/li>
		##li class='poem line'>they are the same thing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i need not believe in I-not-I##/li>
		##li class='poem line'>as long as i believe in love##/li>
		##li class='poem line'>or perhaps##/li>
		##li class='poem line'>they are the same thing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>XII##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the bottom line##/li>
		##li class='poem line'>is that there is no bottom line##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all that i am##/li>
		##li class='poem line'>is all that there is, was or will be##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i would say##/li>
		##li class='poem line'>this is fair compensation##/li>
		##li class='poem line'>and to feel loss##/li>
		##li class='poem line'>as a child of the moment of creation##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>is blasphemy##/li>
		##li class='poem line'>not to mention unreasonable##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and mystery##/li>
		##li class='poem line'>means not knowing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but not##/li>
		##li class='poem line'>doesn't mean never##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>after all##/li>
		##li class='poem line'>we all believe in love, don't we?##/li>
		
		##li class='poem line'>XIII##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>of all the arguments that exist##/li>
		##li class='poem line'>opposing freedom##/li>
		##li class='poem line'>none is so perfect as this:##/li>
		##li class='poem line'>the human mind cannot explain##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is a good argument##/li>
		##li class='poem line'>being exactly as the same##/li>
		##li class='poem line'>as the one about God:##/li>
		##li class='poem line'>the human mind cannot explain##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in fact, it is the only argument##/li>
		##li class='poem line'>that is ever possible##/li>
		##li class='poem line'>opposing the soul:##/li>
		##li class='poem line'>the human mind cannot explain##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>Kant was wrong##/li>
		##li class='poem line'>there are not three meaningful questions##/li>
		##li class='poem line'>there is only one:##/li>
		##li class='poem line'>can the human mind ever explain##/li>
		##li class='poem line'>the mechanics of determinism##/li>
		##li class='poem line'>the physics of materialism##/li>
		##li class='poem line'>and the mathematics of realism?##/li>
	##/ul>
##/article>";    
	
    
