<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##article class='post'>

##h1>Sometimes the kindest thing you can do is to act like you aren&rsquo;t hurt.##/h1>
##p>I have but one true fear in this world. I feel the great fear of a child alone in the dark: &ldquo;I will always be alone in the dark&rdquo;.  Loneliness is my Nemesis, and I can think of no greater terror.##/p>

##p>I am/have/carry a lost child inside me.  He will never grow up; something stopped him there, at the age of five; it wasn&rsquo;t something done to him by another, but something his own, a monster from the under the bed, perhaps. He has only one thought, and only one desire: &ldquo;Be here, I need you here, I need you now&rdquo;. I describe it through this image and voice, but I know that it&rsquo;s either a built-in feeling I give a face to, or it&rsquo;s a still shot from a true-life story. Either way, loneliness is my Nemesis, even when I&rsquo;m not alone.##/p>

##p>It is a vagary of my wiring, and one I can&rsquo;t change; I don&rsquo;t get &ldquo;fear&rdquo; or &ldquo;panic&rdquo; the way other people seem to. It&rsquo;s there, but it&rsquo;s otherwise channeled. When an emergency comes up, I&rsquo;m the reliable one, because I know that I can deal with my own stuff later.  When I or a loved one is threatened, I am constitutionally unable to choose the &ldquo;run away&rdquo; option; I will fight 100% of the time.  I never deliberately provoke; I predictably overreact.  I have a protective streak meant to intimidate, to protect by threat, and it emerges no matter how gentle I am.  I love you, we love you, look at my teeth.  I don&rsquo;t get to do the fear thing, because I&rsquo;m the guard dog, and I have to stay at least a little pissed off for all our sakes, right?##/p>

##p>But I am more than vulnerable on one front. I am practically defenseless at the hands of the people I love. You, stranger, there&rsquo;s nothing you can threaten me with, because I protect my loves.  You, my loves, can threaten me with practically anything, and I am utterly defenseless.  My armor is all outward, and I am exposed to any threat from the ones I protect, and sometimes it seems to me that every single human but me knows how to cut through my hide; you all know my weakness, even if you don&rsquo;t, because every threat from within is the same: I will leave you alone.  You will be alone.  You will always be alone.##/p>

##p>So you see, any of you has all the power over me; all you have to do is love me, and I will make you my own, to guard with my life, because that is how to not be alone. Isn&rsquo;t it? I don&rsquo;t require that every person I feel protective for return my feelings all the time. If you in turn make me one of your own, however, you are a thing in my heart, and in my heart, you have all the power.##/p>

##p>I have a rapid mood cycle, which is, wrongly, called a &ldquo;mood swing&rdquo;. You don&rsquo;t have to be bipolar to have a mood cycle; it&rsquo;s when your mood cycle is the dominant governor of your behaviour that you achieve the title of &ldquo;bipolar&rdquo;.  I&rsquo;m more or less extremely profoundly bipolar, or not, what&rsquo;s it to you?, but I&rsquo;m a little luckier than most. The advantage of a rapid mood cycle, weeks instead of months or years, is that as bad as I feel at any time, I&rsquo;ll at least feel good for a little while soon enough. I need that respite, that up-time; it feels good, and I get to enjoy it as much as I can, because it&rsquo;s the compensation. When I don&rsquo;t get that up, I get no respite. If I go cycles without respite, I run out of fight, and I tip over. That&rsquo;s what I call it. My mood deteriorates, my patience evaporates, my intelligence is dulled, and my already-short attention span falls, literally, to a few minutes at best.  A &ldquo;mood swing&rdquo; is more than moods.  It&rsquo;s a brain-swing: mood and intellect are not distinguishable.  If I&rsquo;m feeling deeply-depressed, I&rsquo;m also being stupider than usual, but I don&rsquo;t know it.##/p>

##p>If my emotional reserves run out, I feel as exposed to the world as a bipolar man can feel.  Breezes on my skin are acid on raw nerves, I have no eyelids, and my hearing-aids are jacked to the max.  I am defenseless. All you have to do is say, &ldquo;I am not with you&rdquo;, and my world turns sideways. I have only one fear, and you have invoked it, and I don&rsquo;t do fear, I do rage. I am the reluctant master of rage; I am monster good at rage. And I love you, damn it all to hell. I have to protect you, even if you don&rsquo;t love me in return, and while I would never hurt someone I love &mdash; I am incapable of acting outside my programming &mdash; you are now terrified by me, and I can&rsquo;t say I blame you.  I am this big scary thing, it&rsquo;s my job, I can&rsquo;t help it.  I&rsquo;m caught in a trap. I cannot respond in anger to threats from my loved ones, because the usual bad things will happen, you know it will, it always does, so I have to leave. I have to go be alone.  I have to be alone.##/p>

##p>I can only be hurt by people that I love. If that hurt goes too deep, they stop being my own, they lose my protection, they lose my compassion, and feelings inevitably get hurt. (##em>Edit: &ldquo;get hurt&rdquo; is not true; I &ldquo;hurt them&rdquo; is true.)##/em>. I&rsquo;m a master of rage, and I am shamefully skilled at seeing into people, finding what they hate about themselves, and serving it back to them with all the restraint of a pit bull. My outward job is spotting and neutralizing threats before they reach the village gates, and if you don&rsquo;t see me coming, I will probably hurt you.  When my brainstorm quiets, I will love you again, but meanwhile I have hurt you, or at least scared you.##/p>

##p>If I love you, every threat is an existential threat. Sorry, it just is.  The longer I go without the relief of an up-time, the thinner the thread of restraint that keeps me together becomes.  When the thread breaks, everything is a threat. I am at DefCon 5.  Anything can trigger the rage at that point, no matter how hard I try to control it.##/p>

##p>My loved ones are not in danger from me. I am a powder keg, it&rsquo;s true, but I protect my loved ones, even from me; I didn&rsquo;t always know how much I could hurt people, and I have hurt people. Words are my weapon; I know that words can do far more damage than any blow, and I know how to make words hurtful. I have built-in protections for you now; I keep the words internal for as long as my strength holds out, and then I go be alone. You don&rsquo;t get it, but when I yell at you to stay away from me and I stomp off into the darkness, I&rsquo;m doing it for you, not for me, and the hurt and resentment you hear in my emotional incoherence is there because I love you, and I ##em>still##/em> have to be alone.##/p>

##p>None of this is what I voted for.  It doesn&rsquo;t matter how well I can describe it here, I am not in control of my moods; my body, yes, my thoughts, no.  Neither are you, you just think you are because you have relatively peaceful moods compared to me. I envy you. When my rage dissipates, because I have punished myself almost adequately &mdash; yes, I know it&rsquo;s ridiculous; that&rsquo;s why they call it crazy &mdash; it&rsquo;s only because I&rsquo;ve used up whichever chemical bee-in-my-bonnet flipped my rage switch.  There is no way I can truly communicate to you what tipped me over, or why my world went to hell just there, but I know it looked as crazy as it was. Now I must face you, and know that there is another person who saw the wrong me, and whom I hurt. I did that, and I will remember it forever.##/p>

##p>If you love me, you should know that you triggered it, but you didn&rsquo;t deserve it, and in a corner of me untouched by crazy, I knew that and I was still protecting you. If it hadn&rsquo;t been you, it would have been someone else, for some other reason, for some other semi-imaginary provocation; probably a stupid one.  It doesn&rsquo;t matter, because my intellect betrayed me and is hiding behind the outhouse. I have awakened a thousand times from a bad dream that was really happening, surveyed the damage, and offered what mea culpa and restoration I can. It is humiliating. Knowing that I lost it, again, and that I will have to face you, again, is another cut in a death of a thousand cuts.##/p>

##p>The kindest thing you can do for me, when I come back to myself and face my loves, is to act like it didn&rsquo;t matter. Don&rsquo;t pretend it didn&rsquo;t happen; that&rsquo;s harmful even if you mean well, because it makes me think you are too ashamed of me to speak of it. Almost every other person in my position will tell you the same.  You can acknowledge it happened, and act like I didn&rsquo;t hurt you, and that you know that wasn&rsquo;t me driving the bus that ran over you. Lie to me a little.  You know you&rsquo;ll get an apology when I can do it.  You know I was protecting you even while I was in full threat display.  You can welcome me home without making me talk about what the other me did; yes, I was there, but no, I was not driving the bus. You know we&rsquo;ll get to it when we&rsquo;re ready. You know that whatever was going on in my brain was worse for me, and that I can&rsquo;t learn from it, and that there&rsquo;s no solving it, so there&rsquo;s no point in talking it over for the 15th time this year.##/p>

##p>You know I love you. Just say you know that, say that you knew it all along. That saves me. That is the warm sun on my face, and I will guard you with my life until the end of days.##/p>";
