<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Bully Culture##/h1>
##p>I�m going to tell you what�s wrong.##/p>
##p>You know why everything is such a mess?  You know why all the women are mad?##/p>
##p>Because way, way back, when Jesus roamed the world slaying dinosaurs with crude stone tools, men and  probably women, really (yes, really, probably women with babies to sing to) invented language.##/p>
##p>No, really. That�s it. That�s what happened. Everything else was just an inevitable consequence of the original offense.##/p>
##p>Before that, you see, it would have been impossible for the small bands of humans who were at the beginning of human language to survive in the constantly-changing world, unless they could rely on across-the-board participation and co-operation; everyone had to do their part, women, men, and children, and no one was spared. The women would not have been slaves ##em>(Edit: Yes, they could be made slaves. I�m speaking generally),##/em> and women were not expendable, or we wouldn�t exist.##/p>
##p>Life before language would have followed inbuilt patterns, nature without nurture. There would be some cultural overlays � the ##em>Three Grunt Opera##/em>, perhaps, but without question ##i>Rock Here Rock There##/i>, now attributed to Rrrrr in his Nnnng Period � but mostly, if you can�t talk about things, you can�t record things, so you only know what your family tells you, and life from generation to generation changes only in trivial ways. You do what is natural, and there�s no one to tell you what to do.##/p>
##p>So aliens come down and teach humans to speak.  Just let it go, it�s easier this way; aliens come down and teach humans to speak. As soon as they can speak, humans start creating modern culture. At first it�s only a mild case, but eventually culture catches on.  With language, it�s possible to start sharing ideas, instructions, and directions, then jokes are invented, which holds up progress considerably, but after a while, history begins to happen.  Trivial changes accumulate at a much higher rate.  Language skills improve. Food supplies are regulated. Alex Trebek makes his first appearance on Jeopardy. And then, the first rules appear. And then the second rules. And then it all goes to hell.##/p>
##p>Now you have both history and rules.  Rules that transcend generations are called laws.  First language, then history, now laws�what�s next?##/p>
##p>Law enforcement. There�s no law that�s a real law that isn�t enforced like a law.  Even today, a law that isn�t enforceable isn�t a law.  We have just witnessed the invention of the power differential, because when the boneheads are around, it isn�t likely to be the soft little delightful ones who get to do the enforcing, now is it? And if it�s always the same bonehead who gets to do the enforcing, then soon it�s the Bonehead-in-Chief deciding for himself what needs enforcing and who doesn�t. The first of the Bonehead-in-Chief decrees is, �Keep the women inside to protect them from us�. Thus, the Protection Racket is born, and Patriarchy is off to a flying start.##/p>
##p>(##em>Edit: No, I never said patriarchy isn�t real.  I said I never got to be part of it.)##/em>##/p>
##p>Are you still along for the ride? Because here�s where it gets nasty.  Some jerk named Mr. Potamia from the Land of Endless Summer starts making little triangular marks in leftover clay, one for each of the cows he owns, so he can show his Bovine Managerial Assistant how many cows he has to take care of, and how many he had better have in the morning when I get back.  Sorry, that�s what language is like sometimes; it�s invented for boring reasons.##/p>
##p>So eventually little marks become cuneiform which becomes the first and only written language which uses sound-marks instead of picture-marks, or, not, and it becomes one of the written languages that sticks with the pictures.  Anyway, now you have writing, and you can keep track of how rich you are, and now you can write down the laws that protect you and your cattle so that the laws outlive you and make your sperm powerful.  And now, you can hire your own enforcement, and invent kings and kingdoms and dukes and dukedoms and counts and counties and bailiwicks and bailiwickies�you get the picture.  Now you have possessions, and Woohoo! possession is ten tenths of the law.##/p>
##p>After several very long times of using writing to enshrine laws that concentrate power in the hands of a few bullies, you have a bully-culture built on bully-power. Now, bullies have inflatable heads; you can�t drown them, and the heads on those things expand as fast as hot air can be manufactured. When they get so big that bursting one will kill everyone around, you have a �Bully System�. Economists define it as follows: big fish eats midsize fish, midsize fish eats small fish, small fish eat extra-small fish, extra-small fish find out the hard way that, too late, the smallest fish have evolved handguns. Yes, fish do not need a bicycle; they need a handgun.##/p>
##p>You should have seen that coming. So now, bully-power is long since enshrined, concentrating all the money and fun in the bullies� own Bully System, every bully and wannabe bully is armed unto the back teeth, and the delightful ones, now called women, are�well�slaves. When the �Bully System�, or the �Violent Ponzi Scheme� if you prefer, runs out of things to possess which aren�t pre-possessed, ##em>harsh drum roll please##/em>, War, Famine, Disease, and Death, roll into town, now featuring Religion in an iconic performance. It�s time for war, because now we�re going to have to acquire possessions that aren�t ours from people who simply refuse to let us have them, or�we�ll have to stop wanting things.##/p>
##p>So now we have war famine pestilence death, oh yeah, and slavery, etc., and hmm�now Religion is running the show. We are in a world of horse potatoes, and we just hired someone dressed in something called a cassock, who hates us and doesn�t allow us to enjoy life, to represent a god who also seems to hate us, and who looks very not surprisingly exactly like the guys who brought us a world of horse potatoes in the first place, and they say that the god has decreed unto us that we will live in a world of horse potatoes, forever, or until the aliens come back down to correct their mistake.##/p>
##p>I told you I�d tell you what�s wrong.##/p>";
