<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Before I declare peace...##/h1>

##p>I&rsquo;ve spent my entire life tolerating casual and undeserved insults to my person. I&rsquo;ve been called a closet pedophile, a rapist, and a wife-beater, and that&rsquo;s just by the people who don&rsquo;t know me and wouldn&rsquo;t care to. I&rsquo;ve been accused of using my penis as a weapon, which, as the bearer of the weapon in question, is the stupidest idea to afflict the cosmos since pre-melted marshmallows showed up at the food rental. I suspect, with reliable if vague reasoning, that I&rsquo;ve been told that I&rsquo;m a sexist at least 666 times by women who don&rsquo;t know me. Not a problem; my wife tells me that I&rsquo;m the sexiest every day, and she do know me&hellip;she know me good.##/p>

##p>The same activists who decry every perceived insult to their human rights, no matter how trivial it may be, advocate with straight faces the publicly-sanctioned dehumanization of half the population. Their reasoning is simple and inflexible: men in the past were bad to women, so men of the future must be compelled to voluntarily give up the right to a fair and public trial, because men always give up their rights voluntarily. Men will agree, just to be nice, that they will be considered guilty of rape charges until proven innocent. What sort of man would not agree to a reasonable demotion to second-class citizen?##/p>

##p>Normally, stripping the rights from a citizen requires an Act of Parliament, at least around these here parts, and applies to only the most egregiously criminal of miscreants, e.g., killers, rapists, drug dealers, and the guy who wrote that stupid MacDonald&rsquo;s jingle. The worst I&rsquo;ve done hardly qualifies, whether or not the statute of limitations on bonehead moves has passed. I&rsquo;ve been told, more than once, that I don&rsquo;t deserve the protections of inalienable human rights, because I&rsquo;m a &ldquo;white male&rdquo;. Better that, I suppose, than a white whale, which is without a doubt a way bigger Dick than I am. Come on, that was funny. Lighten up.##/p>

##p>A trial behind closed doors is not a trial; it&rsquo;s a tribunal, and it&rsquo;s patently unconstitutional by any measure. It won&rsquo;t happen, because I and a lot of other men will blow up the world before we&rsquo;re frog-marched into a kangaroo court. It&rsquo;s not going to happen, and trying to make it happen will cause nothing but trouble. It won&rsquo;t be the activists who stick around to clean up after the riots and raids. Activists are loud, but they can&rsquo;t fight worth a damn when the feces go airborne, because they&rsquo;ve never thought past the verbal abuse and confrontations long enough to solve the problem. Social activists and vigilante do-gooders, in the long run, sacrifice the happiness of millions of women and their families, to no visible benefit to anyone else at all. Opportunists both misandrist and misogynist will keep upping the ante, until they&rsquo;ve successfully created an unbridgeable social divide, leaving a billion women exposed and defenseless on one side, and an imaginary socialoid utopia rounding up the usual suspects on the other.##/p>

##p>Gender warmongers have never done anything positive for women. Gender peacemakers have done a lot for us; everything that matters, in fact. The real work of the women&rsquo;s revolution was done by working women, and the men who volunteered to help; selfie-addicted junior feminists do nothing but hurt people. They have no vision other than conflict, no method other than confrontation, and worst of all, they have nothing&hellip;nothing at all&hellip;to negotiate with. The latest Terror will end when people get tired of being pushed around; the zombies of both the left and right will find jobs in academia, drug-dealing, or literary enforcement, where they can plot, plot, plot, all to their furry little hearts&rsquo; content. When the grownups decide to send the zombies home, the women&rsquo;s revolution will have been set back halfway to Wade v. Roe. If you do nothing but cultivate anger and injury, you harvest nothing but anger and injury.##/p>

##p>I&rsquo;m tired of the wars, and I&rsquo;m not the only one. It&rsquo;s boring, and petty, and we have to end it. I&rsquo;m doing my part&hellip;deep breath, nervous cough&hellip;so I&rsquo;ve registered in the Women&rsquo;s and Gender Studies program at Brock University, here in St. Catharines. I&rsquo;ll be starting courses this fall. I suspect that I will cause quite a stir; I don&rsquo;t know yet what that stir will be. I will be reporting to you via this blog while I&rsquo;m doing it, and attaching whatever interesting documentation or knock-knock jokes I am privy to. I&rsquo;m going to tell you what&rsquo;s in those textbooks, and what gets said in the classroom. I&rsquo;m going to report classroom-politics, particularly when they involve me, but before you get your friend&rsquo;s knickers in a knot, read the rest.##/p>

##p>I clearly state for the record that I have no intention of doing a hatchet job, or picking fights. This is not a slow-motion provocation. I will refuse the politics; I won&rsquo;t be reporting students&rsquo; names or any other information that can be traced to them; I won&rsquo;t be recording anyone but myself and willing, informed participants. I won&rsquo;t be using pejoratives, and I will try to be as unbiased as possible. My motives are clear and simple: I would love this project to help bring the social civil wars to an end. They have to end, or people who have something to lose will lose it. Families will be destroyed, careers ruined, suicide rates will rise&hellip;these are not acceptable collateral in a war more about ego and vengeance than about equality. In a social civil war, if you really want to win, you DECLARE PEACE, and you make it stick.##/p>

##p>The side which declares peace first almost always wins, because people get sick and tired of fighting, and you look pretty useless standing there in your mother&rsquo;s army boots when everyone else decides it&rsquo;s over and goes home. Putting a firm stop to the zombie terror would do a lot more for the women&rsquo;s revolution than all the academic feminists of the last fifty years have done. The zombies will eventually owe me big for saving them the embarrassment of a public spanking.##/p>

##p>You can&rsquo;t successfully intimidate, threaten or bluff me, and I&rsquo;m getting a book out of this project no matter how apoplectic you get, but, as an author, my write is usually worse than my bark. Writing requires a certain over-the-topness every now and then, to get the blood moving, and writing is my joy and passion, so you&rsquo;ll forgive the occasional bit of descriptive excess. The fembies make me mad, but they aren&rsquo;t feminists. Feminists are fine with me&hellip;outdated and&hellip;um&hellip;er&hellip;boring?, but fine, whatever. The world sucks when girls aren&rsquo;t having fun &mdash; there&rsquo;s not a man in big-boy pants who doesn&rsquo;t know that. Have you never heard a man repeat some variation of &ldquo;happy wife, happy life&rdquo;? Have you never visited Earth? Then you&rsquo;re deliberately not listening. I don&rsquo;t like making anyone unhappy; I dig happiness, and I&rsquo;ll rewrite your place in the cosmos if you ask me nicely.##/p>

##p>If you don&rsquo;t like what I&rsquo;m doing, and you don&rsquo;t like what I&rsquo;m saying, then you can be an ass about it, or you can help me. You can write your own chapter, and if it&rsquo;s worth a nickel, I&rsquo;ll put it in my blog and my book. I won&rsquo;t let you tell me what I can put in, but I will discuss fairly anything I say or am oblivious to. You can&rsquo;t accuse me of any of the usual suspicions, because it&rsquo;s all going to be right there, where you can see it. My agenda won&rsquo;t be hidden. I won&rsquo;t be playing games; I will NEVER play head-games unless it&rsquo;s fun for all. In short, there won&rsquo;t be any real reason to obstruct me. Besides, why attack me when I&rsquo;m offering you the power to make friends and influence me? I&rsquo;m pissed at a lot of things, but I&rsquo;m fair at the worst of times, and I&rsquo;m invariably polite if you don&rsquo;t eat the goldfish. If you hate me at the end, it&rsquo;s not because I wouldn&rsquo;t talk to you.##/p>

##p>Aside: I admit that I&rsquo;m not completely calm. I have a little of the butterflies in the tummy reaction going, which I find very interesting because maybe my stomach is smarter than I thought, but it&rsquo;s nothing that will last the night. I&rsquo;m unsure as to what kind of reaction I&rsquo;m likely to get, but there will be one. I hope it is a genuinely positive one which leads to a collaborative work but with my name on it, leading to a constructive and popular proposal for ending the gender wars. People will have to listen to me. Most of them won&rsquo;t, but some might; when people shut up and let me talk, which happens rarely, they&rsquo;re usually surprised to discover a sensible and fair person under the author&rsquo;s wig.##/p>

##p>I doubt I&rsquo;ll get any takers on my offer, but since I&rsquo;m pre-calling their bluffs in writing, accusations won&rsquo;t be sticking to me later. Anyone who cares can advise me, and I&rsquo;ll take it seriously. I might be the only one who does; people who do nothing other than fight probably won&rsquo;t recognize a reason to stop fighting until it shoots them in the conscience. You can&rsquo;t bring your war to my party, but you are invited, so don&rsquo;t come whining to whomever I leave in charge later.##/p>";
