<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Democracy in Trouble##/h1>
##p>Democracy is in trouble.  It�s true, but you still shouldn�t believe it.  It�s too hopeful.##/p>
##p>It�s actually way too late already to call it �trouble�.  Democracy is a dead man who just won�t fall down until the next earthquake.  There is no remedial work to be done: we are long past the point of no-return, which is the delusion procrastinators apply to �never-was-a-return-in-the-first-place�.  You don�t �fix� democracy; it would be profoundly undemocratic to meddle in the natural, if sad, evolution of culture; fixing democracy would mean fighting over how to fix it, and what the result should be.  And by the way, yes, I said �the evolution of culture�, so don�t get your nature-nurture knickers in a knot; evolution and culture are not separable.  That�s the other subject.##/p>
##p>Democracy started its long, agonizing slide into obsolescence the day that Reagan and Thatcher realized that you could simply ignore the weak as a socioeconomic irrelevance, and maintain power with the money you save by �promoting independence�, which is very expensive talk for �setting a price on equality�, or �compassionate conservatism�.  They proudly and very-whitely initiated an era of me-first politics: you can�t claim to represent all the people if you revile half of them.  All that �thoughts and prayers� crap is an embarrassment to God: the right no longer even tries to make sense, and people who countenance gun violence, taking children as hostages, subverting the courts and banks to their own profit, gutting the welfare systems, and redefining �security� as �it�s us or them� really can�t call themselves compassionate.  They do, anyway; dictionaries are impossible to find these days.  There is not a chance in hell that the responsible right of the fairly-recent past, no matter how otherwise odious their beliefs might have been, would have openly sung hosannas to segregation and discrimination, under the most incomprehensible of rationalizations.  There is no aspect of the modern right which is not infected by the I-got-mine virus.##/p>
##p>And where has the noble left been, while self-interest and smug arrogance grind away at the foundations of democracy, relentlessly undermining consensus, compromise, and diplomacy?  It�s been right there, ignoring us.  The left as a political force is, in a phrase, never there; they�re out somewhere yelling at their inferiors. They�re hiding in academia, inventing reasons to do nothing until it�s too late.  The whole left has become a huge club dedicated to selfies and whining; they neither protect the people nor represent them.  In lockstep with the predatory right, they spend all of their energy, meaning �all of their energy�, on bringing new minorities in and keeping old majorities out.  The first problem is not that they want to represent the disadvantaged; it�s that they cherry-pick amongst the disenfranchised whom they consider worthy of defending.  They don�t �represent� anyone at all: they anoint themselves the champions of the oppressed, and nobly lose battle after battle on their behalf.  Their idea of bringing in reinforcements is phoning the Amazon basin to see if there are still some uncontacted, anti-capitalist, ethnically-pure heterophobes hiding deep in the darkest jungle, waiting to be represented to the man.##/p>
##p>Both the left and the right are trapped in a hall of mirrors.  Self-obsession and false nobility are lauded as moral ideals, and compassion is a lucky side-effect of their ever-updating policies. They love conflict more than people, which is manifestly futile, stupid, and suicidal for everyone, starting with themselves.  That means, and I apologise to suicidal humans for the comparison, they�re too dumb to know that they�re bleeding to death from self-inflicted shotgun wounds to the pedal extremities, and they�re too venal to see that they�re taking the entire democratic system down with them.##/p>
##p>Democracy is dead, because civility is dead.  Civility is not a synonym for �polite�: it means �The Golden Rule� applied to the daily interactions of the citizenry, without relation to m.  Remember that crazy shit? Civilization doesn�t breathe without it.  It manifests in every moral structure we maintain, either in absence or in presence: do unto others, the Categorical Imperative, pay it forward, turn the other cheek, honour your commitments in business and home, etc.  They all mean the same thing, and they are so perfectly ubiquitous that they can only be embedded in the human brain: kindness is an evolutionary strategy so successful that all the narcissism in the world barely dented it, until now.  People like each other, so they treat each other nicely: that�s called community, and democracy is how nice people rule nice people.  The left and the right both stopped being nice people a very long time ago.  Funny as it definitely sounds, bad manners is ruining the world we live in, and yes, it�s your fault, and no, I will not go fuck myself for saying so, asshole.##/p>
##p>Isn�t it just so irritatingly annoying to be the one standing on the sidelines, watching everybody lose at a game they say they�re not playing?  It must be how God feels when half of His children die in a bus accident, while the other half sing His praises for not being amongst the dead themselves.##/p>
##p>I can�t just watch and wait.  I know it�s already dead (you do, too: admit it); I just wasn�t ready to say goodbye.  I loved democracy.  I am bereft, and the suspense is killing me.  I�m going to tip the body over and cook it with gas, right here in front of you; I�m going roast marshmallows over the flames while we dance widdershins around the firepit, until the ashes unburn and the Firebird, democracy�s golden phoenix, rises in its unmatched glory to set the world aright.  Democracy is dead, democracy is coming soon to a reality near you. I guarantee that you are not ready for it; next time I run out of doobies I�ll tell you why.  Wanna blaze?##/p>

##p>We are watching democracy die; some of us will attend the wake, and the greater number will mumble homilies as they add their tears to the rain. Woohoo, homilies!##/p>
##p>You�ve heard of this guy Trump. When it first started to look like you poor suckers would elect a fictional character for your Prime Minister or Patotus or whatever, we all felt the pain with you, in our frozen-mukluks way. Nobody wanted our neighbours to suffer under the seat of Trump�s golden toilet. We hoped, without saying much, that some no-such-dude working for some no-such-organization would take him out. Yes, I know many people who wished he was dead on your behalf. Things are weird right now, but we love you.##/p>
##p>Our sympathies are genuine, and I offer mine. My long-distance radar, however, is picking up stirrings of things our friends stateside probably won�t like the sound of. The USA is in serious self-inflicted pain right now, and the outlook for them is not at all pleasant. The entire global econosystem (new word alert!) has been in orbit around the US for almost a century. Global security has hinged on the American mood for even longer (that is another kettle of bouillabaisse altogether, but I�ll get to that later, maybe), and in spite of the terror which gripped the world while nuclear weapons were young and generals were moral robots, America has provided an unshakeable foundation for peace: there has to be at least one guy in the playground no one can ever win a fight with, and who will take your side when the feces go ballistic. Vietnam beat the crap out of their egos, but the US invaded Vietnam; if Vietnam had invaded the US, it would have ended in hours.##/p>
##p>Viet Nam is an excellent example of the wages of hubris. Viet Nam was plain stupid, and it took two decades for the rest of the world to forgive it, and no matter how you wrap that fish, it�s ultimately bad for business, every time.  The world hasn�t forgotten the war of entirely unjustifiable aggression against Iraq, either, but at least that ended quickly.  Sadly, the US hasn�t even tried since that bonehead move to rehabilitate its reputation; instead, it continues to bluster and blunder as if someone still cares, and that�s even embarrassing for their neighbours. What�s happening now will be far more cataclysmic to Americans than those mere peccadillos of historical idiocy. Why, you ask with minor exasperation? As usual, I�ll tell you, and you can assess the odds that I�m right for yourself. I have high confidence in this one, though.##/p>
##p>And the answer is:##/p>
##p>Money. Capitalist play-dough. Stacks of paper rectangles with arbitrary values. Imaginary buying-power.  Are we in perfect accord now?##/p>
##p>Now that Americans have replaced their own Leader of the Free World with Captain Underpants, they no longer honour contracts or negotiate in good faith, their capitalism has descended into corruption, their military is no longer a reliable ally, and most unhappily of all, they no longer succor the huddled masses yearning to breathe free. In short, the King of the World has abnegated every quality and abdicated every power which made America so valuable a linchpin for the whole globe. They still think they�re the King of the World, but they live in a palace of mirrors. The world has moved on, and America, for the first time in a century, has been left behind.##/p>
##p>We, meaning every single living Canadian, sat watching in disbelief as the America that we love without knowing it went to hell in its own handbasket, agonizingly slowly, for months. We watched, moaning in sympathetic terror and disbelief, as that weird College of Electors perversion elected a sick, stupid, lying bastard to the throne, for the sole and simple reason that he definitely doesn�t have a vagina or a brain to operate it.##/p>
##p>Throughout, I was (perhaps obnoxiously) telling anyone who hadn�t yet refused to listen that it�s actually really good  for the whole world.  This is the Fall of the Roman Empire, not an embarrassing blip on the news. The United States of America is still, technically, king of the world, sort of, but the Grand Imperial Potus is no longer the Leader of the Free World by default. You know the Empire is on its last legs when even Caesar�s quislings and servants laugh in his face while looting the treasury behind his back.  Watch for Trump�s cover to melt away as soon as his purpose has been fulfilled, and see for yourself what�s left when the fog of American confusion blows away. Don�t be thinking of Louis XIV anymore�it�s about Louis XVI and Marie Antoinette. The difference is that today the mob doesn�t really want their heads. We just want to make them shut up and go back to hiding in their golden closets like good little billionaires, because they�re totally incompetent. Like, massively, colossally, stupendously, magnificently, amazingly  fucking incompetent.  Could not run a country of robot slaves without fucking it up. They�re rich. They�re alphas. They�re surplus.##/p>
##p>This is the end of the American hegemony, the end of the bully diplomat and the economic overlord. You cannot continue to flood reality with transparent lies and vacuous posturing, expressly and explicitly insult and undermine every communal institution, and still command respect at the negotiating table.##/p>
##p>The silliest Dear Leaders of the world defy the greatest military power of the world openly and without fear, because they know that it�s all bluster and blow; when the US is threatening Mr Peanut with atomic bombs, the jig is obviously up. The US  the Americans can no more make the nuclear button option stick than any more than any other country in the world can. The generals  of the world won�t allow it, because for them, the threat of war is only a prelude to a highly-profitable peace; if they blow up the world, they lose their jobs, and that isn�t good business. The generals are the ones who are quietly saving the world from themselves, and God bless their shiny little cannons.##/p>
##p>Everyone in the world knows that China is coming. Everyone in the world knows that India is coming, Russia is coming, Brazil is coming, Mexico is coming, Vanuatu is coming, and Canada is reluctantly deciding whether to accidentally leave open the back door for them or not. Our greatest friend and ally has have either cheated or reneged on every major economic agreement it has made. It�s suicide in slow motion. Note to self: this is what �business knows best� means. There are plenty of smart Americans of course, and they see what I do and more, and with better insider knowledge, but I cannot imagine, without vapage, like, good, really good vapage, how the shining scion of Capitalist Enterprise could have cut itself off at the knees in order to make itself stronger. Those alliances and agreements between honourable nations are the Silk Road that lead to the Mandalay of the American market; the Silk Road has been closed, the way the Suez Canal was closed in the last century, and the economy will have to work around it. Global work-arounds cost a lot, and in a sizable fraction of cases, the weaker side ends up holding the cards.##/p>
##p>The preceding, all of it, is offered as evidence from the crime scene. I need to build a convincing case for the various hypotheses of ##em>Phoenix in Flames, part 1##/em>, so I need you to see that we�re no longer looking at the microcosmic; it�s the macrocosmic picture we need right now. We need to see ourselves from space, because it becomes more and more apparent every day that we are floundering. and blustering in the face of the most serious issues since the last global extinction event. We are arguing about words, about names, about borders, about budgetary trivia; hang your heads in your hands, folks�we�ve spent ten holy-wtf years deciding who gets to use which public toilet in which bailiwick. We are arguing about the temperature ten holy-wtf years in the future, while we incinerate ourselves and everything that comes with us. We have no time left for trivia, because the feces are already airborne, and the grownups are stepping in.##/p>
##p>In the macrocosmic storybook, entropy always wins. Everything comes to an end, and the only thing humans can do is slow things down in the little eddy of spacetime we occupy. When you pass the point of no returns, you don�t keep throwing good money after bad; that�s delusional behaviour, so leave it to the delusional people. It keeps them happy in the little sandbox they share with the cat, and they won�t get in the way if we don�t keep demanding their attention. There is nothing left to fix, there is no time to fix it, and there is no payoff for the fix; game over, no redos.##/p>
##p>When you can�t save the house, you set the kitchen on fire. You let fire cleanse, as fire does, and you wait. You hide in the rubble, watching from a distance, as democracy burns to the ground. You don�t put it out; the flames must consume hypocrisy and corruption in the most obscure of corners, and you must have the strength not to interfere.  You handle the refugees. You do no harm. You conserve humanity and compassion, because they are the building blocks of civilization, and it was in forgetting them that we almost lost our souls. You wait until nothing remains but cinders and dust, and I guarantee you it will be the longest moment of your life, even if it is over in a single breath.##/p>
##p>And in that moment of finality and birth, the Firebird will rise from the ashes, searing the blinding future into our inner eyes, and we will put on our mukluks and get to work. I will tell you what I think we can do, in the Phoenix in flames, part 3.##/p>
##/div>";
