<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Ethical Porn##/h1>
##p>I was reading ##em>Elle##/em> this afternoon &mdash; sorry to disappoint you, I was waiting for my doctor &mdash; and I stumbled after looking it up in the table of contents onto an article about porn.  That&rsquo;s how it was labeled, but that&rsquo;s not what it was.  It was an article about why porn for men is bad, and porn not for men is good.  The arguments were exactly the same old same old you expect from a junior freelancer writing filler.  I&rsquo;ll get to them, I think, but the point was clear and had nothing to do with the subject: men are defined by the worst of what is offered to them, while women are defined by the best of what they create.  Men are defined by the knuckledraggers, women are defined by whatever has passed this year&rsquo;s Betty Crocker Housekeeping Seal of Approval.##/p>
##p>It&rsquo;s a load of bullshit without even going into the arguments.  It&rsquo;s a load of bullshit because people who have the conviction of their dogmas don&rsquo;t have to be &ldquo;breaking new ground&rdquo;, or &ldquo;challenging established sexualities&rdquo;, or any of the other rituals of braggadocio that accompany approved porn.  They don&rsquo;t have to, because they&rsquo;re equals, and they can stop pointing out everyone else&rsquo;s inadequacies and stick to their own ethical shortcomings.##/p>
##p>I don&rsquo;t care in the least about what someone eats, as long as it didn&rsquo;t cause undue suffering. Vegetarian is just a diet choice to me, and I don&rsquo;t judge the ethics of others based on their shopping preferences, so I cannot resist babbling in annoyance at the rows of &ldquo;ethical&rdquo; food.  I&rsquo;m sorry, Ethical Food, but you&rsquo;re a label, and I&rsquo;m a human, and I don&rsquo;t find it appropriate that you scream at me from every shelf in the health section.  It&rsquo;s food; it&rsquo;s no one&rsquo;s right to judge most of the world evil, insane, or stupid, because they bit a cow.  I&rsquo;m not unethical for buying food, and it strikes me as one stop short of terminally pathetic that some people believe that they&rsquo;re better people than I am, simply because I avoid labels which harangue me in passing.##/p>
##p>Well, that&rsquo;s how the approved &ldquo;feminist&rdquo; porn is advertised.  No one involved seems to be able to talk about it without telling you how brave and honest it is because it doesn&rsquo;t have that male-oriented icky stuff in it.  You can&rsquo;t get the action without the lecture, and the lecture is exactly the same, with the men as the meat-eaters.##/p>
##p>I, like, oh&hellip;everybody, don&rsquo;t need a side-order of feminism with every meal. The idea that I&rsquo;ll somehow be more aroused because feminists have vetted the realism of the female orgasms is not even ridiculous.  I&rsquo;m sorry, but &ldquo;aroused&rdquo; and &ldquo;feminist&rdquo; don&rsquo;t go in the same sentence, unless they both have &ldquo;double quotes&rdquo; around them.  I don&rsquo;t know any men in the entire cosmos who will spring an ethical woodie at the words &ldquo;ethical sex&rdquo;.##/p>
##p>And why not?  Let me speak for the knuckledraggers on this one.  First, it&rsquo;s going to come with a put-down of whatever you keep as your don&rsquo;t-tell-the-female secret, squashing hopes and dreams she didn't even know you had, which is your fault because you didn't tell her, but which is their fault for making both of you feel guilty about everything. Second, it's going to come with a put-down of your penis, couched in the usual explanation of why women don't enjoy \"penetrative\" sex as much as you think they do. It will more than likely be written by a woman who loathes your penis, and frequently tells people that you think with yours, which of course means that you only feel with yours, too.  You'll receive a condescending explanation of why warm fuzzies are what everyone really needs, and everything else is against women, even if they made it themselves, because if it's bad, a man made them do it. Finally, you'll get an explanation of what men must learn in order to \"truly please\" a woman, which means \"us\", and it will have nothing to at all do with fucking, and a lot to do with a series of escalating tests you must pass to really, truly, finally understand what love is all about.  Eventually, you'll come to understand that the only real sex and the only way to show love through sex is by doing it exactly how girls like it, which means \"according to politically-approved guidelines\", and that any girl who doesn't like it the way ##em>they##/em> say girls like it is either not really a girl, or is a dupe of the patriarchal conspiracy.  And then sex stops, and the world ends, and nobody lives happily ever after. Satisfied?##/p>
##p>Here's my two cents: go fuck your own way, and let other people enjoy what they like. If you reach the age of 30 and you still think penises have cooties, seek help. And by the way, I don't do \"penetration\" with my wife. She invited me. See how that works?##/p>";
