<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>The Edge of the World##/h1>
##p>People have told me I�ve changed in the last few years, that I�ve lost my patience and my famous good manners. I haven�t: I just don�t make as much of an effort to tolerate other people, or to make them tolerate me. Me trying to be normal for the company is great for the company, but there�s nothing in it for me.  I no longer feel a need to please people whom I don�t believe would make any such effort for me; I�m naturally kind and polite as it is, but now it�s much more dangerous for people to be rude to me than it used to be, and I gather that bothers them. It has done wonders for my complexion, though; also my sleep, my weight, my energy, my moods, not to mention I no longer roam the moors at night looking for victims. Pleasing people to get their approval doesn�t work; I would please them, but they would never stay pleased for long, and they do not return the effort.##/p>
##p>Some people feed off my addiction to their approval.  When I broke the addiction, people who are used to treating me badly treated me worse; they seemed hurt that I wouldn�t play the game for them anymore.  When that happens, all irony breaks loose. It�s me, the crazy one, the disabled one, the one who can�t, who ends up doing all the work of diplomacy and kindness, not the people who can do it easily. If we succumb to the addiction, relapse into needing approval, we, the crazy people, end up coddling the lucky people, reassuring them, apologizing to them endlessly, promising to be back to not being ourselves when everybody wakes up. We, the crazy ones, put the lucky ones to bed, tuck them in, and then go sit in the dark playing gin rummy with the black dog and the angry monkey, while Goldilocks sleeps the sleep of the just. Yes, I admit it: that one, that one little irony, really, really, really pisses me off.##/p>
##p>From early teenhood, my birthday wasn�t a celebration; it was a memorial. I enjoyed my parties and revelry, but they were more like welcome distractions than markers of happiness. The day itself was the official end of the memory-year, closing the old ledger and opening the new one. My fiftieth birthday party was the first joyous one since boyhood, for many reasons.  There were two quiet, internal reasons for my happiness.##/p>
##p>First, for many years, I didn�t expect to make it to fifty.  I thought I would have long since walked off the edge of the world by then. It wasn�t until I was forty that I�d even contemplated surviving that long. Before then, I didn�t even want to contemplate living that long.  My 50th birthday was not the closing of another ledger; it was the closing of ledgers. It was a triumph over time, my sworn enemy.  It was a statement of defiance.  I�m still here. Take that, reality!  I�m still here.##/p>
##p>Second, my lifelong addiction has been trying to please people by changing myself for them. That, I want you to hear and believe, is a terrible addiction, a habit unbreakable unto the very doorstep of misery. As a child and young man, I was instructed by nature, in a thousand ways, that if I only strove harder, committed more, disciplined myself more, I could use my powers for good instead of evil.  I felt I owed it to the world to live up to my wonderful gifts by mastering myself, that I might take my rightful place in the hall of citizens. My birthday present to myself was giving up. Quitting. Throwing in the towel. Waving the white flag of surrender. Chickening out.  Admitting failure.##/p>
##p>O Great Joy! O Loving Freedom! O Most Generous and Glorious Failure, that I might have embraced Thy Blessings long hence!##/p>
##p>I give up trying, because trying always ends up meaning, �Stop being you, be someone else�.  I am this; this one here, not that one there, and (n)evermore shall be so. Deal with it. I must reconcile myself to the idea that if people don�t like me, I will no longer make any effort to like them, and no, I won�t make any special effort to restrain myself if I feel a need to defend myself. Reconciling the idea�reconciling�reconciling done.  Yes, I have changed, you�re right.  I�m not going to try to be you anymore, and while I can see that offends you, I have to say�##em>meh. Meh ##/em>is a Yiddish word which means what ##em>annh##/em> would mean if it was an English word.##/p>
##p>At fifty-four, there�s no approach I haven�t tried, no advice I haven�t heard a hundred times before, nothing new to learn, and a mountain of evidence that I can�t fit in an way but mine, ever, and that trying to is ruining my life.  Fitting in makes people die. You can fit me, or stay away, because I�m the disabled one, not you.##/p>";
