<!-- InstanceBegin template="/Templates/standard_post_content_1.dwt.php" codeOutsideHTMLIsLocked="false" --><!-- InstanceBeginEditable name="post_meta" -->
<!------------ RGCafe blog post -------------------------
Date: 2018-09-14
Categories: 
Tags: 
Title: How to Wreck a Boy
Subsite: Love and Chaos
Number: 1014
ID: how_to_wreck_a_boy
Post description: 
--------------------------------------------------------->
<!-- InstanceEndEditable -->
	<div class="blog post default wrapper">
<!-- InstanceBeginEditable name="post_title" -->
		
<!-- InstanceEndEditable -->

<!-- InstanceBeginEditable name="post_content" -->

<p>Stop him from being a boy.</p>
<p>That’s all it takes to wreck a boy.  That’s it. That’s all you have to do; you take away his boyhood, and you replace it with girlhood.</p>
<p>Before the knee-jerk, “What’s wrong with being a girl?”, shut up.  It’s not about you, it’s about boys, male children under the age of legal emancipation. No one thinks there is anything wrong with being a girl; that doesn’t mean that boys want to be them. Boys have a complex and difficult childhood to master, no less than girls, and the cynical reduction of boyhood behaviour to a linear and predictable process of learning to be grown-up assholes instead of child-assholes is the single worst impediment in the road of social progress.  Nobody learns nothing when nobody’s listening to no one, right?</p>
<p>The whisper-attack on boys and boyhood has gone on for so long that it hardly gets noticed.  Girls are treated as special in every way, as if boys should pay in loss of status for the moral debts of their fathers.  So little attention is paid to boys that their standards of education are falling, their ability to work productively is failing, and their ability to socialize ethically is being compromised.  Their self-esteem is constantly under attack by the social workers and teachers who claim to protect and represent them. They are brought up being told daily that they are rapists at heart, before they even know what it means.  They watch girls excel through girl-power programs, while they’re given daily instructions on why being a boy is evil, and saddled with long lists of things not to do.  They’re told not to fight, not to wrestle, not to play with guns, not to try to win games, not to stand up for themselves, not to be aggressive in any way if females are even rumoured to be present, to expect derision for every display of masculine pride, and to be afraid of women in general. That’s what solving problems by confrontational methods alone is doing to our children.</p>
<p>The price of trying to change people is distrust, and distrust is the chief ingredient of hatred. The wages of fanning the flames of distrust is burning your own ass to the ground, which is your problem, but taking children down with you is unacceptable.  Our obsession with “equality” has devolved into a dogma of enforced symmetry, and has become a huge, ungoverned, ridiculously unsophisticated experiment using children as test subjects: let’s see what happens if we undervalue half of our children and overvalue the other half.  Will it lead to a new era of harmony and healing? Will it cure boys of toxic masculinity? Will it make ordinary women happier?  Would most women prefer neutered men to unaltered men?  Would you?</p>
<p>Those questions are not real.  The only real question is, “will it make the child happier, or are you using him to prove something? Is it about him, or is it about you?”</p>
<p>I have to say rather obnoxiously so you hear it that I don’t see much difference between parents who put their children in beauty pageants and parents who use their children as test subjects. None of the parents I’ve heard of or have known who use their children in this way has ever done any research into the claims they make. They don’t look up some research to see whether childish weapon-play really leads to abusive treatment of women; that is, after all, what they claim. If they did their homework, they’d find nothing, because it is literally impossible for such research to exist. If the scenario is “toy guns lead to real guns, real guns lead to violent natures, violent natures means violence against women, plus orphans, don’t forget the orphans”, then there should be no women left alive right now.</p>
<p>If the research says that “90% of boys in our culture have played with guns”, then the 90% should have a significantly higher crime and murder rate. It should be a statistically-meaningful number, not a debatable one; no 1% fudging.  That number would mean there’s a lot of violent men everywhere, all the time, and that the more guns there are for children to play with, the fewer adult women there should be left alive. There should be more men than women, in any culture in which children play with handguns. You check the demographics for yourself: there are way too many women walking around in total freedom in every social stratum for the theory to be true. QED.</p>
<p>What if we get all generous and misguided, and we take the “leads to violence against women” part of the slippery-slope out?  Now handguns lead to real guns, real guns lead to mayhem; that might be a testable hypothesis, so we need to treat it seriously.</p>
<p>First question: what other childhood toys or games have lifelong, irreversible, unmitigable effects on children who play with them? Do toy stoves make girls into kitchen slaves? Do teddy-bears lead to widespread teddy-bear fetishism? Does chasing Mary-Lou with a water balloon turn a boy into a stalker?  For the theory to be true, an increasing number of children should be turning into fine-art painters, reflecting the steady increase in the international crayon trade over the last 67 years. Q…</p>
<p>Second question: why does it only happen to boys?  You keep saying that boys and girls are alike at birth. How is it that all the talk about violence revolves almost exclusively around men, if we’re all the same?  Shouldn’t girls be symmetrically and equally subject to the dire consequences of weapon-play?  Shouldn’t they be just as likely to engage in it? They should be enjoying it as much as the boys do, if they all have the same brain. Where are they? …E…</p>
<p>Well, we can still fudge our way around that if we resort to conspiracy-theory: we teach boys one thing and girls another; what we teach to boys is violence, what we teach to girls is victimhood.  So, third question: if we teach violence to boys who are exactly the same as girls, there should be a huge number of little boys clamouring to do what the girls do.  If the girls enjoy it, the boys should enjoy it as well.  Their fathers should have enjoyed it as often as girls do.  Every man in the world should have enjoyed is as often as girls do, and yet somehow, society teaches boys exactly the opposite: don’t enjoy what you enjoy because girls enjoy it, and embrace hatred and violence instead. That is, remember, what the theorists say: society conditions boys to violence. How does such asymmetry develop if all our brains are the same?  The theory only works if boys respond differently to the same stimuli as girls, which means that they are not the same, and never were. You can’t have a society which teaches evil which is entirely made up of people who believe in good, because society <em>is</em> those people, by definition.  …D.</p>
<p>Some debates are not applicable to children, ever; children are all equally valuable and worthy of love, and there’s no excuse for sexism against children.  I’m an adult, and, yes, fuck you, I’m a man and you can’t hurt me, but boys are children — vulnerable, sensitive children — who want nothing more out of life than to be themselves.</p>
<p>The notion that masculinity is a form of original sin visited upon boys at birth is an outcropping of the long-since discredited notion that boys and girls are exactly the same  at birth, and can be molded not only to exhibit desirable traits in terms of socialization, rights, privileges, and powers, but in terms of sexual identity as well.  We are, the theory goes, all <em>tabula rasa</em>, waiting to be shaped and molded in the image of our society, through the power of the family; all the ills of the world can be traced to the fact that boys are not raised to be girls.  Likewise, the solution to every problem is “make boys be girls”; make them soft and gentle, make them play with dolls instead of swords, enforce tea parties over rough-housing, and stamp out aggression at every sign.</p>
<p>That’s not what happens.  You don’t make them soft and gentle; if they are that, then they are, but if they’re not, you make them fake-soft, fake-gentle, and resentful towards women.  The evidence is in, right beside global-warming and the fall of democracy: the more you mess with the rights and privileges of boys, the worse they are to women, and it’s because women still think, against, oh…150,000 years of evolution, that they can fix men.</p>
<p>Holy shit, did he really say that?</p>
<p>Yes, he did.  He said that women are trying to fix men, and it’s a disaster.  How crude! How unnuanced!  How obvious!</p>
<p>There’s a theory, popular amongst the creepier leftists and feminist warheads, called “Toxic Masculinity”.  It’s a pretext for a program of social-eugenics, meant to turn the development of normal masculine characteristics into a crime.  It’s as stupid as any bigotry can be; you can take any claim any eugenicist makes and match it up to the same claims used by any other eugenicist: “they” are born evil, “they” must be removed from the gene pool.</p>
<p>Nobody takes that kind of feminism seriously.  It’s like herpes; it never quite goes away, but it gets easier and easier to ignore as time goes by. When proud public haters can’t bring themselves to admit that they’re haters, their public images begin to slide. The spew of hate becomes first predictable, then irrelevant, then laughable. Militant feminism of that type has painted itself into a tiny little corner, in a tiny little  because it bought its philosophy from a fascist outlet store that doesn’t take returns.  It is stuck with that stink forever now. They’re not the problem.  If they were, they’d have been put out of business long ago.</p>
<p>The problem is that people bought into the largest conspiracy-theory in history <em>before</em> it was discredited.  The theory’s foundation is that male humans are shaped to evil by invisible forces in “society”, none of which can ever be named, and of which no concrete examples exist, but the evidence of which is “all around us”.  People who bought into the “tabula rasa” social experiment didn’t stick around to see all the false theorizing  dismantled; the zealots have their dogma, and logic be damned.  There is no evidence that boys are forced to like blue, and that girls are forced to like pink; there is no evidence that rough-housing or weapon-play leads to lives of violence; there’s no evidence that boyhood play is associated with anything except boyhood learning and fun.  What there is a lot of is evidence that you shouldn’t mess with normal human expression, because it twists people, any people.  Since when did messing with people’s heads improve the world?</p>
<p>Boys know they’re hated.  How could they not?  They know that their fathers are hated.  They have not the slightest idea why.  They know that boys are bad, girls are special, and that some grownup women really truly hate them, and say things about them, but what they’re saying isn’t true. The first thing boys learn about gender relations is that they’re unfair, but they don’t see it in the abstract.  They don’t do politics.  To them, it’s unfair in every way they can think of, and no matter what, the grownups side with the girls. To boys, to children, it doesn’t look like it’s the girls who get the worst of the deal.  You create unfairness if you right other unfairness punitively, and you create children who remember it all their lives.  That’s how boys are introduced to feminism: as an explanation for meanness plus also lying plus also not being fair.  Oddly enough, children do not grow up aware of the swirling political forces around them, engaging in glorious and noble civil tug-o-wars over the right to model their children’s personalities after completely unattainable ideals.  Who saw that coming?</p>
<p>None of which answers the original knee-jerkery: why do boys rebel so strongly, even violently, when made to emulate girls?  Ignoring the obvious reciprocal question, what is it about femininity which boys so deeply need to avoid, even to repudiate? It expresses itself in some way, in almost every boy’s life, through bullying, exclusion, homophobia, sexism, and/or violence.  Those are probabilities, by the way.  They are not definitions. Trying to turn them into stereotypes is evil, so stop it.</p>
<p>Those probabilities are applicable to every boy differently, sometimes in absence.  Pretending that the worst in boyhood behaviour is a template for further development is a cheap and easy score here, but it ignores the fact that all children go through phases of development marked by observable transitions and passages.  Boys are not a Lego building with an immutable foundation; they pass through a stage of identity-building which requires that males learn to be uncivilized goofs.  They’re little boys; they can’t hurt you or each other anywhere near as much as a sharp tongue can.  They might also like ballroom dancing, or cooking.  They may dislike competition.  They still have to go through the development of male body consciousness, which they base upon physical prowess and achievement.  If they are not allowed to do so, if they are feminized before or during this phase, they are denied a fundamental building block of masculinity: the capacity for aggression, including expression through violence.</p>
<p>Eeyagh!  Yikes! Gazounds or whatever!  Violence is evil!  Stamp out violence!</p>
<p>The sad part of the bonehead left is the two-dimensional thinking: violence is evil, so make it illegal and shameful.  That’s the left’s modern MO: identify evil and make it shameful and illegal.  I defy you to think of a leftist campaign which actually touches your life which does not follow this pattern. If you can, please, please, please…let me join.</p>
<p>You don’t stamp out evil by passing laws demonizing normality.  You make rebellion and blowback that way, not model citizens.  It’s called “repression”;  I read somewhere that women don’t like it.  Surprise! Boys don’t like it, either. You stamp out evil by making it useless, boring, pointless, ineffective, embarrassing to even try…you stamp out evil by (I have never needed a drum roll more) civilizing humans.</p>
<p>Really? That’s your answer? Civilization? That’s so not possible, with men in the world!</p>
<p>Yes, civilization: the macro-scale cultural state of civility amongst the citizens.  A novel idea if ever there was one!  You don’t fix civilization by endlessly adding to the list of things people are never going to remember not to do.  You fix civilization by enabling people to be the best people possible.</p>
<p>For boys, that means emerging from the development of aggression and violence, into a state of assertiveness and readiness for action. If you stomp out aggression with aggression, you create resentment.  If you make aggression impossible, the child will never grow out of that stage and learn the sensible limits of aggression.  The sensible limits of aggression are assertiveness and self-confidence, neither of which the boy-with-boyhood will learn in the normal way.</p>
<p>Girls go through their princess-with-dollies stage.  They like it.  They make dolls if they don’t have them.  They beg for them as gifts.  No one forces boyhood on them.  The irony is that when girls exhibit the characteristics for which boys are punished or inhibited, they’re rewarded for it.</p>
<p>Yes, boys do really need to learn violence, so they can learn not to be violent.  They need to learn assertion, not bullying.  You can’t teach children who are not allowed to show up for class.  Humans are apes; don’t pretend we’re not all the same that way.  The tabula rasa theory fails to explain <em>why</em> males tend to violence; who cares how society shapes boys and girls? As soon as you ask the next question, “Well, why does society shape boys one way and girls another?” the whole thing falls down.</p>
<p>That’s the example.  The underlying problem is not male violence: it’s the inadequacy of male civilization in a severely-overcrowded world.  The idea that boys are inherently-violent is a sexist ruse; “theoretically capable of violence” and “inherently violent” have not the least degree of similarity beyond spelling.  Men are inherently human, nothing less or more, and civilization requires that courtesy leaves it at that.</p>
<p>Girls are raised by mothers; they learn as they get older to normalize their loving relationships with fathers, but they are not born into the same world as men are; love for a male figure is a process of earning and learning, and is founded upon a sense of protection foremost, and a sense of nurturing second.  They learn love and respect for boys and men behaviourally.  Ask any father how thrilled he is the first time his child wants his attention as much as mommy’s.</p>
<p>Boys are different.  They are raised by mothers and introduced to fathers as their sisters are, but unlike their sisters, they must learn and grapple with the fact that they are not like mommy in fundamental ways.  Boys have to learn separation long before girls; girls have their moms forever, but boys have to let go of their allegiance to mommy, beginning at a very tender age.  Mommy’s in charge of everything, but she’s not a boy; realizing that there is an unbridgeable gap there is a crucial and difficult moment, and it comes early for boys.  It comes early, and it comes over and over again.</p>
<p>Boys have to deal with it as boys always have, but it’s a violent act, even if it goes unnoticed, and there are costs.  The harder it is for a boy to carve out an acceptable boy-territory for himself, the more damaging it becomes.  Boys need markers, notes of passage, and sorry moms, but you’re not good at recognizing that.  Mothers say no to most of the things that boys love and must experience.  They don’t know when to say yes or no, because they aren’t boys: they’re trying to solve a person, not a problem, and that’s not how boys roll.</p>
<p>Passing from mom-world to man-world is a huge moment in a boy’s life, a magic moment of blossoming, as well as a moment of sadness and loss.  He has to feel that.  He has to miss his mom, not cling to her: missing mom is the secret ingredient to gender happiness, being her is disastrous.  He has to learn civility, to learn what his possible roles in the world are, from a person who shares his sense of industry, strength, power, protection, and love of others, and in most cases, it’s better for a man to do it than a woman.  It doesn’t always work that way, but the world is flexible, if you don’t always push your luck.</p>
<p>There has to be a time when a boy is no longer under the pressure to be a girl — and remember, that’s how he sees it — and can just be proud of his boyhood.  It’s normal, at that stage, for the boy to turn himself over to a father, having learned all the civility from his mother that he can; that will change again, when a man teaches a boy to respect girls and women, but likely not until then.  That’s how you teach honour and integrity.  Nothing else matters, if you start with those, and those don’t start with continuous streams of “you’re a bad boy”.  They start with, “Let’s say you and me go for a walk”.</p>
<p>And, ahem, it’s really smart to get it done before a boy discovers masturbation, so he isn’t just making crap up because he’s lonely, horny, and confused. Unbidden erections and a hurricane of new and uncontrollable thoughts and feelings are terrifying enough, and if all a boy ever hears is that both his desire and his penis should stay hidden, especially when girls and women are present, he may never know that his own body can be desirable, or that women would want it willingly. Boys need to be taught and encouraged to feel good about feeling good, not taught to fear their own sexual beings and pleasures. They should be taught to put women on pedestals, where they belong. That is best taught to boys by men, not by mothers; chivalry is a manly art, symmetry be damned, and who cares if you don’t like it? It works, and it makes girls happy, and there ain’t nothing you can do about that.</p>
<p>Messing with evolution exacerbates problems in people.  It makes bad behaviour worse. The worst part of boyhood, not only for the people who are victimized by it but for the bullies as well, is the phase of rampant homophobia which begins with the first expressions of an adolescent boy’s sexuality.  The sexual urge begins before the sexual desire crystallizes, and boys go through a homoerotic phase before they know about girls. Some stay in it, of course, and they become victims.</p>
<p>When the other boys start to realize that they need to be men in order to get girls (no one said logic applied in teenage boy world), they start to try very hard not to be girls themselves. It’s built into their brains that having sex like you’re a girl makes you a kind of girl, so they make public displays of intolerance towards the boys who were their friends before they turned gay. The pop-psych theories about boys hiding their own gayness, or mimicking their father’s machismo…they’re popcorn and fluff.  The truth is never so simple with real humans.</p>
<p>Boys have to work very hard to not be girls, sometimes for their whole lives.  It’s not because boys are inadequate emotionally.  It’s because girls get to be the real ones.  They get to just be themselves.  Boys have to prove they’re real.   They can’t just be real, they have to do things.  Girls have it easy.  They don’t have to prove they’re not boys.  They don’t have to prove they don’t need mommy, because they still have mommy.</p>
<p>Boys don’t get to really start being boys until it’s time to begin the lifelong process of letting go.  Girls and women usually don’t get how hard it is, or how scarring it can be, just to learn to be your own boy, and some, far too many, dismiss it far too casually, as if the trials of a boy’s life are somehow inconsequential compared to a girls.  They choose to see boys only through a lens of hostility, when they can as easily be seen through a lens of charity.  They see only the worst, deliberately. That’s called “dehumanization”, and it’s the worst idea in the history of existence.</p>
<p>We are wrecking boys, children, to make a political point which we know is based on a falsehood.  We wouldn’t allow such experiments on prisoners, so we shouldn’t be performing them on children.  Boys are not meant to be girls, not even close, and feminists who want boys to be girls are doing more to promote gender war, and the violence that follows it, than any of the accused “sexists” whom I know.</p>
<p>If I’m wrong, so be it, but at least I’ve done no harm.  If you social experimenters using your children as guinea pigs are wrong, you may have ruined your own child’s life. Are you going to be there to say, “I’m sorry”, if it turns out badly for him? How will you undo what you’ve done?  How will you unmake the unman you so proudly engineered?  Eugenicists and experimenters are never around when the brakes fail and the train wrecks.</p>
<p>How you change things between men and women: you accept that males and females are equal, not symmetrical or identical, and that boys are not subjects for radical experimentation.  You make the passage from mother-figure to father-figure as happy and painless as possible, and if you don’t have that luxury, you get as male in your thinking as you can, before the child does; trying to do the right thing is as good as doing the right thing, and you don’t need to be a typically-gendered family for that. If you can’t teach anything but mutual respect, you still create gratitude, not resentment, and you create men who will treat women properly.</p>
<p>How do I know they will treat women properly?</p>
<p>Because <em>they will love them</em>.  Don’t say you can’t do the math.</p>

<p>The notion that masculinity is a form of original sin visited upon boys at birth is an outcropping of the long-since discredited notion that boys and girls are exactly the same&nbsp; at birth, and can be molded not only to exhibit desirable traits in terms of socialization, rights, privileges, and powers, but in terms of sexual identity as well.&nbsp; We are, the theory goes, all <em>tabula rasa</em>, waiting to be shaped and molded in the image of our society, through the power of the family; all the ills of the world can be traced to the fact that boys are not raised to be girls.&nbsp; Likewise, the solution to every problem is “make boys be girls”; make them soft and gentle, make them play with dolls instead of swords, enforce tea parties over rough-housing, and stamp out aggression at every sign.</p>
<p>That’s not what happens.&nbsp; You don’t make them soft and gentle; if they are that, then they are, but if they’re not, you make them fake-soft, fake-gentle, and resentful towards women.&nbsp; The evidence is in, right beside global-warming and the fall of democracy: the more you mess with the rights and privileges of boys, the worse they are to women, and it’s because women still think, against, oh…150,000 years of evolution, that they can fix men.</p>
<p>Holy shit, did he really say that?</p>
<p>Yes, he did.&nbsp; He said that women are trying to fix men, and it’s a disaster.&nbsp; How crude! How unnuanced!&nbsp; How obvious!</p>
<p>There’s a theory, popular amongst the creepier leftists and feminist warheads, called “Toxic Masculinity”.&nbsp; It’s a pretext for a program of social-eugenics, meant to turn the development of normal masculine characteristics into a crime.&nbsp; It’s as stupid as any bigotry can be; you can take any claim any eugenicist makes and match it up to the same claims used by any other eugenicist: “they” are born evil, “they” must be removed from the gene pool.</p>
<p>Nobody takes that kind of feminism seriously.&nbsp; It’s like herpes; it never quite goes away, but it gets easier and easier to ignore as time goes by. When proud public haters can’t bring themselves to admit that they’re haters, their public images begin to slide. The spew of hate becomes first predictable, then irrelevant, then laughable. Militant feminism of that type has painted itself into a tiny little corner, in a tiny little&nbsp; because it bought its philosophy from a fascist outlet store that doesn’t take returns.&nbsp; It is stuck with that stink forever now. They’re not the problem.&nbsp; If they were, they’d have been put out of business long ago.</p>
<p>The problem is that people bought into the largest conspiracy-theory in history <em>before</em> it was discredited.&nbsp; The theory’s foundation is that male humans are shaped to evil by invisible forces in “society”, none of which can ever be named, and of which no concrete examples exist, but the evidence of which is “all around us”.&nbsp; People who bought into the “tabula rasa” social experiment didn’t stick around to see all the false theorizing&nbsp; dismantled; the zealots have their dogma, and logic be damned.&nbsp; There is no evidence that boys are forced to like blue, and that girls are forced to like pink; there is no evidence that rough-housing or weapon-play leads to lives of violence; there’s no evidence that boyhood play is associated with anything except boyhood learning and fun.&nbsp; What there is a lot of is evidence that you shouldn’t mess with normal human expression, because it twists people, any people.&nbsp; Since when did messing with people’s heads improve the world?</p>
<p>Boys know they’re hated.&nbsp; How could they not?&nbsp; They know that their fathers are hated.&nbsp; They have not the slightest idea why.&nbsp; They know that boys are bad, girls are special, and that some grownup women really truly hate them, and say things about them, but what they’re saying isn’t true. The first thing boys learn about gender relations is that they’re unfair, but they don’t see it in the abstract.&nbsp; They don’t do politics.&nbsp; To them, it’s unfair in every way they can think of, and no matter what, the grownups side with the girls. To boys, to children, it doesn’t look like it’s the girls who get the worst of the deal.&nbsp; You create unfairness if you right other unfairness punitively, and you create children who remember it all their lives.&nbsp; That’s how boys are introduced to feminism: as an explanation for meanness plus also lying plus also not being fair.&nbsp; Oddly enough, children do not grow up aware of the swirling political forces around them, engaging in glorious and noble civil tug-o-wars over the right to model their children’s personalities after completely unattainable ideals.&nbsp; Who saw that coming?</p>
<p>None of which answers the original knee-jerkery: why do boys rebel so strongly, even violently, when made to emulate girls?&nbsp; Ignoring the obvious reciprocal question, what is it about femininity which boys so deeply need to avoid, even to repudiate? It expresses itself in some way, in almost every boy’s life, through bullying, exclusion, homophobia, sexism, and/or violence.&nbsp; Those are probabilities, by the way.&nbsp; They are not definitions. Trying to turn them into stereotypes is evil, so stop it.</p>
<p>Those probabilities are applicable to every boy differently, sometimes in absence.&nbsp; Pretending that the worst in boyhood behaviour is a template for further development is a cheap and easy score here, but it ignores the fact that all children go through phases of development marked by observable transitions and passages.&nbsp; Boys are not a Lego building with an immutable foundation; they pass through a stage of identity-building which requires that males learn to be uncivilized goofs.&nbsp; They’re little boys; they can’t hurt you or each other anywhere near as much as a sharp tongue can.&nbsp; They might also like ballroom dancing, or cooking.&nbsp; They may dislike competition.&nbsp; They still have to go through the development of male body consciousness, which they base upon physical prowess and achievement.&nbsp; If they are not allowed to do so, if they are feminized before or during this phase, they are denied a fundamental building block of masculinity: the capacity for aggression, including expression through violence.</p>
<p>Eeyagh!&nbsp; Yikes! Gazounds or whatever!&nbsp; Violence is evil!&nbsp; Stamp out violence!</p>
<p>The sad part of the bonehead left is the two-dimensional thinking: violence is evil, so make it illegal and shameful.&nbsp; That’s the left’s modern MO: identify evil and make it shameful and illegal.&nbsp; I defy you to think of a leftist campaign which actually touches your life which does not follow this pattern. If you can, please, please, please…let me join.</p>
<p>You don’t stamp out evil by passing laws demonizing normality.  You make rebellion and blowback that way, not model citizens.  It’s called “repression”;  I read somewhere that women don’t like it.  Surprise!  Boys don’t like it, either. You stamp out evil by making it useless, boring, pointless, ineffective, embarrassing to even try…you stamp out evil by (I have never needed a drum roll more) civilizing humans.</p>
<p>Really? That’s your answer? Civilization? That’s so not possible, with men in the world!</p>
<p>Yes, civilization: the macro-scale cultural state of civility amongst the citizens.  A novel idea if ever there was one!  You don’t fix civilization by endlessly adding to the list of things people are never going to remember not to do.  You fix civilization by enabling people to be the best people possible.</p>
<p>For boys, that means emerging from the development of aggression and violence, into a state of assertiveness and readiness for action. If you stomp out aggression with aggression, you create resentment.  If you make aggression impossible, the child will never grow out of that stage and learn the sensible limits of aggression.  The sensible limits of aggression are assertiveness and self-confidence, neither of which the boy-with-boyhood will learn in the normal way.</p>
<p>Girls go through their princess-with-dollies stage.  They like it.  They make dolls if they don’t have them.  They beg for them as gifts.  No one forces boyhood on them.  The irony is that when girls exhibit the characteristics for which boys are punished or inhibited, they’re rewarded for it.</p>
<p>Yes, boys do really need to learn violence, so they can learn not to be violent.  They need to learn assertion, not bullying.  You can’t teach children who are not allowed to show up for class.  Humans are apes; don’t pretend we’re not all the same that way.  The tabula rasa theory fails to explain <em>why</em> males tend to violence; who cares how society shapes boys and girls? As soon as you ask the next question, “Well, why does society shape boys one way and girls another?” the whole thing falls down.</p>
<p>The underlying problem is not male violence: it’s the inadequacy of male civilization in a severely-overcrowded world.  The idea that boys are inherently-violent is a sexist ruse; “theoretically capable of violence” and “inherently violent” have not the least degree of similarity beyond spelling.  Men are inherently human, nothing less or more, and civilization requires that courtesy leaves it at that.</p>
<p>Girls are raised by mothers; they learn as they get older to normalize their loving relationships with fathers, but they are not born into the same world as men are; love for a male figure is a process of earning and learning, and is founded upon a sense of protection foremost, and a sense of nurturing second.  They learn love and respect for boys and men behaviourally.  Ask any father how thrilled he is the first time his child wants his attention as much as mommy’s.</p>
<p>Boys are different.  They are raised by mothers and introduced to fathers as their sisters are, but unlike their sisters, they must learn and grapple with the fact that they are not like mommy in fundamental ways.  Boys have to learn separation long before girls; girls have their moms forever, but boys have to let go of their allegiance to mommy, beginning at a very tender age.  Mommy’s in charge of everything, but she’s not a boy; realizing that there is an unbridgeable gap there is a crucial and difficult moment, and it comes early for boys.  It comes early, and it comes over and over again.</p>
<p>Boys have to deal with it as boys always have, but it’s a violent act, even if it goes unnoticed, and there are costs.  The harder it is for a boy to carve out an acceptable boy-territory for himself, the more damaging it becomes.  Boys need markers, notes of passage, and sorry moms, but you’re not good at recognizing that.  Mothers say no to most of the things that boys love and must experience.  They don’t know when to say yes or no, because they aren’t boys: they’re trying to solve a person, not a problem, and that’s not how boys roll.</p>
<p>Passing from mom-world to man-world is a huge moment in a boy’s life, a magic moment of blossoming, as well as a moment of sadness and loss.  He has to feel that.  He has to miss his mom, not cling to her: missing mom is the secret ingredient to gender happiness, being her is disastrous.  He has to learn civility, to learn what his possible roles in the world are, from a person who shares his sense of industry, strength, power, protection, and love of others, and in most cases, it’s better for a man to do it than a woman.  It doesn’t always work that way, but the world is flexible, if you don’t always push your luck.</p>
<p>There has to be a time when a boy is no longer under the pressure to be a girl — and remember, that’s how he sees it — and can just be proud of his boyhood.  It’s normal, at that stage, for the boy to turn himself over to a father, having learned all the civility from his mother that he can; that will change again, when a man teaches a boy to respect girls and women, but likely not until then.  That’s how you teach honour and integrity.  Nothing else matters, if you start with those, and those don’t start with continuous streams of “you’re a bad boy”.  They start with, “Let’s say you and me go for a walk”.</p>
<p>And, ahem, it’s really smart to get it done before a boy discovers masturbation, so he isn’t just making crap up because he’s lonely, horny, and confused. Unbidden erections and a hurricane of new and uncontrollable thoughts and feelings are terrifying enough, and if all a boy ever hears is that both his desire and his penis should stay hidden, especially when girls and women are present, he may never know that his own body can be desirable, or that women would want it willingly. Boys need to be taught and encouraged to feel good about feeling good, not taught to fear their own sexual beings and pleasures. They should be taught to put women on pedestals, where they belong. That is best taught to boys by men, not by mothers; chivalry is a manly art, symmetry be damned, and who cares if you don’t like it? It works, and it makes girls happy, and there ain’t nothing you can do about that.</p>
<p>Messing with evolution exacerbates problems in people.  It makes bad behaviour worse. The worst part of boyhood, not only for the people who are victimized by it but for the bullies as well, is the phase of rampant homophobia which begins with the first expressions of an adolescent boy’s sexuality.  The sexual urge begins before the sexual desire crystallizes, and boys go through a homoerotic phase before they know about girls. Some stay in it, of course, and they become victims.</p>
<p>When the other boys start to realize that they need to be men in order to get girls (no one said logic applied in teenage boy world), they start to try very hard not to be girls themselves. It’s built into their brains that having sex like you’re a girl makes you a kind of girl, so they make public displays of intolerance towards the boys who were their friends before they turned gay. The pop-psych theories about boys hiding their own gayness, or mimicking their father’s machismo…they’re popcorn and fluff.  The truth is never so simple with real humans.</p>
<p>Boys have to work very hard to not be girls, sometimes for their whole lives.  It’s not because boys are inadequate emotionally.  It’s because girls get to be the real ones.  They get to just be themselves.  Boys have to prove they’re real.   They can’t just be real, they have to do things.  Girls have it easy.  They don’t have to prove they’re not boys.  They don’t have to prove they don’t need mommy, because they still have mommy.</p>
<p>Boys don’t get to really start being boys until it’s time to begin the lifelong process of letting go.  Girls and women usually don’t get how hard it is, or how scarring it can be, just to learn to be your own boy, and some, far too many, dismiss it far too casually, as if the trials of a boy’s life are somehow inconsequential compared to a girls.  They choose to see boys only through a lens of hostility, when they can as easily be seen through a lens of charity.  They see only the worst, deliberately. That’s called “dehumanization”, and it’s the worst idea in the history of existence.</p>
<p>We are wrecking boys, children, to make a political point which we know is based on a falsehood.  We wouldn’t allow such experiments on prisoners, so we shouldn’t be performing them on children.  Boys are not meant to be girls, not even close, and feminists who want boys to be girls are doing more to promote gender war, and the violence that follows it, than any of the accused “sexists” whom I know.</p>
<p>If I’m wrong, so be it, but at least I’ve done no harm.  If you social experimenters using your children as guinea pigs are wrong, you may have ruined your own child’s life. Are you going to be there to say, “I’m sorry”, if it turns out badly for him? How will you undo what you’ve done?  How will you unmake the unman you so proudly engineered?  Eugenicists and experimenters are never around when the brakes fail and the train wrecks.</p>
<p>How you change things between men and women: you accept that males and females are equal, not symmetrical or identical, and that boys are not subjects for radical experimentation.  You make the passage from mother-figure to father-figure as happy and painless as possible, and if you don’t have that luxury, you get as male in your thinking as you can, before the child does; trying to do the right thing is as good as doing the right thing, and you don’t need to be a typically-gendered family for that. If you can’t teach anything but mutual respect, you still create gratitude, not resentment, and you create men who will treat women properly.</p>
<p>How do I know they will treat women properly?</p>
<p>Because <em>they will love them</em>.  Don’t say you can’t do the math.</p><p>It’s easy to wreck a boy: you make him be a girl.  That’s why boys are destroyed by rapists; not only does it prove that you’re weak, it proves that you’re not a man and never will be.  As I tried to “explain” yesterday (that’s what I call a 4,000 word essay: an “explanation”.  Be thou warned.), there are many other ways to wreck a boy by making him be a girl, and two-dimensional politics, one-dimensional religion, and zero-dimensional sociology are engage in a culture-wide crusade to do just that.  Before you line up the little arguments so I can knock them down, remember, it’s not about how you see things, it’s about how boys see things.  Children.  The small young people with penises and testes, you know…the ones who don’t give a damn about politics, religion, or sociology, but know perfectly well when things are unfair.  Which they are.</p>
<p>No one makes girls be boys. They give them that option, and they laud them for choosing it, but no one ever asks them to stop being girls. Politicians and social do-gooders who demand symmetry must grant symmetry, but there is no attempt made to do so, and such suggestions are shouted down.  Instead, privilege and empowerment continue to become more asymmetrical, and the pressure on boys to conform to social rules entirely adapted to women and girls continues to increase.  There is no backtalk permitted on this issue: we are talking about children, and your political and social principles do not apply.</p>
<p>The way to end the gender wars is to stop letting people mind each other’s business. That means stop telling other people what to do, stop trying to legislate behaviour, stop dictating morals, stop condemning and shaming people, and generally do what humans are supposed to do: act with respect for the rights and dignity of others.  Men do not tell women what to do, women do not tell men what to do, heterosexuals do not tell homosexuals what to do, homosexuals do not tell heterosexuals what to do.</p>
<p>(Aside: sorry about the overly-sciencey nomenclature, but “straight” and “cis” are words that began as insults, and I’m old enough to remember when they were. I won’t have that applied to people who don’t want it, any more than I’d permit you to call Africans “niggers” on my watch. “LGBT” implies that non-heteros are some kind of unified voting block defined by the conscious exclusion of “straight” and “cis” people, not by any unifying qualities; that’s called bigotry.  It further implies that heterosexuality is also some kind of unified voting block, as if “straight” also meant “predictable and stupid”, and as if sexual orientation was the primary political motivation of 95% of the population, but not the other 5%.  Finally, I get really tired of the “we know what you really think” mentality.  You don’t.  Grow up.  You really don’t know anything about me, because my sexual identity is “monogamous”.  Since I don’t see an “M” right beside the “B” in “LGBT”, you will never ever know whether I’m “straight” or not, will you?)</p>
<p>We know how to wreck boys; you don’t let them be boys.  You legislate and shame boyhood into a twisted version of girlhood which can end well for nobody. You abuse them sexually, the way rapists do, or you abuse their sex and sexuality, like zealots do; either way, you wreck them both for women and for themselves.  Now let’s talk about saving boys, and this time, frankly, the women will stop talking like the know what the fuck they’re doing, and they will listen to someone who speaks from a place of caring, not from a place of derision.  If you don’t like it, go to Mars.  They have openings for windbags there.</p>
<p>Boys go through a separation event early in their lives: they dial down their allegiance to mother, and dial up their allegiance to father.  Yes, I know, there are plenty of families without such arrangement which work honestly and well: of course there are, but we’re not talking about them right now; this is not an issue for identity politics of any stripe. We all acknowledge that anyone may rise above evolution through the mechanism of culture, and no one is bound by rules, because there aren’t any, so it’s ok not to make every conversation about minority involvement.  Really, it’s ok; it hurts no one, and it helps many, so don’t make this about that.</p>
<p>When a boy separates from his mother, he begins a lifelong process of learning how to be himself, as boy and as man. I don’t pretend to know what it’s like for girls, but that is how it is for boys: you have to prove and reprove yourself every day until you die.  It’s not a quaint machismo taught by a sexist society; it’s reality, and it was there long before “society” was invented.  You can either catch that moment of separation and work with it, or you can snort derisively and let it pass.  If you’re insane, you try to stop it.  Real men, good men, respectful and honourable men, are born at that moment, or they may never have the chance.</p>
<p>If the first act of a parent after the separation is uncaring or nasty, the boy will carry that all of his days.  It may not be a conscious issue, but his first real impression of “woman” as a thing other than himself will be an unfair, undeserved insult.  Welcome to the adult world, little boy; we hate you.  What to a woman is another moment is the <em>first</em> moment of his self-owned life, and the world will only get that one chance to make a first impression.  It’s isn’t fatal to mess it up, but it’s always dangerous.</p>
<p>If it’s possible, women have to let go at that point, and let the father begin the training for manhood that produces well-adjusted men. Again, if it’s not possible, we’re not talking about you right now, so we can concentrate on the boys, and most of them come from mommy-daddy families, so we can concentrate on them.  Women are no more adept at “getting” boys and men than men do women and girls, and the complexities of male passage make adolescence a difficult time for boys, best understood by men.  Can we stop talking about that now?  In general, boys need men, and I’m tired of apologizing for reality.</p>
<p>Men used to believe in something called “honour”.&nbsp; It was a combination of integrity and respect for the manly arts and sciences.&nbsp; It required good manners, respect for other men of honour, rigorous honesty, a willingness to take risks for the right reasons, a vow to protect women and children, a promise to fight fairly when fighting is required, and a guarantee that you will stand with your peers and do the right thing at any cost.&nbsp; A man who gave his word of honour and broke it was himself a broken man, an outcast, a coward and a cheat, unworthy of civility.&nbsp; A man who lied to or about another risked more than his honour; he might be called out, and his life ended in a duel.&nbsp; You did not play games with your honour.</p>
<p>Men no longer teach honour.&nbsp; Honour went out when the Women’s Revolution came in.&nbsp; It seemed like a relic of a bygone era, when men were men and etc.&nbsp; Here we are, a century later, and honour is in very short supply.&nbsp; Lying is the national sport, internationally.&nbsp; Theft is applauded.&nbsp; Corruption is expected.&nbsp; Courtesy is almost non-existent.&nbsp; Men and women yell at each other over a fence they keep building.&nbsp; Left and right oppose each other for the sake of opposing each other.</p>
<p>Boys need to learn honour.&nbsp; Men need to start teaching boys honour again.&nbsp; That is how you save boys: you teach them to be gentlemen.&nbsp; Notice I said “gentlemen”, not “men”, and certainly not “effeminate”.&nbsp; A gentleman is an honourable man who works for a living; that’s what the word actually means.&nbsp; An artisan or craftsman worked with his hands, a gentleman worked with his mind, and a nobleman worked very little, but was supposed to be keeping guard.&nbsp; All and any of them could be honourable, but it is “gentleman” which has survived as a label.</p>
<p>Gentlemen do not act like women.&nbsp; Women act like women, thank you, and we will act like men, like gentlemen.&nbsp; That means, in part, sorry if you don’t like it, that we don’t have to do what we’re told: we teach boys by making them understand, not by telling them the rules.&nbsp; Telling a boy the rules of courtesy, for instance, does not tell them why, and women cannot communicate to a boy exactly why, in a boy’s heart, you have to love women and treat them like treasures.&nbsp; If a woman tells a boy the same things, she saying, “You have to treat me this way, because those are the rules”.&nbsp; Rules are made to be broken, in a little boy’s world.&nbsp; Boys have to know why they should treat women like treasures, but only men can teach them that, because it ain’t all about words, kid.&nbsp; It’s about hearts and minds, and a lot of the talking men do isn’t done with talking.</p>
<p>Honour is a very complex system, with a lot of requirements and demands.&nbsp; Exactly what a boy needs, in other words.&nbsp; Something to learn, something to master, something to teach in turn; this is gold.&nbsp; A boy raised in the honour system knows things that mamma’s boys just don’t learn: you respect everyone, and fear no one; you never forget where your loyalties lie; you never have to care whether you’re gay or trans, because you know that other men of honour won’t care; you know who has your back, and you know whose back you have.&nbsp; Above all, you are bound, bound, to treat women as treasures; at work, on the street, at home.&nbsp; At one time, that didn’t include work, of course, but respect for women now includes respect for women’s work in any milieu, so boys now can learn respect for women there, too.</p>
<p>What does respect mean? It means you don’t prejudge people.&nbsp; You give people the benefit of the doubt.&nbsp; You uphold and defend human rights and dignities at all times.&nbsp; You don’t lie, cheat, or slander.&nbsp; You treat all humans as individuals of equal value.&nbsp; Those are the qualities of honour as well; respect is a wholly-contained subset of honour.</p>
<p>In yore-days, or days of yore or whatnot, a gentleman learned also to respect poetry, music, dance, law, philosophy, art, and combat, even if he didn’t partake of those career choices.&nbsp; Bad manners were out.&nbsp; Tough guys wore lace.&nbsp; Forgive me, but isn’t that the kind of man we want, a man who is good by choice, gentle by training, and fiercely protective by nature?&nbsp; Or do we prefer boys in men’s bodies, who are good by appearance only, useless by training, and protective only as human shields.</p>
<p>I don’t “know” women, but I do know this about them: they do not date dweebs.&nbsp; They do not date the kind of men that feminists say they should be.&nbsp; Women don’t want men like that; never have, never will.&nbsp; They like men who are confident in their manhood and don’t need to prove it anymore. You make boys into men like that by respecting manhood, not stripping it of dignity.&nbsp; You don’t let the people who respect manhood the least teach it to boys.&nbsp; Boys aren’t girls.&nbsp; And besides, girls don’t know nothin’.</p>

<!-- InstanceEndEditable -->
	</div><!-- InstanceEnd -->