<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>I'm a Survivor##/h1>

##p>Imagine not being able to forget.  Nothing goes away.  Pain piles on top of pain, and it barely erodes in a lifetime.  The store of bad memories I carry is mind-breaking.  Don't think I'm not tough, that I'm just too weak to stand up to it; I carry a weight that only a few people do: memories that won't go away.  I don't always remember details; I get colours wrong, for instance, but I remember every gut-wrenching moment as if I were still there.  I have many good memories, and I feel them too; I feel every pain or pleasure, happiness or humiliation, insult or injury, as if it is happening now.  Twenty years ago, ten years ago'it doesn't make any difference.  I still feel it.  I live in constant awareness that if I let bad things happen now, they will be happening in my memory forever.  I will feel it with practically undiminished intensity, until my memory shuts down.##/p>
##p>When I'm not busy, and I'm not in a good phase, I loop.  We all have words for it: losing it for a while, spiraling down, getting lost in the fog, obsessing. I watch endless memory-movies, sometimes in series and sometimes the same one repeatedly, and I don't run dry no matter how long it lasts.  They call each other out, linked by only the thinnest of threads, one after another. I can spend days looping, unable to stop until I've rerun every shame or embarrassment in my memory, heard every insult, felt every blow, remembered every humiliation. I reargue old arguments, refight old fights'strangest of all is remembering past mood swings; I remember what I was thinking, and pick up the loop where I left off. I cannot be alone at those times; not 'I shouldn't be alone', but 'I can't.' Loneliness is my Nemesis, an implacable enemy clothed in darkness, who never speaks and has no eyes, and somehow, is always waiting there when you arrive, wherever there is.##/p>
##p>It doesn't, ultimately, matter how tough or strong you are.  Brains are finite things, and you just run out of good chemistry. Eventually the pain overloads me, and I give up fighting back, and I get lost in my crazy again, and my list grows longer again.  Forgetting is your friend, and you should cherish it. You've heard of repressed memory syndrome? I would have given almost anything to make that work for me.##/p>
##p>I've only ever buried one fragment of a single memory and retrieved it later.  There may be others I lost, and I wouldn't know it, but only one has ever come back to me.  I lost the face of the man who violated me as a child. (##em>Edit: 'violated?' I called it 'violated'? That's how hard it is; I can't even call it rape without trying to hide it both from myself and from you.)##/em> No, it was not my family or friends, and I'm sad that I would even think that you might think that.  It was a total stranger who was very adept at collecting and hurting teenage boys, and no one of my own has ever done such a thing to me.  I'd know.##/p>
##p>He was not the only one; there were seven over the years, both male and female, or not; what would I know? I came to believe that I was a pervert-magnet, that everywhere I went they would find me. I began to see death as the solution to my problems.  I did not know that I am capable of normal relationships; I came to believe that I didn't deserve a great love, and I stopped looking for one for a long time. I came to believe that I couldn't ever let people know what I'm 'really like', and that I would die, sooner than later, without ever having known a great love. They all hurt me, the seven, but one man ruined me. Unruining myself has been a full-time job for the last 17 years of my life, and I don't know if it will ever be finished.##/p>
##p>'Repressed memories', in my experience, are not quite what you think. If it's gone, it's gone. If it's a memory, it's not exactly 'repressed'.  It looks the same; you just don't look at it.  My memory wasn't repressed; I just couldn't ever look directly at the image onscreen. I couldn't bury the memory, not for a second, but I learned eventually to blur the face, lower the volume on the soundtrack, and darken the image. I practiced it constantly. In time, it gets easier, and after decades, it's just maintenance; you're not repressing it so much as whitewashing it.  The memory either goes away permanently, or is still there under the paint.##/p>
##p>It is not a memory a boy can share; doing so will cost you the manhood you've been chasing all your life. Boys can be extremely homophobic; it is built into the psyche that you can never be an alpha if you've let yourself be mounted, and that the shame will make you a slave all your days. You can't imagine a time when this will not be the first thought and the last thought of the day.  You hope you will care less someday, but you don't know that it's even possible. You only know that you let someone make you a girl and that life is over; it just won't end.##/p>
##p>I was in lockdown for half my teens, and for my entire adult life.  I got really good at it.  If keeping your feelings out of sight is hard, imagine how hard it is for a guy who averages 17 mood cycles per year; I wore a poker face of remarkable shallowness, with a fascinating disinterest in you and the horse you rode in on. One day, I'll show you a useful trick: how to rig your face so even professional microreaders (lie-spotters) wouldn't get anything from you.  Here's a clue: don't lie. If you have to lie, lie with your face first, not your words. There's more, but it's long, and if I tell you, you'll have to kill me.##/p>
##p>##span id='more-292'>##/span>After 35 years of 'controlling myself', I ran out of resources. I cracked, then I exploded, and I filled up another room in the warehouse of memory. I knew I would, eventually, but I got complacent, and then apathetic. I didn't ever plan beyond it. Until I was 40, I always figured that if it got to be too much, I could just step into the abyss and be lost; it was knowing that it would hurt others even more deeply than I had been that stopped me. Life changes for better or worse, but luck changes too.  When the world caved in on me, I had help; I had loved ones to take care of the others for me, and to keep me in health and safety. That is all the gold there is in this world.##/p>
##p>Memories can ruin you, but burying them is the hardest thing you can do, and it costs you everything.  Not thinking of it takes effort, not talking of it takes discipline, and it demands daily, even hourly practice. I spoke twice in 35 years of that memory, and spent the last 29 years in complete silence. Somehow, in the first few years, the face of my demon disappeared, and left a strange grey smear in its place. I thought that was a good thing, that I was leaving it behind, but pain is corrosive, and ignoring it doesn't lessen its burn. It took years, but it melted its way through my zen until zen itself was just a memory.  It wasn't until my therapist helped me dig through that accumulated pain, and look without looking away, that I saw him again. Until that moment I didn't know it even mattered, but that was the moment that changed everything for me.##/p>
##p>'Healing' is a hard word for me to use, because I had no reason to believe in it, but that moment of transcendent pain is when healing began for me; when you can finally gather the courage to sit and watch the movie without turning away, and you let yourself be there, and you let it hurt, and you do it anyway. My therapist knows how to look for dark things in obscure places; it is not something you do for yourself, because you are not that brave. My brain doesn't really do fear properly ' I don't quite feel it, even when I can feel that I should be able to feel it ' but I was never that close to brave. You cannot do it on your own. You cannot look directly into the face of evil to take back your soul if you have no love in your life; I, quite literally, fear almost nothing, but was never close to brave enough to do it alone. I needed a loving face to look to, an antidote, a haven to come home to. Without that, the pain of the memory would have turned me away before I could start.##/p>
##p>Not looking becomes more than a habit; it becomes part of you. You become the guy who can't look, and then you have to unbecome him. If you want this to work, you don't just look, you change into the guy who can look. You can't be the guy who peeks at evil through his fingers just to say he did. You have to be the guy who can stare evil down, break his gaze, own him like he owned you.  You stand up straight, you uncoil the serpent in the belly, you breathe, you let your fists relax into hands, and you take back what is righteously yours.##/p>
##p>I saw him; I saw his face, and I remembered. I saw what a lost, stupid man he was. I saw that he looked like a clown on steroids. I remembered that he was a babyface; he sported the face of a preschooler, on an outlandishly large, very spherical head.  He wore black leather, and the tough guy image really didn't work with that face at the top. I remembered that he had performance issues; he kept having to start over. I realized that time as we know it had stopped for me, leaving me without an index to my vast library, and that I could restart it.  I realized, finally, that there is no chance he survived the AIDS pandemic, and that I'm safe at last. I don't have AIDS. I'm here, and he's gone, and I can breathe, and I don't have to spend the rest of my life fantasizing about hunting him down and showing him the meaning of pain.##/p>
##p>I had to tell you that.  It's not my secret anymore, but talking about it is difficult no matter how much time goes by. I had to think for a long time before I could do this. I need you to know about this, because if you know the rest of me without knowing that, you'll know something's missing, and you'll think its my honour and integrity, and I can't have that. This writing, this blog, is my way of caring for the world; it is my ##em>tikkun olam##/em>, my compassionate service, but I speak of things that make people angry. People will not listen if they think I don't understand or care.##/p>
##p>I understand, and I care. I am a survivor. Disagree with me about anything else, make me see and own unfairness or unkindness in my words, question my logic and evidence, but please, show me the small, appropriate respect of never saying that I don't understand or care.##/p>";
