<!-- InstanceBegin template="/Templates/standard_post_content_1.dwt.php" codeOutsideHTMLIsLocked="false" --><!-- InstanceBeginEditable name="post_meta" -->
<!------------ RGCafe blog post -------------------------
Date: 2018-09-18
Categories: 
Tags: 
Title: Let the Revels Begin
Subsite: Love and Chaos
Number: 1018
ID: let_the_revels_begin
Post description: 
--------------------------------------------------------->
<!-- InstanceEndEditable -->
	<div class="blog post default wrapper">
<!-- InstanceBeginEditable name="post_title" -->
<h1>Let the Revels Begin</h1>		
<!-- InstanceEndEditable -->

<!-- InstanceBeginEditable name="post_content" -->


<p>I’ve been looking for a new project for a while.  There is no shortage of challenges, but I’ve been trying to hone in on the one thing which the world needs most from me.  I’m not presumptuous enough to know what the whole world needs, but trying on one idea or another for a few hours or days each allows me to isolate the need which calls the loudest.  It’s not like “choosing” from a set of real possibilities; it’s more like allowing my intuition and instincts to guide me, while trying not to impose my wants and desires upon the mission statement.  It’s taken me a long time, which would, of course, seem way longer to my wife than to me (I don’t sense the passage of time very well), but I believe I know what humanity and its planet require from me.</p>
<p>I’m not under the illusion that I’ll save the world, but saving the world is one of my stated goals, and I like to set my goals so far above my potential that I never run out of noble ideals to strive for.  If you say to yourself, “I’m going to be Mickey Mouse”, you can go get a job at Disneyworld.  If you say, “I’m going to be God”, then no, you’ll never succeed; if you spend your life trying anyway, you will never run out of good things you can do for people, and that can only be good for everyone.  The most compassionate thing you can do in life is to try to be God; it doesn’t do much for your ego, because people will decide that you’re crazy, but it does wonders for your happiness.</p>
<p>People tend to dismiss anything beyond their comprehension as “crazy”, meaning that they don’t see how it makes sense, and that it’s your fault.  For some reason, saying, “I don’t understand, but I’m sure you’re on to something” is not the standard human reaction to intellectual provocations.  Saying, “You’re lying/stupid/crazy/ignorant” is easier than thinking, and is instantly gratifying to the speaker.  “Crazy” is one of the worst insults in English.  “Stupid” is possibly the strongest insult in the English language; people who don’t respond to any other insult get all up and hairy, the moment they are faced with the task of learning something from a peer whom they believe to be more intelligent than themselves.  The greater the intellectual disparity (which is NOT numerically representable), the quicker the angry response to the perceived slight.  “Learn this”, in the mind of the peer, doesn’t mean “you will benefit from processing the information”.  It means, “You’re a fuckin’ idiot who should do what my superior mind dictates“, which, I assure you, does not rate highly on the usual bonehead wish-list of ego enhancers.  There is no insult I can think of that will rile more people than “you’re stupid”, unless it’s “you’re ugly and stupid”.</p>
<p>I’m not going to save the world even if I keep saying I will; that’s not the point of the exercise.  I am going to keep on saving the world, until I’m dead, or the world is no longer in need of saving. The Big Save will not occur by the end of business today, or tomorrow, or ever.  Saving the world is a full-time occupation that can lead to exciting careers in both futility and contentment; futility if you think you’ll succeed, contentment if you don’t care that you’ll fail.  The pay is lousy, don’t even go there.</p>
<p>Here’s how I’m going to save the world: I have a contract with the Ministry of Making Sense to teach the world the fundamentals of logic and compassion. Logic is not a toy you apply to reality to force it to make sense; logic is the arithmetic of life, but you do the math with words and symbols which represent ideas, instead of with numbers.  In arithmetic, 2 + 2 always equals 4.  In logic, adding fact A and fact B together either results in fact C, or it doesn’t, and if you have to cheat somehow to make facts A and B add up to what you want, then it ain’t logic.  You can’t change 2 + 2 = 4.  It just is what it is, because it makes sense. When you learn logic, you come to understand why <em>compassion makes perfect sense</em>.  Ultimately, logic and compassion are close to indistinguishable in the equations of life for people within the standard deviation, which is a way of saying “regular folk”.</p>
<p>The problem with teaching logic is that you have to teach it with rigorous logic itself, to people who don’t know logic yet.  I’ve done it, and it’s not a task you finish in one semester.  First you have to deal with the fact that they don’t even know what logic is; second, you have to deal with the fact that many of them will find it offensive; third, you have to deal with the fact that all of us live in a world that makes little sense on the surface, and that the surface is all most of them have ever seen.  Their minds are full of false assumptions, misinformation, and ego by the time they make it to logic class, and some people fight really hard to keep their falsehoods in place.  If you come into my class believing in God, there’s a good chance you’ll leave believing that I’m the devil.</p>
<p>When people drop their falsehoods, such as belief in the natural superiority or inferiority of some humans over others, they learn to see things in a different way.  Sometimes I think it’s a mean trick to teach people to see everything that’s wrong with the world, but you know how I am.  It takes a while, but once you’ve developed a taste for making sense of things, you’re hooked; now you want to make sense of everything.  Now you want the big picture, because things which don’t always make sense under a microscope often make sense when you step back and take a wider perspective.  You want the world to make sense. It comes to annoy you that the world doesn’t make sense.  It comes to a choice between anger and bitterness, or constructive involvement, which means doing what makes sense when you figure out how it makes sense.  You’re a logician now, and it’s obvious to you that anger and bitterness are diametrically-opposed to happiness, while constructive involvement, at a minimum, makes happiness more attainable. Okay, logicians screw up from time to time, like normal people, and there will be setbacks, where happiness is eaten by the dog before you can hand it in, but so what? If happiness is the goal (it is), then Door Number 2 is the one you open.  Welcome to saving the world.</p>
<p>Happiness for all is the goal, because it only makes sense that my happiness potential is enhanced by the happiness of those around me, and theirs’ is enhanced by the people around them, and so on and so forth, right up to 7.whatever billion people.  Max-happiness for all ? max-happiness for me.  Max-happiness is achieved by removing impediments to happiness, and putting up road signs and ice cream stands to make the trip easier.  You can’t force happiness on people, but given the option, more people will choose sleeping on a bed of rose petals than will choose the bed of thorns; they will choose the path of least resistance, which is always (unless you face brain disabilities as I do) the one which causes the least pain. Humans are like that, because pain hurts and pleasure feels good, and, barring dire need for sacrifice, it is perfectly logical to choose what feels good over what doesn’t. Suffering is not noble, and happiness is not a crime; the right to pursue it is the Prime Directive of humanity.</p>
<p>Logic says that you gotta make people happy.  That, my loves, is called “compassion”, and it is the <a href="http://www.sacred-texts.com/bud/tib/omph.htm" target="_blank" rel="noopener">jewel in the lotus</a> we call life.</p>

<!-- InstanceEndEditable -->
	</div><!-- InstanceEnd -->