<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Un-knot your knickers, you�ll breathe better.##/h1>
##p>I�m not a xyz-ist, because I am impartial to the best of my abilities, and �isms� and their relations make impartiality impossible.  I support all affirmation and defense of the inalienable rights of humans, I can tolerate no form of repression, and I believe in the fair balance of opposing or contradictory demands upon society�s resources.  Don�t accuse me of ethical hanky-panky, because it�s not true in advance, and it just wastes human-redemption time.##/p>
##p>I�m a �responsible capitalist technocrat�, if you want a label, and it means I�d vote to alter the framework of capitalism to require social responsibility equal to the profit-motive in the missions of corporations, and supplying a pool of high-credibility consultants and peer-qualified actors in the public sector.  That sounds like a lot, but it�s the jargon.  The gist of the platform is##/p>
##p>##strong>Everybody really do what everybody says they�re doing now.##/strong>##/p>
##p>Governments govern, corporate citizens act responsibly, the right people are hired for the right job, capitalists capitalize, socialist do social work.  Wow!  A democratic, capitalist system in which everybody acts honourably and with forethought.  How unexpected!  How refreshing! And all you have to change is (cough cough) to make the big boys stop doing do what they already say they don�t, and to start doing what they already say they do.##/p>
##p>FUN EXPERIMENT: go to a political party meeting, and make a fine speech about doing the above.  When they�ve finished telling you how deluded you are, read their own propaganda back to them. Read to them, in a firm but contemptuous drawl, exactly what their own employers and parties claim to be doing already.  Zany antics ensue!##/p>
##p>If corporations wish to be treated as �corporate citizens�, rather than as rapacious hostiles, they have to act as responsible citizens.  Right now, they get all the protections of citizenship, but have none of the liabilities or responsibilities. They are not even required to pay taxes, if they can come up with enough excuses. I think they should have to prove their citizenship before they can act in ways that affect us all; acting in ways that affect everyone is the responsibility of governments, not profiteers.  Profit is fine, but profit at the expense of the common good?  Nah, we�re not having that.  Your corporation can make you all as rich as you want, but you have to do your share: you avoid collateral damage, you don�t reward sociopathy, you don�t make poor people suffer, and you don�t leave your garbage for others to pick up.  Your business charter include a clear statement of social mission, right there beside your profit-making mission, and they are ##em>always##/em> of equal importance, except under emergency governance.##/p>
##p>That is no more than businesses have been claiming, for as long as propaganda and business have co-existed.  Capitalism is normal; it�s as human as clothing.  We want stuff�we want more stuff�we get bored with stuff�we want new stuff�  That�s how it is, and you�ll get shot by do-gooders if you try to change it.  I just want corporate citizens to actually be corporate citizens, and that�s all.  Large corporations acting as public citizens can do all the work that government functionaries and contractors do now, and, yes, they�ll do it better.  We have to be able to trust them to be good citizens; that�s the hard part, because there is no law saying that profiteers have a responsibility to their profitees, the way elected governments sometimes actually have to the general population.  Corporations can supply the planners, the builders, the medical staff, and the various janitorial tasks of civilization.  That�s what they do, and that�s what good citizens with too much money ought to be doing, anyway. And they can start paying their damn taxes, too.##/p>
##p>Government, to technocrats of my stripe, is the set of democratically-elected policy-makers and human-resources experts who make the moral and ethical decisions which define society�s future, at any given juncture.  To plain-Anglicize (wasn�t a word until just now)  the preceding: we elect people of both compassion and efficiency to ##em>hire##/em> people of both compassion and efficiency, who solve problems instead of people, and who don�t make up their morals as they go along, who won�t debate �right or wrong� while the city burns, and who always put people, real humans, first.  We don�t need to hire a work force; we need to hire people who know how to choose the right people for the jobs that need doing, and that, my sad little anti-capitalists, means not-you. Corporations solve corporate problems, and government solves governance problems.  Again, if you�ll notice now and not get angry at me, all I�m unreasonably undemanding is that governments do exactly what every party claims to be doing: making impartial decisions according to both human and corporate necessities, with humans always coming first; upholding human rights equally and without exception; protecting the vulnerable from harm wherever and whenever possible; preparing for future needs in timely fashion.##/p>
##p>If it all sounds familiar�well, um�er�I dare you to find a politician who does not make the above claims.  The problem is that the people we elect to govern us are the same people we elect to guide and protect us, and it can never quite work. First, having an idea does not make you a manager.  Second, talking about your idea does not make you a manager.  Third, blaming the previous administrations for the last three hundred failures of your idea makes you a dangerous anti-manager (see any ##em>Dilbert##/em>); it means, ahem�you fucked up, and don�t have the gonadal fortitude to eat the blame.##/p>
##p>Letting the ethics and morals guys run the company is a recipe for getting nothing at all done very slowly and over-budget.  Do not hire me.  No, seriously; I�m an ethics and morals man, and I will feed your cash-flow to cows, because they look so sad.  That said, running the company without an ethics and morals guy at the big table should be illegal, and punished with unholy long stays in a Las Vegas casino so blindingly lit you get a sunburn while losing all your money.##/p>";
