<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>What�s wrong with you people? #582##/h1>
##p>I just read a couple of fascinating articles on The Atlantic�s website.  The first is about feminist neurosurgeon who discounts any evidence of brain differences between men and women.  The second is about the �masculinity crisis�.  They are examples of the way the selfie-driven leftists manage to make everyone who isn�t them hate them.  They�re full of insults, lies, hidden agendas, presumption�all the usual tools of the warring zealot, but that�s not the problem.  They throw honesty, fairness, and respect for human rights under the bus without a second thought.  They do it constantly, all day, every day, and it�s all, and I mean all, exactly the same: every one of them blames me for their unhappiness, and finds no fault in shaming or punishing me, whether I�ve done something offensive or not.##/p>
##p>Let me describe myself:  I�m large, which gives people licence to accuse me of bullying.  I�m of euro descent, so idiots call me white; I�m beige, and proud of it, but I get no say in the matter.  I don�t dress like the disabled poor are supposed to, and my disability was, until recently, invisible; evidence to many that I�m ripping off the taxpayers, but proof of my middle-class privilege nonetheless.  I�m smart, which offends everybody, and leftists most of all.  I�m fair and politically impartial, which to leftists means I�m a crypto-conservative, and to the right means I�m not a crypto-conservative, and both of them accuse me of being the other.  I�m not LGBTQFRD or whatever the latest is, because my sexual orientation is �wife�, so I�m homophobic, transphobic, or the shiny new panqueerophobic, which actually would have no meaning, since �queer� and �pan� are not genders.  That�s all I�ll say for now.   Wait, before I forget: I�m a man.  Sorry.##/p>
##p>The point is that every single disadvantaged person in the world either hates me, or reserves the right to hate me.  I�ve never met every single disadvantaged person in the world, so I am, joking aside, hurt daily by false accusations, character assassination, and outright bigotry.  I�m barred from social events or meetings, even when I�ve helped pay for them.  I�ve been forced to sit through ambush theatre, where every aspect of masculinity was treated like diaper play.  I�ve been randomly insulted by people who don�t know me.##/p>
##p>I�ve never deliberately harmed anyone. When I�ve hurt people, I�ve done the right thing, to the best of my abilities.  I�m as innocent of sin as anyone out there can claim to be.  I�ve believed in nothing but equality, compassion, and universal and inalienable human rights above every other facet of my life, save the individual humans I love.  Why do I have to hear all the time that I�m evil?##/p>
##p>It hurts me.  I don�t like being accused of being evil, whether you dress it up in a bunny suit like �homophobia� or not.  I don�t do that, so I don�t deserve that.  It�s one of the great fictions of the outraged victim set, which never includes me, that men are cold, hard creatures who respond only to verbal violence.##/p>
##p>Here�s the first article.##/p>
##p>On the face of it, this seems like a fair and honest bit of reportage, but it�s so full of convenient half-truths and end-runs around pure logic that it shouldn�t have been published.  It starts with a put-down: it�s only �pop psychologists� who are willing to believe that there are sex-based differences between human brains; the hundreds of peer-reviewed articles on the subject are worth nothing.  When the author uses the phrase �pop psychology�, she�s attributing a hidden agenda to any scientist who disagrees with her, which is exactly what she�s doing. How is this piece not pop psychology?   No points for recognizing irony there.##/p>
##p>Having immediately dispensed with all opposing voices, she first introduces a bad guy, a straw-man, who will stand for all the scientists and everyone who believes them.  She chooses a non-scientist, whose opinion was published as just that, to represent all the men of the world.  The straw-man fallacy is the form of argument in which you tell everybody what someone else is really like, and really believes, in spite of what someone else really does or believes.  It�s easy to knock down a target you set up.  It�s also cheating.##/p>
##p>Now we know that the author won�t respect the rules of logic.  That�s another way of saying that she�ll lie when convenient.  That�s how she introduces the hero of the story, the lone gunman standing against the world.  She�s a hero already.##/p>
##p>What she says, however, is ludicrous.  Her studies may be honest, but her logic is the logic of convenience.  It�s lies, and someone that smart should know that other people that smart will know it�s a lie.  The next set of lies the author trots out are what is called in sensible circles �confirmation bias�.  When studies agree with her, they confirm that she�s right; when the studies say she�s wrong, she simply dismisses them as irrelevant, because they don�t say what they�re supposed to.  The problem is that even her own pronouncements and admissions show that she�s wrong, and it�s not even difficult to spot.##/p>
##p>If a large study in the UK indicates that there are small sex differences, but what they do is unclear, it�s dismissed.  When the article presents evidence in the author�s favour, she undermines her own position.  Yes, the brains are different sizes. Yes, they�re wired differently. Yes, there are small differences in the construction of certain brain parts.  Yes, men are violent hulking creatures where women are normal.  No, there�s no difference.##/p>
##p>But how do we know that there�s no real brain differences when the author just presented a great deal of solid evidence against her own position?  Well, since we don�t really know what those differences do, they aren�t evidence of ##em>real##/em> differences.  The meaning of �real� just changed; now it means, �approved�.  The argument just changed as well.  Now, the people who say there are differences have to prove that the differences they�ve found really are different.##/p>
##p>When you make a factual statement, you need facts to back it up.  Saying �you can�t prove that they�re real facts� is called �The Trump Gambit�.  It attempts to put the onus of proof on the audience, not on the performer.  It also is cheating, and it goes on all the time in articles like this.  But it�s nothing compared to the fun still to come.##/p>
##p>When doctors didn�t know how to treat my pain when I was a child, they told me, one and all, that it was �psychosomatic�.  That was medical code for �he�s either deluded or faking it�.  Any symptom not easily attributable was �all in my head�, which was a very weird thing to hear from the depths of a migraine, which is definitely in your head.##/p>
##p>Well, the sociologists equivalent response to anything for which a discrete (easily recognized and defined) mechanism isn�t visible, it�s caused by �society�.  All the differences between the ways men and women act are learned from the world at large.  My question is: �who taught the world at large?�  Where did all these invisible social mechanisms originate?  When did society perform the first socialization that made a boy like blue, instead of froofroo?  Exactly how did society learn to fetishize the female breast?  Who was the very first person to decide that men should repress their emotions so that the other men won�t see him cry?  If it�s society that causes these things, it has to have a mechanism.  �Socialization� is not a mechanism; it�s a way of saying �society did it�, which was what you�re supposed to be proving in the first place.##/p>
##p>When a scientist has to deny the validity of ALL the other science, you should be suspicious.  You should look, for instance, at what that scientist said in the past.  It seems that in the last five years, her opinion has gone from there being only small differences which probably aren�t that important, to there being huge differences which are completely unimportant which means there are no differences at all.  That�s not science anymore; that�s politics.  When it doesn�t even make sense on the surface, it�s doesn�t make sense below it either.##/p>
##p>This post-scientific agenda makes everything this woman says worthy of suspicion, as it would if a deeply Christian scientists presented evidence that God exists. Extraordinary claims require extraordinary evidence, and the lack of evidence against such a claim is only evidence itself, not proof, and it�s not even good evidence, either.##/p>
##p>I don�t even need to see the science that backs her up or knocks her down, because her science may be pristine, but that doesn�t mean she knows what it means in a social context.  When a neuroscientists requires such pseudo-science as �society did it, round up the usual suspects� to make her case, then her case is not science.  �Society did it� is not science, and never was, anymore than �your migraines are all in your head� was.##/p>
##p>A difference is a difference.  Listing the differences, and then saying that they aren�t differences, is not even common sense.  It�s Trumpian.  It�s weird.  It has an orange face and little chubby fingers.  And it is so far from what THE ENTIRE WORLD ALREADY KNOWS IS TRUE BECAUSE IT�S SMASH YOUR FACE OBVIOUS, that I would want review this reporter�s credentials.  If you spend ten minutes visiting reality, you�ll see a million ways in which the tendencies of female and male patterns are reflected over a huge (i.e., global) scale.  Those tendencies don�t just arise from nothing.  No one invented sexism, and put out a catalogue.  Trans-people have only been around for half a century; how did �society� come to invent transphobia before anyone knew what �trans� meant? Social constructs shape, not design.  Nature designs.  Evolution designs.  Otherwise, your entire sociological system is based on the feminist version of �intelligent design�; if humans made it, there must have been a first one.##/p>
##p>And now, gentle readers, a final kick in the teeth before bedtime: if my entire personality is based on �society made me what I am�, then so is yours.  If masculinity is shaped by society, then your femininity is too.  All your feminism is just stupid crap that society did, not me.  If it�s society�s fault, and not yours, then ##em>Gott im Himmel##/em> it�s not mine either..  There�s no out, so stop looking for an escape strategy: you can�t have the logic both ways.  If society made me what I am, and you�re part of society, then ##em>you##/em> made me what I am.  I�m your fault, aren�t I?  You�re as guilty as me.  And that means that I owe you nothing.  If I owe you nothing, then my next question will always be the same: �what�s in it for me?�##/p>
##p>Selfie-feminism treats me as an enemy.  It you offer me nothing but the threat of more insults, then why, out of all the gin joints in all the world, would I bother walking into yours?  Why, if I�m already guilty, do I care what you�ll think of me in the morning?  You hate me, so don�t be surprised when all you ever get is �what�s in it for me?�  Tell you what, though, if you go tell society to stop doing what it does, and it stops, let me know: you just said that it�s not my responsibility, and, really, you�re the one with the problem, so�you take care of it, OK?##/p>";
