<?php

namespace raingarden\rg_content\rg_poems\rg_t_to_other;

$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Things that are lies##/h2>##/li>
		##li class='poem line'>a dragonfly##/li>
		##li class='poem line'>in a spider's web##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a colourless veil of sheerest gauze, surrounding a red brocade divan##/li>
		##li class='poem line'>a lissom female, large of breast, dark of hair and mien##/li>
		##li class='poem line'>beyond the veil, another, and another still##/li>
		##li class='poem line'>receding into an unfathomable distance ##/li>
		##li class='poem line'>slender feet bare, neck pearled and fingers bejeweled##/li>
		##li class='poem line'>skirted in the egyptian style, a silken bodice barely covering##/li>
		##li class='poem line'>languid, soporific, she exudes the sultry##/li>
		##li class='poem line'>wrapped, as she is, in the musky perfume of want##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is a marble pedestal close at hand##/li>
		##li class='poem line'>on it arrayed fine fruit, temperate and sweet##/li>
		##li class='poem line'>gathered from far corners of a heavy-scented land##/li>
		##li class='poem line'>a glass of fine wine mingles it's heady nose##/li>
		##li class='poem line'>with the perfume of which we spoke##/li>
		##li class='poem line'>there can be no finer thing##/li>
		##li class='poem line'>no man could stumble across this sight##/li>
		##li class='poem line'>and not get hard##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>many veils away##/li>
		##li class='poem line'>a man in a boring suit is pushing at the fabric##/li>
		##li class='poem line'>he's a regular guy, beige and unpolished##/li>
		##li class='poem line'>maybe a little smarter than most, but##/li>
		##li class='poem line'>definitely unspectacular##/li>
		##li class='poem line'>he sees the lady##/li>
		##li class='poem line'>the lady of his dreams, she's relaxing##/li>
		##li class='poem line'>he wants that, got to have that##/li>
		##li class='poem line'>has never seen anything like that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>he pushes aside another veil##/li>
		##li class='poem line'>each one he moves, he can see her better##/li>
		##li class='poem line'>this is very good##/li>
		##li class='poem line'>there is nothing between him and her##/li>
		##li class='poem line'>except these goddamn veils##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a goddess in white, she hears a distant sound##/li>
		##li class='poem line'>a swishing, the sound a golden wing would make##/li>
		##li class='poem line'>as she turns her head, her midnight tresses##/li>
		##li class='poem line'>spread out, a fan on the perfect skin of her olive shoulder##/li>
		##li class='poem line'>her bosom shifts enticingly, her glorious hips turn##/li>
		##li class='poem line'>as she moves to face the source##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a graceful hand reaches for the fruit##/li>
		##li class='poem line'>selects an unblemished grape, she closes red lips##/li>
		##li class='poem line'>around it, reaches long fingers, beringed and painted,##/li>
		##li class='poem line'>for the wine, drinks like a queen##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the guy is pushing the veils aside still##/li>
		##li class='poem line'>he can see her almost clearly now, excellent##/li>
		##li class='poem line'>just a couple more of these curtains##/li>
		##li class='poem line'>and he will be there, to sit down and fondle her##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>her oval face registers the faintest alarm##/li>
		##li class='poem line'>she can see him now, emerging from the darkness##/li>
		##li class='poem line'>but she feels amost nothing, nothing but herself##/li>
		##li class='poem line'>a hand, rough and masculine##/li>
		##li class='poem line'>pushes aside the final protection##/li>
		##li class='poem line'>a man steps through, he blinks twice##/li>
		##li class='poem line'>at first glance, a look of longing and hunger,##/li>
		##li class='poem line'>that fades through surprise to disappointment##/li>
		##li class='poem line'>her face mirrors his, the sequence identical##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>he stands over her, the big goof##/li>
		##li class='poem line'>she's nothing special, what the hell?##/li>
		##li class='poem line'>a small woman, ordinary, a little flat where##/li>
		##li class='poem line'>he'd expected more, a little wide where##/li>
		##li class='poem line'>he'd expected less, dressed like a nurse, what's##/li>
		##li class='poem line'>up with that?  Where's the golden babe,##/li>
		##li class='poem line'>the jewelled whore, the dark piece he'd seen##/li>
		##li class='poem line'>from far away?  He's pissed, stubs his toe on something##/li>
		##li class='poem line'>can't see what, it's outside the pool of light##/li>
		##li class='poem line'>trips and falls forward, hands out in front of him##/li>
		##li class='poem line'>like he's reaching for her, but he just wants the couch##/li>
		##li class='poem line'>so he doesn't hit the floor face first##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>she screams, almost to break his ears##/li>
		##li class='poem line'>leaps to her feet, backs away, in terror##/li>
		##li class='poem line'>what happened to the handsome man she'd glimpsed##/li>
		##li class='poem line'>through the final veils? this lout, this lumpy thing##/li>
		##li class='poem line'>he lunges for her, she backs away, turns##/li>
		##li class='poem line'>finds a space in the veil on the side far side##/li>
		##li class='poem line'>pushes it aside, runs through one veil at a time, until she##/li>
		##li class='poem line'>disappears##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>he's tired he thinks, maybe I should just sit down##/li>
		##li class='poem line'>plops his ass down on the couch, wonders##/li>
		##li class='poem line'>what just happened?  he really thought he had##/li>
		##li class='poem line'>something##/li>
		##li class='poem line'>he looks up, sees the fruit, the unfinished wine##/li>
		##li class='poem line'>reaches for it, pops a grape into his mouth##/li>
		##li class='poem line'>sips at the wine, suddenly he has to lie down##/li>
		##li class='poem line'>he reclines, lost for a time, I'll just close my eyes##/li>
		##li class='poem line'>for a minute##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>he hears something, the sound of a wing##/li>
		##li class='poem line'>a hundred veils away, someone approaches##/li>
		##li class='poem line'>the footsteps are light, almost delicate##/li>
		##li class='poem line'>a woman's step, seemingly retracing his own path##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>she pushes one veil after another away, pesky things##/li>
		##li class='poem line'>she can see something now##/li>
		##li class='poem line'>a man, tall and perfectly formed##/li>
		##li class='poem line'>lying, carefree and handsome##/li>
		##li class='poem line'>on a red brocade divan##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a dragonfly##/li>
		##li class='poem line'>in a spider's web##/li>
	##/ul>
##/article>";