 class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2 class='poem'>You, my darlings##/h2>##/li>
		##li class='poem line'>by now you will have noticed##/li>
		##li class='poem line'>I'm making this up as I go along##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is my internal dj speaking##/li>
		##li class='poem line'>next up##/li>
		##li class='poem line'>a little song and dance##/li>
		##li class='poem line'>a little story##/li>
		##li class='poem line'>a joke or two.##/li>
		##li class='poem line'>then me again##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but first:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>tonight I have no poems in me##/li>
		##li class='poem line'>at least, I thought I didn't##/li>
		##li class='poem line'>my muse is having a bath, I miss her##/li>
		##li class='poem line'>but even muses have to take time off##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but there is always one thing I can write##/li>
		##li class='poem line'>says my internal dj, imagining an audience##/li> 
		##li class='poem line'>out there in the night##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there are invisible lines##/li>
		##li class='poem line'>unknowable forces##/li>
		##li class='poem line'>that link me to you (all of you)##/li>
		##li class='poem line'>what you get of me##/li>
		##li class='poem line'>is as inevitable as rain##/li>
		##li class='poem line'>and as long fore-ordained##/li>
		##li class='poem line'>if you were smart enough##/li>
		##li class='poem line'>you'd know what I was going to say next##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I am saved only by the quantum##/li>
		##li class='poem line'>a soup&ccedil;on of the random##/li>
		##li class='poem line'>the jello in the salad##/li>
		##li class='poem line'>when I'm replaced with a silicon chip##/li>
		##li class='poem line'>there will be no jello##/li>
		##li class='poem line'>
##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but you can't take an uninterrupted flow of poesy##/li>
		##li class='poem line'>you'd feel sick, like eating too much chocolate##/li>
		##li class='poem line'>so here I am, the master of ceremonies##/li>
		##li class='poem line'>providing the light in a basket of dark##/li>
		##li class='poem line'>and what is the one thing##/li>
		##li class='poem line'>I can always say to you?##/li>
		##li class='poem line'>it is this:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we are the same, you and I##/li>
		##li class='poem line'>we share this night, belong to each other##/li>
		##li class='poem line'>drink from the same trough.##/li>
		##li class='poem line'>collections of the physical, reaching##/li>
		##li class='poem line'>for the metaphysical##/li>
		##li class='poem line'>those lines that connect us, they are real##/li>
		##li class='poem line'>just ask your right brain##/li>
		##li class='poem line'>there is only one thing, and it is us##/li>
		##li class='poem line'>it's time to listen to the other hemisphere, people##/li>
		##li class='poem line'>that's what we do in the dark##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>you can ask my muse, when she finishes her bath##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>next up##/li>
		##li class='poem line'>a little song and dance##/li>
		##li class='poem line'>a little story##/li>
		##li class='poem line'>a joke or two.##/li>
		##li class='poem line'>then me again##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>always me (you, my darlings)##/li>
	##/ul>
##/article>";