<?php

namespace raingarden\rg_content\rg_poems\rg_g_to_m;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>How to Deal with Nothing##/h2>##/li>
		##li class='poem line'>hold your hands apart##/li>
		##li class='poem line'>you think:##/li>
		##li class='poem line'>there is nothing between them##/li>
		##li class='poem line'>but you know that's only##/li>
		##li class='poem line'>a convenient fiction##/li>
		##li class='poem line'>there is a small pond of air##/li>
		##li class='poem line'>between your outstretched fingers##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now close your eyes##/li>
		##li class='poem line'>relax your body##/li>
		##li class='poem line'>and think of nothing##/li>
		##li class='poem line'>no, i mean it##/li>
		##li class='poem line'>don't think##/li>
		##li class='poem line'>who is this idiot poet##/li>
		##li class='poem line'>telling me to think of nothing##/li>
		##li class='poem line'>in the middle of a poem?##/li>
		##li class='poem line'>stop all conscious thought##/li>
		##li class='poem line'>for just long enough##/li>
		##li class='poem line'>to not read this verse##/li>
		##li class='poem line'>think of nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now think again##/li>
		##li class='poem line'>stay with me, here##/li>
		##li class='poem line'>you tried to think of nothing##/li>
		##li class='poem line'>but even if you cleared your mind##/li>
		##li class='poem line'>as well as a Buddhist lama could do##/li>
		##li class='poem line'>your brain was still working##/li>
		##li class='poem line'>you were thinking##/li>
		##li class='poem line'>breathe, lungs##/li>
		##li class='poem line'>beat, heart##/li>
		##li class='poem line'>flow, blood##/li>
		##li class='poem line'>you cannot think nothing##/li>
		##li class='poem line'>as long as you are alive##/li>
		##li class='poem line'>nothing, again, is a convenient fiction##/li>
		##li class='poem line'>that means nothing of noticeable value##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now, stretch out your mind##/li>
		##li class='poem line'>further than the reach of your hands##/li>
		##li class='poem line'>stretch it all the way to Proxima Centauri##/li>
		##li class='poem line'>the star that is our nearest neighbour##/li>
		##li class='poem line'>trillions of kilometres of nothing away##/li>
		##li class='poem line'>luxuriate in the space##/li>
		##li class='poem line'>the freedom of room##/li>
		##li class='poem line'>the treasure of emptiness##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>are you done?##/li>
		##li class='poem line'>is the furthest reach of your mind##/li>
		##li class='poem line'>in orbit around a star?##/li>
		##li class='poem line'>that nothing##/li>
		##li class='poem line'>through which the tendrils of your consciousness##/li>
		##li class='poem line'>have traveled at faster than the speed of light##/li>
		##li class='poem line'>is not nothing at all##/li>
		##li class='poem line'>it is a sea##/li>
		##li class='poem line'>without borders##/li>
		##li class='poem line'>of particles##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>those particles##/li>
		##li class='poem line'>from the smallest string##/li>
		##li class='poem line'>to the greatest dust mote##/li>
		##li class='poem line'>exist everywhere##/li>
		##li class='poem line'>even in the deepest vacuum##/li>
		##li class='poem line'>particles pop into existence##/li>
		##li class='poem line'>and pop out again##/li>
		##li class='poem line'>there is never nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>even the space between the particles##/li>
		##li class='poem line'>is not nothing##/li>
		##li class='poem line'>the universe is not an emptiness##/li>
		##li class='poem line'>begging to be filled##/li>
		##li class='poem line'>it is stuff##/li>
		##li class='poem line'>wishing for space##/li>
		##li class='poem line'>we see it as empty##/li>
		##li class='poem line'>because our eyes are big##/li>
		##li class='poem line'>and our minds are clumsy##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>imagine now##/li>
		##li class='poem line'>a movie screen##/li>
		##li class='poem line'>you with your popcorn##/li>
		##li class='poem line'>and a brain bigger than the biggest computer##/li>
		##li class='poem line'>you are so smart##/li>
		##li class='poem line'>that you can watch every movie ever made##/li>
		##li class='poem line'>at the same time##/li>
		##li class='poem line'>and all on the same screen##/li>
		##li class='poem line'>(of course, you only watch the good ones)##/li>
		##li class='poem line'>while Marilyn cavorts##/li>
		##li class='poem line'>and Gable plays cowboy##/li>
		##li class='poem line'>you are watching a cartoon##/li>
		##li class='poem line'>and you are understanding all of it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that screen is the multiverse##/li>
		##li class='poem line'>and each movie projected onto it##/li>
		##li class='poem line'>is a universe##/li>
		##li class='poem line'>if part of a movie goes black##/li>
		##li class='poem line'>another movie fills in the blank space##/li>
		##li class='poem line'>there is never nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all the spaces that share our space##/li>
		##li class='poem line'>(some are next door, not right in our house)##/li>
		##li class='poem line'>share the stuff of reality,##/li>
		##li class='poem line'>the seething sea of objects.##/li>
		##li class='poem line'>some are of a single dimension##/li>
		##li class='poem line'>others of two##/li>
		##li class='poem line'>many of three##/li>
		##li class='poem line'>and so on up to ten##/li>
		##li class='poem line'>some are as big as our universe##/li>
		##li class='poem line'>and some are so small##/li>
		##li class='poem line'>that we have no words to define them##/li>
		##li class='poem line'>(we make up cute names for them##/li>
		##li class='poem line'>strings, branes, blobs)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>you may retract your mind##/li>
		##li class='poem line'>leave the Proxima Centaurians to their supper##/li>
		##li class='poem line'>(they were getting tired of seeing you there##/li>
		##li class='poem line'>they are not like us, they don't like peaches)##/li>
		##li class='poem line'>and as your mind crosses##/li>
		##li class='poem line'>the Great Nothing##/li>
		##li class='poem line'>you will feel the warm caress##/li>
		##li class='poem line'>of the Great Something##/li>
		##li class='poem line'>and as you return to your parochial home##/li>
		##li class='poem line'>you will know##/li>
		##li class='poem line'>that you will never feel nothing again.##/li>
	##/ul>
##/article>";