<?php

namespace raingarden\rg_content\rg_poems\rg_g_to_m;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>in praise of your body##/h2>##/li>
		##li class='poem line'>the body knows##/li>
		##li class='poem line'>what the body is for##/li>
		##li class='poem line'>it remembers##/li>
		##li class='poem line'>every moment##/li>
		##li class='poem line'>every sliding of my fingers##/li>
		##li class='poem line'>across##/li>
		##li class='poem line'>your magnetic skin##/li>
		##li class='poem line'>it knows##/li>
		##li class='poem line'>as i take##/li>
		##li class='poem line'>your breasts in my hands##/li>
		##li class='poem line'>that these hands##/li>
		##li class='poem line'>are the architects##/li>
		##li class='poem line'>of exactly now##/li>
		##li class='poem line'>and that they know##/li>
		##li class='poem line'>the future##/li>
		##li class='poem line'>that onrushing time##/li>
		##li class='poem line'>of coalescence##/li>
		##li class='poem line'>when my touch##/li>
		##li class='poem line'>will come home##/li>
		##li class='poem line'>part your lips##/li>
		##li class='poem line'>and smooth the way##/li>
		##li class='poem line'>for utter normality##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>pardon me a second -##/li>
		##li class='poem line'>your nipples##/li>
		##li class='poem line'>have something to tell me##/li>
		##li class='poem line'>and who am i##/li>
		##li class='poem line'>not to listen?##/li>
		##li class='poem line'>come closer##/li>
		##li class='poem line'>it is a secret what they say##/li>
		##li class='poem line'>a message##/li>
		##li class='poem line'>for my tongue's ears only##/li>
		##li class='poem line'>and##/li>
		##li class='poem line'>i must reply!##/li>
		##li class='poem line'>this cannot##/li>
		##li class='poem line'>go unanswered##/li>
		##li class='poem line'>tell your clitoris##/li>
		##li class='poem line'>that i will get there##/li>
		##li class='poem line'>soon##/li>
		##li class='poem line'>and that your void##/li>
		##li class='poem line'>will yet be filled.##/li>
		##li class='poem line'>void? what void?##/li>
		##li class='poem line'>do i speak of your mind?##/li>
		##li class='poem line'>or  do i talk circles##/li>
		##li class='poem line'>around what is you?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is a spot##/li>
		##li class='poem line'>i have never seen##/li>
		##li class='poem line'>i cannot give it a name##/li>
		##li class='poem line'>but##/li>
		##li class='poem line'>its essence is yearning##/li>
		##li class='poem line'>there is nothing else##/li>
		##li class='poem line'>that it does##/li>
		##li class='poem line'>but beg and reward##/li>
		##li class='poem line'>i will not tell you##/li>
		##li class='poem line'>where it is##/li>
		##li class='poem line'>i couldn't##/li>
		##li class='poem line'>if i wanted to##/li>
		##li class='poem line'>it is the source##/li>
		##li class='poem line'>of my power##/li>
		##li class='poem line'>and must remain known to##/li>
		##li class='poem line'>none##/li>
		##li class='poem line'>but my me##/li>
		##li class='poem line'>the lodestone of my hunger##/li>
		##li class='poem line'>draws me on##/li>
		##li class='poem line'>and in##/li>
		##li class='poem line'>but not through:##/li>
		##li class='poem line'>never that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now stop me if you've heard this before -##/li>
		##li class='poem line'>bells, whistles, cherries and lemons.##/li>
		##li class='poem line'>a willow weeping##/li>
		##li class='poem line'>its love##/li>
		##li class='poem line'>in a wind, on a beach;##/li>
		##li class='poem line'>what did you expect##/li>
		##li class='poem line'>after thirty thousand years?##/li>
		##li class='poem line'>there is nowhere##/li>
		##li class='poem line'>left on you##/li>
		##li class='poem line'>on which i have not lain##/li>
		##li class='poem line'>no part of me##/li>
		##li class='poem line'>that has not lain on you##/li>
		##li class='poem line'>in the ten trillion##/li>
		##li class='poem line'>mathematical possibilities##/li>
		##li class='poem line'>of sex##/li>
		##li class='poem line'>my cells##/li>
		##li class='poem line'>know you##/li>
		##li class='poem line'>hello you, remember me?##/li>
		##li class='poem line'>you used to be forbidden##/li>
		##li class='poem line'>now my master##/li>
		##li class='poem line'>will tickle##/li>
		##li class='poem line'>that place in your throat##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>wait, let me##/li>
		##li class='poem line'>put this##/li>
		##li class='poem line'>another way##/li>
	##/ul>
##/article>";