<?php

namespace raingarden\rg_content\rg_poems\rg_g_to_m;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Joke##/h2>##/li>
		##li class='poem line'>a man walks into a bar##/li>
		##li class='poem line'>welcome, says the bartender##/li>
		##li class='poem line'>what can i get you?##/li>
		##li class='poem line'>where am i, the man asks##/li>
		##li class='poem line'>you're in the bar, the bartender answers##/li>
		##li class='poem line'>and i'm the bartender##/li>
		##li class='poem line'>what'll you have?##/li>
		##li class='poem line'>i'm confused, i only fell off my chair##/li>
		##li class='poem line'>a lot of people come here that way##/li>
		##li class='poem line'>ok...i guess i'll have a martini##/li>
		##li class='poem line'>the bartender hands him a beer##/li>
		##li class='poem line'>no, i said a martini##/li>
		##li class='poem line'>oh, sorry, says the bartender##/li>
		##li class='poem line'>he takes back the beer##/li>
		##li class='poem line'>puts a beer down on the counter##/li>
		##li class='poem line'>there you go##/li>
		##li class='poem line'>no, a martini##/li>
		##li class='poem line'>oh, sorry, says the bartender##/li>
		##li class='poem line'>and hands him the beer##/li>
		##li class='poem line'>ok, i'll have a beer then##/li>
		##li class='poem line'>the bartender smiles##/li>
		##li class='poem line'>we always try to please##/li>
		##li class='poem line'>the man drinks the beer##/li>
		##li class='poem line'>sometime between looking up and looking down##/li>
		##li class='poem line'>the beer is empty##/li>
		##li class='poem line'>the bartender is right there##/li>
		##li class='poem line'>what can i get you?##/li>
		##li class='poem line'>how about a rum and coke?##/li>
		##li class='poem line'>coming right up, says the bartender##/li>
		##li class='poem line'>and hands him a beer##/li>
		##li class='poem line'>by now the man is used to this##/li>
		##li class='poem line'>thanks he says##/li>
		##li class='poem line'>no problem##/li>
		##li class='poem line'>the man drinks the beer, the beer is gone##/li>
		##li class='poem line'>the beer is right there and the bartender is smiling##/li>
		##li class='poem line'>what's the alcohol percentage in this beer?##/li>
		##li class='poem line'>no idea, but it's just normal beer, says the bartender##/li>
		##li class='poem line'>welcome, what can i get you?##/li>
		##li class='poem line'>i suppose i'll have a beer##/li>
		##li class='poem line'>the man drinks his beer, bored now##/li>
		##li class='poem line'>takes a table in the back##/li>
		##li class='poem line'>all around him people are laughing and ##/li>
		##li class='poem line'>smoking and grabbing a handful of breast##/li>
		##li class='poem line'>he checks his pocket, there's a pack of cigarettes there##/li>
		##li class='poem line'>he doesn't smoke but he lights one anyway##/li>
		##li class='poem line'>the waitress comes to the table##/li>
		##li class='poem line'>evening handsome, what'll it be?##/li>
		##li class='poem line'>he decides to try again##/li>
		##li class='poem line'>martini, very dry##/li>
		##li class='poem line'>oh, sophisticated man##/li>
		##li class='poem line'>she comes back with a beer##/li>
		##li class='poem line'>the man is not surprised##/li>
		##li class='poem line'>he drinks the beer##/li>
		##li class='poem line'>finishes his cigarette, butts it out into a clean ashtray##/li>
		##li class='poem line'>the waitress is there##/li>
		##li class='poem line'>he says no more for me##/li>
		##li class='poem line'>just the bill please##/li>
		##li class='poem line'>on the house says the waitress and smiles at him##/li>
		##li class='poem line'>from behind the bar the bartender smiles too##/li>
		##li class='poem line'>everybody smiles at him##/li>
		##li class='poem line'>he finds himself smiling back##/li>
		##li class='poem line'>stands, heads for the door##/li>
		##li class='poem line'>he steps out into the street##/li>
		##li class='poem line'>next door to the bar is a door to a bar##/li>
		##li class='poem line'>there's a bus coming down the street##/li>
		##li class='poem line'>the driver is smiling##/li>
		##li class='poem line'>the man steps out in front of the bus##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a man walks into a bar##/li>
		##li class='poem line'>welcome says the bartender##/li>
		##li class='poem line'>let me guess...you're a martini man##/li>
		##li class='poem line'>have a seat##/li>
		##li class='poem line'>the bartender shakes the gin and vermouth##/li>
		##li class='poem line'>pours the drink, pops in an olive##/li>
		##li class='poem line'>hands it to him##/li>
		##li class='poem line'>at least you know how to make a martini, says the man##/li>
		##li class='poem line'>sorry? says the bartender##/li>
		##li class='poem line'>i said at least...forget it##/li>
		##li class='poem line'>the man goes to a table##/li>
		##li class='poem line'>he likes it here better than the other place##/li>
		##li class='poem line'>he drinks the martini, it's passable##/li>
		##li class='poem line'>the waiter is there, smiling and slicked hair##/li>
		##li class='poem line'>another, sir?##/li>
		##li class='poem line'>absolutely says the man, make it two##/li>
		##li class='poem line'>excellent sir##/li>
		##li class='poem line'>the waiter is back with a martini##/li>
		##li class='poem line'>the man says nothing##/li>
		##li class='poem line'>he's beginning to see a pattern here##/li>
		##li class='poem line'>what do i owe you?##/li>
		##li class='poem line'>on the house, sir, enjoy it##/li>
		##li class='poem line'>the man gets up and goes to the washroom##/li>
		##li class='poem line'>there's a row of urinals stretching into infinity##/li>
		##li class='poem line'>oh, wait, that's a trick with mirrors, there's only one##/li>
		##li class='poem line'>he pisses out the beer to make room for the martinis##/li>
		##li class='poem line'>on his way out he notices a stairway##/li>
		##li class='poem line'>he climbs up to the second floor, leans out a window##/li>
		##li class='poem line'>next door to the bar is the door to another bar##/li>
		##li class='poem line'>there's a bus coming##/li>
		##li class='poem line'>he throws himself down into the street, steps out##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a man walks into a bar##/li>
		##li class='poem line'>the bartender smiles at him##/li>
		##li class='poem line'>the man grabs him by the shirt##/li>
		##li class='poem line'>where am i, who are you?##/li>
		##li class='poem line'>you're in the bar, mister, i'm the bartender##/li>
		##li class='poem line'>i was just in a bar##/li>
		##li class='poem line'>oh, that wasn't the bar, this is the bar##/li>
		##li class='poem line'>there are bars all up and down the street##/li>
		##li class='poem line'>no sir, this is the only bar on this street##/li>
		##li class='poem line'>maybe you're lost##/li>
		##li class='poem line'>the man runs to the door##/li>
		##li class='poem line'>steps out into the street##/li>
		##li class='poem line'>goes next door to the bar##/li>
		##li class='poem line'>the bartender is smiling at him##/li>
		##li class='poem line'>did you find what you were looking for sir?##/li>
		##li class='poem line'>the man steps out into the street##/li>
		##li class='poem line'>there's a bus coming##/li>
		##li class='poem line'>while he watches, a man steps out of the bar next door##/li>
		##li class='poem line'>jumps into the path of the bus##/li>
		##li class='poem line'>the bus doesn't stop##/li>
		##li class='poem line'>there's no body after the bus passes by##/li>
		##li class='poem line'>the man goes back into the bar##/li>
		##li class='poem line'>steps outside again##/li>
		##li class='poem line'>the bus is coming##/li>
		##li class='poem line'>he steps out##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a man walks into a bar##/li>
		##li class='poem line'>the bartender reminds him of somebody##/li>
		##li class='poem line'>where am i really, he screams at the bartender?##/li>
		##li class='poem line'>you're in the bar, sir##/li>
		##li class='poem line'>i was just in a bar##/li>
		##li class='poem line'>oh, that wasn't the bar sir, this is the bar##/li>
		##li class='poem line'>what's the difference?##/li>
		##li class='poem line'>oh, those other places, they don't know how to serve a martini##/li>
		##li class='poem line'>get me a martini##/li>
		##li class='poem line'>the bartender hands him a beer##/li>
		##li class='poem line'>this again says the man##/li>
		##li class='poem line'>he steps out into the street##/li>
		##li class='poem line'>steps in front of the bus##/li>
		##li class='poem line'>walks into a bar##/li>
		##li class='poem line'>steps in front of the bus##/li>
		##li class='poem line'>walks into a bar##/li>
		##li class='poem line'>steps in front of the bus##/li>
		##li class='poem line'>walks##/li>
		##li class='poem line'>steps##/li>
		##li class='poem line'>walks##/li>
		##li class='poem line'>steps##/li>
		##li class='poem line'>walks##/li>
		##li class='poem line'>steps##/li>
		##li class='poem line'>walks##/li>
		##li class='poem line'>steps##/li>
		##li class='poem line'>walks##/li>
		##li class='poem line'>steps##/li>
		##li class='poem line'>walks##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a man walks into a bar##/li>
		##li class='poem line'>sits down at the bar, holding his head in his hands##/li>
		##li class='poem line'>sobbing uncontrollably##/li>
		##li class='poem line'>at any moment, the bartender will say welcome##/li>
		##li class='poem line'>nothing happens##/li>
		##li class='poem line'>he looks up on time to see the bartender going upstairs##/li>
		##li class='poem line'>he bangs on the counter##/li>
		##li class='poem line'>the other patrons stare at him like he's crazy##/li>
		##li class='poem line'>maybe he is crazy##/li>
		##li class='poem line'>what do I have to do to get a drink around here?##/li>
		##li class='poem line'>he goes behind the counter, frothing and swearing##/li>
		##li class='poem line'>puts together a martini##/li>
		##li class='poem line'>he's shaking it when a man walks into the bar##/li>
		##li class='poem line'>sits down at the counter, looking dazed##/li>
		##li class='poem line'>the first man catches sight of himself in the mirror##/li>
		##li class='poem line'>nice uniform he thinks##/li>
		##li class='poem line'>welcome, he says##/li>
		##li class='poem line'>what can i get you?##/li>
		##li class='poem line'>the man orders a beer##/li>
		##li class='poem line'>the bartender puts a martini down in front of him##/li>
		##li class='poem line'>no, a beer##/li>
		##li class='poem line'>the bartender takes the martini away##/li>
		##li class='poem line'>mixes the man a martini##/li>
		##li class='poem line'>ok...says the man ##/li>
		##li class='poem line'>i only fell off a chair he says##/li>
		##li class='poem line'>we get a lot of people that way##/li>
	##/ul>
##/article>";