<?php

namespace raingarden\rg_content\rg_poems\rg_g_to_m;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Language##/h2>##/li>
		##li class='poem line'>in the beginning##/li>
		##li class='poem line'>was the word##/li>
		##li class='poem line'>and the word##/li>
		##li class='poem line'>was##/li>
		##li class='poem line'>keffuffle##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>everything since then##/li>
		##li class='poem line'>has mirrored that moment##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>eventually##/li>
		##li class='poem line'>words invented physical objects, actions, and events##/li>
		##li class='poem line'>to give meaning to themselves##/li>
		##li class='poem line'>they started with the basics##/li>
		##li class='poem line'>universe##/li>
		##li class='poem line'>kaboom##/li>
		##li class='poem line'>expansion##/li>
		##li class='poem line'>and other keffuffular things##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in time, they gave meaning to evolution##/li>
		##li class='poem line'>for which evolution was eternally grateful##/li>
		##li class='poem line'>it took only a few billion years##/li>
		##li class='poem line'>(which eternally thinks is funny)##/li>
		##li class='poem line'>to give meaning to human and intelligence##/li>
		##li class='poem line'>although these do not always belong in the same sentence##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>suddenly, there was a way##/li>
		##li class='poem line'>for words of all sorts##/li>
		##li class='poem line'>to give themselves meaning##/li>
		##li class='poem line'>words began to coalesce into groups##/li>
		##li class='poem line'>to organize##/li>
		##li class='poem line'>to form meaningful collections##/li>
		##li class='poem line'>words that had never had a hope in hell##/li>
		##li class='poem line'>suddenly found ways##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>be##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>stuff##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>some words got together##/li>
		##li class='poem line'>and became abstract concepts##/li>
		##li class='poem line'>these aggregations of words##/li>
		##li class='poem line'>occupied many minds##/li>
		##li class='poem line'>using brains and bodies##/li>
		##li class='poem line'>as their bases of operation##/li>
		##li class='poem line'>they became law##/li>
		##li class='poem line'>and math##/li>
		##li class='poem line'>and philosophy##/li>
		##li class='poem line'>some very specialized words##/li>
		##li class='poem line'>got together to describe all the other words##/li>
		##li class='poem line'>and became science##/li>
		##li class='poem line'>some very abstract words##/li>
		##li class='poem line'>that could not be written with letters##/li>
		##li class='poem line'>became even more abstract##/li>
		##li class='poem line'>and were art##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the finest of the words##/li>
		##li class='poem line'>those who existed in response##/li>
		##li class='poem line'>to their own aesthetic urges##/li>
		##li class='poem line'>became literature##/li>
		##li class='poem line'>words begat words##/li>
		##li class='poem line'>words begat ideas##/li>
		##li class='poem line'>ideas needed words##/li>
		##li class='poem line'>to define them##/li>
		##li class='poem line'>words poured out##/li>
		##li class='poem line'>from the word-vats##/li>
		##li class='poem line'>called humans##/li>
		##li class='poem line'>surely##/li>
		##li class='poem line'>this was mankind's finest task##/li>
		##li class='poem line'>to give life to all the words##/li>
		##li class='poem line'>which we had never even known##/li>
		##li class='poem line'>could be invented, arranged##/li>
		##li class='poem line'>and perhaps controlled##/li>
		##li class='poem line'>their raw power directed##/li>
		##li class='poem line'>to give meaning##/li>
		##li class='poem line'>to the word god##/li>
		##li class='poem line'>i mean good##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am a son of this evolution##/li>
		##li class='poem line'>i have given myself to the words##/li>
		##li class='poem line'>i am their slave##/li>
		##li class='poem line'>they have loved me##/li>
		##li class='poem line'>and used my hands##/li>
		##li class='poem line'>to write##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this##/li>
	##/ul>
##/article>";