<?php

namespace raingarden\rg_content\rg_poems\rg_g_to_m;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Me in a mirror##/h2>##/li>
		##li class='poem line'>It is impossible to like what I see##/li>
		##li class='poem line'>I cannot look at my reflection##/li>
		##li class='poem line'>without making the same wish##/li>
		##li class='poem line'>I have made a million times##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but there are good things too##/li>
		##li class='poem line'>my straight jawline##/li>
		##li class='poem line'>my deepset eyes##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I don't get along with my nose##/li>
		##li class='poem line'>we are enemies, my nose and me##/li>
		##li class='poem line'>it's not enough that it is too big for my face##/li>
		##li class='poem line'>it has to grow hairs##/li>
		##li class='poem line'>which must then be removed##/li>
		##li class='poem line'>not a delicious process at all##/li>
		##li class='poem line'>I often think##/li>
		##li class='poem line'>I am only one surgery away##/li>
		##li class='poem line'>from being handsome##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>my eyes are the blue of a hazy sky##/li>
		##li class='poem line'>when I was young, they were the blue of a clear sky##/li>
		##li class='poem line'>but all things fade as one ages##/li>
		##li class='poem line'>I like my eyes, they make up for my nose##/li>
		##li class='poem line'>they have mystery, but they are clear at the same time##/li>
		##li class='poem line'>this is a good thing, my eyes are an oxymoron##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>my hair has retained its blondness##/li>
		##li class='poem line'>when the blondness of my brother has faded to brown##/li>
		##li class='poem line'>blonds do not have more fun, but we have fun trying##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is a 96 percent chance that I'm taller than you##/li>
		##li class='poem line'>in most mirrors, the top of my head is truncated##/li>
		##li class='poem line'>it is as if my braincase is not important to##/li>
		##li class='poem line'>the manufacturers of mirrors##/li>
		##li class='poem line'>I don't like looking at my pants in the mirror##/li>
		##li class='poem line'>they're always too short...it's hard to find a 35 inch inseam##/li>
		##li class='poem line'>with a 38 waist##/li>
		##li class='poem line'>which brings me to my fatness##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I have put on a lot of weight lately##/li>
		##li class='poem line'>4 years ago, I was 160 pounds##/li>
		##li class='poem line'>now I am 240, a big man##/li>
		##li class='poem line'>it's good to be big, but I've started to jiggle##/li>
		##li class='poem line'>this is not a good thing at all##/li>
		##li class='poem line'>my belly hangs over my belt slightly##/li>
		##li class='poem line'>oddly, the weight only shows on my trunk##/li>
		##li class='poem line'>neither on my legs, nor my arms##/li>
		##li class='poem line'>but I can tell you, it's better##/li>
		##li class='poem line'>than being the effeminate bone rack##/li>
		##li class='poem line'>that I once was##/li>
		##li class='poem line'>I am hard to intimidate, as I have the security of size##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I know my girlfriend thinks I'm good-looking##/li>
		##li class='poem line'>I won't permit her to call me cute, although I have dimples.##/li>
		##li class='poem line'>I hate cute.##/li>
		##li class='poem line'>she's biased, but I like it anyway##/li>
		##li class='poem line'>I wish I could see what she sees, but almost nobody##/li>
		##li class='poem line'>can see him/herself##/li>
		##li class='poem line'>without cringing##/li>
		##li class='poem line'>the only people who can are usually repulsive in another way##/li>
		##li class='poem line'>they represent to us the triumph of form over substance##/li>
		##li class='poem line'>I don't hate them##/li>
		##li class='poem line'>ok, I hate them##/li>
		##li class='poem line'>no, I don't hate them##/li>
		##li class='poem line'>wait, I do##/li>
		##li class='poem line'>not##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I admit my vanity##/li>
		##li class='poem line'>I don't know from whom I inherit this##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is a good thing I am not better-looking##/li>
		##li class='poem line'>or my perfection would go to my head##/li>
	##/ul>
##/article>";