<?php

namespace raingarden\rg_static_pages;

$the_html = "
##section class='archives poetry' id='the_poetry_intro' role='index'>
	##div class='archives poetry intro' id='the_poetry_shelf'>
		##h1>You want to hear something funny?##/h1>
		##p>The only career I ever actually wanted to have was “poet”.  I realized at 13 that I was all about words, and when I looked up Hamlet’s soliloquies to find out what Shakespeare’s big problem was, I knew I was staring into the face of magic.  I recognized instantly that I was reading the Sir Isaac Newton of literature, listening to words of transcendent genius, of a magnitude far, far greater than mere brilliance, as if they were speaking to me alive, right there, and they were right.  Some of it I didn’t get, but it was as if I was listening to a dialect of English close enough to understand, with a few gaps; what was new to me was the music in it, the emotion expressed in rhythm and timing so powerful that you couldn’t help singing it to yourself, no matter what the missing words meant.  You could get it, grasp it, know what it was telling you, just by the cascade of emotions it triggers. I knew at that moment that I had found my demi-god.##/p>
		##p>The problem, of course, is that poetry is a particularly low-paying position these days.  Poets don’t just get jobs to support their own art; they get jobs to support their art-form itself.  We pay to keep poetry alive.  I’ve tried to give up on the idea of poetry many times, but it’s never real, and I always know that underneath the bravado. I are it, it are me, done deal.##/p>
		##p>Before you console me with “poetry is all around us, it’s just disguised as teenage hoodlums yelling about bitches and money”, no, it most certainly is not. Let’s sort this out right now.##/p>
		##p>Rap is not poetry.  It is poetic at times, but the practitioners of a hybrid art form are not automatically practitioners of any of its contributing forms.  Angry shouting over a synthetic and entirely undanceable one-drum band is not music — a vague beat alone is not music; we don’t credit clocks or cicadas for theirs, and they’re better at it.  A vague rhyming scheme attached to a self-referential stream-of-bravado is not poetry. I’m not even sure that it can be called poetic, because it shows none of the other qualities normally present in poetry, but calling something “poetic” and calling it “poetry” are not the same.  Rap, as good, bad, or ugly as it may be, is perfectly entitled to its own category, and hybrid art forms are no less legitimate than the art forms they grow out of, but rap is not poetry, and it’s not music; it’s rap.##/p>
		##p>The point of which is: don’t tell me that poetry is alive and well in hip-hop culture.  It isn’t. Even real poetry written and performed according to the standards of rap music, but without the gold chains and bitches, is turgid, predictable self-advertising, over a boring beat, but this time an imaginary one. They call this form “slam poetry”, as if the implicit violence of the label belies the inadequacy of its practice.  By this measure, “ultimate fighting throw-down poetry” must absolutely…um…rock. You will find me not there at any local events where skill with nunchaku sticks is a valuable poetic tool.##/p>
		##p>No, if poetry is to be saved, it will have to be me who does it. If poetry is ever to emerge once again from the dank off-night coffeeshops and dive bars where it’s presently found, or maybe just lost, it will have to be stripped down to the frame and rebuilt from the ground up.  It has to get relevant, and not by yelling about Republican politics; it has to replace “poetry” with “spoken art” in the minds of the iClique. Poetry is guys with beards and identity-problems to most people; they’re right. Not because it really is like that, but because image is everything in the entertainment world. I thought we knew that.##/p>
		##p>Of course we knew that. What we find amusing is the idea of poetry as entertainment.  Yeah, right, poetry…you go, girl.  Sell tickets, see the world, call me when you give up trying. That’s what you said, there in the dark privacy of your inner cynic, isn’t it? Which explains things perfectly: the most entertaining thing in poetry is the idea that anyone would find poetry entertaining.##/p>
		##p>How do you make poetry entertaining? That’s like making toast vivacious. That’s like making sitting down the national sport. I guaranteest thee: that’s not going to help. Here’s what’s going to help:##/p>
		##p>Write better poetry.  Perform it better.  Stop “writing for myself” and have the courtesy to think about the audience.  Think about how much you hate listening to bad poetry poorly performed in lousy venues, or in any performance equivalent, and don’t do that. Get real.  Make it worth it. And please stop making it about you.  Really, that’s enough; stop making it about you. You’re boring. A poem can be about you, but poetry is not “about” you.  Poetry is about poetry; poetry is speech, speech requires an audience, audiences require entertainment, gee whiz wordfreaks get your heads out of the echo chambers of your own asses and start talking to people about themselves, not about you, because, as they say in reality, no one cares what you think…extended pregnant pause…unless its about them. Ding!##/p>
		##p>Now, again, slowly, for the people who were watching themselves gesticulate: no…one…cares.##/p>
		##p>What exactly all the preceding means in terms of my own product will remain a proprietary secret until I’m convinced I’m not under surveillance, poetry secrets being the jealously-guarded powder-kegs we see on so many TV shows these days.  Do not tell the entire world to stay tuned on my behalf, or at least everyone you’ve personally ever heard of.  Thanks.##/p>
	##/div>	
	
##/section>";