<?php

namespace raingarden\rg_static_pages;

$the_html = "
	##p>##strong>Copyright:##/strong> All rights belong to Adam J. Richards, of St. Catharines, Ontario, 1979 to 2018.##/p>

	##p>##strong>License:##/strong> The earliest creative work on this site is from 1979, when Jesus was still an apprentice, and God roamed the earth dressed as Diplodocus. My copyright applies to these and to all material created between then and today, without exception, including my web designs and code as they appear on my sites.  You can repost most material as you see fit, if you don't change the text, and you identify me, 'Adam J. Richards, Raingarden.Cafe', as the source. If you repost any of my work for commercial purposes, you owe me every cent you make from it, because I'm not selling the rights to anyone who will profit by them, and by using the material you agree to pay me whatever profit you gain by it.  If you ask permission to use my work, and then use it for other purposes than the one we agreed on, then the price is again every cent you make on it.##/p>

	##p>##strong>Corrections: ##/strong>If you find mistakes, invalid statements of fact, or are offended in some way, use the ##a href='htt p://raingarden.cafe/contact/'>Contact Me##/a> page to tell me about it.  I fix errors and misjudgments on my own if I find them, but if you find one and don't care enough to let me know, then it's your problem; go ahead and stay offended, if you must.  If I'm wrong, I'm wrong, and I don't care if you see me make mistakes; honesty is how you ensure trust between author and audience, and principled flexibility is how you assure your audience that you are both listening to them, and adhering to a moral code.  What the hell else could you want from me?##/p>

	##p>##strong>Authorship: ##/strong>I have proof of authorship going back to the 1970s, including timestamped, encrypted, unalterable copies of everything, stored in multiple locations.  Don't bother trying to claim you wrote this stuff, or thought of it first, because you didn't and it's easy to prove.  If I have, however, infringed on your own copyrights, we can talk about that, and fix it.##/p>

	##p>##strong>Libel and slander: ##/strong>Do it!  Please tell people lots of nasty lies about me. Say the nastiest, most unbelievable crap you can think of, and do your best to stick it on me.  Tell them anything: terrorist, drug dealer, axe murderer, pedophile...whatever. Go nuts. Leave a billion traces of your various opinions about me in every location in the web and print universe; that's how you can help indemnify me against all charges of any kind, and make people less stupid than you want to give me money. Hell, I'll even write the material for you, if you vehemently-enough don't ask nicely. Don't thank me; I'll be thanking you, when nothing you say about me matters anymore, because there's no reliable evidence of anything, anywhere.  Woohoo, hypocrisy!##/p>

	##p>##strong>Credits: ##/strong>I do the writing, but only because Andrea, wife-extraordinaire, does everything else. I couldn't plan my way out of a paper bag if I had a flashlight and a map, and I don't actually sense time passing, so quotidian reality is not really my home turf. Thank heaven for people who live there; they give me a place to stay when I visit.  Andrea is an equal partner in my writing, and any credit due me is credit due her. My family and friends contribute to my writing, both in terms of the material needs of life, and in the thoughts and influences that appear in my material. I also cannot give enough credit to the good people all around me, both in my home and in the greater world, for making this writing important, and for letting me write it.  This is what I do, this is what makes me run smoothly, this is what I love; giving me a reason to write for you is the greatest gift you can give me. Thank you.##/p>";