<?php

namespace raingarden\rg_content\rg_poems\rg_t_to_other;

$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>the what##/h2>##/li>
		##li class='poem line'>what does that mean?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>no, the question is what does what mean?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>why?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>because that means certainty. what means what?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>ok, what does what mean?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i told you what##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>you told me what?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the meaning of what.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>precisely.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what does that mean?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what does what mean?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that's what i'm asking.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so you are asking what?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i'm asking the meaning of what the meaning of what is##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what does the meaning of what mean?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>meaning is what what means.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so asking what is the meaning##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>yes, the what of meaning is the meaning of what##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>meaning?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>yes.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>wait.  i need to know what meaning means##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>meaning is the what##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so the meaning of meaning is meaning##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>yes.  meaning is what.  the what is meaning.  the meaning of what is what is meaning.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>ok.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and now i gotta go.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>wait.  i need to know why what.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>you mean, why not whom?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>yes, why what?  and why not why?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>because the meaning of what implies why##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>how?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>if you have the meaning of what, you have a why already.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so my what is also a why, and my whom is a what?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>your whom is what, and what is the answer to your why##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>because what is not certain?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what is always a what, not a that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so the meaning of my what is not that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the meaning of your what is your whom, not that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so that is not the meaning of what##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what? is the meaning of what, who? is the meaning of who?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and why is the meaning of why?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>yes and no.  and now i gotta go##/li>
	##/ul>
##/article>";