<?php

namespace raingarden\rg_content\rg_poems\rg_n_to_s;

$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Past life regressions##/h2>##/li>
		##li class='poem line'>it is a cave##/li>
		##li class='poem line'>narrowing as it goes deeper into the mountain,##/li>
		##li class='poem line'>high enough and wide enough to hold a small temple.##/li>
		##li class='poem line'>Smoky fires burn at the entrance, wafting##/li>
		##li class='poem line'>a smell of burning flesh, entrancing and demanding.##/li>
		##li class='poem line'>Bears once lived here, but have given up##/li>
		##li class='poem line'>trying to reclaim their territory; they don't need##/li>
		##li class='poem line'>space for so many.  Sounds of love##/li>
		##li class='poem line'>emerge from the darkened throat of the passage;##/li>
		##li class='poem line'>young men and women have gone back there to please##/li>
		##li class='poem line'>the elders who have lost their mates.  Later,##/li>
		##li class='poem line'>they will return to their own mates or lovers,##/li>
		##li class='poem line'>the children now asleep,##/li>
		##li class='poem line'>and pair off around the fire, spreading their##/li>
		##li class='poem line'>leather sheets over the bundled grass,##/li>
		##li class='poem line'>and more of the music of fucking##/li>
		##li class='poem line'>will grace the air.  It is like a contagion:##/li>
		##li class='poem line'>love spreads from couple to couple, the sounds##/li>
		##li class='poem line'>of the others urging them onward.  Techniques##/li>
		##li class='poem line'>will be compared, ideas will be exchanged##/li>
		##li class='poem line'>and partners will occasionally be shared.##/li>
		##li class='poem line'>The boys, urged on by smell, sight and hearing##/li>
		##li class='poem line'>will masturbate together in the darkness,##/li>
		##li class='poem line'>touching each other nervously, each anticipating the day##/li>
		##li class='poem line'>when a girl will allow him his desire.##/li>
		##li class='poem line'>One man, especially repulsive, scarred##/li>
		##li class='poem line'>in a tribal war, will be left##/li>
		##li class='poem line'>alone by the fire, hoping for a mercy##/li>
		##li class='poem line'>from one of the already-sated, he doesn't care which.##/li>
		##li class='poem line'>The eldest women emerge to gather##/li>
		##li class='poem line'>around their own fire, chatting and planning -##/li>
		##li class='poem line'>even the chief, hidden in the dark with his##/li>
		##li class='poem line'>sinuous child-woman, will bow to the wisdom##/li>
		##li class='poem line'>they have cooked up together.##/li>
		##li class='poem line'>They have had their fill of sex for now,##/li>
		##li class='poem line'>their men already snoring gracelessly,##/li>
		##li class='poem line'>while the full moon soars silver##/li>
		##li class='poem line'>over the untraveled horizon.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is a hut##/li>
		##li class='poem line'>circular with a cone-shaped roof.##/li>
		##li class='poem line'>A woman and a man live there with a child,##/li>
		##li class='poem line'>a boy of few years, and a teenage girl##/li>
		##li class='poem line'>ripening in the heat of late summer.##/li>
		##li class='poem line'>Tonight she will leave her parents to go##/li>
		##li class='poem line'>to the hut of a boy of similar age##/li>
		##li class='poem line'>who has brought her a gift, a token##/li>
		##li class='poem line'>of his longing, and they will sit together##/li>
		##li class='poem line'>under the watchful eye of his grandmother##/li>
		##li class='poem line'>and whisper furtively of their desire.##/li>
		##li class='poem line'>Even as the evening is gradually filled##/li>
		##li class='poem line'>with the ghosts and culture of sex,##/li>
		##li class='poem line'>they will feel the blood rushing hot##/li>
		##li class='poem line'>to their hidden places, and know that##/li>
		##li class='poem line'>later that night they will have to take care, ##/li>
		##li class='poem line'>each alone and filled with visions,##/li>
		##li class='poem line'>of the needs they cannot quite speak,##/li>
		##li class='poem line'>whose forms have been learned##/li>
		##li class='poem line'>in the shape of those random lessons in love##/li>
		##li class='poem line'>provided by a settlement without doors.##/li>
		##li class='poem line'>When she returns to her hut##/li>
		##li class='poem line'>she will hear her probable father##/li>
		##li class='poem line'>labouring massively over the body##/li>
		##li class='poem line'>of her mother, and she will do her best##/li>
		##li class='poem line'>not to disturb them as she finds her##/li>
		##li class='poem line'>palette in the dark.  She will lay there##/li>
		##li class='poem line'>in the black, listening and wishing##/li>
		##li class='poem line'>she did not have to listen.##/li>
		##li class='poem line'>When they are finished, and their breathing##/li>
		##li class='poem line'>has subsided into the gentle breeze##/li>
		##li class='poem line'>of a tropical night, she will reach down##/li>
		##li class='poem line'>her skirt and finger herself gently,##/li>
		##li class='poem line'>until sleep takes her, and she finds##/li>
		##li class='poem line'>one form of relief after another.  She does##/li>
		##li class='poem line'>not know that her young brother remains awake,##/li>
		##li class='poem line'>already familiar with such sounds and motions,##/li>
		##li class='poem line'>and full of contempt for them. Once he laughed aloud,##/li>
		##li class='poem line'>and his probable father cuffed him into silence.##/li>
		##li class='poem line'>Soon it will be harvest time, and there will be##/li>
		##li class='poem line'>many initiates, and three seasons after, much##/li>
		##li class='poem line'>gurgling of babies, and perhaps a few deaths.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is a house##/li>
		##li class='poem line'>in a town with high walls:##/li>
		##li class='poem line'>not an impressive house, not a manor##/li>
		##li class='poem line'>or the home of a big man,##/li>
		##li class='poem line'>but full of wives and children.##/li>
		##li class='poem line'>The man has his own room, the doorway##/li>
		##li class='poem line'>covered with a curtain of rude linen.##/li>
		##li class='poem line'>The wives have another room, where the youngest##/li>
		##li class='poem line'>of the children sleep with them,##/li>
		##li class='poem line'>while the older ones sleep on common beds,##/li>
		##li class='poem line'>divided by sex, in the main room.##/li>
		##li class='poem line'>The husband practices safe sex;##/li>
		##li class='poem line'>that is, he doesn't have sex with##/li>
		##li class='poem line'>the wife or daughter of any man##/li>
		##li class='poem line'>who could beat him in a fight.##/li>
		##li class='poem line'>Each night, if he has the energy,##/li>
		##li class='poem line'>he takes one of his wives to bed with him,##/li>
		##li class='poem line'>while the other two sleep in the next room.##/li>
		##li class='poem line'>He vaguely understands that they make love##/li>
		##li class='poem line'>to each other when they are not privileged##/li>
		##li class='poem line'>to sleep with him, but what he doesn't know##/li>
		##li class='poem line'>is that they prefer it.  The children feel##/li>
		##li class='poem line'>surrounded, oppressed by sex, especially##/li>
		##li class='poem line'>the eldest son, who is embarrassed by his##/li>
		##li class='poem line'>masturbation, feeling it a sign of weakness##/li>
		##li class='poem line'>and unmanliness.  He does his work alone,##/li>
		##li class='poem line'>while tending the sheep, far from the prying##/li>
		##li class='poem line'>eyes of his three sisters, but is unaware##/li>
		##li class='poem line'>that they know exactly what he has been doing,##/li>
		##li class='poem line'>and that he gets mighty erections##/li>
		##li class='poem line'>many times each night, tenting the fabric##/li>
		##li class='poem line'>of his blanket most humorously.  One night, drunk##/li>
		##li class='poem line'>on the rough beer of the priests, he tried##/li>
		##li class='poem line'>to crawl into bed with them, and they scratched##/li>
		##li class='poem line'>him viciously.  He awoke bloody, unable##/li>
		##li class='poem line'>to remember where he got the welts. He##/li>
		##li class='poem line'>has heard rumours that his best friend's##/li>
		##li class='poem line'>mother will fuck any man who can##/li>
		##li class='poem line'>evade her husband's stern gaze, but as yet,##/li>
		##li class='poem line'>he has not spoken with any honest man who can claim##/li>
		##li class='poem line'>to have done so, and he therefore keeps his distance.##/li>
		##li class='poem line'>On occasion, he has sex with his friend,##/li>
		##li class='poem line'>an ill-kept secret in a tightly knit community,##/li>
		##li class='poem line'>not realizing the contempt the women##/li>
		##li class='poem line'>hold him in as a result, and how it hurts his chances##/li>
		##li class='poem line'>of his father finding him a wife.  When the rains##/li>
		##li class='poem line'>come, the sheep will be penned, and his##/li>
		##li class='poem line'>desperation will beat down on him like##/li>
		##li class='poem line'>droplets of icy revenge.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>It is a palace##/li>
		##li class='poem line'>surrounded by slum, and she is a slave.##/li>
		##li class='poem line'>The tiny sum she receives each month##/li>
		##li class='poem line'>does not change her status: she is at their##/li>
		##li class='poem line'>beck and call twenty-four hours a day.##/li>
		##li class='poem line'>The master of the house uses her occasionally,##/li>
		##li class='poem line'>for his own pleasure or that of his guests, and##/li>
		##li class='poem line'>consequently she is hated by her mistress,##/li>
		##li class='poem line'>who has no say in the matter.  She has##/li>
		##li class='poem line'>learned to hate fucking, and learned to hate men,##/li>
		##li class='poem line'>seeing them all as measures of depravity,##/li>
		##li class='poem line'>their status being in direct relation##/li>
		##li class='poem line'>to the strangeness of the demands that they##/li>
		##li class='poem line'>make of her.  There is no part of her body##/li>
		##li class='poem line'>that has not been abused, but she is too##/li>
		##li class='poem line'>strong to internalize her hatred, and too##/li>
		##li class='poem line'>smart to externalize it.  Instead, it rides##/li>
		##li class='poem line'>her like a second skin.  Many of the##/li>
		##li class='poem line'>palace women, and some of the younger men,##/li>
		##li class='poem line'>feel the same, for youth is a commodity here.##/li>
		##li class='poem line'>She does not know, however, that she is##/li>
		##li class='poem line'>loved from afar, by the master of horse,##/li>
		##li class='poem line'>a decent and strong man, too ugly##/li>
		##li class='poem line'>to be taken into the private chambers##/li>
		##li class='poem line'>of either nobleman or noblewoman,##/li>
		##li class='poem line'>and that if she would have him, her lot##/li>
		##li class='poem line'>would improve immeasurably.  He sees##/li>
		##li class='poem line'>images of her when he is lying awake##/li>
		##li class='poem line'>on his straw bed, and must seek a##/li>
		##li class='poem line'>weak satisfaction at his own hands.##/li>
		##li class='poem line'>What is unusual is that he does not##/li>
		##li class='poem line'>see her naked, but robed like a rich lady,##/li>
		##li class='poem line'>almost virginal in her vestments.  To##/li>
		##li class='poem line'>him, the sexuality of the palace is a river##/li>
		##li class='poem line'>that flows around him, an island##/li>
		##li class='poem line'>of humanity in a stream of degeneracy,##/li>
		##li class='poem line'>and he is right.  The priests, tonight##/li>
		##li class='poem line'>and again tomorrow, will sacrifice##/li>
		##li class='poem line'>a bull and many chickens and sheep,##/li>
		##li class='poem line'>to satiate a god who rapes as he pleases.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is a complex##/li>
		##li class='poem line'>A city unto itself.##/li>
		##li class='poem line'>I am a tiny cog in a great machine;##/li>
		##li class='poem line'>one neither efficient nor designed##/li>
		##li class='poem line'>but accreted by time.  Much##/li>
		##li class='poem line'>lip service is paid to justice##/li>
		##li class='poem line'>and peace, but we hide behind##/li>
		##li class='poem line'>the pillars of fate, duck under##/li>
		##li class='poem line'>the symbols of destiny, flee##/li>
		##li class='poem line'>the fact of eternity. I am guilty##/li>
		##li class='poem line'>of many crimes against love, but##/li>
		##li class='poem line'>not guilty of many more.  Accusations##/li>
		##li class='poem line'>fly like birds trapped in a building.  You,##/li>
		##li class='poem line'>my love, have the only breasts##/li>
		##li class='poem line'>in the world worth knowing,##/li>
		##li class='poem line'>and as much as others grace my vision,##/li>
		##li class='poem line'>they will never grace my hands.##/li>
		##li class='poem line'>All around me, strange glances,##/li>
		##li class='poem line'>innuendos and bad jokes substitute##/li>
		##li class='poem line'>for the gifts men once gave to women,##/li>
		##li class='poem line'>and the delights those women##/li>
		##li class='poem line'>bestowed on their suitors - the Dionysian##/li>
		##li class='poem line'>is long forgotten and the wine##/li>
		##li class='poem line'>has been priced out of my hands, but##/li>
		##li class='poem line'>the priapic dance goes on in my##/li>
		##li class='poem line'>head in spite of all.  I mourn nothing:##/li>
		##li class='poem line'>in this time, I am given##/li>
		##li class='poem line'>what has always been missing:##/li>
		##li class='poem line'>the chance to know you, really##/li>
		##li class='poem line'>know you, to examine you##/li>
		##li class='poem line'>on a cellular level, to breathe in##/li>
		##li class='poem line'>every string of thought that##/li>
		##li class='poem line'>circulates around the##/li>
		##li class='poem line'>circumference of you.##/li>
		##li class='poem line'>This life is always ending,##/li>
		##li class='poem line'>and yesterday is never seen##/li>
		##li class='poem line'>except through a filter of pain##/li>
		##li class='poem line'>and the steely glint of sorrow.##/li>
		##li class='poem line'>The clich&eacute; would have it##/li>
		##li class='poem line'>that a new life begins with each##/li>
		##li class='poem line'>ending - it is not so: the end##/li>
		##li class='poem line'>is now, and now, and now.  You and I,##/li>
		##li class='poem line'>we travel forward through the thickest##/li>
		##li class='poem line'>of air, fighting gravity, to find each##/li>
		##li class='poem line'>other a thousand times; magnets, polar##/li>
		##li class='poem line'>opposites, we fuck our way through time,##/li>
		##li class='poem line'>and when we cannot come together##/li>
		##li class='poem line'>we come for each other.  I have##/li>
		##li class='poem line'>gathered much intelligence##/li>
		##li class='poem line'>on my windings, and time is##/li>
		##li class='poem line'>like a bed of sand.  If you lie long##/li>
		##li class='poem line'>enough, the imprint of your body##/li>
		##li class='poem line'>remains when you stand up; likewise,##/li>
		##li class='poem line'>when we drop our shells, our##/li>
		##li class='poem line'>impressions are left behind,##/li>
		##li class='poem line'>moulds for the new world,##/li>
		##li class='poem line'>and the clay is given form##/li>
		##li class='poem line'>and outline by the remains.  If##/li>
		##li class='poem line'>I cannot have you in one life,##/li>
		##li class='poem line'>rest assured, I will penetrate##/li>
		##li class='poem line'>the lie of the future to bring##/li>
		##li class='poem line'>you to your knees.  All##/li>
		##li class='poem line'>the past, all the past, was##/li>
		##li class='poem line'>two rodents grubbing in the dark,##/li>
		##li class='poem line'>finding each other in spite of##/li>
		##li class='poem line'>the odds stacked against us,##/li>
		##li class='poem line'>and the millions to whom we##/li>
		##li class='poem line'>have given rise compensate me##/li>
		##li class='poem line'>for the sterility of now.  I have no ##/li>
		##li class='poem line'>sperm to give you, and we##/li>
		##li class='poem line'>are both past the time of such things,##/li>
		##li class='poem line'>but I promise you that until##/li>
		##li class='poem line'>the universe dies the final death##/li>
		##li class='poem line'>my cock is yours.  Love me.##/li>
	##/ul>
##/article>";