<?php

namespace raingarden\rg_content\rg_poems\rg_n_to_s;

$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Reboot##/h2>##/li>
		##li class='poem line'>a creation story##/li>
		
		##li class='poem line'>B##/li>
		##li class='poem line'>efore there was the word##/li>
		##li class='poem line'>there was##/li>
		##li class='poem line'>the voice##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the voice was mine##/li>
		##li class='poem line'>and me##/li>
		##li class='poem line'>as i was yours##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and the voice said##/li>
		##li class='poem line'>be now##/li>
		##li class='poem line'>and i began##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to speak being##/li>
		##li class='poem line'>to impose##/li>
		##li class='poem line'>my existence##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>on the endless ##/li>
		##li class='poem line'>spilling forth##/li>
		##li class='poem line'>becoming##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that which was not##/li>
		##li class='poem line'>was made less so##/li>
		##li class='poem line'>and was##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all wrong##/li>
		##li class='poem line'>and was undone##/li>
		##li class='poem line'>and as before##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there was the voice##/li>
		##li class='poem line'>muffled##/li>
		##li class='poem line'>by the silence##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and the voice said##/li>
		##li class='poem line'>be now##/li>
		##li class='poem line'>and I began##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>anew, and this time let##/li>
		##li class='poem line'>the verse##/li>
		##li class='poem line'>unfold. ##/li>
		##li class='poem line'>
##/li>
		##li class='poem line'>B##/li>
		##li class='poem line'>efore there was##/li>
		##li class='poem line'>the verse##/li>
		##li class='poem line'>there was the voice##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the voice##/li>
		##li class='poem line'>spoke only truth##/li>
		##li class='poem line'>and nothing else##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>could be##/li>
		##li class='poem line'>for all that was spoken##/li>
		##li class='poem line'>became##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the stuff of light##/li>
		##li class='poem line'>in darkness##/li>
		##li class='poem line'>and shone through##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the void##/li>
		##li class='poem line'>and it was very cool##/li>
		##li class='poem line'>I said##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>let small things##/li>
		##li class='poem line'>create big things##/li>
		##li class='poem line'>and they did##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>as the verse##/li>
		##li class='poem line'>demanded of them##/li>
		##li class='poem line'>so that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>verse##/li>
		##li class='poem line'>became song##/li>
		##li class='poem line'>and the myriad creatures##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>emerged, among them##/li>
		##li class='poem line'>those with sense##/li>
		##li class='poem line'>to know##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>beauty in truth##/li>
		##li class='poem line'>and they looked##/li>
		##li class='poem line'>and listened##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and saw nothing##/li>
		##li class='poem line'>and heard nothing##/li>
		##li class='poem line'>no truth##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and no beauty##/li>
		##li class='poem line'>so the voice said##/li>
		##li class='poem line'>stop now##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and it all being##/li>
		##li class='poem line'>wrong##/li>
		##li class='poem line'>it was undone##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>before##/li>
		##li class='poem line'>there could yet ##/li>
		##li class='poem line'>be another word##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there was the voice##/li>
		##li class='poem line'>muffled##/li>
		##li class='poem line'>by the silence.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>T##/li>
		##li class='poem line'>he voice was mine##/li>
		##li class='poem line'>and me##/li>
		##li class='poem line'>as i was yours##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and will be##/li>
		##li class='poem line'>- could be again -##/li>
		##li class='poem line'>verse willing.##/li>
	##/ul>
##/article>";