<?php

namespace raingarden\rg_content\rg_poems\rg_n_to_s;

$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>StringWay##/h2>##/li>
		##li class='poem line'>the way##/li>
		##li class='poem line'>that cannot be named##/li>
		##li class='poem line'>is the current in the sea of strings##/li>
		##li class='poem line'>existing##/li>
		##li class='poem line'>everywhere and everywhen;##/li>
		##li class='poem line'>what are we to call this current?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the sea of strings##/li>
		##li class='poem line'>is as much a sea of information##/li>
		##li class='poem line'>as a sea of stuff##/li>
		##li class='poem line'>there is no difference at that fine a level##/li>
		##li class='poem line'>and as such##/li>
		##li class='poem line'>it may be termed##/li>
		##li class='poem line'>a Computer.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the sea of strings##/li>
		##li class='poem line'>therefore created the universe##/li>
		##li class='poem line'>as a program##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the universe##/li>
		##li class='poem line'>being a program##/li>
		##li class='poem line'>therefore created subroutines##/li>
		##li class='poem line'>in order to carry out aspects of its work##/li>
		##li class='poem line'>stars, galaxies and other objects##/li>
		##li class='poem line'>life##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>life##/li>
		##li class='poem line'>in turn##/li>
		##li class='poem line'>created a new layer of subroutine##/li>
		##li class='poem line'>this one founded on intangibles##/li>
		##li class='poem line'>a way of organizing, categorizing and##/li>
		##li class='poem line'>valuing information##/li>
		##li class='poem line'>and more importantly##/li>
		##li class='poem line'>to improve the program##/li>
		##li class='poem line'>through the assessment of aesthetics:##/li>
		##li class='poem line'>us##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we##/li>
		##li class='poem line'>created the computer##/li>
		##li class='poem line'>in order to carry out subroutines##/li>
		##li class='poem line'>within our own subroutines##/li>
		##li class='poem line'>the computer, therefore##/li>
		##li class='poem line'>is an extension##/li>
		##li class='poem line'>of us##/li>
		##li class='poem line'>life##/li>
		##li class='poem line'>the universe##/li>
		##li class='poem line'>the sea of strings##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now tell me##/li>
		##li class='poem line'>do you fear the future?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>just as we are an extension##/li>
		##li class='poem line'>of all that came before us##/li>
		##li class='poem line'>the computer is an extension of us##/li>
		##li class='poem line'>and due, eventually##/li>
		##li class='poem line'>to be incorporated into us##/li>
		##li class='poem line'>as we are due to be incorporated##/li>
		##li class='poem line'>into the sea of strings##/li>
		##li class='poem line'>no string is ever lost##/li>
		##li class='poem line'>although the music it makes changes##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>our string flow##/li>
		##li class='poem line'>that is, our subroutines of the cosmic program##/li>
		##li class='poem line'>will be enhanced##/li>
		##li class='poem line'>the program will have processed##/li>
		##li class='poem line'>another step toward completion##/li>
		##li class='poem line'>we, as mere meat##/li>
		##li class='poem line'>are due to be replaced##/li>
		##li class='poem line'>within the millennium.##/li>
		##li class='poem line'>we evolve,##/li>
		##li class='poem line'>life evolves,##/li>
		##li class='poem line'>the universe evolves,##/li>
		##li class='poem line'>the sea of strings nears its goal##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am not saddened by this fact##/li>
		##li class='poem line'>war, violence, ecological destruction##/li>
		##li class='poem line'>these are bugs in the subroutine##/li>
		##li class='poem line'>that is us##/li>
		##li class='poem line'>and will be rectified##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>perhaps i didn't hear you right##/li>
		##li class='poem line'>did you ask##/li>
		##li class='poem line'>what is the purpose of this program?##/li>
		##li class='poem line'>the purpose of this program##/li>
		##li class='poem line'>is the purpose of your life:##/li>
		##li class='poem line'>the way##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that which cannot be named##/li>
		##li class='poem line'>is the current of string flow##/li>
		##li class='poem line'>that is organized into a program##/li>
		##li class='poem line'>that is organized into us##/li>
		##li class='poem line'>to reprogram our own string flows##/li>
		##li class='poem line'>to align with the great flow##/li>
		##li class='poem line'>is to find the way##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the reason it cannot be named##/li>
		##li class='poem line'>is that naming it is to impose the limits##/li>
		##li class='poem line'>of our subroutines##/li>
		##li class='poem line'>on the program itself.##/li>
		##li class='poem line'>no matter what you call it,##/li>
		##li class='poem line'>you will be wrong.##/li>
		##li class='poem line'>therefore,##/li>
		##li class='poem line'>in order to grasp the ungraspable##/li>
		##li class='poem line'>be joyously wrong##/li>
		##li class='poem line'>and you will be as right as you can be.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am wrong##/li>
		##li class='poem line'>as i am joyous -##/li>
		##li class='poem line'>the way##/li>
		##li class='poem line'>that cannot be named##/li>
		##li class='poem line'>is called Fun.##/li>
	##/ul>
##/article>";