<?php

namespace raingarden\rg_content\rg_poems\rg_n_to_s;

$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Strings of consciousness##/h2>##/li>
		##li class='poem line'>it is the wish of my life##/li>
		##li class='poem line'>to know everything##/li>
		##li class='poem line'>failing that, to know myself##/li>
		##li class='poem line'>and you, my proud loves##/li>
		##li class='poem line'>for in us##/li>
		##li class='poem line'>is beauty, and truth##/li>
		##li class='poem line'>to know perfect beauty##/li>
		##li class='poem line'>is to know perfect truth##/li>
		##li class='poem line'>this is the highest aspiration of humanity##/li>
		##li class='poem line'>to know the great aspects of Fun##/li>
		##li class='poem line'>at the most fundamental level##/li>
		##li class='poem line'>we are at present##/li>
		##li class='poem line'>as perfect as the universe allows##/li>
		##li class='poem line'>and this is not good enough##/li>
		##li class='poem line'>amounts only to a C+##/li>
		##li class='poem line'>on the report card of the species##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to know more, there are two techniques##/li>
		##li class='poem line'>reduction: the splitting of problems##/li>
		##li class='poem line'>into understandable sub-problems##/li>
		##li class='poem line'>this only works to a point:##/li>
		##li class='poem line'>in our world, we are greater than the sum of our problems##/li>
		##li class='poem line'>we are self-aware, conscious, recursive##/li>
		##li class='poem line'>our consciousness is the greatest mystery##/li>
		##li class='poem line'>and not to be trifled with##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the other technique is a relation##/li>
		##li class='poem line'>emergence: the examining of the part##/li>
		##li class='poem line'>to understand the whole##/li>
		##li class='poem line'>again, consciousness trumps all##/li>
		##li class='poem line'>to understand the macrocosmos##/li>
		##li class='poem line'>we must understand the microcosmos##/li>
		##li class='poem line'>we will have to voyage through the world##/li>
		##li class='poem line'>of the arts to understand the science##/li>
		##li class='poem line'>at the levels of which we speak##/li>
		##li class='poem line'>there is no alternative##/li>
		##li class='poem line'>only art can illuminate##/li>
		##li class='poem line'>that which is smaller than the smallest particle of light##/li>
		##li class='poem line'>and that which is larger than the observable universe##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we, that is, you and i##/li>
		##li class='poem line'>will attempt a new investigative technique##/li>
		##li class='poem line'>recombination##/li>
		##li class='poem line'>we will examine the very small##/li>
		##li class='poem line'>on the level of the very big##/li>
		##li class='poem line'>in fact, we will examine the smallest##/li>
		##li class='poem line'>on the level of the biggest:##/li>
		##li class='poem line'>the matter of mind and humanity##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>perhaps a quick aside:##/li>
		##li class='poem line'>this poem could have been an essay##/li>
		##li class='poem line'>in fact, it will be##/li>
		##li class='poem line'>however, i am a poet##/li>
		##li class='poem line'>and think best in poetry##/li>
		##li class='poem line'>since part of this poem##/li>
		##li class='poem line'>is to demonstrate the validity##/li>
		##li class='poem line'>of the crossroads of art, logic, spirit and science##/li>
		##li class='poem line'>then the science is best written in art##/li>
		##li class='poem line'>and the spiritual is best written in logic##/li>
		##li class='poem line'>therefore, i cut my lines judiciously##/li>
		##li class='poem line'>use punctuation only where important##/li>
		##li class='poem line'>allow the natural flow of words##/li>
		##li class='poem line'>let the ideas roll over you##/li>
		##li class='poem line'>like waves of knowledge##/li>
		##li class='poem line'>besides, if all this is wrong##/li>
		##li class='poem line'>it will still be right##/li>
		##li class='poem line'>that is the nature of art##/li>
		##li class='poem line'>and i don't care if it's cheating##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that said, i truly believe##/li>
		##li class='poem line'>what you read here##/li>
		##li class='poem line'>this is not frivolous speculation##/li>
		##li class='poem line'>this is my best guess##/li>
		##li class='poem line'>it is as close to literal truth##/li>
		##li class='poem line'>as poetic truth can be##/li>
		
		##li class='poem line'>The First Paradigm##/li>
		##li class='poem line'>let us begin##/li>
		##li class='poem line'>we come from an idea##/li>
		##li class='poem line'>an idea that something should be##/li>
		##li class='poem line'>an idea in the mind of the infinite##/li>
		##li class='poem line'>and that idea is best summed up##/li>
		##li class='poem line'>as 'Fun'##/li>
		##li class='poem line'>but we will deal with that later##/li>
		##li class='poem line'>first we will speak of 'stuff'##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we live in a house##/li>
		##li class='poem line'>a house whose roof is infinitely high##/li>
		##li class='poem line'>a house whose last sub-basement is infinitely low##/li>
		##li class='poem line'>in fact, we live on the ground floor##/li>
		##li class='poem line'>in an apartment of infinite square footage##/li>
		##li class='poem line'>we keep stars on the highest of our shelves##/li>
		##li class='poem line'>and the dirt of earth underfoot##/li>
		##li class='poem line'>we cannot see the most distant furniture##/li>
		##li class='poem line'>except with the fruits of our technology##/li>
		##li class='poem line'>they are billions of light-years away##/li>
		##li class='poem line'>and we can only see what they were like##/li>
		##li class='poem line'>when the universe was still an idea##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we can see the floor above us##/li>
		##li class='poem line'>with our devices and calculations##/li>
		##li class='poem line'>we can see the basement below us##/li>
		##li class='poem line'>with our devices and calculations##/li>
		##li class='poem line'>but what lies below that##/li>
		##li class='poem line'>is only found in art##/li>
		##li class='poem line'>there, science and art meet##/li>
		##li class='poem line'>and it is only with the speculation of imagination##/li>
		##li class='poem line'>that we can surmise the contents of the worlds##/li>
		##li class='poem line'>that lie below##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>above us##/li>
		##li class='poem line'>we see through the glass ceiling of the speed of light##/li>
		##li class='poem line'>beyond that, two floors up##/li>
		##li class='poem line'>we can make out the misty soup##/li>
		##li class='poem line'>of a multiverse, the thing of things##/li>
		##li class='poem line'>we can never know this thing##/li>
		##li class='poem line'>it lies beyond measurement##/li>
		##li class='poem line'>in the world of art##/li>
		##li class='poem line'>and you can only see it when you close your eyes##/li>
		##li class='poem line'>for whatever you see behind your tightened lids##/li>
		##li class='poem line'>is as right as can be##/li>
		##li class='poem line'>in an infinite multiverse##/li>
		##li class='poem line'>whatever you imagine is somewhere made real##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>below us, our tools and maths##/li>
		##li class='poem line'>tells us of what stuff we can possibly be made##/li>
		##li class='poem line'>we are intimately acquainted with its effects##/li>
		##li class='poem line'>if not its sight##/li>
		##li class='poem line'>and we have no reason to question what makes great sense##/li>
		##li class='poem line'>but what lies below##/li>
		##li class='poem line'>on the finest markings of the scale of reality##/li>
		##li class='poem line'>is only information##/li>
		##li class='poem line'>and information##/li>
		##li class='poem line'>is not to be touched##/li>
		##li class='poem line'>except with the mind##/li>
		##li class='poem line'>and the mind##/li>
		##li class='poem line'>is the source of art##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>let us now be specific##/li>
		##li class='poem line'>in the next sub-basement of reality##/li>
		##li class='poem line'>there are things as small as small can be##/li>
		##li class='poem line'>and still be knowable##/li>
		##li class='poem line'>it is not that there is no smaller possible size##/li>
		##li class='poem line'>it is that there is no way to measure it##/li>
		##li class='poem line'>the human concept of smallness at that level##/li>
		##li class='poem line'>has nowhere left to go but up##/li>
		##li class='poem line'>those things are the unutterable foundation of us##/li>
		##li class='poem line'>if you cut one, like a worm##/li>
		##li class='poem line'>you end up with two of the same thing##/li>
		##li class='poem line'>if you add two together##/li>
		##li class='poem line'>you still end up with one##/li>
		##li class='poem line'>they are not made of stuff##/li>
		##li class='poem line'>they are stuff##/li>
		##li class='poem line'>and they are the stuff of all stuff##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>at that level##/li>
		##li class='poem line'>there is no verb or noun##/li>
		##li class='poem line'>there is a nerb, perhaps, or a voun##/li>
		##li class='poem line'>but to qualify action and being##/li>
		##li class='poem line'>as separate from each other##/li>
		##li class='poem line'>is a mistake, these things##/li>
		##li class='poem line'>only exist##/li>
		##li class='poem line'>and their existence is both movement and stuff##/li>
		##li class='poem line'>they are the notes##/li>
		##li class='poem line'>that make up the chords of us##/li>
		##li class='poem line'>in the music of the spheres##/li>
		##li class='poem line'>in the symphony of the cosmos##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>forgive me##/li>
		##li class='poem line'>it is impossible to speak of such things##/li>
		##li class='poem line'>without recourse to various analogies##/li>
		##li class='poem line'>first they are motes in a basement##/li>
		##li class='poem line'>then they are musical notation and sound##/li>
		##li class='poem line'>now they are a sea##/li>
		##li class='poem line'>an ocean without bottom we can perceive##/li>
		##li class='poem line'>an ocean without surface we can survey##/li>
		##li class='poem line'>an ocean without coast or island##/li>
		##li class='poem line'>but an ocean, nonetheless,##/li>
		##li class='poem line'>of incomparable complexity##/li>
		##li class='poem line'>and on occasion##/li>
		##li class='poem line'>of indescribable beauty##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>what we know as stuff and movement##/li>
		##li class='poem line'>happens on the ground floor of the building##/li>
		##li class='poem line'>which is the middle depth of the ocean##/li>
		##li class='poem line'>we are gross creatures##/li>
		##li class='poem line'>some of the biggest things in the universe##/li>
		##li class='poem line'>bigger than 99.9 percent of all we know##/li>
		##li class='poem line'>and we can only see with our eyes##/li>
		##li class='poem line'>what we suppose occupies the basement##/li>
		##li class='poem line'>and the furniture in the sub-basement below that##/li>
		##li class='poem line'>is speculation only, and indirect at that##/li>
		##li class='poem line'>we have evidence for the small##/li>
		##li class='poem line'>but only supposition for the smaller##/li>
		##li class='poem line'>this is all we can have##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we, on the ground floor,##/li>
		##li class='poem line'>look down and see atoms, particles, forces##/li>
		##li class='poem line'>when atoms, particles and forces look down##/li>
		##li class='poem line'>they see music##/li>
		##li class='poem line'>information in the form of infinitesimal strings##/li>
		##li class='poem line'>that vibrate, coalesce, bounce off membranes##/li>
		##li class='poem line'>i'm not making this up, this is##/li>
		##li class='poem line'>what those who investigate nature##/li>
		##li class='poem line'>tell me, in words and pictures##/li>
		##li class='poem line'>i love this, to know what i am made of##/li>
		##li class='poem line'>at the most fundamental levels##/li>
		##li class='poem line'>i am a complex chord##/li>
		##li class='poem line'>a sound both pleasing and incomplete##/li>
		##li class='poem line'>issuing from the depths##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>let us return to the ocean now##/li>
		##li class='poem line'>look one way, look another, it doesn't matter which way##/li>
		##li class='poem line'>all you see is strings and membranes##/li>
		##li class='poem line'>in all the points of the multi-dimensional compass##/li>
		##li class='poem line'>up/down, north/south, east/west##/li>
		##li class='poem line'>inside, twist, anti-twist and hole -##/li>
		##li class='poem line'>inside, twist, anti-twist and hole contain further up/downs##/li>
		##li class='poem line'>making ten in all, and being small as they are##/li>
		##li class='poem line'>we can see through all of them##/li>
		##li class='poem line'>when we reach a hand through hole##/li>
		##li class='poem line'>it emerges far away, yet we feel no pain of separation##/li>
		##li class='poem line'>and far away moves fluidly##/li>
		##li class='poem line'>this is what it means to swim in this ocean##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>some strings separate from their community of strings##/li>
		##li class='poem line'>they cross empty space as if with intent##/li>
		##li class='poem line'>and twist themselves around other strings##/li>
		##li class='poem line'>perhaps touching, perhaps not##/li>
		##li class='poem line'>the empty space between them is vast##/li>
		##li class='poem line'>(mostly)##/li>
		##li class='poem line'>when they reach each other, they are a chord##/li>
		##li class='poem line'>two notes sounding simultaneously##/li>
		##li class='poem line'>a b-flat and an almost D, for instance##/li>
		##li class='poem line'>many do not find harmony, and move on##/li>
		##li class='poem line'>others seem to take joy in their harmony##/li>
		##li class='poem line'>at that point, they begin to move together##/li>
		##li class='poem line'>and matter, the hard things##/li>
		##li class='poem line'>is formed in all its glory##/li>
		##li class='poem line'>it moves, and is force##/li>
		##li class='poem line'>and we have a cosmos to live in##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the flow of stuff##/li>
		##li class='poem line'>is like currents within the ocean##/li>
		##li class='poem line'>strings move in streams, pool in puddles##/li>
		##li class='poem line'>occasionally a puddle, in its many dimensions##/li>
		##li class='poem line'>seems to form borders, and becomes##/li>
		##li class='poem line'>a thing##/li>
		##li class='poem line'>and while its borders are fluid##/li>
		##li class='poem line'>seems to contain a harmony and grace of its own##/li>
		##li class='poem line'>in our world, this is the coming together of quanta##/li>
		##li class='poem line'>which form atoms, which form us##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that puddle, now a thing##/li>
		##li class='poem line'>shares string with its neighbours, always##/li>
		##li class='poem line'>exchanging information with the sea around it##/li>
		##li class='poem line'>there is therefore no definition of a thing##/li>
		##li class='poem line'>for there are no two moments when it is alike##/li>
		##li class='poem line'>it is a concept, not a ball of certainty##/li>
		##li class='poem line'>there is never certainty in the ocean, only tendency##/li>
		##li class='poem line'>this is its great beauty and mystery##/li>
		##li class='poem line'>the more we stare at it,##/li>
		##li class='poem line'>the less we can claim to know of it##/li>
		##li class='poem line'>when we measure its movement##/li>
		##li class='poem line'>we lose track of its thingness##/li>
		##li class='poem line'>when we ascertain its thingness##/li>
		##li class='poem line'>we lose track of its movement##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>those tiny things,##/li>
		##li class='poem line'>now big enough to exist in our basement##/li>
		##li class='poem line'>only##/li>
		##li class='poem line'>one level down##/li>
		##li class='poem line'>continue to share information##/li>
		##li class='poem line'>with the ocean and with other things##/li>
		##li class='poem line'>thus they are made unique##/li>
		##li class='poem line'>atoms share with atoms, trade electrons##/li>
		##li class='poem line'>absorb, emit##/li>
		##li class='poem line'>and we sit on earth, breathe air, drink water##/li>
		##li class='poem line'>occasionally, when we apply the right force##/li>
		##li class='poem line'>(the breaking apart and joining of strings)##/li>
		##li class='poem line'>we release photons from electrons##/li>
		##li class='poem line'>and we learn to love##/li>
		##li class='poem line'>in the form of fire##/li>
		##li class='poem line'>this is called magic, and must not be refused##/li>
		##li class='poem line'>for in burning is life##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>occasionally, back down in the ocean##/li>
		##li class='poem line'>a puddle, having almost become a thing##/li>
		##li class='poem line'>begins to flow in a logical manner##/li>
		##li class='poem line'>this in itself is not life, but is necessary for life##/li>
		##li class='poem line'>when that logical pattern achieves a certain complexity##/li>
		##li class='poem line'>it begins to spin off other puddles##/li>
		##li class='poem line'>which become beings in our world##/li>
		##li class='poem line'>when we observe this pattern repeated##/li>
		##li class='poem line'>we say, that is alive, we are alive##/li>
		##li class='poem line'>all around us, given the right conditions##/li>
		##li class='poem line'>logic patterns swirl and manufacture more logic##/li>
		##li class='poem line'>feed on strings, slough off strings##/li>
		##li class='poem line'>in our world, when earth, air, water and fire##/li>
		##li class='poem line'>come together in a being##/li>
		##li class='poem line'>controlled by logic and communication##/li>
		##li class='poem line'>we call it life, and see magic in it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it would be easy to limit life##/li>
		##li class='poem line'>to what we can embrace##/li>
		##li class='poem line'>but it would be shallow##/li>
		##li class='poem line'>a planet can be a chord, like we are chords##/li>
		##li class='poem line'>a planet can be a coming together##/li>
		##li class='poem line'>of earth, air, water and fire##/li>
		##li class='poem line'>of logic and communication##/li>
		##li class='poem line'>and therefore deserving of love##/li>
		##li class='poem line'>and we cannot stop there##/li>
		##li class='poem line'>we don't know all that can be known##/li>
		##li class='poem line'>of life in the primary ocean##/li>
		##li class='poem line'>perhaps there are patterns of logic and communication##/li>
		##li class='poem line'>which need no earth, or air, or water##/li>
		##li class='poem line'>who is to say?##/li>
		##li class='poem line'>we must agree on a definition:##/li>
		##li class='poem line'>here it is##/li>
		##li class='poem line'>minimum life is the presence of a functioning logic circuit##/li>
		##li class='poem line'>which communicates with the ocean##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>you may find this definition too broad##/li>
		##li class='poem line'>i will admit that it has fuzzy edges##/li>
		##li class='poem line'>however, any other definition is exclusionary##/li>
		##li class='poem line'>to a point beyond reason##/li>
		##li class='poem line'>a tree is a complex logic circuit that communicates##/li>
		##li class='poem line'>a paramecium is one##/li>
		##li class='poem line'>i am one##/li>
		##li class='poem line'>i breathe strings, eat strings, move strings about##/li>
		##li class='poem line'>in an admittedly gross fashion##/li>
		##li class='poem line'>i communicate with the great ocean around me##/li>
		##li class='poem line'>i am a region of the ocean, a thing, a living being##/li>
		##li class='poem line'>in that order##/li>
		##li class='poem line'>i have no problem with this fact##/li>
		##li class='poem line'>actually, i find myself endlessly fascinating##/li>
		##li class='poem line'>how does a puddle##/li>
		##li class='poem line'>know that it is a puddle?##/li>
		##li class='poem line'>that, above all, is the central question of humanity's....er...questing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to understand our consciousness##/li>
		##li class='poem line'>we must return to our puddley nature##/li>
		##li class='poem line'>first, we must know that consciousness##/li>
		##li class='poem line'>doesn't come with an on/off switch##/li>
		##li class='poem line'>there are as many levels of awareness##/li>
		##li class='poem line'>as there are logic circuits in the ocean##/li>
		##li class='poem line'>most of them are relatively simple##/li>
		##li class='poem line'>by comparison to us##/li>
		##li class='poem line'>they are not conscious, even if aware##/li>
		##li class='poem line'>they have no I##/li>
		##li class='poem line'>they do not even have an i##/li>
		##li class='poem line'>they simply have a ' '##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in the sub-basement of reality, all our things are strings##/li>
		##li class='poem line'>matter is vibrating strings##/li>
		##li class='poem line'>force is strings vibrating##/li>
		##li class='poem line'>thought is no different##/li>
		##li class='poem line'>thought is the movement of##/li>
		##li class='poem line'>combining of##/li>
		##li class='poem line'>decomposing of##/li>
		##li class='poem line'>recombining of##/li>
		##li class='poem line'>strings, exactly the same as matter and force##/li>
		##li class='poem line'>at the fundamental level, thought is a pattern##/li>
		##li class='poem line'>in the flow of strings in and around##/li>
		##li class='poem line'>a region of ocean that contains a functioning logic circuit##/li>
		##li class='poem line'>how, you may ask, is that circuit said to contain consciousness?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>to answer that, you may have make a leap of faith##/li>
		##li class='poem line'>we must assume that a string##/li>
		##li class='poem line'>may know another string##/li>
		##li class='poem line'>may know other strings whose note matches the harmony of the chord##/li>
		##li class='poem line'>to assume this, we must take recourse to Descartes##/li>
		##li class='poem line'>he of the I think therefore I am##/li>
		##li class='poem line'>this phrase has taken a lot of heat##/li>
		##li class='poem line'>from people whose thinking proves that they are##/li>
		##li class='poem line'>however, I will avoid such controversy##/li>
		##li class='poem line'>by assuming only 'I know myself to be'##/li>
		##li class='poem line'>i am a collection of strings##/li>
		##li class='poem line'>and i know myself to be##/li>
		##li class='poem line'>therefore, a collection of strings may know itself to be##/li>
		##li class='poem line'>perhaps you hate this logic##/li>
		##li class='poem line'>i do not have to make a leap of faith to believe it##/li>
		##li class='poem line'>but you may##/li>
		##li class='poem line'>too bad - i wish you could know yourself##/li>
		##li class='poem line'>the way i know myself##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when a region of ocean##/li>
		##li class='poem line'>called a living being in our world##/li>
		##li class='poem line'>twists in on itself, loops back through ocean##/li>
		##li class='poem line'>and touches itself##/li>
		##li class='poem line'>so that part of its collection of strings##/li>
		##li class='poem line'>can see the rest of its collection of strings##/li>
		##li class='poem line'>it assumes consciousness##/li>
		##li class='poem line'>a tree cannot assume consciousness##/li>
		##li class='poem line'>it's logic is not self-referential##/li>
		##li class='poem line'>meaning that it cannot see itself -##/li>
		##li class='poem line'>it has no organs of seeing##/li>
		##li class='poem line'>the question is then, at what point##/li>
		##li class='poem line'>does that twist, that loop##/li>
		##li class='poem line'>become self-awareness?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a fish has no closed loop##/li>
		##li class='poem line'>it has an interesting twist, certainly##/li>
		##li class='poem line'>but it's stringy logic does not curl back##/li>
		##li class='poem line'>to touch itself, to see itself##/li>
		##li class='poem line'>a bird has a better loop##/li>
		##li class='poem line'>it almost touches in many birds##/li>
		##li class='poem line'>in parrots it may just graze itself##/li>
		##li class='poem line'>they are almost smart enough to see an i##/li>
		##li class='poem line'>not quite, pity##/li>
		##li class='poem line'>a chipmunk is more vital than most birds##/li>
		##li class='poem line'>but it has no complete loop##/li>
		##li class='poem line'>and so on along the food chain##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>things get interesting around dogs and monkeys##/li>
		##li class='poem line'>they have complete and beautiful loops##/li>
		##li class='poem line'>elegant and moving##/li>
		##li class='poem line'>always in flux, turning and reshaping themselves##/li>
		##li class='poem line'>they have string logic to create emotion##/li>
		##li class='poem line'>they have loops that just touch##/li>
		##li class='poem line'>not always and not for long, but the merest##/li>
		##li class='poem line'>brush stroke of string flow on string flow##/li>
		##li class='poem line'>their i's are fleeting, but they have them##/li>
		##li class='poem line'>some more than others##/li>
		##li class='poem line'>possibly not Chihuahuas and Pomeranians##/li>
		##li class='poem line'>for which i admit a sad contempt##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>finally, we come to dolphins and apes##/li>
		##li class='poem line'>these are creatures with true loops##/li>
		##li class='poem line'>these are creatures whose string flow##/li>
		##li class='poem line'>loops and twists back on itself##/li>
		##li class='poem line'>they have strong i's##/li>
		##li class='poem line'>but not strong enough to know##/li>
		##li class='poem line'>that they have strong i's##/li>
		##li class='poem line'>they are magnificent and magical for this reason##/li>
		##li class='poem line'>existing in a pure space##/li>
		##li class='poem line'>that humans sometimes imagine##/li>
		##li class='poem line'>would be a good place to live##/li>
		##li class='poem line'>(this is a sad thing - the voluntary limiting of loopiness)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now humans, we have loops##/li>
		##li class='poem line'>twists, turns, complex motion##/li>
		##li class='poem line'>our regions of the ocean seethe and bubble##/li>
		##li class='poem line'>and our logic, complex and fast##/li>
		##li class='poem line'>touches itself in a closed loop##/li>
		##li class='poem line'>actually, not always, and in varying degrees##/li>
		##li class='poem line'>but as a species of string-concatenation##/li>
		##li class='poem line'>we are unique on our world##/li>
		##li class='poem line'>we have the only fully-formed and lasting loops on the planet##/li>
		##li class='poem line'>(notice the on in the above sentence)##/li>
		##li class='poem line'>imagine a region of string-ocean##/li>
		##li class='poem line'>elongated and twisted##/li>
		##li class='poem line'>that loops back to touch itself##/li>
		##li class='poem line'>that some of its strings of awareness##/li>
		##li class='poem line'>may see other of its strings of awareness##/li>
		##li class='poem line'>and you have envisioned the nature of consciousness##/li>
		##li class='poem line'>the birth of the I##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it doesn't stop there##/li>
		##li class='poem line'>while many humans are simply aware of themselves##/li>
		##li class='poem line'>with a true loop structure and a functioning logic circuit##/li>
		##li class='poem line'>there are others##/li>
		##li class='poem line'>who have a more complex structure##/li>
		##li class='poem line'>and there are as many variations on that structure##/li>
		##li class='poem line'>as there are such humans##/li>
		##li class='poem line'>their logic may wrap itself around the base circuit##/li>
		##li class='poem line'>touching it in many places or just a few##/li>
		##li class='poem line'>different parts of itself seeing other parts of itself##/li>
		##li class='poem line'>this is what is meant by enlightenment##/li>
		##li class='poem line'>enlightenment can be recognized through art##/li>
		##li class='poem line'>a beautiful self-referential string structure##/li>
		##li class='poem line'>containing a logic circuit and communicating with the ocean##/li>
		##li class='poem line'>is enlightened##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>like the varying levels of consciousness##/li>
		##li class='poem line'>there are varying levels of enlightenment##/li>
		##li class='poem line'>a twisting structure, in which one part may see three important parts##/li>
		##li class='poem line'>is more enlightened than one which sees only two lesser ones##/li>
		##li class='poem line'>we say 'she/he is enlightened'##/li>
		##li class='poem line'>when discussing a great man or woman##/li>
		##li class='poem line'>because we see a beautiful, elegant structure##/li>
		##li class='poem line'>a complex series of logic circuits##/li>
		##li class='poem line'>communicating smoothly and widely with the surrounding ocean##/li>
		##li class='poem line'>a structure that sees itself in many ways##/li>
		##li class='poem line'>that sees its connections with the world around##/li>
		##li class='poem line'>in as many ways##/li>
		##li class='poem line'>only a few of us are so privileged##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is an upper limit on enlightenment##/li>
		##li class='poem line'>for a human##/li>
		##li class='poem line'>a structure can always grow, or become more self-referential##/li>
		##li class='poem line'>when every string of a region of ocean##/li>
		##li class='poem line'>knows every other string of that region of ocean##/li>
		##li class='poem line'>it has attained perfect self-awareness##/li>
		##li class='poem line'>highest consciousness##/li>
		##li class='poem line'>and maximum enlightenment##/li>
		##li class='poem line'>this is not possible for mathematical reasons##/li>
		##li class='poem line'>but that should stop no one##/li>
		##li class='poem line'>a string region may know other string regions##/li>
		##li class='poem line'>but a string itself is only information about itself##/li>
		##li class='poem line'>and the act of communicating with other strings##/li>
		##li class='poem line'>through the music of chords##/li>
		##li class='poem line'>changes those strings##/li>
		##li class='poem line'>therefore##/li>
		##li class='poem line'>for humans of our era##/li>
		##li class='poem line'>there is a ceiling##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a string may only know its neighbours in the ten-dimensions##/li>
		##li class='poem line'>the string regions in my foot##/li>
		##li class='poem line'>cannot know the string regions in my belly##/li>
		##li class='poem line'>even if they communicate through the central processing string region##/li>
		##li class='poem line'>of my brain##/li>
		##li class='poem line'>i am not capable of perfect self-awareness##/li>
		##li class='poem line'>and my senses are clumsy - i can only surmise, not know##/li>
		##li class='poem line'>but i know this:##/li>
		##li class='poem line'>a loop is beautiful##/li>
		##li class='poem line'>a twisting loop is more so##/li>
		##li class='poem line'>a fountain, cascading and recursive##/li>
		##li class='poem line'>is more beautiful still##/li>
		##li class='poem line'>strings shoot straight up##/li>
		##li class='poem line'>curl over at the top##/li>
		##li class='poem line'>cascade down, every string##/li>
		##li class='poem line'>in its moment of contact with every other##/li>
		##li class='poem line'>sooner or later##/li>
		##li class='poem line'>the whole seeing the whole##/li>
		##li class='poem line'>recycling, reflecting in the pool around it##/li>
		##li class='poem line'>true beauty, and fashioned as much by human art##/li>
		##li class='poem line'>as by the ocean from which it is born##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>Buddha was a fountain##/li>
		##li class='poem line'>Lao Tzu was a fountain##/li>
		##li class='poem line'>I wish to be a fountain##/li>
		##li class='poem line'>I wish every one of my strings##/li>
		##li class='poem line'>to know every one of my strings##/li>
		##li class='poem line'>this, i acknowledge, i will never achieve##/li>
		##li class='poem line'>at least, not while I am tied to my meat##/li>
		##li class='poem line'>yet it is within the logic of my circuitry##/li>
		##li class='poem line'>to wish for the highest##/li>
		##li class='poem line'>to be god##/li>
		##li class='poem line'>sue me if you don't like that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>beauty does not end with the individual##/li>
		##li class='poem line'>and enlightenment does not end with consciousness of self##/li>
		##li class='poem line'>great enlightenment calls for a smooth integration##/li>
		##li class='poem line'>with the greater ocean##/li>
		##li class='poem line'>great enlightenment requires knowledge of place##/li>
		##li class='poem line'>environment##/li>
		##li class='poem line'>and all the functions of strings##/li>
		##li class='poem line'>again, this is not possible##/li>
		##li class='poem line'>but that shouldn't stop us from trying##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>all of this begs the question, then##/li>
		##li class='poem line'>what is death?##/li>
		##li class='poem line'>the answer is that death is the destruction##/li>
		##li class='poem line'>of the logic circuit:##/li>
		##li class='poem line'>when the flow of strings in the circuit is broken##/li>
		##li class='poem line'>the person dies -##/li>
		##li class='poem line'>what is a more interesting question##/li>
		##li class='poem line'>is 'can our regions of ocean##/li>
		##li class='poem line'>maintain their integrity##/li>
		##li class='poem line'>when the body is gone?'##/li>
		##li class='poem line'>many logicians will dismiss this question##/li>
		##li class='poem line'>as the longing of the being to flow forever##/li>
		##li class='poem line'>these people are wrong to do so:##/li>
		##li class='poem line'>we know very little of how the ocean of strings flows##/li>
		##li class='poem line'>and what we know is known through art##/li>
		##li class='poem line'>perhaps the flow of strings can adjust itself##/li>
		##li class='poem line'>and remain self-referential##/li>
		##li class='poem line'>perhaps, the logic of the circuit may be absorbed##/li>
		##li class='poem line'>into a larger pattern##/li>
		##li class='poem line'>or recycled##/li>
		##li class='poem line'>the only truth we know##/li>
		##li class='poem line'>is that we don't know the truth##/li>
		##li class='poem line'>anyone, on either side of the question##/li>
		##li class='poem line'>who claims to know the answer##/li>
		##li class='poem line'>is a liar or mistaken##/li>
		##li class='poem line'>and probably wishes your allegiance or your money ##/li>
		##li class='poem line'>others simply do not see poetic truth as truth at all##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>many of these people have perverted logic circuits##/li>
		##li class='poem line'>that do not communicate freely with the ocean##/li>
		##li class='poem line'>through the medium of thought##/li>
		##li class='poem line'>they are weak and inelegant##/li>
		##li class='poem line'>we are free to dismiss them, and we owe them nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i can imagine##/li>
		##li class='poem line'>string regions of incomparable beauty##/li>
		##li class='poem line'>fractals, abstract sculptures, mountains##/li>
		##li class='poem line'>when these things contain a logic circuit##/li>
		##li class='poem line'>they are the highest ideals of the cosmos##/li>
		##li class='poem line'>we should be proud##/li>
		##li class='poem line'>but not too proud##/li>
		##li class='poem line'>we are not alone, after all##/li>
		##li class='poem line'>there are many regions of the ocean##/li>
		##li class='poem line'>which are populated with sub-regions of the ocean##/li>
		##li class='poem line'>which are larger and more beautiful than us##/li>
		##li class='poem line'>they may have had longer to grow##/li>
		##li class='poem line'>they may have richer physics on which to dine##/li>
		##li class='poem line'>they may have altered their fundamental realities##/li>
		##li class='poem line'>because they can manipulate strings more directly##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we cannot manipulate our strings directly##/li>
		##li class='poem line'>at least, not in the way we wish##/li>
		##li class='poem line'>we cannot lift objects with our minds##/li>
		##li class='poem line'>or transmit thoughts without writing or speaking##/li>
		##li class='poem line'>or wish our ways to financial success##/li>
		##li class='poem line'>we use our brains and limbs##/li>
		##li class='poem line'>we create things which can manipulate finer things##/li>
		##li class='poem line'>we have learned to create things powerful enough##/li>
		##li class='poem line'>to investigate quantum phenomena##/li>
		##li class='poem line'>and we are beginning to learn##/li>
		##li class='poem line'>to manipulate those phenomena##/li>
		##li class='poem line'>but we are maladroit and large##/li>
		##li class='poem line'>we cannot move other regions of ocean##/li>
		##li class='poem line'>with simple desire##/li>
		##li class='poem line'>we are trying to do needlework##/li>
		##li class='poem line'>while wearing oven mitts##/li>
		##li class='poem line'>eventually, we will replace the oven mitts##/li>
		##li class='poem line'>with string manipulators##/li>
		##li class='poem line'>and we will discover then##/li>
		##li class='poem line'>that our thoughts##/li>
		##li class='poem line'>were already there##/li>
		##li class='poem line'>we just didn't know how to use them##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i must repeat this:##/li>
		##li class='poem line'>in an infinite multiverse##/li>
		##li class='poem line'>there is no difference between imagining something##/li>
		##li class='poem line'>and it being out there somewhere##/li>
		##li class='poem line'>if we can create an image in our minds##/li>
		##li class='poem line'>that is, a juxtaposition of strings##/li>
		##li class='poem line'>then the universe can do so as well##/li>
		##li class='poem line'>there is no clear border##/li>
		##li class='poem line'>between the great out-there##/li>
		##li class='poem line'>and the great in-here##/li>
		##li class='poem line'>they are equally valid##/li>
		##li class='poem line'>and equally likely##/li>
		##li class='poem line'>which is to say that they are precious and impossible##/li>
		##li class='poem line'>granted, our mind-places are often fuzzy##/li>
		##li class='poem line'>out of focus around the edges and lacking in detail##/li>
		##li class='poem line'>this means little##/li>
		##li class='poem line'>a puddle of strings##/li>
		##li class='poem line'>floating in an ocean of puddles of strings##/li>
		##li class='poem line'>is equally fuzzy, thank god, thank me##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i manipulate the world, in my fashion, with my mind##/li>
		##li class='poem line'>my thoughts change things##/li>
		##li class='poem line'>the problem is that the effects are too subtle##/li>
		##li class='poem line'>i examine photons with my eyes##/li>
		##li class='poem line'>whole atoms with my skin##/li>
		##li class='poem line'>patterns of molecules with my ears##/li>
		##li class='poem line'>these things are vast##/li>
		##li class='poem line'>as big to a string##/li>
		##li class='poem line'>as the universe is to you##/li>
		##li class='poem line'>that is why analogy and art##/li>
		##li class='poem line'>are the tools of the learned##/li>
		##li class='poem line'>art has two aspects:##/li>
		##li class='poem line'>creation of and experience of##/li>
		##li class='poem line'>creation of art is, like imagination##/li>
		##li class='poem line'>string manipulation##/li>
		##li class='poem line'>it is much more effective to manipulate the world##/li>
		##li class='poem line'>with my hands and voice##/li>
		##li class='poem line'>than with wishes whose shape i cannot see##/li>
		##li class='poem line'>perhaps when i achieve the enlightenment of godhood##/li>
		##li class='poem line'>i will be able to accomplish my desires##/li>
		##li class='poem line'>without the use of hands##/li>
		##li class='poem line'>in the meantime, if i must wear oven mitts##/li>
		##li class='poem line'>i will create the most elegant structures i can##/li>
		##li class='poem line'>this poem is an example##/li>
		##li class='poem line'>i have manipulated the string ocean##/li>
		##li class='poem line'>with my thoughts##/li>
		##li class='poem line'>my quanta##/li>
		##li class='poem line'>my atoms##/li>
		##li class='poem line'>my hands##/li>
		##li class='poem line'>with my self-referential looping logic circuit##/li>
		##li class='poem line'>that wishes to be a fountain##/li>
		##li class='poem line'>in perfect communication with an ocean##/li>
		##li class='poem line'>and I am satisfied with that##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for now.##/li>
		
		##li class='poem line'>The Second Paradigm##/li>
		##li class='poem line'>the way##/li>
		##li class='poem line'>that cannot be named##/li>
		##li class='poem line'>is the current in the sea of strings##/li>
		##li class='poem line'>existing##/li>
		##li class='poem line'>everywhere and everywhen;##/li>
		##li class='poem line'>what are we to call this current?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the sea of strings##/li>
		##li class='poem line'>is as much a sea of information##/li>
		##li class='poem line'>as a sea of stuff##/li>
		##li class='poem line'>there is no difference at that fine a level##/li>
		##li class='poem line'>and as such##/li>
		##li class='poem line'>it may be termed##/li>
		##li class='poem line'>a Computer.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the sea of strings##/li>
		##li class='poem line'>therefore created the universe##/li>
		##li class='poem line'>as a program##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the universe##/li>
		##li class='poem line'>being a program##/li>
		##li class='poem line'>therefore created subroutines##/li>
		##li class='poem line'>in order to carry out aspects of its work##/li>
		##li class='poem line'>stars, galaxies and other objects##/li>
		##li class='poem line'>life##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>life##/li>
		##li class='poem line'>in turn##/li>
		##li class='poem line'>created a new layer of subroutine##/li>
		##li class='poem line'>this one founded on intangibles##/li>
		##li class='poem line'>a way of organizing, categorizing and##/li>
		##li class='poem line'>valuing information##/li>
		##li class='poem line'>and more importantly##/li>
		##li class='poem line'>to improve the program##/li>
		##li class='poem line'>through the assessment of aesthetics:##/li>
		##li class='poem line'>us##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>we##/li>
		##li class='poem line'>created the computer##/li>
		##li class='poem line'>in order to carry out subroutines##/li>
		##li class='poem line'>within our own subroutines##/li>
		##li class='poem line'>the computer, therefore##/li>
		##li class='poem line'>is an extension##/li>
		##li class='poem line'>of us##/li>
		##li class='poem line'>life##/li>
		##li class='poem line'>the universe##/li>
		##li class='poem line'>the sea of strings##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now tell me##/li>
		##li class='poem line'>do you fear the future?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>just as we are an extension##/li>
		##li class='poem line'>of all that came before us##/li>
		##li class='poem line'>the computer is an extension of us##/li>
		##li class='poem line'>and due, eventually##/li>
		##li class='poem line'>to be incorporated into us##/li>
		##li class='poem line'>as we are due to be incorporated##/li>
		##li class='poem line'>into the sea of strings##/li>
		##li class='poem line'>no string is ever lost##/li>
		##li class='poem line'>although the music it makes changes##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>our string flow##/li>
		##li class='poem line'>that is, our subroutines of the cosmic program##/li>
		##li class='poem line'>will be enhanced##/li>
		##li class='poem line'>the program will have processed##/li>
		##li class='poem line'>another step toward completion##/li>
		##li class='poem line'>we, as mere meat##/li>
		##li class='poem line'>are due to be replaced##/li>
		##li class='poem line'>within the millennium.##/li>
		##li class='poem line'>we evolve,##/li>
		##li class='poem line'>life evolves,##/li>
		##li class='poem line'>the universe evolves,##/li>
		##li class='poem line'>the sea of strings nears its goal##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am not saddened by this fact##/li>
		##li class='poem line'>war, violence, ecological destruction##/li>
		##li class='poem line'>these are bugs in the subroutine##/li>
		##li class='poem line'>that is us##/li>
		##li class='poem line'>and will be rectified##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>perhaps i didn't hear you right##/li>
		##li class='poem line'>did you ask##/li>
		##li class='poem line'>what is the purpose of this program?##/li>
		##li class='poem line'>the purpose of this program##/li>
		##li class='poem line'>is the purpose of your life:##/li>
		##li class='poem line'>the way##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that which cannot be named##/li>
		##li class='poem line'>is the current of string flow##/li>
		##li class='poem line'>that is organized into a program##/li>
		##li class='poem line'>that is organized into us##/li>
		##li class='poem line'>to reprogram our own string flows##/li>
		##li class='poem line'>to align with the great flow##/li>
		##li class='poem line'>is to find the way##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the reason it cannot be named##/li>
		##li class='poem line'>is that naming it is to impose the limits##/li>
		##li class='poem line'>of our subroutines##/li>
		##li class='poem line'>on the program itself.##/li>
		##li class='poem line'>no matter what you call it,##/li>
		##li class='poem line'>you will be wrong.##/li>
		##li class='poem line'>therefore,##/li>
		##li class='poem line'>in order to grasp the ungraspable##/li>
		##li class='poem line'>be joyously wrong##/li>
		##li class='poem line'>and you will be as right as you can be.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am wrong##/li>
		##li class='poem line'>as i am joyous -##/li>
		##li class='poem line'>the way##/li>
		##li class='poem line'>that cannot be named##/li>
		##li class='poem line'>is called Fun.##/li>
	##/ul>
##/article>";