<?php

namespace raingarden\rg_static_pages;

$the_html = "
##article class='page static' id='the_privacy_policy' draggable='true' resize='both' onmouseenter='there_is_only_one_draggable_element_at_a_time( this )'>

	##p>You worry about the wrong things.  You worry about privacy and security.  You've got better things to think about than that, and you're trusting the wrong people. You're trusting people who don't mean what they say or say what they mean, and they're telling you to be scared, and you, dingbat, are doing it.##/p>

	##p>Privacy is not an issue. It's not real. You and I are not important enough to need to worry about it. So what if Google knows which underwear you prefer? Isn't that exactly what the Future has been promising us since it was invented? A knowledgeable, respectful servant who anticipates your wishes? An automated assistant to take care of the dumb stuff? Your present lack of privacy is exactly what we all said we couldn't wait to possess, only a quarter-century ago. Now, you have what was promised you, and a bunch of guys in suits, all of whom are either spooks, work for spooks, or boss spooks around, are telling you to be afraid/enraged over the disappearance of an imaginary commodity which they have done more to compromise than all the corporate boneheads in the world could do if they put all of their mind to it.##/p>

	##p>The only reason anyone in the business world wants to track you is to sell you stuff.  They don't care how you feel, or why you think what you do, or what your ultimate goals in life are.  They don't care about your future, your wealth, your personal life...they care that you buy something.  Why the hell would Big Bidness care about anything else?  They are not in the take-over-the-world-and-enforce-rigid-conformity business. There's no money in that. There's no fun in that.  There's no competition, nor gambling, nor ladder-climbing, nor getting raises and bragging to your friends, so who needs it?  Slaves can't buy stuff, can they?##/p>

	##p>Sad but true fact #7493.b: capitalism is actually the real bulwark against totalitarianism, not politicians. Take that, anti-reality protesters! If Microsoft, Amazon, and Walmart, or, the 'MAW', if you prefer, decide to take over the world, the world is taken over, or everything just stops...deal with it.  If a country or a political party tried that shit, there would be serious blood paid. Think Afghanistan. Think Watergate. Think the Cuban Missile Crisis. Politicians have been trying to take over the world since the British Empire retired to the country, and was replaced with the Commonwealth. Neither the American, Soviet, nor Chinese hegemonies, for all their size and money and nuclear flyswatters, managed the job; conquering countries is one thing, holding on to them and making money from the deal is another.##/p>

	##p>Privacy between you and Facebook and Facebook's advertisers is so irrelevant that it's useful to all the wrong people. Politicians are going to great lengths to convince us that Facebook's power to collect your stats and vitals is dangerous to you. They are going to great lengths to convince you that the data gathered by governmental and quasi-governmental agencies for non-commercial purposes is only used to protect and defend you against evil. So walk through this with me: the people with the most to gain from compromising your privacy, politicians and mandarins who oversee intelligence and other officially-empowered agencies, are requiring that you be terrified, simply terrified, of the people who sell you toenail clippers and dog food. They want you scared, so you won't notice that they always end their speeches with, 'Ok, now give me money, so I can protect you from people who just want your money'. This is policy on roller skates, people.##/p>

	##p>Ask yourself what Walmart could possibly do with information about an affair you wish you hadn't had ten years before.  Now ask yourself what law enforcement agencies looking for a hook to hang you from will do with that information now that you've authorized them to collect it.  Mark Zuckerberg is rich and famous, so dragging him up to defend himself against the whole peanut-gallery distracts from the real invasions of your privacy, and those are authorized so high over our heads that they're just a fact of life to us yokels and nerds.##/p>

	##p>There's a joker in the deck, of course.  Most people don't have anything worth hiding, but they're still afraid of losing their privacy.  They don't want their porn preferences and boob-flashing selfies turning up and embarrassing them in public. What? You really think it's because people are trying to hack your home computer to steal money?  You hardly even qualify as a target.  Home security isn't a problem; large-scale commercial security is a problem. Yes, take simple and reasonable precautions on your private systems, but in almost every case, you'll get your money back from the bank, because payouts are cheaper than real security.  You aren't the problem.  They are.##/p>

	##p>Forget about privacy. It doesn't protect you, because it isn't real. You gave it away every time you used your credit card, or changed your phone number, or registered to vote.  Worry about piracy, not privacy.  Worry about powerful people using trivial nonsense and fearmongering to hijack democracy.##/p>

##/article>";