<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Art that Awes Me: An Imaginary Class in Cultural Appreciation##/h1>

##p>Don�t get it wrong�I�m not teaching a master class, here.  I don�t always think that much of myself. No, the �Master� in �Master Class� is the master craftsman, the human who has put in her time, paid his dues, made the study of their craft a lifelong pursuit�the person who has maintained her devotion to the craft of his choice, and has truly mastered it.  The person who honors the craft and the craftspeople before him, who began as a apprentice, strove to become a journeywoman, and graduated at last to the Master level, the journeyman who has learned everything the best of her forebears knew, feels it in the hands, or the eyes, or the voice�the human who has loved the craft and the work until it is part of him, inside her, informing every moment in a mind so shaped to the craft that I am nothing without it.##/p>

##p>For me, the craft is the word.  I write and compose constantly, albeit with long dry spells, but I do not award myself Mastery; you don�t award yourself anything as you learn and work your way up.  You don�t get to choose when you�ve made journeyman, for instance.  Only your peers can confer such prestige; only those who�ve earned it can give it.  I�d rate myself highly as a journeyman, but don�t think I�m about to fall into an ego trap: I�ve put in my 10,000 hours, more than once, but I�ve done so almost completely without sharing my work. The Masters of my craft don�t know about me yet.##/p>

##p>This is about the humans whom I�ve come to believe are the best in their fields, artisan and artists who make the impossible look easy, and make the merely difficult look like something they were born to. I don�t know how their processes unfolded for them, but I�ve been privileged at times to have buried myself so deep in my words and music that I reach that point of satori, the zen moment that stretches on forever, and I am at one and at peace with my art.  I have reached a point, usually after sustained efforts of two months or more, where my understanding and feeling of the materials and tools suddenly blossoms, and what previously I had to consciously program into myself begins to happen without the interference of my conscious mind.  I think it constantly, proposing and testing variations and styles without trying, without making myself do anything.  I�m not a great guitarist, but sometimes I just forget to think, and my fingers just do stuff, and I go, �I didn�t know I could do that�.  I write poetry in my unclaimed moments, turning the usual background blather of my mind into my writing.##/p>

##p>For me, writing is not just the art of words and voices; it�s the art of meaning.  I rarely have to work very hard to write the words and voices anymore, because I study the art of meaning. ##em>�##/em>##em>Meaning what you say and saying what you mean�##/em> is more than advice for a stuffy English gentleman.  It is the keystone of my craft. If it makes perfect sense, then you�ve already gotten the rest of it right.  If you write fiction, your characters shouldn�t be talking about stuff to make readers understand, they should be doing it and living it: experienced writers often remind you �Show, don�t tell� for a good reason. Living it makes it real; talking about it makes it talk.##/p>

##p>I mention the above for purposes of illustration only.  This isn�t going to be about me, but about what I love, admire, wish I could do myself and never will.  I have favourites in almost every craft and art, including those for which I have no taste. I�m not a big fan of yodeling, but there is a master yodeler out there who knows his yodel six ways to Sunday; if he�s that good, even a non-yodeler like me will recognize it.  I�ll feel it.  I�ll know this guy is doing something amazing, because when the talent is real, the talent is visible.  That�s what I�m looking for in a master craftsman, and if you look with respect, you�ll see the touch of God in artists and artisans of all disciplines and modes.##/p>

##p>I issue one caveat before embarking upon this task: I�m a man, which means that I�m likely to recognize mastery in men. Male actors, for instance, are easier for me, because the echoes in my own mind of the lines the actor speaks are louder than those of women.  I�m as easily impressed by female actors, but I�m more wary of awarding or denying their status as masters, because I�m more likely to miss what others might not. The outrage artists will have something to say about it, of course, but no one cares what they say anymore, now that all 1.7 billion of them have each said something similar thirty to forty thousand times.##/p>

##p>My Lord and Master, in predictable fashion, is Shakespeare.  His mastery of English and the stage set a standard for richness and invention that will never, and can never, be met.  Shakespeare lived at a crucial time, in a crucial place, and that time and place will never come again. English is too big, now.  There are, by purely mathematical determination, at least 600 writers living today who have as much skill and talent, but none of us (ha!) has the open horizon and vast scope that a language in rapid ferment offers. I will never be a Shakespeare, no matter how good I get, because in any craft, there is only one demi-god at a time, and only one god, ever.  When there are two, there may as well be a million; the blessing of perfection is laid upon but a few, and only within the thin slice of history that marks the emergence of an art from the intellectual shadows.  Before Shakespeare, there was English.  After Shakespeare, there was truth.##/p>

##p>My list of masters in long.  I won�t get to it all, but here are a few of the masters I know and love.##/p>

##p>Shakespeare. John Lennon. Jimmy Stewart. Rembrandt. Mozart. Michelangelo. Bill Reed.##/p>

##p>Yes, they�re all men, so far.  I just named the ones who sprang instantly to mind, and I know men better than women.  If that still bothers you, boring.  There isn�t a deep pool of women to choose from, prior to the 1960s. I didn�t vote for that, so don�t be getting all uppity about it; talent and artistry are equal-opportunity employers.  I hope someone is willing to assist me in rectifying my deficit, instead of reviling me for it.##/p>

##p>My first column, of course, will be William Shakespeare, because the Gods of the Quill require fealty, and fealty they shall have.##/p>";
