<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>And now for something completely the same...##/h1>

		##p>That's how politics really works, out there in Fantasy World.  When you make your point, and then make it again, and then make it over and over, until there's no way to have a conversation, you lose your audience.  It's called 'nagging', and it doesn't do anything positive whatsoever.  It doesn't matter how noble you believe your ideals to be if you're so rude and obnoxious that no one listens.##/p>

		##p>The market for identity-based politics is stagnant at the moment, and is due to begin shrinking, as do all outdated social movements, and it cannot be fixed.  Identity politics has reached the bloated and smug level, joining the people it reviles, in spreading acrimony in the name of understanding, and exclusion in the name of tolerance.  The identity-politics paradigm is a self-defeating one, even when used in the service of a good cause; it advocates hatred of an enemy, rather than inviting consensus, with the apparent goal of toppling the powers-that-be and replacing them with nice people who like them.  The problem, stupid kid, is that you topplers, no matter how loud you get, are fighting against people with real power, and you have none.  Protests are tolerated, not effective.  When you get that special bug up your ass that says, 'God/Reason/Walmart is on our side. Tally-ho, scallywags; we must strike while the iron is hot!' then hey, you're already dead as well as outdated, and now you've taken all the people you represent down with you.  Because you couldn't mind your manners.  Jerk.##/p>

		##p>Hear that, meatworld? You lost the goddamn revolution because you couldn't shut up. You show up to a war no one but you is fighting, and you even lose that?  It strikes me as a rather pathetic marker of the times that the left stands in the rain yelling about one thing, while the right stands in the rain yelling about another thing, and they're both too stupid to come in out of the rain.  There will never be any movement from either left or right, there will never be anything to negotiate, and there will never be any reward for anyone even remotely involved.  That kind of warfare democracy is done, so perfectly deadlocked that all the shouting is just shouting. They could be singing Kumbaya in Russian as easily as making political speeches, because no one is listening.  No one has listened for a long time.##/p>

		##p>The left long ago fell into the selfie-politics trap.  They forgot that the left is supposed to protect THE PEOPLE, as in, THE PEOPLE.  They're supposed to be standing up for the little guy against the entitled rich. They're supposed to be representing me, for instance, and they aren't.  They don't represent me, because I'm not visibly identifiable as one of the downtrodden, which means, of course, that I'm one of the downtreaders. You can't represent half the population against the other half, and call it politics.  It's just civil war for pre-schoolers; Pampers vs. Huggies.  Elected officials are supposed to represent the electorate, not their electors.  Identity politicians make no effort to represent anyone but their chosen disadvantaged.  The left is supposed to be smarter than that, but very few leftists seem to know that the left existed before they did, and without the perspective of history, they have no idea exactly how ridiculous they are.##/p>

		##p>That's the nature of selfie-politics, and it's why the system's best-before date was long-before now. The incredible prosperity of the west has created a huge bolus of the super-entitled, which crosses all demographic lines, including age, wealth, employment, sex, and education.  It's not a 'generation etc.' thing.  Kids these days are the most egregious examples of selfie-culture, but that's only because they had parents like us; when you add our narcissism and willful blindness to the frothy little bubble-bath of hormones called a teenager, you have an adulty person who not only thinks only of herself, but can't keep his hands off her growing personality in public.  You have politicians who are unable to distinguish between self-interest and common-interest. You have reporters who cannot distinguish between human interest and news.  You have a giant entertainment industry almost entirely dependent upon self-referential musical baby-talk, and hyped-up billion-dollar retakes of movies that were not worth seeing before either.  You have Twitter, and Facebook, and all the rest, and the common theme is 'Me'.##/p>

		##p>Now, it's not really much more than the self-interest of any generation or era.  It's always been about the Me, and the Zeitgeist ('the predominant spirit of the times' is the best translation I can think of) is no less about compassion and the good stuff than any previous Zeitgeisten (probably not a real word, but it would be a plural if it was).  People is people; living in a time of weird transitions between the mechanical age and the digital age does not change the equipment humans are born with; brains were the same before the time of big changes as they are now, and instincts don't just disappear in a couple of decades.  The problem is that the technology has changed, but people haven't, and won't.  It's the nature of the technology that it brings out the worst in people: selfie-culture is just the visible symptoms of human obsolescence; we just haven't kept up with our own technology.##/p>

		##p>Selfie-culture is what happens when people have no idea what to do with all the strange new toys the digital-whiz-kid magicians have supplied.  The first significant social phenomenon to emerge from the nascent internet was pornography: ye masses took to it in droves, and still do, I reckon. It was the first time in anyone's memory that masturbation materials didn't involve a guilty slinking between ATM and the back room at the video store.  Speaking of which, I saw this amazing thing with this gir&lt;&lt;##em>looming wifely presence behind left shoulder##/em>&gt;&gt; which I wasn't really looking at, I just thought it was interesting.  Anyway, it turns out that the whole world has been waiting for guilt-free selfie-sex for a long time.  Try and put a cork in that dam.##/p>

		##p>No, I'm not knocking masturbation, and selfie-sex could also mean any sex which Kim Kardashian is not too dumb to understand.  And speaking of which, what, after kvetching, is the most famous thing Kim-thing has ever done?  An accidentally-released sex video.  Yes, another one.  Accidental displays of celebrity genital combat are, in the opinion of experts, NOT.  Just NOT. How else can I say it?##/p>

		##p>Now, this is why the phenomenon is so interesting: the selfie-freaks are pretending to be porn actors.  These are not porn actors hiding their shameful pasts in order to fit in, these are boring people who are trying to invent shameful pasts, and they do it only for the attention, because they don't seem to be very good at it, from what I never actually saw.##/p>

		##p>The sky is falling, my little chickens.  Reality is going meta.  Satire is out of a job.  Irony is hiring new staff.  Tell me that I'm not imagining this, because it's'well, you check it out:##/p>

		##p>Porn invented fake sex.  Politicians invented fake news.  TV invented fake politicians. And now, celebrities have invented fake porn.##/p>

		##p>Isn't that like 'artificial corn flakes'?##/p>

		##p>That's gotta hurt.  It's not enough that real porn actors get paid so little for fake sex.  Now they have to compete with rich celebrities producing a poor-quality, watered-down imitation of the real thing, but without the realism.##/p>

		##p>After the runaway success of the masturbation industry, everyone got on board.  The internet quickly devolved into a loosely-connected network of echo chambers, almost all of which are devoted to the form of politics which thrives on having no one talk back.  When anyone can say anything, some of those echo chambers go all Lord of the Flies with inappropriate alacrity, and we end up with such moral abortions as Fox News and Donald Trump.  It's easy to find people to talk to who tell you you're right about everything; that was a service provided only to pop stars, presidents, and poodles.  That's why pop stars turn into divas, and presidents turn into dictators, and poodles turn and run when they see the others coming.  Trump was probably unaware, before becoming the first entirely fictional character ever to have a nuclear trigger on the night table, that he was capable of being wrong.  Good luck, world.##/p>

		##p>Entertainment, politics, academia, pool parties, play-dates'it's everywhere.  Just don't think that it's permanent, or real.  Selfie-culture is self-limiting; when you can't see past yourself, you see very little.  You do very little.  Selfie-culture, being about self, isn't really that much fun at parties, is it?  It talks endlessly about it's own trial and tribulation, when everyone else is doing the same thing.  It brags about things everyone knows, and already does, and probably shouldn't.  It keeps bringing the subject back to either its shoes or incipient alcoholism, of which it is inordinately proud.  It cheerfully eats fermented garlic while smoking a cigar dipped in a skunk's latrine, and then it talks to you, ol' buddy. You know the type.  Selfie-culture is like the yogurt it's named after.  It's a rotting lactobacilli colony before it expires, and it's the same after, but you only call it what it is when you lose your taste for it.##/p>

		##p>Selfie-culture won't be dominant forever.  Kids born two generations after the digital switch will likely find the selfie fascination quaint, as in: 'Wow, Dad, you guys really went nuts with that shit!  Who can look at that many pictures?  Didn't you have time for masturbation?'  The kids tend to find the parents uncool, or so I hear, so they aren't likely to find ostentatious displays of technology which everyone has to be very interesting, and who can blame them? Think of the generation of hippies which rejected their parents' ungroovy vibe, dig?  Then think of the Yuppie disco-pervs with the powdery nostrils who followed the hippies? Then think of the covertly-gay entire decade of the eighties erasing the overtly-homophobic entire decade of the seventies.  Ok, don't necessarily think of that'I just threw that in for symmetry, and because Flock of Seagulls have apparently survived a carefully-planned mass extinction eons in the making.##/p>

		##p>There is no fix for selfie-culture, because it'll all be over but the billing soon enough.  It's too boring to live long in its present form.  The problem, of course, is that the cult of self-esteem is profoundly pervasive, because it's based on what is missing, not what is there. It exists because it's the easiest, most novel thing you can do with technology, not because the selfie-mob actually understands the technology it lives by.  Kids these days do not know any more about tech than their grandparents; they practice more, so they're better at it, but they still don't have anything better to do than take pictures of themselves smoking cigarettes in the boys' room, or riding their bike no hands (a lot of famous last words were 'Look, Ma!').  Selfies are exactly the response you'd expect from a kid with a new toy, and the kid is all of us, so don't take it out on young Norbert.  Besides, the kid's a nerd, but he stole your sex tape, so you owe him.##/p>";
