<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Blackbirds and Gender Politics##/h1>

##p class='entry-meta'>I read, much too long ago to remember wherein, a study of the social habits of the red-wing blackbird.  What had seemed to a previous (male) scientist like territorial squabbling seemed to a later (female) scientist more like hide-and-seek, or tag. The disparity is often held up as an example of the gentler, kinder nature of female science and scientists, in classifying and understand the cute little creatures of the forest.##/p>

##p>The problem, of course, is that neither explanation is right, and it&rsquo;s nothing but offensive politics to hold &ldquo;male&rdquo; science as somehow different and less reliable than female science.  Science doesn&rsquo;t have a gender, and the idea that women&rsquo;s science explains birds better that men can should be embarrassing for women&rsquo;s scientists.  The chance of being right in this debate is NOT NOT NOT, which is very NOT.  The chance of there being a gender-related correctitude to the question of what birds with pea-sized brains do in their spare time is aggressively zero.  None.  Nada.  Modeling bird behaviour along human gender lines has no probability of turning out to be right, because them birds ain&rsquo;t doing that, because they have pea-sized brains which cannot afford deeply compartmentalized, discrete, parallel processing systems.  Play and territoriality are human things. Birds is not human.  Do you see how that works?  A feminist interpretation is no more likely to explain birdy behaviour than any other.  What makes it truly a load of horse potatoes is that feminists really have no business re-interpreting the word of a previous scientist as &ldquo;male&rdquo;.  Perhaps the circumstances were different; environmental concerns will certainly crowd out playtime when the food supply is scarce.  The &ldquo;male&rdquo; interpretation is almost certainly correct to the same degree as the later one, but science is a process, in many cases, of optimization, not invention. A scientist arriving late on the scene should be testing and building, not discarding and replacing, the work of previous iteration of the experimental process.##/p>

##p>Conflicting interpretations do not science make.  They politics make.  Choosing one unverifiable, unfalsifiable hypothesis over another is not science.  It&rsquo;s personal choice, informed as much by constipation or itchy mucous membranes as by science.  The point is that this should never even have become an issue; results get reinterpreted all the time, and it&rsquo;s boringly certain that many women have misinterpreted birdy-num-nums (The Party, Peter Sellers, comedic acting at a master craftsman&rsquo;s level) in other species, with the same frequency as men.  This cannot be an issue, but it is an issue, and not for any reasons of science; it&rsquo;s an issue because selfie-feminists, whom I clearly distinguish from feminists who do real work, made it an issue.  That&rsquo;s why so many citizens can&rsquo;t stand feminists at all: too many of them are willing to bend any of the phenomena of human expression to their own hostile purposes, and truth be damned.  Inventing statistics and evidence only works until you get arrogant and go too far, and after that, the primary result of such conceit is an inability to trust ##em>anything##/em> selfie-feminists say. Selfie-feminists are the girl who cried wolf, over and over, and who keeps crying wolf even after the truth is evident, they way kids lie about stealing cookies from the jar after being caught red-handed by Grandma.  In the end, no one knows what the real statistics are, or how the interpretations were made, and no one can find out, because finding out is then labeled as sexist.  I know, I know&hellip;put a cold compress on your forehead until the nausea passes.##/p>

##p>The net result of conflict is usually more conflict.  In this case, it&rsquo;s more conflict, and more violence against women.  When it becomes impossible to find out exactly what the problem is, because the statistics are not reliable and the research is largely fictional, it&rsquo;s the women who suffer.  It makes reform impossible.   For men, it makes knowing whom to out as a danger is impossible.  It makes prosecutions fail##/p>

##p>If you can&rsquo;t trust selfie-feminists about birds, you definitely cannot trust them about men. The belief-systems invented by feminists to describe their enemies is the opposite of the above: every feminist explanation for male behaviour is the same: nasty territorial squabbling and threat display.  Alternatives, such as love, play, or protective impulses are not allowed.  Men squabble, women play nicely; that&rsquo;s all the science we ever get, and it&rsquo;s not science##/p>

##p>Humans don&rsquo;t have the right to remake other humans in their own images, but that is exactly what is happening.  Women in particular don&rsquo;t get to tell men what we are, or should be; hostile women more so.  Women don&rsquo;t stand for it, so they shouldn&rsquo;t be permitting roaming gangs of child-feminists to do it to men.  No human being has the right to try to confine others to manufactured labels they just made up, with NO discussion with the subjects of the experiment at all.  Every piece of masculine behaviour is interpreted in a violent light, and every such piece is ascribed en masse with the same limited, evil emotions and motivations.  Protective impulses are turned into displays of patriarchal possessiveness.  A loving nature is turned into an exception.  Admiration and attraction are turned into &ldquo;rape culture&rdquo;, which is undoubtedly the most evil of feminist weasel words.  Hitting on chicks is turned into sexual harassment; I&rsquo;m asking you out, so I plan to rape you later.##/p>

##p>Take my very strong protective impulses.  I would literally take a bullet for a woman in danger.  I loathe bullies, and I don&rsquo;t fear them, and I stand up to any man who is threatening a woman.  I&rsquo;ve stepped between threatening men and their victims too many times to count.  I risk my health and welfare for the sake of women I will never know, even if they&rsquo;re selfie-feminists, and I don&rsquo;t think twice before locking and loading.  How my impulse to protect women and children at great risk is reinterpreted as patriarchal possessiveness is impossible to understand.  Why women who should be grateful for my protection get to insult me for protecting them is beyond me.  Beyond anyone, really, except the feminist in the ivory tower who arrogate unto themselves the right and power to sit in judgment of all the rest of the world.##/p>

##p>Here&rsquo;s another one: we&rsquo;ve come to feel that blanket accusations against men are justifiable, while those against women are not.  We&rsquo;ve come to that, because angry ivory-tower puppeteers have been trying to cast men as brutes, and penises as weapons, for more than my entire life.  The fact that some men respond to self-perceptions of sexual inadequacy with stupid posturing or violence is not proof, or even evidence, that their behaviour reveals what lurks deep in the hearts of me.  The nasty ones are held up as the template for masculinity, and goodness, for some reason, is never taken equally as a revelation of core manhood.  Why the untold billions of kindnesses men show women every day are statistically meaningless, but the unkind actions of a statistically-demonstrable few are written in stone as my deepest motivations.  The people who decry any evidence of brain differentials paint me as an automaton.##/p>

##p>Get this straight: the majority of men do not have rape and violence as their core motivations.  They are programmed to resort to violence in case of threat, which is pretty normal in the creature world, and has nothing to do with &ldquo;society&rdquo;.  That doesn&rsquo;t mean that they&rsquo;re programmed to use violence as a tool of gender-based repression.  There&rsquo;s no linkage: just because red-winged blackbirds can peck each other&rsquo;s eyes out in a rage doesn&rsquo;t make them do it.  No scientists has ever reported that.##/p>

##p>Yet another: the feminist ideology holds that men respond to feelings of sexual inadequacy with threats and violence, and that rape is never far from our minds (which is, apparently, why we support rape culture).  That may be true in a very small minority, but it isn&rsquo;t how men think.  Only a hostile interpretation assigns such violence to men so casually, because there isn&rsquo;t any evidence whatsoever that men in general think that way, any more than we can accuse all women of being nasty bitches, just because some immature feminists definitely are.  Women do have a greater tendency to gossip; does that mean that all women savage men behind their backs?  No, it means that women discuss things more and differently, because they have different evolutionary roles.##/p>

##p>Men don&rsquo;t want to hurt women.  Men spend half their time trying not to hurt women.  If our society was really based on rape and rape fantasies, there wouldn&rsquo;t be a human species.  Who knows what there would be? Evolutionary paradigms very rarely admit of rape as a viable and exclusive survival trait; if it were a dominant trait, women wouldn&rsquo;t enjoy sex.  Why would evolution need them to?  The fact that women have both external and internal pleasure buttons they want men to learn to press right is all the proof that rape is not central to the male psyche any more than compulsive slander is central to the female&rsquo;s.##/p>

##p>Men and women have our mating rituals both social and genetic.  Most men, that vast majority, do not ever think of rape as a reproductive strategy, or as sexually pleasurable.  Most men will not get aroused by violence: they&rsquo;re far too busy thinking about how to protect the victim.  They don&rsquo;t know how, and they don&rsquo;t know they&rsquo;ll get support, so the protective impulse is undermined as often by women as by men.  That is the nature of &ldquo;rape culture&rdquo;; if I&rsquo;m in it, you&rsquo;re in it, and if I&rsquo;m responsible for it without doing it, then so are the selfie-feminists.  Culture is not an &ldquo;opt-in&rdquo; arrangement; if you&rsquo;re living in it, you are it, and that&rsquo;s just by definition.##/p>

##p>When men fear sexual inadequacy, they don&rsquo;t go out to rape women.  They stay at home with porn, or fantasies, or they just surrender to loneliness.  Violence isn&rsquo;t even an option to consider; it is a turn-off, not a turn-on.  Guys do not get a boner from hitting girls.  Guys with wiring problems do, but they aren&rsquo;t us; they don&rsquo;t represent us at all.  We&rsquo;re men, and the masculine code says protect, not violate; women, I&rsquo;m sad to say, who accuse us of violence without any concrete reason will eventually lose the protection of men, which leaves them open to the 1% (the one-percenters weren&rsquo;t originally people who glommed all the money; they were people who had killed other people and were proud of it), and they have no right or reason to cry rape culture to the whole world when they refuse our protection.  We don&rsquo;t owe you; we love you, and it would be nice if feminists would let people enjoy that.  They can&rsquo;t, because they&rsquo;ve got so much ego and pride wrapped up in their campaign that they cannot let it go.##/p>

##p>Ladies, let me explain: at the core of most men is not a desire to own and control, it&rsquo;s a desire to be loved.  We live in a world where love is being turned into a crime, and men in general don&rsquo;t know what to do with that.  That&rsquo;s because&hellip;hey! they shouldn&rsquo;t have to.  Bonehead stereotyping is a children&rsquo;s game, and men, by their natural standards, are not supposed to engage in children&rsquo;s games, even when, especially when, women are the players.  Do you know any women who admire childish men?  Then why do we have to prove our loving natures by playing at hostility?  When men are having sex, they&rsquo;re looking for love, just like women, and just like women, EXCEPTIONS DO NOT PROVE RULES.  Men have the same loving and nurturing natures that women do; we just express it our way, and if you don&rsquo;t like that, then you don&rsquo;t like men, in which case, we probably have no reason to give a damn about you and your loudmouth friends.##/p>

##p>Making love to a woman well is the great test of a man&rsquo;s worth.  Maybe medieval dudes liked violence a lot more, but they&rsquo;re dead, and they don&rsquo;t exert that much influence anymore.  Men generally prefer discussing life with dudes who aren&rsquo;t dead, because we like to make things work, and dead guys are no help.  Sexual inadequacy hurts; it&rsquo;s one of the most painful aspects of a man&rsquo;s life, and one of the hardest to deal with.  Women have a choice: sympathize and be nice and make things work, or use it as a wedge issue to make men feel even less adequate, because we all know and understand that a sexually-inadequate man is a fair target. Feminists who decry any mention of a vagina by an unlicensed male have no trouble making men feel as bad/evil as they can; have you never noticed the number of penis insults selfie-feminists toss about like hand grenades?  Have you never noticed how they make fun of any man who expresses unhappiness over his sexual problems, insulting his penis size, or staying power, like 12-year-old boys do?  Have you not heard how often women who don&rsquo;t want sex with men dehumanize men by referring to them as &ldquo;penis&rdquo;?  These are not women who want to end the rape epidemic; these are women who want to end masculinity.##/p>

##p>Women who complain about men&rsquo;s violence while encouraging it cannot ever be trusted.  Selfie-feminists have a vested interest in maintaining the &ldquo;rape culture&rdquo; fiction; they don&rsquo;t make any efforts of any kind to stop it from happening.  Solving a problem doesn&rsquo;t mean changing the human species; it means lowering the hate index and upping the pleasure capacity for all humans.  Latter-day feminism has nothing at all to say that is capable of reaching men.  They hate us, so they can go fuck themselves; that&rsquo;s how humans are.##/p>

##p>Selfie-feminists do not solve problems; they prefer to solve people.  If the problem is rape, we&rsquo;ll stamp out masculinity, because disempowering and devaluing people who are already suffering is known to be the safest and most effective method of reforming the species for the purpose of social and educational eugenics.  Women who hate men don&rsquo;t get to define them.  Or more accurately, they can go ahead and define them, and live with the consequences, and the rest of us will shake our heads sadly, because there&rsquo;s nothing we can do.  Feminists recognize problems, but they always solve the problems by telling people what to do, and then bullying them if they&rsquo;re reluctant.  Making enemies for fun and profit is every bit &ldquo;rape culture&rdquo;. I&rsquo;m sorry, but it is just normal, genderless, human behaviour not to take shit from idiots.  If the real feminists don&rsquo;t leash their angry lapdogs and put a stop to the hostility, then there&rsquo;s nothing we can do, and we all, as in all, end up caring a lot less than we should.##/p>

##p>One day, in a far distant future, a feminist will ask a man to explain things, instead of inventing girly explanations for stuff that is not girly. If she actually listens, which is not where the smart money goes these days, she&rsquo;ll learn that her cardboard-cutout stereotyping got it pretty much all wrong. Feminist scientists should be coming to the same conclusions that any other scientist would, because science doesn&rsquo;t play politics.  If you go to the marsh looking for territoriality, you&rsquo;ll find it.  If you go to the marsh looking for play, you&rsquo;ll find it.  If you go to the marsh looking for rape culture, you&rsquo;ll find that.  You&rsquo;ll find anything you want to, because we&rsquo;re not birds, and what birds do is not what humans do. If you go to the marsh looking for people to hate, you&rsquo;ll find that, too.##/p>";
