<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Declare Peace: a message to men##/h1>

##p>Yes, men, feminism can be a real pain in the ass.  The arrogance, the hostility, the phony ideals�their incredibly poor manners have reduced feminism at large to meaningless drivel over �slutwalks�, and endless insults over �mansplaining� and �manspreading�, as if how a man sits is of comparable importance for women to the sexual mutilation of girls.  No one ever changed the world for the better by building walls between people, and it breaks our hearts to see rude, ignorant children doing their best to undo decades of deepening gender-d�tente in their search for self-esteem. Feminism as we know it now seems devoted to providing women with new reasons to hate their fathers, brothers, and sons; men have no reason to show feminists any love.  Hate begets hate, and there is no such thing as hate in a good cause.##/p>
##p>No, men, we have no reason to respect phony feminism, and no, we have no reason to take anything they say seriously.  But no one ever needed us to take feminists seriously; we were supposed to take women seriously. We were supposed to value them above all other gifts, and to protect them from harm and slavery, that they might work their daily magic in our otherwise gloomy lives. That�s our duty, our role, our meaning in the world, and we failed at it.  Our forebears became bullies, instead of husbands.  Feminism happened, in all its rage, because men made it happen.  Feminism turned rude and abusive because we didn�t listen until women everywhere were as angry as hell. Feminism is not the women�s fault, my brothers; it�s ours.  It�s the men�s fault. Stop arguing, own it, and declare peace.##/p>
##p>We started the gender wars, men; you and I, in our own hearts, may know ourselves innocent, but it is upon our heads that the responsibility for peace falls. You don�t get to be a hero by saving damsels in distress anymore; you get to be a hero by shutting your mouth and taking the hit, whether you deserve it or not, knowing that no one will ever know but you.  Heroism is in that lonely moment when you just look at the world, look at the people in it, and say, �Fuck it, this is mine, this needs doing, I will do this�. We, as men, rightly value strength and bravery highly; strength can mean accepting defeat in victory, and bravery can mean accepting punishment in innocence, if that is what it takes. That is, and must remain, our most noble ideal: we will do what it takes, in silence if we must.##/p>
##p>A man can be accountable without guilt, and take responsibility without fault.  He can make amends for things he didn�t do, to people he will never know, because that is what the world needs. He can be innocent while apologizing, because it needs doing; the peace of having done right is the highest wage you will ever earn.  A man, being a man, can shut up and take the hit, because being right is never as important as doing right.##/p>
##p>So, listen up, men: you want to end the war? Surrender. Shut up. And then, after that, we�ll make some good shit happen, ok?  So maybe the whole world won�t ever know you�re a hero, but the other heroes will know. I�ll know. You�ll know. What else is there?##/p>
##p>So here's the deal: coffee time�s over. Be men. Make things work.##/p>";
