<!-- InstanceBegin template="/Templates/standard_post_content_1.dwt.php" codeOutsideHTMLIsLocked="false" --><!-- InstanceBeginEditable name="post_meta" -->
<!------------ RGCafe blog post -------------------------
Date: 2018-09-19
Categories: 
Tags: 
Title: Livin with (an) LCD
Subsite: Love and Chaos
Number: 1019
ID: living_with_lcd
Post description: 
--------------------------------------------------------->
<!-- InstanceEndEditable -->
	<div class="blog post default wrapper">
<!-- InstanceBeginEditable name="post_title" -->
<h1>Living with (an) LCD</h1>		
<!-- InstanceEndEditable -->

<!-- InstanceBeginEditable name="post_content" -->


<p>There’s a new cultural phenomenon asserting itself through the chaos of Western Civilization: the Cowboy Crybaby.  Only selfie-culture could produce anything as counterintuitive as the tough guy whose only tough guy technique is yelling insults and running away, and who morph every few mouthfuls from Reaganite good ol’ boys with shotguns and beer-guts into little boys and girls who like yelling insults and running to Mummy. We are beset by whiners, complainers, victims, and protesters; the shamers, blamers, and gamers, some (but nowhere near most) of whom are professionals and/or instigators, who have ridden the selfie-culture wave to an impractically-high level of self-esteem, at the expense of, oh…let’s say…democracy, courtesy, and the “victims” they claim to represent.  We have seen the lowest common denominator, and it is us.</p>
<p>Identity-politics, the self-esteemizationing of the recently-marginalized, has a genuine purpose.  We just don’t see anyone working at it.  It was supposed to bring the marginalized and segregated into the eye of the general public, where its practitioners hoped to arouse enough conscience amongst the prosperous to open the doors to the prosperity of all citizens, including the minorities and sectors of the traditionally-excluded.  It was supposed to rescue Canada’s first peoples from their dire poverty, for instance.  It was supposed to normalize parliamentary representation for women and minorities, elevate immigrants to full economic citizenship, end discrimination against gays.  Those balls were already rolling when selfie-culture reached voting and taxing age; now we’re spectators to a race between mounting hostility stoked by opportunists and mounting resistance stoked by other opportunists, watching and holding our breath as the hard-won détente of two generations is undone.</p>
<p>Specifically, what we’re seeing is calculated hostility and intimidation from both identity-politicians, and the traditionalists who oppose them. We like to slap phony labels on every side in every dispute, but they aren’t for real; the left no longer represents even the downtrodden within majority populations, and the right no longer stands for economic opportunity, law and order, or national defense.</p>
<p>Conservatives no longer conserve anything but their own privileges; they no longer wish to serve all the people under a set of selected policies, but to serve only their own supporters under the most self-serving of mandates.  Conservatives have become the least-patriotic of all citizens, publicly and consciously repudiating not just the policies of their political enemies, but their enemies themselves, and those who support them, and even those who discuss supporting them.  Conservatives once stood for protection of individuality and fair opportunity, but that’s long gone. There’s no longer any effort to make sense; they operate on pretext and accusation alone.  They have no desire to solve any of society’s ills; they wish only to cement the political and economic status quo, maintaining power for their own purposes only.  They stare at themselves in the mirror, pretending that what they see is their own superiority, with no sense of community required.</p>
<p>The identity-politicians, who inherited the machinery of their socialist forebears but not their ethics, have abandoned everything the left once stood for, and like the children they think they aren’t, they represent only themselves.  They make lists of the admissible and inadmissible, shuffling minorities constantly to best effect, inventing new victims to represent daily, and adding more reasons to keep “white males” out.  There is no more effort at negotiation or compromise than from the anti-abortion freaks on the other side.  Scapegoating white males is a professional requirement, and victimizing all others is a full-time job.  Minorities making up 0.almost nothing percent of the population demand equal representation.  They actively recruit new categories of sexual dissident; being weird is now a gender, and being first peoples grants you a special form of gay.  The racism and sexism of the left has become a deafening betrayal of all that liberals of every colour worked for.</p>
<p>When there is nothing real to debate, you don’t send debaters: you send in the professional Lowest Common Denominators, the ones who win any race to the bottom of the barrel, who are immune to truth and decency, and who can afford nice shoes but never seem to do any actual work. I can’t resist telling you that I call this phenomenon “Wrapping Shit in Slime”.  Sorry, back to business.  There’s no hope of discussion.  There are no important issues left, because there is no chance of diplomacy or flexibility on any side.  There’s no longer any point in building a moral groundwork or an intellectual framework, because with amateurs and carpetbaggers running democracy, you don’t campaign for election; you recruit an army.  You send out your snake-oil salesmen, who play to their own audiences with a continuous stream of embarrassingly-shallow invective completely independent of reality.</p>
<p>If the only point to getting elected is to undo what the other guys did, what do you do for an encore?  If you were hired to wreck things, you probably know nothing about building things, so once you’ve set the clock back a whole political term by dismantling social nets in favour of billionaires or micro-minorities, you have nothing left to occupy you.  Imagine what would happen if identity-politicians took majority power: they would do nothing but repeal and alter, because that’s all they’ve ever trained for.  We already know what happens when billionaires take majority power.</p>
<p>And how does one get elected when two-thirds of the population revile you?  By divide-and-conquer techniques a million years old.  If you can only bring a little more than one-third of the electorate onside, your only hope is to keep all the other parties at slightly under one-third at best.  You do that by splitting the opposition into as many fragments as possible, while maintaining solidarity within your own ranks.  It never really works like it’s supposed to, because there really is no room for growth anywhere; with each election, divisions deepen and allegiances narrow, because campaigns are insult-based, not platform-based.  That leaves the social fabric in tatters, the vulnerable undefended, the billionaires unleashed, the country poorly-defended, and the lunatics in charge of the asylum.</p>
<p>If the whole system is a gridlocked mess of idle chatter, with government by decree in effect because there’s no way to negotiate or debate in the legislative fora, then there is no system.  There’s no one in charge, anywhere, ever.  The least-committed, most opportunistic political functionaries take over, and yell at each other, and then yell at each other some more, take a break, and go back in to yell some more.  What do you expect to get when you let the children take over?</p>
<p>You get an awful lot of “I know you are but what am I?”, a tidal wave of “he started it”, endless variations on “poo-face, poo-face”…every one of the greatest hits of primary school is included.  You get ritual repetitions of juvenile classics, like “it’s not my fault”, “they won’t let me play”, “you’re not being fair”, “boys have cooties”, and “you may not be a rich white rapist, but you’re privileged”, which, being unfalsifiable, is the almost-grown-up equivalent of “You’re a fuckin’ Jew”, “You’re a fuckin’ nigger”, “You’re a fuckin’ homo”, “You’re a fuckin’ nutcase”, or “girls have cooties”, because insulting people for what they were born to be is evidence of the worst form of bigotry.  The most dangerous and intransigent of racists, sexists, heterophobes, and “anti-“whatevers is within the left, because we expect more of them, so we are more likely to feel betrayed.  We expect the right to act selfishly; that’s what they do and they’re proud of it, which makes them as predictable as clockwork.  The left is supposed to be the protector of the community from the depredations of empire-builders and despots; instead, they do nothing but self-represent.  They feel no sense of community at all.  They feel no sense of greater responsibility than to their own privileges, which are considerable; most of the selfie-politicians represent communities which have no reason to call themselves the downtrodden; there are few stranger sights in democracy than protesters giving stentorian voice to their voicelessness in every forum, whether they were invited or not.  That’s exactly what you’d expect to happen when the primary motive of the community-builders is the destruction of communities, and the primary motive of social reformers is self-esteem, not social work.</p>
<p>Now, let me crawl out to the end of the limb, where the fruit is tastiest but the risks are higher; I don’t care whether you’re part of a minority or not.  I don’t care, because I shouldn’t care.  It shouldn’t be an issue.  Protesting racism is normalizing racism, particularly if the racism involved is trivial or exaggerated, which they most-often are.  Protesting unfair trial practices, whether real or not, only works if you don’t turn it into yet another form of rape; inventing “rape culture” revealed the moral and organizational weakness of the feminist movement as it stands now. Inventing crimes overnight just alienates the people who might have supported you; now we’re all criminals anyway, so you can go to hell.  That’s how it works.</p>

<!-- InstanceEndEditable -->
	</div><!-- InstanceEnd -->