<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Please just listen##/h1>
##p>I�m comfortable addressing men.  We�re more likely to get each other, so I feel safe doing it.  I don�t feel as comfortable addressing women, because I don�t want to be presumptuous in matters where I have much less experience.  I am sad to warn you that I have stuff to say to pretty much everyone, but I addressed the men first, to maintain both integrity and the appearance of integrity.  Now I address women.##/p>
##p>It�s mystifying to men, us, that women, the emotionally-talented ones, haven�t noticed that good and honourable men � their men � have been tolerating the most vile attacks on our integrity, honesty, masculinity, compassion, ability to love, and yes, even our genitals, for six decades. Every day, without rest or respite, for our whole lives.  There has never been a day in our lives when there wasn�t someone, somewhere, accusing any or all of us of rape, or something like it.  We�ve never had a day off from being hated, ever. We�ve been under unremitting attack for sixty years, and we still can�t even get an understandable explanation for it.  We�re tired, we�re wounded, we�re disoriented and confused, and we�ve been begging for peace since before the war started�so�where are you? Why aren�t you there?##/p>
##p>Men need you like we�ve never needed anyone, and you�re not there.  You don�t pick up.  You don�t come to our aid.  Good men of honour and character are being hurt, and we are slowly coming to the conclusion that the women we love have abandoned us. We wonder whether we are to be sacrificed on the altar of expediency. We keep calling to you for help, but you�re not there. We�re your husbands, your sons, your fathers�why will you not come to us?  Why do you not defend us?##/p>
##p>Things between men and women were getting better.  They�re not getting better anymore.  I feel a very powerful need right now, and so do legions of my brethren, to remind the women of the world that we are human first, in flesh and blood and mind, and men second. We are human, and we feel pain, and we have loves, and we do good in the world. It seems to us that many women have chosen to forget that we bleed red, that our hearts break, that our loves go unrequited, and that you, you, you, are our loves and the objects of our yearning.  We fear marginalization and slavery as you do; our lives may be ruined in the same blink of an eye as a woman�s can; our happiness can be as easily destroyed, with no more than a word from a tyrant.##/p>
##p>We need to show you our pain, and what it does to us when the love goes out of our world. Our very humanity is under sustained and overwhelming assault, and you, our women, seem to have forgotten to think of us as people.  We need you to see that we are honourable creatures who do not deserve what is said of us or done to us.  We need to remind you that we are not impervious to insult, that we cry when we are devalued, that we are injured when attacked, and that we fear in our deepest souls dying alone, longing for the touch of a loved one�s hand.  We need women to remember that we feel the crushing weight of responsibility and circumstance in our own way, and that it can be heartbreaking, even lethal, not to have the support of people we love.  This is not a casual fist-fight or street brawl; this is an all-out emotional war for which men are ill-equipped, and men are more fragile than you.  You know this.  You love to remind us that it�s true, that we are reliant upon you; we are, and you love it.  Why do you not act upon it? We are all aware that bodies mean nothing in the emotional battlefield; size and strength avail us nothing, and we are running out of alternatives and emotional reserves.  All of us.  We keep saying �uncle�, we keep saying �I give�, we keep saying �you win�, but no one will take our surrender, and the punishment just continues.##/p>
##p>We need to make women see through all that blind anger that we are each and only a single man, with little power to control or influence the minds of people, beyond the few we know.  We need you to remember that we love you, and that hurting people who love you is anathema to everything you are supposed to believe in.  We need you to stop listening to angry strangers who repeat the same accusations like a mantra.  We need you to stop giving your trust to strangers who call us rapists and misogynists, because you know us better than that.  You know it�s hurting us, and you owe us the same loyalty we owe you.##/p>
##p>I�m not �men�. I�m a man, a single person, entitled to my dignity. I�m worried that women seem determined to leave me none.  How much humiliation must any one individual endure, for the sins of others�for things I would never do or permit in others?  How often, our loves, are you going to let hostile strangers slander us, make scurrilous allegations, or plant the seeds of anger in minds where there was none, before you do what you demand of us?  We are men who never pretended to be superior or invincible, and we feel no shame in asking and expecting our women to defend us. That is what you wanted of us, is it not? Freedom from assigned roles? We have begun to wonder whether freedom from assigned roles only applies to women; you seem to treat us as if we think we�re tough guys, and want to fight.  We�re not tough guys, never said we were, don�t want to be,  .  We�re responsible, normal, moral people, and you�re supposed to be there to defend our right to be that way.##/p>
##p>When are you going to protect us, our loves, if not right now? We would do anything to protect you; that is how we earn your love and you all know it perfectly well; why will you not step in to protect us now, when we pledge our lives to you? Do we not deserve your protection?  Do we not need your protection? Have we not earned your protection?  Why are you not there when a man who loves you is taking a savage beating from bullies who know he can�t defend himself?  Why are you not there when another human is being hurt, and you have the power to stop it?##/p>
##p>If you will not protect us, who will?##/p>
##p>There is no one on earth who can justify the tide of abuse that men and boys are suffering. A boy doesn�t deserve to grow up in a world that hates him, any more than a girl does. A single man does not deserve the punishment you set for all men; that is called scapegoating, and it is the practice of fascists.  We are no more than ourselves, no matter how hard we try or wish, and that�s hard enough for a man to bear.  It is the final kiss of death to our happiness: we are terrified, terrified and drowning in it, to be abandoned by our loves for not being more than merely human.##/p>
##p>Women, you do not own suffering.  You own your own suffering, but you have spoken of nothing but your own suffering for our entire lifetimes.  That�s enough; you were heard, you were honoured, you received the due mea culpas, and you are long overdue to return the kindness. The horse we rode in on was almost dead before the flogging began; it�s warm mush now, but the emotional violence continues. Men are weary of hearing about your suffering; you had your turn, and now it�s ours. You must let us feel entitled to our own suffering for a time.  You owe us that, because while it�s a high privilege to take a bullet for the women we love, we�ve taken a lot of bullets for you that we shouldn�t ever have had to.  Suffering is a demon who doesn�t play favourites, and watching every shred of our beings devalued and defiled, without respite, for decades, while women we love stand idly by�trust me, that�s suffering.##/p>";
