<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>The Ravages of Entropy##/h1>
##p>There is no object, motion, or idea in the universe which escapes the ravages of entropy. In time, all things go the way of all things. It falls apart. All of it. Stuff, people, movements�even ideas; nothing is immune. Democracy is toast; journalism is toast; economics is toast�don�t look for silver linings here, because there aren�t any; they�re just toast.  They won�t be fixed, or replaced.  They won�t even be studied seriously after the funerals.##/p>
##p>That�s an intimidating prospect, isn�t it?  All the systems we took for granted, and any benefits that resulted from them, are obsolete, and way past their best-before dates.  The world that spawned them was built on cultural assumptions which no longer hold meaning for our futures; democracy, journalism, and economics require impartiality and honesty, and there ain�t none of that left.  Our political leadership is not even a joke, it�s so embarrassingly pathetic.  Our journalists care little for facts, and concentrate on reporting feelings, as if what people feel on hearing the news ##em>is##/em> the news.  Our expert economists have missed their guesses on every major development of the past half-century.  They get almost nothing right, but if they do guess correctly every now and then, they don�t have to apologise for giving everyone bad advice all the other times.  Try to find a set of economic forecasts made in the last century that have turned out to be accurate; they�re out there, but you�ll have to dig way down before you hit one.##/p>
##p>Here�s the deal: the world is over.  The old world, where things had to make sense to work, is long gone.  There is no �getting back to the basics�, or �restoring democracy�.  There�s no money to talk about, because the few rich people of the world have it all, and they don�t have any idea what to do with it.  We vote for fictional characters: Arnold Schwarzenegger, Donald Trump, Kevin O�Leary�all of them legends in their own minds, and none of whom is capable of doing a job normally reserved for real live humans.  Journalists who should be holding politicians to account care more about bus accidents than they do about preparations for warfare or economic subjugation, because their obsession with reporting the �human side� of politics makes amazingly extreme super-heroes out of fictional characters.  When it�s all about �feelings�, you can make any stupid shit up, and no one can do anything about it, because feelings must be validated, unless they come from white males, who have none.##/p>
##p>Now, you knew already that the world is over, didn�t you?  You may have a different version of the world being over, but we all know that it is; we just don�t agree on what to do after the grieving period, which there wouldn�t ever be anyway.  The world will reconstitute itself out of the glorious swirl of human confusion that governs our species, and the kids these days won�t know any better.  They will grow up in a culture with little respect for truth, little need for egalitarianism, no interest in democracy, and no coherent voices to raise their speakers to the level of social leadership.  It can�t happen, and there�s no going back.  It�s way easier these days to present evidence of historical paradigms evaporating, than it is of democratic reforms solidifying, and since there�s no money in it, voting seems quaint at best.  Who votes when you have Twitter?##/p>
##p>Aye, there�s the rub: we thought the digital revolution (ha!) would lead to some sort of sensible organization, a la Google�s drive to archive the world�s collective library for the sake of wisdom and knowledge.  There are too many good citizens doing good work to permit the lazy philosophers� blanket condemnations of all social graces � think of all the times some brilliant rebel has announced that all people suck � but good works have become islands in an ocean of rarefied bullshit.  A quick glance at any of the news-outlets we endure here in Toronto�s hegemony will assure you that not too many people in the public eye have any useful wisdom or knowledge to impart.  Our very own Toronto Sun, by way of poor example, is an enthusiastic cheerleader for the frat-boy faction of the conservadroid choo-choo; the CBC, once the safe-haven of truthseekers, has devolved into an endless infomercial for the Outrage Industry, suffocating fair debate with liberal floods of maple syrup.##/p>
##p>Perhaps journalists have forgotten this: feelings do not balance the budget, or shoot immigrants in the leg whenever our leaders find it convenient.  Feelings lead to other feelings, but they don�t mean anything at all in the greater world if they affect nothing but the CBC�s budget.  I, quite frankly, don�t care how grateful you are that God cured your cancer while 900 refugees were drowning ten minutes from safety.  I don�t care that you feel unhappy because the rest of the world isn�t like you.  I don�t owe anyone in our former democracy any more respect than I receive from them, and I�m not a �men�, or �white�, or �cis�.  Those are insults, not politics.  I�m a man; that is not plural, and I�m not answerable for chromosomes, colours, or choice of sex-organs.##/p>
##p>But it�s not just the journalists who have created this mess.  I�m mad at them for abrogating their duty to tell the truth, in favour of ice cream and Timmy falling down the well again.  They�re not, on the whole, responsible for the kind of wholesale lying that politicians accept on our behalf; they just don�t do anything about it.  It�s the politicians.  The politicians did this to us, and you know what?  We seem to like it, and we keep paying them, even when they do nothing of value at all.  How does that work in a pretend place called reality?##/p>
##p>It doesn�t work.  Politics doesn�t work, governance doesn�t work, economics doesn�t work; they�re all based on a form of wishful thinking preferred by the powerful, and they all fail because the powerful aren�t as smart as they think.  Democracy is dead; it just won�t fall down, and anyone who is still planning for an improvement in the situation will wait forever.  Democracy died the day humans discovered the internet.##/p>
##p>When everybody has access to the media which formerly supported �truth�, at least in policy, then everyone is an expert.  Everyone can write their own �how to be a better human� how-tos.  Everyone can be a �political insider�.  You can take courses on �how to be an expert on TV�; kits are available.  Everybody is a genius, everyone knows best, everyone has the right idea�all of which indicates that, in reality, no one is a genius, no one knows best, no one has the right idea, and no one actually cares.  Truth is not the issue. �Likes� is the issue.##/p>
##p>When selfie-culture overruns participatory democracy, as it has � and don�t even argue with me � you have an entire social construct of billions of humans and pets who come to the political discussion the way they come to a party, or a hockey game.  Football is too boring for Canadians.  They show up to the Party, thinking they�re coming to a party.  They�re chock-full of self-esteem � way more self-esteem than any teenager is entitled to.  Self-esteem has become both a cause and a symptom of the obsessive pursuit of self-esteem: self wants more self, and then more.  Children who are taught that they�re more deserving than others, but don�t need to actually ##em>do anything##/em> to earn �specialness� feel entitled to have things their own way, and that they deserve their specialness in spite of the fact that they don�t do anything of value to anyone, and that includes themselves most of the time.##/p>
##p>Hip-hop: singing about me.  Rap: talking about me.  Education: enhancing my self-esteem.  TV: telling me how great I am a hundred times a day. Selfie-culture destroys every democratic institution it comes to, because democracy is based on the desire to be equal under the law.  No one equals me � I�m special � so who cares about democracy?  There is no social institution of any kind which is not undermined by obsessive self-promotion at the expense of collective responsibility.  None, by definition.  �Social� means �collectively�; obsessive self-promotion cannot be collective in nature�don�t argue with me, it�s what the word means.##/p>
##p>Who said that?  Who used the word �responsibility� around here?  Democratic civics is founded upon responsibility as much as it is upon rights, but when civics are replaced with odes to entitlement, responsibility doesn�t make the shortlist.  Selfies do not propagate collectively; they make all mens an island (no, it�s not a typo. The ##em>s##/em> is there on irony duty).##/p>
##p>So politics is about the selfie-politician, economics is about the selfie-financier, and the news is about the selfie-advocate.  That, ladies and gentlemen, is the death of democracy in a bathtub.  Selfie culture is incompatible with democracy, and the internet makes every selfie worth it.  Facebook, Twitter, Tumblr, whatever�they�re all constant reinforcements of the specialness of self. All 7.3 billion selves. At once.##/p>
##p>Forget about it.  It�s a done deal.  Don�t fix it, because it won�t be there ten minutes after it�s fixed.  There�s no cure for democracy�s illness, any more than there was a cure for the fall of the Roman Empire.  The paradigm is obsolete.  Deal with it.##/p>
##p>Or, ignore it and move on.  Let all the other idiots argue about how to dress up the corpse, while the few people who dare to read such blogs as this gather quietly in social backwaters to plan for reality, because it�s going to happen; reality is a bitch that way.  Let the perverts and carpetbaggers split up the booty; it�ll be useless to them anyway.  Plus, it�s traumatically boring, and I�ve had enough.  You probably have too.##/p>";
