<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Stop Being You.  Be Someone Else.##/h1>
##p>When I was less huge, we�d each receive a monthly magazine for Jewish kids.&nbsp; I think it was called �World Over�, or some such defiant sound-bite.&nbsp; It was full of wonderful reasons to be a happy Jew, instead of a miserable outcast Jew.&nbsp; It was a necessary and appropriate counter-measure to the Jew-baiting and casual racism of the schoolyard, and I have no problem with that.&nbsp; I encourage that.&nbsp; What I didn�t like was what I called �Jew-boosters�. That�s the name I gave the entirely-superfluous self-esteem support which every minority seems to use to flag itself in public. I was a Jewish kid, dealing with anti-Semitic silliness; that didn�t make me want to wear a fluorescent yarmulke (skull-cap) and burn a Star of David on the lawn at City Hall.##/p>
##p>Fighting anti-Semitism is normal and appropriate, even mandatory, to every Jew.&nbsp; Fighting homophobia is normal and appropriate to every gay.&nbsp; That�s what everyone, every human on earth, should be doing, regardless.&nbsp; Revolutionary actions shouldn�t be DNA-specific, or geographically-defined; they should support and uphold human rights, and anything else is an egregious waste of time and lives.&nbsp; Jews and gays had to fight to be considered equals; a few decades go by, and we all know it�s stupid, and only the lowest now-uncommon denominators care anymore. Judaism and homosexuality in my world are just normal, boring things, and only need to be �fought for� until everyone, both slaves and overseers, agrees that the conflict is more useless than Kim Kardashian.&nbsp; If I, as a Jew, had to jump out of my seat at every political gathering to yell, �I�m a Jew and I want to be equal�, then it would be manifestly obvious that I�m NOT equal yet.&nbsp; It�s when you no longer need to announce your origins that you know you are in, you�re part of the normal world.&nbsp; If no one at the political gathering cares, and I keep shouting anyway, I�m just an idiot.&nbsp; You know�sound and fury and all that..##/p>
##p>Jews should be normal.&nbsp; Gays should be normal.&nbsp; Blacks should be normal, and have a name that is not a pigment.&nbsp; You can tell we�re not yet normal, meaning a normalized presence within chosen social strata, if we still have to talk about what we are, not what we do in the world.&nbsp; It�s not something that can be rushed; normalization is an agonizingly slow process, with prerequisits, and pushing premature normalization can do nothing but interfere with progress.&nbsp; Jews had to go through the �I�m a Jew, go fuck yourself if you don�t like it� stage, because people really did have to learn to go fuck themselves when they don�t like Jews.&nbsp; People who don�t care about Jewishness don�t need to go fuck themselves. They already did that. Jews struggled for an age and an eon, and then, to joyous surpise, they let us in. They opened the door, and invited us to dinner.&nbsp; Who saw that coming? They deserve a made-in-Canada gold medal and a kiss on the cheek from the movie star of their choice.##/p>
##p>The insiders didn�t need to invite the outsiders in; they can�t erase us, but they could easily have continued to marginalize us as long as they chose.&nbsp; Powerful people have power; powerless people have to change the minds the powerful with words and appeals to empathy alone. That�s what Jews have done: they have slowly been integrated into �normal�, after centuries of words and appealing to empathy.&nbsp; It helped that our little, fiercely unassimilable subculture suffered the greatest cultural catastrophe in history, making it impossible to for the powerful to close their eyes.&nbsp; The price was too high, but it was the soul-shocking display of the human cost of empire-building and the misery it creates amongst the weak and innocent that ensured that the world was hugely changed by it. The powerful chose to liberate us and protect us, because they saw what the powerful so often do to the poor and weak, and it touched them. It reminded them of humanity.&nbsp; It burned a hole in their hearts that caused them pain, and they learned empathy for us because of it.&nbsp; You need to have been hurt, to feel the hurt of others; the rich are as human as the poor, and they did feel it.&nbsp; They got it. They didn�t have to change; they chose to, and started a new civil war within their own ranks that cost them greatly too. They gambled big on us. They took a big chance on one future over another. You don�t get to keep hating them.##/p>
##p>The disadvantaged have no more reason to be unkind and rude than anyone else; bad manners are the single greatest impediment to tolerance and equality in the human condition. You don�t insult the king to convince him to free the slaves. You say please and thank you, and the more risk the king takes, the more generous you become in your pleases and thank-yous: you thank your allies. You thank them, you celebrate your freedom WITH them, you take your place as a peer of the realm, and you remain appropriately grateful all your days. The next generations require that of you.##/p>
##p>That is the root of civility, and civility, in case you haven�t noticed, is the root of civilization. Why would I need to be presumptuous and unkind at the expense of the people who just ##em>talked all of their friends into giving in to my demands, at their own manifest risk##/em>?&nbsp; If they made the effort to stop caring about my Jewishness in a world that tries to make sure they do care, then they�re entitled to gratitude; they didn�t have to do it, but they did it, and if they did it for all, then they did it for me. I won�t have my comrades pissing on the shoes of the people who liberated my sorry ass. Insulting the converted will change them right back, and it ends badly for everyone.##/p>
##p>You already knew this.##/p>";
