<?php

namespace raingarden\rg_content\rg_posts;

$the_html = "##h1>Who�s in charge here, and why isn�t it you?##/h1>
##p>I�m sure there are feminists who will hate me one day, because they don�t understand me, or they misread me, or, hmm, they have a real reason�whatever. The percentage of feminists who hate me will probably, after all demographics are accounted for, be a tiny bit more than the standard deviation.  That�s the science way of saying feminists as a whole are no more bigoted or discriminatory than any other ground of people, or have worse diplomatic skills. They aren�t likely to be smarter, dumber, more fair, less fair�from space, hundreds of millions of people look no different from other hundreds of millions of people.##/p>
##p>I�m sure there are feminists who will hate me one day, but then, I�m exactly equally sure that there are men�s groups who will hate me, and that neither group of haters is statistically meaningful. So why do the two sides in the �Gender Wars� get more headlines than the average real-blood-and-widows war does?  If you actually distill the philosophies of the traditionalists and the feminists, the list of demands you�re left with, the things each side wants changed in order to end the war, are laughable on one hand, and eugenics on the other. We�re letting people who want to own the moon lead our negotiating teams, speak publicly for us, and commit us all to a war that�s already long-dead and boring. Don�t take my word for it, though. There�s nothing I say that can�t be checked with a search query.##/p>
##p>Why would anyone care what the outliers on either side think? Why do I care?##/p>
##p>I shouldn�t have to, but I do. I care because the extremists in both camps claim to represent all the rest of us, and that the anger and hate they spew endlessly is on all our behalves. Nobody cares anymore whether feminist theory is valid; we are not haters.  We don�t hate, and we don�t want to hate, and we will not be represented by haters, that�s it, end-of-story.  Nobody cares whether extremists of all stripes are trying to abrogate human rights for their own purposes. Right and wrong were lost in the fog and din of this war a long time ago, and now it�s just the bloody Somme*, a barren killing ground between two deeply-entrenched armies run by pompous and incompetent generals who only got their jobs because there was no one qualified.##/p>
##p>If that�s how it is, it behooves me to cease to use �feminist� as a pejorative.  Okay, I�m stopping, I was letting petulance rule my judgment.  Now, you, extreme-feminist-person, please stop hiding behind �feminism� and �women� to take your cheap shots. You want a fair fight, step out into the light.  Your bluff is called. My gauntlet is thrown. Make it real, or make it go away.##/p>
##p>The degree to which ownership of the language is enforced is a fair measure of the oppressive tendencies of a movement   When one side or another claims words or phrases as their own, and begins using that ownership as a means of diverting or ending possible discussion of its subject, it is no longer on the side of the angels. It has given in to the pressure of internal corruption; the generals who now run the Women�s Revolution are not doing it for the Women, they�re doing it for the Revolution, and nobody knows anymore what the hell they�re talking about. We just know it�s all good for them, but it leaves the rest of us hating each other forever. Optics are everything in a war over nothing.##/p>
##p>If we�re arguing about real life, don�t defend the theory to me; defend the optics if you can.  If you can�t, then you may already ruined the whole war for the rest of us. It doesn�t matter whether any of the words are real or not; if we can�t discuss them, we can�t use them in other discussions. The power of a twisted word dwindles with every manipulation. If the words don�t mean anything, how interesting could they be?##/p>
##p>Objectification, rape, society, patriarchy, harassment, oppression, culture, masculinity, femininity, gender, victim, rights, sex, freedom, identity, feminist, minority, man�woman��equality���.##/p>
##p>Those are keywords, power words which started out with Oxford definitions; standard meanings we could all look up in the same place. I�m an academic insider, and a potential candidate linguist, and I still don�t know what people mean now when they use these words. What does �man� mean now, after decades of hostile deconstruction? Why do people laugh when I say �I�m a man�? When did �sexual harassment� come to include �unwanted conversation�? Those words have been hijacked, stolen by agenda-driven word-pirates from all the Seven Seas, to be deconstructed and refashioned as weapons. Whether any of those words means anything is now impossible to even discuss; we can�t even find a way to ask for a debate without the above becoming missiles aimed at our minds. Doesn�t that scare you, that now there�s no way to distinguish between objectification and oppression, or between identity and minority, or between woman and victim, or between society and rape?  There�s no longer even a way to fairly compare man and woman without causing trouble. That�s entirely and absolutely the inevitable result of allowing minority sectors to own words which are common property. I�m a minority sector, too, so take that, Oversensitive Minority Man!.##/p>
##p>Men are no more stupid than women. Yeah, yeah, you know we can hear you, right? Hrmph.  We can see a shell game better than you can, you know that�women are accusing us of playing games like that all the time; wouldn�t we know when someone�s cheating? We know when women are lying with the same degree of accuracy that women enjoy while winning every argument since the invention of hormones (Woohoo, losing arguments!).  The game is rigged, the judge has been bribed, the seats and the table are reserved for people who don�t like us, and, really�you know�we actually wouldn�t have much of a problem with that. If things get done, that is. There�s no surer way to peace than doing what your wife says. Everyone knows that. What applies to one is largely applicable to all, sort of.##/p>
##p>As I�ve said before, women are the conscience of the world. Every human being may transcend any inherited role at any time; don�t make me keep repeating that � it�s a given. In macro-scale human terms, though, the evolved relationship between men and women is ##em>meant##/em> to give power to the women.  Here�s the delightful sorry fact, my brothers; those females, the friendly-looking ones you love to grouse about when they have no spies nearby: they really ARE allowed to tell us what to do�because they probably DO know, god damn it all to hell, and we�re not completely sure we know better. They can�t do their own plumbing to save the world, but they do know better than we do what�s stupid and what isn�t.  Look what happens when large groups of men are left to themselves to make lunch: [[ insert faded photo of mushroom cloud over Bikini Atoll ]]. The point of having women tell us what to do is that we won�t blow up the fucking world. Besides, you know they�ll just keep telling you.##/p>
##p>Nature could not have produced a species so successfully fecund that it is capable of ruining the planet, if there were not an evolved counterbalance to bully-power. A species run entirely top-down by bullies has the same long-term survival probability as a Ponzi scheme: the alphas bully the betas bully the deltas bully the gammas, right to the bottom of the barrel�where they discover that there is no one left to bully. The gammas, the men at the bottom, suddenly hold all the cards. The event-chain is reversed, and the now-very-numerous bullies at the bottom begin looting, murdering, and pillaging their way back up the food-chain. That�s just math: supply, distribution, carrying capacity, lunacy, etc.##/p>
##p>Now, try to see how women can possibly fit into a system in which the males engage in periodic races to suicide, over power, status, or you know. Women are the first thing to go: they serve as units of exchange, negotiable assets, slaves, hostages, bribes�you name it. This is what �objectification� really means, not the casual abuse of the word we hear constantly.  In a bully-power econosystem (it�s a word now), women are chattel, and chattel who don�t have time or resources for babies and children are expendable. The pool of available women crashes. The pool of lonely, heavily-armed idiots overflows. Crash, sploosh, kaput, dig?  End-of-speculation. Bully-power is short-game only. Without adequate female overlordship in the training and guidance of the human species, the wheels stay on the bus, and the bus drives off a cliff.  But it�s a bus with wheels, yo.  Real. Wheels. Yo.##/p>
##p>So whether it fits the chapter and verse of the Bonehead Bible or not, women are, evolutionarily-speaking, ordained to be both the conscience and the compass of the tribe; that gives them veto power over matters of conscience, and veto powers over matters of development; in a forward-looking culture, they�re supposed to be driving the bus. It�s not subtle, but you have to zoom way out to see it; the complex interactive traits governing gender relations evolved long before the language we describe it with; they are almost too normal to notice, like breathing. If you look carefully, you may notice that the world is still not blown to smithereens, even after six decades of existential risk-taking; you may further notice that the waning of the global nuclear threat is in tidy inverse correlation to the participation of women in the guidance systems of human civilization. Please, read that twice.##/p>
##p>Women direct tribal evolution, the social direction, the owners of the future; they know it, we know it, and all the violence and repression in the world will not beat it out of them. The human dynamic is not meant to be a power-differential; it�s meant to be a power-distribution.  It is gender-specific, but not gender-assigned; you have the power, Luke. No one�s forcing you to use it. I, speaking only for myself, can�t wait to watch women do all the work, because I�m buying a snowmobile.##/p>
##p>But just think, Great Female Spirit, what you could do for the world if you gratefully accepted the protection of men, so bully-power and violence need be intractable problems no longer, and yet retained all the powers women are meant to have. Already have. C�mon, socially-perceptive female human people! Aren�t you seeing this?##/p>
##p>Please. We�re beggin. Take the deal; it leaves you in charge. You can run the show now. Yeah, that�s right, sucker�see how you like it, Ms. Tough Guy. I�m not waiting until winter to try out my new snowmobile.##/p>";
