<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Cmajor Aminor Fmajor Gmajor##/h2>##/li>
		##li class='poem line'>C Amin F G##/li>
		##li class='poem line'>(doo doo wop, doo doo wop, ooby dooby wah)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is the verse##/li>
		##li class='poem line'>a tonic chord change, with a minor tossed in##/li>
		##li class='poem line'>a fourth to build, a fifth to release##/li>
		##li class='poem line'>it's all about her##/li>
		##li class='poem line'>always about her##/li>
		##li class='poem line'>perhaps we love her, perhaps I do##/li>
		##li class='poem line'>she is the star##/li>
		##li class='poem line'>the light in my sky##/li>
		##li class='poem line'>I Must Have Her.##/li>
		##li class='poem line'>the tune is simple here##/li>
		##li class='poem line'>no hooks, or ornaments##/li>
		##li class='poem line'>I want it to build##/li>
		##li class='poem line'>slowly, steadily##/li>
		##li class='poem line'>almost frustratingly##/li>
		##li class='poem line'>(C a F G)##/li>
		##li class='poem line'>but wait for it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>B minor##/li>
		##li class='poem line'>the bridge, the pre-chorus##/li>
		##li class='poem line'>the tension increases, a hint of warning##/li>
		##li class='poem line'>a touch of the sad##/li>
		##li class='poem line'>give us what we want, you say,##/li>
		##li class='poem line'>but no, not yet##/li>
		##li class='poem line'>it's still about her, but it is asking, not telling##/li>
		##li class='poem line'>E minor##/li>
		##li class='poem line'>darkness descends##/li>
		##li class='poem line'>you wanted the release,##/li>
		##li class='poem line'>but what you get is a vampire's kiss##/li>
		##li class='poem line'>now you are hungry, hurried.##/li>
		##li class='poem line'>Me, you say, me##/li>
		##li class='poem line'>when, you ask?##/li>
		##li class='poem line'>wait for it, wait for it...##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>C Amin F G##/li>
		##li class='poem line'>The Hook!##/li>
		##li class='poem line'>sweet release##/li>
		##li class='poem line'>the tonic returns, the chords are restored##/li>
		##li class='poem line'>clouds part, the sun reigns##/li>
		##li class='poem line'>perhaps an octave higher##/li>
		##li class='poem line'>a counterpoint holds court##/li>
		##li class='poem line'>a bassline...dum da dum dum##/li>
		##li class='poem line'>a happy, sleepy man, with a small gift##/li>
		##li class='poem line'>she is mine, she is yours##/li>
		##li class='poem line'>she is love incarnate##/li>
		##li class='poem line'>doo doo wop, doo doo wop, ooby dooby wah##/li>
		##li class='poem line'>my lips turn up at the corners,##/li>
		##li class='poem line'>even as the roots of the chords##/li>
		##li class='poem line'>escape my involuntary mouth##/li>
		##li class='poem line'>she is in love! I am in love!##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the octave drops away##/li>
		##li class='poem line'>the chords remain, but calm is restored##/li>
		##li class='poem line'>dum dum ditty dum dum##/li>
		##li class='poem line'>this is the second verse##/li>
		##li class='poem line'>more of the same##/li>
		##li class='poem line'>she is loving me, but may be##/li>
		##li class='poem line'>she is leaving me, what can I do?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the minor again, we fall into an abyss##/li>
		##li class='poem line'>the second minor, the sky darkens above us##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>The Chorus!##/li>
		##li class='poem line'>how could we live without it?##/li>
		##li class='poem line'>the cycle is complete##/li>
		##li class='poem line'>again, and we are already addicted##/li>
		##li class='poem line'>so we withdraw a step##/li>
		##li class='poem line'>the vocal stops, the guitar takes the melody##/li>
		##li class='poem line'>we are left to fill in the words on our own##/li>
		##li class='poem line'>8 bars of imagination, with a solo as a guide##/li>
		##li class='poem line'>this is our own love now, we need no prompting##/li>
		##li class='poem line'>but like an addict seeing a needle##/li>
		##li class='poem line'>we ache for fulfillment##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>and finally, a last verse##/li>
		##li class='poem line'>the resolution, the end of the story##/li>
		##li class='poem line'>she does love me, she does!##/li>
		##li class='poem line'>and my life is good##/li>
		##li class='poem line'>this time the minor is good to us##/li>
		##li class='poem line'>there is no sense of loss, we know##/li>
		##li class='poem line'>the chorus is coming##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>here it is!##/li>
		##li class='poem line'>sweet light! sweet saviour!##/li>
		##li class='poem line'>we are yours, my love##/li>
		##li class='poem line'>you are mine, my love##/li>
		##li class='poem line'>and we will repeat this,##/li>
		##li class='poem line'>our holy refrain##/li>
		##li class='poem line'>until we fade away.##/li>
	##/ul>
##/article>";