<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Agony##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the words in the poem##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a poem contains (is) words##/li>
		##li class='poem line'>among those words are keywords##/li>
		##li class='poem line'>these are special words that sport a richness of meaning##/li>
		##li class='poem line'>this poem contains such##/li>
		##li class='poem line'>so far, it contains at least three:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>poem, keyword, meaning##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the choice of keywords is meaningful##/li>
		##li class='poem line'>witness:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>soul##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now this poem contains at least four keywords##/li>
		##li class='poem line'>(not really)##/li>
		##li class='poem line'>soul, here, is a lost lamb, devoid of useful meaning##/li>
		##li class='poem line'>it has many potential meanings inherent to it##/li>
		##li class='poem line'>but here we gain nothing##/li>
		##li class='poem line'>other than that it is now a keyword##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this poem has soul##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now soul means something##/li>
		##li class='poem line'>its use has been defined##/li>
		##li class='poem line'>this poem now has soul##/li>
		##li class='poem line'>we place two keywords together here##/li>
		##li class='poem line'>and newness erupts##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in fact##/li>
		##li class='poem line'>this poem is cold##/li>
		##li class='poem line'>and arguably ain't got soul##/li>
		##li class='poem line'>but hola!##/li>
		##li class='poem line'>cold and soul are not mutually exclusive keywords##/li>
		##li class='poem line'>although they carry this baggage##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>poets often shy away from keywords##/li>
		##li class='poem line'>they are too easy##/li>
		##li class='poem line'>they don't wish to say soul when speaking of soul##/li>
		##li class='poem line'>use custom metaphors##/li>
		##li class='poem line'>this may or may not be a good idea.##/li>
		##li class='poem line'>desirous of lending meaning to a poem##/li>
		##li class='poem line'>they may so obscure the intended meaning##/li>
		##li class='poem line'>as to lose all meaning##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>speaking personally:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am not afraid of keywords##/li>
		##li class='poem line'>if they describe my idea##/li>
		##li class='poem line'>i use them##/li>
		##li class='poem line'>i am not in competition with other poets##/li>
		##li class='poem line'>sometimes a leaf is a leaf##/li>
		##li class='poem line'>not the withered detritus of october's fate##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this does not mean i object to metaphor, simile, analogy, obfuscation, tangents, obliques##/li>
		##li class='poem line'>or other stuff##/li>
		##li class='poem line'>i attempt to use them only if they illuminate meaning##/li>
		##li class='poem line'>or add depth##/li>
		##li class='poem line'>or layer ideas##/li>
		##li class='poem line'>or i feel like it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this poem about keywords##/li>
		##li class='poem line'>is now full of keywords##/li>
		##li class='poem line'>this is now a keyword ( i made it so, ##/li>
		##li class='poem line'>try and stop me )##/li>
		##li class='poem line'>as i use this##/li>
		##li class='poem line'>in this series of poems##/li>
		##li class='poem line'>The Deconstructionist's Series of Poems##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>headache is a keyword##/li>
		##li class='poem line'>life is a keyword##/li>
		##li class='poem line'>together they are suspicious##/li>
		##li class='poem line'>Life is a headache.##/li>
		##li class='poem line'>but life is not a headache##/li>
		##li class='poem line'>not is the keyword##/li>
		##li class='poem line'>the keyword is not##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i have a headache##/li>
		##li class='poem line'>such is life##/li>
	##/ul>
##/article>";