<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Lament##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the demise of poetry##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>as noted before##/li>
		##li class='poem line'>(sue me if you don't like it)##/li>
		##li class='poem line'>there are seven fundamental arts:##/li>
		##li class='poem line'>cooking##/li>
		##li class='poem line'>music##/li>
		##li class='poem line'>dance##/li>
		##li class='poem line'>2d visual##/li>
		##li class='poem line'>3d visual##/li>
		##li class='poem line'>acting##/li>
		##li class='poem line'>	and##/li>
		##li class='poem line'>the spoken word##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>of these##/li>
		##li class='poem line'>only two are not a luxury:##/li>
		##li class='poem line'>cooking##/li>
		##li class='poem line'>	and##/li>
		##li class='poem line'>the spoken word##/li>
		##li class='poem line'>all the others##/li>
		##li class='poem line'>are done only for purposes##/li>
		##li class='poem line'>beyond the needs of the belly##/li>
		##li class='poem line'>for this reason##/li>
		##li class='poem line'>cooking and the spoken word##/li>
		##li class='poem line'>are not pure##/li>
		##li class='poem line'>they are one with the science of survival##/li>
		##li class='poem line'>go ahead poets, choke on it if you must##/li>
		##li class='poem line'>your art is not the virginal white of music##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>cooking is even less pure than speech art##/li>
		##li class='poem line'>it is a long road from burning your meat##/li>
		##li class='poem line'>to the saffron bliss##/li>
		##li class='poem line'>take heart poets##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>specifically:##/li>
		##li class='poem line'>speech allows:##/li>
		##li class='poem line'>hunting##/li>
		##li class='poem line'>gathering##/li>
		##li class='poem line'>defence##/li>
		##li class='poem line'>war##/li>
		##li class='poem line'>history##/li>
		##li class='poem line'>cohesion##/li>
		##li class='poem line'>safety##/li>
		##li class='poem line'>	and##/li>
		##li class='poem line'>whispers of love##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>these are the stones##/li>
		##li class='poem line'>upon which are laid the foundations##/li>
		##li class='poem line'>of humanity's humanity##/li>
		##li class='poem line'>upon these are stood##/li>
		##li class='poem line'>the pillars of society:##/li>
		##li class='poem line'>magic, science, politics and art##/li>
		##li class='poem line'>and none of these##/li>
		##li class='poem line'>can be divorced from speech##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is only through the trick of speech##/li>
		##li class='poem line'>that there is room for the luxury of dance##/li>
		##li class='poem line'>speech is therefore the most fundamental##/li>
		##li class='poem line'>of the fundamental arts##/li>
		##li class='poem line'>you may speak of the dance##/li>
		##li class='poem line'>it is hard to dance of the speech##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when speech became advanced enough##/li>
		##li class='poem line'>to allow the luxuries of the pure arts##/li>
		##li class='poem line'>it also allowed the luxury of the spoken art##/li>
		##li class='poem line'>storytelling was the first##/li>
		##li class='poem line'>the TV of the prehistoric world##/li>
		##li class='poem line'>the bridge between entertainment and the spiritual##/li>
		##li class='poem line'>with the development of vocabulary##/li>
		##li class='poem line'>came the beginnings of poetry##/li>
		##li class='poem line'>the creation of speech##/li>
		##li class='poem line'>with aesthetics in mind##/li>
		##li class='poem line'>and history began##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>10 000 years later##/li>
		##li class='poem line'>and we are all as dependent on speech##/li>
		##li class='poem line'>as ever our species was##/li>
		##li class='poem line'>those of us who do not speak##/li>
		##li class='poem line'>are pitied##/li>
		##li class='poem line'>speech is the norm, in a thousand thousand variants##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so why is poetry dying?##/li>
		##li class='poem line'>the answer will surprise you:##/li>
		##li class='poem line'>freedom##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>early poetry##/li>
		##li class='poem line'>was full of rules##/li>
		##li class='poem line'>this had to be this way##/li>
		##li class='poem line'>that had to be that way##/li>
		##li class='poem line'>so many lines##/li>
		##li class='poem line'>so many alliterations##/li>
		##li class='poem line'>one rhyme here##/li>
		##li class='poem line'>another there##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>while great poetry was written##/li>
		##li class='poem line'>following these rules##/li>
		##li class='poem line'>poets gradually came to dislike them##/li>
		##li class='poem line'>even while venerating their proponents##/li>
		##li class='poem line'>the necessity of rhyme##/li>
		##li class='poem line'>dictated what could be said##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>gradually the rules were weakened##/li>
		##li class='poem line'>sometime around 1900##/li>
		##li class='poem line'>some poets finally decided##/li>
		##li class='poem line'>to throw all the rules out the window##/li>
		##li class='poem line'>even the use of real words##/li>
		##li class='poem line'>was no longer necessary##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it didn't last long##/li>
		##li class='poem line'>when poetry is indistinguishable##/li>
		##li class='poem line'>from speaking in tongues##/li>
		##li class='poem line'>the audiences farts and leaves##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but even when poets chose to apply rules##/li>
		##li class='poem line'>there were no rules that said they had to##/li>
		##li class='poem line'>the art of speech was purified##/li>
		##li class='poem line'>each word, each line, each verse##/li>
		##li class='poem line'>was dictated by need##/li>
		##li class='poem line'>(that is the##/li>
		##li class='poem line'>theory, any##/li>
		##li class='poem line'>way)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i use no rhymes, most of the times##/li>
		##li class='poem line'>i      change      my      line      lengths##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i change my verse lengths##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i do what my inner voice demands##/li>
		##li class='poem line'>in order to become my outer voice##/li>
		##li class='poem line'>my only rule is that things must flow like water##/li>
		##li class='poem line'>except when they don't##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>paradoxically, all this freedom##/li>
		##li class='poem line'>has led to an obsession with form##/li>
		##li class='poem line'>at the expense of meaning##/li>
		##li class='poem line'>when poets are free to experiment##/li>
		##li class='poem line'>the experiment becomes more important##/li>
		##li class='poem line'>than the reader##/li>
		##li class='poem line'>freedom from rules##/li>
		##li class='poem line'>has lead to freedom from an audience##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>everyone speaks##/li>
		##li class='poem line'>when poetry follows too closely##/li>
		##li class='poem line'>the conversational tone##/li>
		##li class='poem line'>then everyone is a poet##/li>
		##li class='poem line'>in order to distinguish oneself from everyone##/li>
		##li class='poem line'>poets play games, indulge their egos##/li>
		##li class='poem line'>congratulate themselves on their cleverness##/li>
		##li class='poem line'>because no one else will##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>poetry is not meant##/li>
		##li class='poem line'>to be a ghetto##/li>
		##li class='poem line'>it is meant##/li>
		##li class='poem line'>to be the most fundamental##/li>
		##li class='poem line'>of the seven fundamental arts##/li>
		##li class='poem line'>it is meant to be of import##/li>
		##li class='poem line'>to all who speak##/li>
		##li class='poem line'>the greatest sadness of all##/li>
		##li class='poem line'>is that it is poets##/li>
		##li class='poem line'>who have written##/li>
		##li class='poem line'>the death of poetry##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>finally, i must point out##/li>
		##li class='poem line'>that this poem is conversational in tone##/li>
		##li class='poem line'>that it follows no rules##/li>
		##li class='poem line'>that it is aimed at the ghetto ##/li>
		##li class='poem line'>and that i wish to be seen as clever##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in short, it is guilty##/li>
		##li class='poem line'>and i am guilty##/li>
		##li class='poem line'>of all that i bemoan##/li>
		##li class='poem line'>in my own defence##/li>
		##li class='poem line'>i will say only##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the demise of poetry##/li>
	##/ul>
##/article>";