<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Trial##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about why everybody hates poetry##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>100 000 years ago##/li>
		##li class='poem line'>when smelly people ruled the earth##/li>
		##li class='poem line'>the height of entertainment was farting and telling stories by the fire##/li>
		##li class='poem line'>today, this is still entertainment##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>in its day, the fireside gathering##/li>
		##li class='poem line'>which could include music, dancing, jokes, and all manner of low-tech amusement##/li>
		##li class='poem line'>was the ultimate in immersive technology##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>eventually##/li>
		##li class='poem line'>entertainment became codified##/li>
		##li class='poem line'>jokes became theatre##/li>
		##li class='poem line'>storytelling became acting##/li>
		##li class='poem line'>dancing became communal ritual##/li>
		##li class='poem line'>these became the ultimate in immersive technology##/li>
		##li class='poem line'> ##/li>
		##li class='poem line'>as poetry developed##/li>
		##li class='poem line'>it became immersive technology##/li>
		##li class='poem line'>stories in poetic form##/li>
		##li class='poem line'>went on for days##/li>
		##li class='poem line'>the minds/brains of the audience##/li>
		##li class='poem line'>delighting in immersion##/li>
		##li class='poem line'>built pathways of receptivity##/li>
		##li class='poem line'>learned to absorb rhythm and meter##/li>
		##li class='poem line'>they were trained to poetry from an early age##/li>
		##li class='poem line'>participating in immersive technology was the order of the day##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>sadly##/li>
		##li class='poem line'>we have so much immersive technology##/li>
		##li class='poem line'>that our immersive technology receptors##/li>
		##li class='poem line'>require immense amounts of stimulation##/li>
		##li class='poem line'>we are addicted to such stimulation##/li>
		##li class='poem line'>and like any addiction##/li>
		##li class='poem line'>more more more is the order of the day##/li>
		##li class='poem line'>poetry is no longer a viable immersive technology##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there will always be people##/li>
		##li class='poem line'>who prefer the scalpel to the sledgehammer##/li>
		##li class='poem line'>poetry can still be a scalpel##/li>
		##li class='poem line'>but we are few##/li>
		##li class='poem line'>and even those of us who love poetry##/li>
		##li class='poem line'>would rather write it than read it##/li>
		##li class='poem line'>this is because the act of writing##/li>
		##li class='poem line'>is a more immersive technology##/li>
		##li class='poem line'>than the act of reading##/li>
		##li class='poem line'>our brains simply are not set up anymore##/li>
		##li class='poem line'>to focus on the narrow##/li>
		##li class='poem line'>Ritalin for all!##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>trying to focus on poetry##/li>
		##li class='poem line'>for most people##/li>
		##li class='poem line'>is a matter of having to turn off##/li>
		##li class='poem line'>tv##/li>
		##li class='poem line'>from inside their minds##/li>
		##li class='poem line'>we humans have been redesigned by tv##/li>
		##li class='poem line'>movies, radio, temples, theatre, music##/li>
		##li class='poem line'>all these forms of psychology are far more immersive##/li>
		##li class='poem line'>than any poem##/li>
		##li class='poem line'>no matter how good it is##/li>
		##li class='poem line'>can ever be##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is not to say that important things cannot be said##/li>
		##li class='poem line'>in poetic form##/li>
		##li class='poem line'>but it is to say##/li>
		##li class='poem line'>that unless poets find a way to make poetry##/li>
		##li class='poem line'>into immersive technology again##/li>
		##li class='poem line'>then poetry will continue to suffer the dilapidation of modernity##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>oddly##/li>
		##li class='poem line'>poets must take their cue##/li>
		##li class='poem line'>from the worst poets in the world##/li>
		##li class='poem line'>shallow egotists yelling about their penises##/li>
		##li class='poem line'>to a machinelike beat too slow to motivate##/li>
		##li class='poem line'>the most successful poets in history##/li>
		##li class='poem line'>are some of the least literate in history##/li>
		##li class='poem line'>this is called irony##/li>
		##li class='poem line'>i am not a big fan of irony##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this series of deconstructions##/li>
		##li class='poem line'>is not aimed at a general audience##/li>
		##li class='poem line'>it is aimed at poets and writers and lovers of poetry##/li>
		##li class='poem line'>you are a rare breed, and perhaps idiots##/li>
		##li class='poem line'>in a city of five million people, it is hard##/li>
		##li class='poem line'>to get 100 together to hear poetry##/li>
	##/ul>
##/article>";