<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The deconstructionist's shame##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the difficulty of being a poet##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this was supposed to be an erotic poem##/li>
		##li class='poem line'>it may still be, sort of somewhat##/li>
		##li class='poem line'>but mainly, this is a test of my ability to write proudly##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i'm sitting in my usual coffeeshop##/li>
		##li class='poem line'>in a high-traffic area##/li>
		##li class='poem line'>surrounded by other customers,##/li>
		##li class='poem line'>sitting, walking, standing at the magazine shelves##/li>
		##li class='poem line'>almost any one of them could be reading over my shoulder##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>with this in mind, i have decided##/li>
		##li class='poem line'>to write a poem that will be both honest and shocking##/li>
		##li class='poem line'>the poem will serve as a metaphor for the greater question:##/li>
		##li class='poem line'>why would anyone want to advertise himself as a poet##/li>
		##li class='poem line'>in a world which has no respect for poets?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is very hard to offend##/li>
		##li class='poem line'>simply writing scatologically won't do it##/li>
		##li class='poem line'>everyone has heard every dirty word a hundred thousand times##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>therefore, in order to be shocking##/li>
		##li class='poem line'>i must remove the merely scatological##/li>
		##li class='poem line'>and replace it with the embarrassingly personal##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i just did a quick shoulder check##/li>
		##li class='poem line'>i couldn't help it##/li>
		##li class='poem line'>it seems no one is reading my screen right now##/li>
		##li class='poem line'>time to plunge in##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is an element of braggadocio##/li>
		##li class='poem line'>in writing about sex##/li>
		##li class='poem line'>it is good to be known as a sexual person##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is no element of pride, however##/li>
		##li class='poem line'>in what this poem is about##/li>
		##li class='poem line'>i wish to write about masturbation##/li>
		##li class='poem line'>specifically, mine##/li>
		##li class='poem line'>i wish to poeticize about masturbation##/li>
		##li class='poem line'>as i cannot masturbate about poetry for you##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>many poets will say they write personally, for themselves##/li>
		##li class='poem line'>those of them who aren't lying are making a case for poetic masturbation##/li>
		##li class='poem line'>i don't write for myself##/li>
		##li class='poem line'>i write to impress you, to change you, to entertain you##/li>
		##li class='poem line'>and to garner the ego-enhancement that comes with success##/li>
		##li class='poem line'>my poetry is sex##/li>
		##li class='poem line'>and you are my girl, get used to it, it doesn't stop there##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>next, in my own defence, i will announce loudly##/li>
		##li class='poem line'>That I Have A Beautiful Female Partner Whom I Love##/li>
		##li class='poem line'>And Our Sex Is Laudable.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>however, she lives apart from me##/li>
		##li class='poem line'>and in order to meet my daily physical urges##/li>
		##li class='poem line'>i resort to self-satisfaction when my love is absent##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>she knows this and encourages it##/li>
		##li class='poem line'>but for some reason, it continues to embarrass me on occasion##/li>
		##li class='poem line'>perhaps i'm a bit of a prude##/li>
		##li class='poem line'>admitting to masturbation is to admit to inadequacy##/li>
		##li class='poem line'>like admitting to poetry is to admit to not writing a novel##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>men don't want to be known as masturbators##/li>
		##li class='poem line'>nor do men don't want to be known as poets##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>my poetry is not masturbation##/li>
		##li class='poem line'>and my masturbation is not particularly poetic##/li>
		##li class='poem line'>it wouldn't be that interesting to watch##/li>
		##li class='poem line'>perhaps i make funny faces or sounds##/li>
		##li class='poem line'>i don't know, really##/li>
		##li class='poem line'>sometimes it goes on forever##/li>
		##li class='poem line'>linearly or in waves##/li>
		##li class='poem line'>other times i've barely gotten started when i'm finished##/li>
		##li class='poem line'>luckily, i don't have to apologize to myself for that##/li>
		##li class='poem line'>oddly, although i'm right-handed, i use my left hand more than my right##/li>
		##li class='poem line'>perhaps i'm leaving open the possibility of making notes##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is amusing/embarrassing for you, but don't get me wrong:##/li>
		##li class='poem line'>i love it, i need it##/li>
		##li class='poem line'>i look forward to that small section##/li>
		##li class='poem line'>of each otherwise solitary day##/li>
		##li class='poem line'>that is devoted just to myself##/li>
		##li class='poem line'>the pleasure, of course, does not compare to that of sex##/li>
		##li class='poem line'>but is a pleasure nonetheless##/li>
		##li class='poem line'>perhaps in another poem i will attempt to describe the thrill of erection##/li>
		##li class='poem line'>the rightness of slippery friction##/li>
		##li class='poem line'>the mounting tingling that marks the path to orgasm##/li>
		##li class='poem line'>the joy of contraction and emission##/li>
		##li class='poem line'>the peace of rest##/li>
		##li class='poem line'>i will tell you of all that and more##/li>
		##li class='poem line'>but that is not what this poem is about, is it, you horny toad you?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>now the final analysis:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>by admitting to and claiming joy in##/li>
		##li class='poem line'>something that almost all men hide##/li>
		##li class='poem line'>and that many women are unimpressed with##/li>
		##li class='poem line'>i have made this poem shocking##/li>
		##li class='poem line'>you will see yourselves in this poem##/li>
		##li class='poem line'>and either agree or reject##/li>
		##li class='poem line'>it doesn't matter, you are affected##/li>
		##li class='poem line'>you, reader/listener, must grant me the credit##/li>
		##li class='poem line'>that I am, in spite of my manhood,##/li>
		##li class='poem line'>admitting to what i should deny, or at least hide##/li>
		##li class='poem line'>i won't pretend this is easy##/li>
		##li class='poem line'>but it must be done##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the question now is##/li>
		##li class='poem line'>am i talking about poetry or masturbation?##/li>
	##/ul>
##/article>";