<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Reflection##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about not being able to write a poem##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>perhaps this might be a left-brain poem##/li>
		##li class='poem line'>is that you, right-brain?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>We need to talk.##/li>
		##li class='poem line'>without you i have nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i've spent the whole day thinking##/li>
		##li class='poem line'>i have laid hands on this keyboard##/li>
		##li class='poem line'>over and over##/li>
		##li class='poem line'>and gotten nowhere##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the first thing to do##/li>
		##li class='poem line'>with writer's block##/li>
		##li class='poem line'>is to write about writer's block##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>therefore, this is a poem about writer's block##/li>
		##li class='poem line'>i could stop now and the poem would be complete##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>no it wouldn't be##/li>
		##li class='poem line'>why not?##/li>
		##li class='poem line'>because a poem about not being able to write a poem##/li>
		##li class='poem line'>is a boring poem##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>then this is not a poem about not being able to write a poem##/li>
		##li class='poem line'>it is a poem about being able to write a poem when you can't write a poem##/li>
		##li class='poem line'>it has an interesting mechanism##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>yes, it does##/li>
		##li class='poem line'>it purports to be a conversation between the two halves of a brain, which is struggling to write a poem##/li>
		##li class='poem line'>why is the brain struggling to write a poem?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>because it is the brain of a poet, ##/li>
		##li class='poem line'>and a poem gives meaning to the thought processes of the poet##/li>
		##li class='poem line'>so the brain has no meaning without a poem?##/li>
		##li class='poem line'>the perception of the brain, measured in measures of self-esteem##/li>
		##li class='poem line'>requires that the poet do poetry##/li>
		##li class='poem line'>we call this meaning##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so if the poet writes a poem about not being able to write a poem##/li>
		##li class='poem line'>that turns into a dialogue between the two halves of his brain##/li>
		##li class='poem line'>which are discussing the poet's ability to give meaning to the poet##/li>
		##li class='poem line'>then the poet has given himself meaning?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that is more or less what i am saying##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>who are you?##/li>
		##li class='poem line'>i forget...when we think so much i lose track of which of us is talking##/li>
		##li class='poem line'>maybe we are both talking,##/li>
		##li class='poem line'>maybe we speak with a single voice and are only pretending to be two halves in order to provide a mechanism to lend interest to the poem which is now about the meaning of the poet##/li>
		##li class='poem line'>precisely##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>so is this a good poem?##/li>
		##li class='poem line'>it is not##/li>
		##li class='poem line'>why is it not a good poem?##/li>
		##li class='poem line'>because a poem must be about something##/li>
		##li class='poem line'>i dispute that##/li>
		##li class='poem line'>why do i slash you dispute that?##/li>
		##li class='poem line'>because perhaps a poem is about the words,##/li>
		##li class='poem line'>not the meaning of the words##/li>
		##li class='poem line'>so a poem does not have to be about the meaning of the words to be a good poem?##/li>
		##li class='poem line'>no##/li>
		##li class='poem line'>so this, a poem which is about the meaning of the meaning of the words lending meaning to the poet##/li>
		##li class='poem line'>is not a good poem?##/li>
		##li class='poem line'>no##/li>
		##li class='poem line'>then what is wrong with this poem?##/li>
		##li class='poem line'>because it is so reflexive that the meaning has been obscured##/li>
		##li class='poem line'>no, the meaning is that a poem must be about something to be meaningful##/li>
		##li class='poem line'>what about sound poetry? do those noises have meaning?##/li>
		##li class='poem line'>yes they do##/li>
		##li class='poem line'>so a sound poem can be a good poem?##/li>
		##li class='poem line'>if you speak the language##/li>
		##li class='poem line'>who speaks the language?##/li>
		##li class='poem line'>nobody##/li>
		##li class='poem line'>so how can it be a good poem?##/li>
		##li class='poem line'>it can't##/li>
		##li class='poem line'>is this a sound poem then?##/li>
		##li class='poem line'>it is if the meaning of the words that are about the words that lend meaning to the poet are so obscure as to be meaningless##/li>
		##li class='poem line'>are these words so obscure that they are meaningless then?##/li>
		##li class='poem line'>they just may be##/li>
		##li class='poem line'>then why have i slash you slash we written them?##/li>
		##li class='poem line'>because we needed to write a poem##/li>
		##li class='poem line'>and it is easiest when you can't write a poem##/li>
		##li class='poem line'>to write a poem about not writing a poem##/li>
		##li class='poem line'>and then let the poem turn into a poem about the meaning of the poem##/li>
		##li class='poem line'>which is what this poem is about##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>at first this poem was about not being able to write a poem##/li>
		##li class='poem line'>now it is a poem about having written a poem about being able to write a poem that gives meaning to the poet##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>can i have some ice cream?##/li>
		
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'> ##/li>
	##/ul>
##/article>";