<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Plumbing##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the techniques of creating poetry##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i use a computer##/li>
		##li class='poem line'>a strange little box##/li>
		##li class='poem line'>i poke my little buttons with the arcane rhythms##/li>
		##li class='poem line'>of the adept##/li>
		##li class='poem line'>my poetry, aided by speed##/li>
		##li class='poem line'>therefore matches (i hope)##/li>
		##li class='poem line'>the contours of the human voice##/li>
		##li class='poem line'>while containing the humours of music##/li>
		##li class='poem line'>i could not do this with a pen##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>as i speak##/li>
		##li class='poem line'>my lips are not moving at all##/li>
		##li class='poem line'>i have learned to speak through my fingers##/li>
		##li class='poem line'>to listen to myself with my eyes##/li>
		##li class='poem line'>speech, therefore, has become##/li>
		##li class='poem line'>a multisensual activity##/li>
		##li class='poem line'>it is through the dance of my hands##/li>
		##li class='poem line'>that the rhythms are maintained##/li>
		##li class='poem line'>it could be said##/li>
		##li class='poem line'>that the rhythm##/li>
		##li class='poem line'>is the rhythm of the blood, the nerves, the muscles and the mind##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i could alter this##/li>
		##li class='poem line'>methodology by##/li>
		##li class='poem line'>simply go##/li>
		##li class='poem line'>ing back over this##/li>
		##li class='poem line'>verse and cutting the##/li>
		##li class='poem line'>lines in different##/li>
		##li class='poem line'>places.  this creates a##/li>
		##li class='poem line'>broken and##/li>
		##li class='poem line'>jagged rhythm of##/li>
		##li class='poem line'>which i am not##/li>
		##li class='poem line'>fond.  this is##/li>
		##li class='poem line'>especially easy with the##/li>
		##li class='poem line'>sophisticated software with##/li>
		##li class='poem line'>which i create my opi.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>opi?##/li>
		##li class='poem line'>my computer tells me that there##/li>
		##li class='poem line'>is no word opi##/li>
		##li class='poem line'>can your pen do that?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>if i don't like what i have done##/li>
		##li class='poem line'>it requires very little work to repair it to my##/li>
		##li class='poem line'>to my satisfaction##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for instance##/li>
		##li class='poem line'>i could alter this methodology##/li>
		##li class='poem line'>by simply going back over this verse##/li>
		##li class='poem line'>and cutting the lines in different places.##/li>
		##li class='poem line'>this creates a smoother and more comfortable rhythm##/li>
		##li class='poem line'>of which i am fond.##/li>
		##li class='poem line'>this is the work of a few seconds##/li>
		##li class='poem line'>with the sophisticated software##/li>
		##li class='poem line'>with which i create my opuses.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is not an assumption of superiority##/li>
		##li class='poem line'>ok it is##/li>
		##li class='poem line'>no wait, it isn't##/li>
		##li class='poem line'>i can make arguments for both sides##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>composing poetry longhand##/li>
		##li class='poem line'>forces more reflection on any single word##/li>
		##li class='poem line'>more intense thought on each line##/li>
		##li class='poem line'>a more technical and studied approach to wordsmithy##/li>
		##li class='poem line'>on the other hand, it means that errors or misjudgements##/li>
		##li class='poem line'>are less often corrected##/li>
		##li class='poem line'>and grander revisions harder to make##/li>
		##li class='poem line'>and therefore less likely##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there was a long, long time##/li>
		##li class='poem line'>when poetry was only oral##/li>
		##li class='poem line'>when words were passed down only by memory##/li>
		##li class='poem line'>change in the stories and songs##/li>
		##li class='poem line'>happened organically##/li>
		##li class='poem line'>mistakes and revisions were passed down##/li>
		##li class='poem line'>and the stories and epic poems grew ##/li>
		##li class='poem line'>- there are stories 10 000 years old -##/li>
		##li class='poem line'>when writing was invented##/li>
		##li class='poem line'>poems took a long time to make the jump##/li>
		##li class='poem line'>poets took a back seat to accountants and phony historians##/li>
		##li class='poem line'>but once we climbed aboard the bandwagon##/li>
		##li class='poem line'>we took pride of place.##/li>
		##li class='poem line'>poor poets##/li>
		##li class='poem line'>history slaps us in the face again##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the quill##/li>
		##li class='poem line'>was a great leap forward##/li>
		##li class='poem line'>ink and paper are still the choice of millions of invisible wordsmiths##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i used to write that way##/li>
		##li class='poem line'>but my hands disliked it##/li>
		##li class='poem line'>i only did it because the technology was out of my league##/li>
		##li class='poem line'>once i made the jump##/li>
		##li class='poem line'>i had jumped for good##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i am sure##/li>
		##li class='poem line'>that there are purists##/li>
		##li class='poem line'>who will tell you that the only way##/li>
		##li class='poem line'>to write a great poem##/li>
		##li class='poem line'>is by hand##/li>
		##li class='poem line'>this is like saying##/li>
		##li class='poem line'>that the only way to paint a great painting##/li>
		##li class='poem line'>is with a natural brush##/li>
		##li class='poem line'>or that the only way to have sex##/li>
		##li class='poem line'>is with a natural lubricant##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>because i type swiftly##/li>
		##li class='poem line'>and my words are recorded naturally##/li>
		##li class='poem line'>my poetry is very oral##/li>
		##li class='poem line'>the voice in my head##/li>
		##li class='poem line'>is the voice with which i would say these lines##/li>
		##li class='poem line'>by speeding up the process of writing##/li>
		##li class='poem line'>i have brought poetry full-circle##/li>
		##li class='poem line'>finally and firmly marrying##/li>
		##li class='poem line'>the verbal and the written##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i hope##/li>
		##li class='poem line'>that the tickling of my keyboard##/li>
		##li class='poem line'>with the fingers##/li>
		##li class='poem line'>connected to the nerves##/li>
		##li class='poem line'>connected to my brain##/li>
		##li class='poem line'>connected to my voice##/li>
		##li class='poem line'>will resonate with your internal voice##/li>
		##li class='poem line'>and that we will##/li>
		##li class='poem line'>for just a moment##/li>
		##li class='poem line'>be truly one##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>failing that, just give me some money##/li>
		##li class='poem line'>poetry is great, but the pay is terrible##/li>
	##/ul>
##/article>";