<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The Deconstructionist's Conundrum##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem that i write in my head##/li>
		##li class='poem line'>that is meant to be read aloud##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the problem, you see##/li>
		##li class='poem line'>is that the poem in my head##/li>
		##li class='poem line'>which is presently in my hands##/li>
		##li class='poem line'>is not the poem i wish to read aloud##/li>
		##li class='poem line'>it has changed with the act of transcription##/li>
		##li class='poem line'>from head to hands##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>nor, i might add, he said to himself##/li>
		##li class='poem line'>is it even the poem i wrote, ##/li>
		##li class='poem line'>and by wrote i mean heard, in my head##/li>
		##li class='poem line'>before i started writing it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>		it's hard to be the Midnight Deconstructionist##/li>
		##li class='poem line'>		but don't feel sorry for me##/li>
		##li class='poem line'>		i chose this life##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>these##/li>
		##li class='poem line'>are black dots on a white screen##/li>
		##li class='poem line'>or black lines on a sheet of paper##/li>
		##li class='poem line'>while these are ringing tones that compete with the music##/li>
		##li class='poem line'>ever present in my mind##/li>
		##li class='poem line'>oh wait, i'm listening to the radio, silly me##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the problem, you see##/li>
		##li class='poem line'>is that i speak the poem internally##/li>
		##li class='poem line'>i don't write it on the blackboard of my brain##/li>
		##li class='poem line'>i save that for making grocery lists##/li>
		##li class='poem line'>this poem##/li>
		##li class='poem line'>is meant to be read aloud to you##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>(oh wait, i am reading it aloud)##/li>
		##li class='poem line'>(no, maybe i'm not)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when you raed##/li>
		##li class='poem line'>you here the voice of yourself##/li>
		##li class='poem line'>you talk the worms##/li>
		##li class='poem line'>written poetry, then##/li>
		##li class='poem line'>is never silent,##/li>
		##li class='poem line'>it is always speech.##/li>
		##li class='poem line'>writing is democratic that way##/li>
		##li class='poem line'>where reading is fascist##/li>
		##li class='poem line'>call me a fascist, then##/li>
		##li class='poem line'>i don't care##/li>
		##li class='poem line'>ok, i do##/li>
		##li class='poem line'>no, i don't##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is the problem of written poetry##/li>
		##li class='poem line'>that good poetry is almost always better read aloud##/li>
		##li class='poem line'>so that the voice in our heads##/li>
		##li class='poem line'>mirrors more closely the voice##/li>
		##li class='poem line'>in which it was written##/li>
		##li class='poem line'>on many occasions##/li>
		##li class='poem line'>a poem which i disliked in my head##/li>
		##li class='poem line'>i liked coming from someone else's head, thank you for sharing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this is##/li>
		##li class='poem line'>for##/li>
		##li class='poem line'>instance why i do##/li>
		##li class='poem line'>not use odd line##/li>
		##li class='poem line'>breaks, besides of##/li>
		##li class='poem line'>course, that i find such##/li>
		##li class='poem line'>methodologies somewhat##/li>
		##li class='poem line'>clich&eacute;d##/li>
		##li class='poem line'>i attempt to write in such a way##/li>
		##li class='poem line'>that reading this poem##/li>
		##li class='poem line'>is natural##/li>
		##li class='poem line'>and comfortable##/li>
		##li class='poem line'>and, of course,##/li>
		##li class='poem line'>in the eyes of other poets##/li>
		##li class='poem line'>old-fashioned and clich&eacute;d##/li>
		##li class='poem line'>it's a clich&eacute;-eat-clich&eacute; world out there##/li>
		##li class='poem line'>but i make concessions##/li>
		##li class='poem line'>i use punctuation sparingly##/li>
		##li class='poem line'>so you may choose for yourselves##/li>
		##li class='poem line'>where to end a verse.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>doubtless, i've said all this before##/li>
		##li class='poem line'>however##/li>
		##li class='poem line'>a poem is not usually a method of saying something##/li>
		##li class='poem line'>that has never been said before##/li>
		##li class='poem line'>it is a way of saying something familiar##/li>
		##li class='poem line'>in such a way that it triggers new meaning##/li>
		##li class='poem line'>in the mind of the reader##/li>
		##li class='poem line'>whom, i hope, at the moment that##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>is not a reader##/li>
		##li class='poem line'>but is the listener##/li>
		##li class='poem line'>if you are not##/li>
		##li class='poem line'>then do your best##/li>
		##li class='poem line'>and don't blame me if you don't like it##/li>
	##/ul>
##/article>";