<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Dark ages##/h2>##/li>
		##li class='poem line'>it is not new, the dark ages##/li>
		##li class='poem line'>when a window opens, a wind blows through##/li>
		##li class='poem line'>when closed, the wind rattles the pane##/li>
		##li class='poem line'>disturbs our painless sleep##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I am twenty at forty##/li>
		##li class='poem line'>as pink and unlearned as any man##/li>
		##li class='poem line'>I am tempted to tell you##/li>
		##li class='poem line'>that I am yours, but a step##/li>
		##li class='poem line'>is not a journey, and many steps##/li>
		##li class='poem line'>is also not a journey##/li>
		##li class='poem line'>a journey must have a first step, passage##/li>
		##li class='poem line'>and destination##/li>
		##li class='poem line'>I have the beginning, I claim##/li>
		##li class='poem line'>the middle##/li>
		##li class='poem line'>but I am unsure of my end##/li>
		##li class='poem line'>save that I know it is night##/li>
		##li class='poem line'>and that you wait there for me##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>rain on the window, of which we spoke##/li>
		##li class='poem line'>what is there to say?
the branch that scrapes,##/li>
		##li class='poem line'>fingernails on a blackboard##/li>
		##li class='poem line'>against the chill pane##/li>
		##li class='poem line'>has said it already##/li>
		##li class='poem line'>get out and find love##/li>
		##li class='poem line'>do greatness, do honour##/li>
		##li class='poem line'>but I am warm here, and not wanting##/li>
		##li class='poem line'>and there is nothing to converse with##/li>
		##li class='poem line'>save the inanimate,##/li>
		##li class='poem line'>the droplets that descend,##/li>
		##li class='poem line'>one moment/distance at a time##/li>
		##li class='poem line'>seeking the centre of this branded earth##/li>
		##li class='poem line'>can we not all heed this call?##/li>
		##li class='poem line'>go down and down, finding##/li>
		##li class='poem line'>a level, equilibrium like a bedspring##/li>
		##li class='poem line'>holding one##/li>
		##li class='poem line'>deep in place, without pressure##/li>
		##li class='poem line'>without complaint##/li>
		##li class='poem line'>be a raindrop, says my goofy inner voice##/li>
		##li class='poem line'>love gravity, find a place in living cells##/li>
		##li class='poem line'>there is always further down to go, but not for you##/li>
		##li class='poem line'>the earth is greedy, but needs you not##/li>
		##li class='poem line'>will let you rest, finally##/li>
		##li class='poem line'>where your density is matched##/li>
		##li class='poem line'>by the soil beneath you##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>welcome to the dark ages##/li>
		##li class='poem line'>get out and vote!##/li>
		##li class='poem line'>in a time of a million lights##/li>
		##li class='poem line'>we must look under rocks for inspiration##/li>
		##li class='poem line'>this earth is heavy with us##/li>
		##li class='poem line'>if we all jumped together##/li>
		##li class='poem line'>the sun would move##/li>
		##li class='poem line'>we have such power, we individuated souls##/li>
		##li class='poem line'>I never take off my hat##/li>
		##li class='poem line'>never let the light into my eyes##/li>
		##li class='poem line'>never let god see my bald spot##/li>
		##li class='poem line'>I reach, stupid##/li>
		##li class='poem line'>into a pocket of nothing##/li>
		##li class='poem line'>looking for my keys, finding lint and foolishness ##/li>
		##li class='poem line'>let your voice be heard!##/li>
		##li class='poem line'>says the one who will ignore you##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I am so lonely##/li>
		##li class='poem line'>I have places that have never been caressed##/li>
		##li class='poem line'>how can this be? I followed##/li>
		##li class='poem line'>all the instructions##/li>
		##li class='poem line'>inserted knob a into slot b##/li>
		##li class='poem line'>attached lever c to the great red wedge##/li>
		##li class='poem line'>I can move the whole earth now##/li>
		##li class='poem line'>and not reach the one thing I desire##/li>
		##li class='poem line'>don't read the news##/li>
		##li class='poem line'>don't heed the radio##/li>
		##li class='poem line'>I bury my head in speed and silence##/li>
		##li class='poem line'>dream of you, surrounded by haze and indifference##/li>
		##li class='poem line'>and only you, why not?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the sun is gone now,##/li>
		##li class='poem line'>the coffee is drunk or cold##/li>
		##li class='poem line'>I could play checkers on the floor##/li>
		##li class='poem line'>or dance to dead Sinatra##/li>
		##li class='poem line'>but I choose instead to watch steam rising##/li>
		##li class='poem line'>bubbles bursting in boiling water##/li>
		##li class='poem line'>it's too late to see clouds##/li>
		##li class='poem line'>and I know that there are no stars,##/li>
		##li class='poem line'>have never been stars##/li>
		##li class='poem line'>have never been moon or comets or flaking rock##/li>
		##li class='poem line'>my hands are so sore##/li>
		##li class='poem line'>I've been using them too much##/li>
		##li class='poem line'>time to rest now (why,##/li>
		##li class='poem line'>I've been resting all day?##/li>
		##li class='poem line'>because doing nothing is hard work,##/li>
		##li class='poem line'>and you have to take it easy##/li>
		##li class='poem line'>when nothing is done.)##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>ok, I lied##/li>
		##li class='poem line'>I don't welcome you##/li>
		##li class='poem line'>and these aren't the dark ages##/li>
		##li class='poem line'>they are simply a time of fog##/li>
		##li class='poem line'>when we navigate by radar##/li>
		##li class='poem line'>blips on a monitor##/li>
		##li class='poem line'>and only touch what has the courage##/li>
		##li class='poem line'>to touch us first##/li>
	##/ul>
##/article>";