<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>The deconstructionist's triumph##/h2>##/li>
		##li class='poem line'>this is a poem##/li>
		##li class='poem line'>it is a poem about the poetic prerogative##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for now, let me speak##/li>
		##li class='poem line'>without artifice or obscurity.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>hmm...um...##/li>
		##li class='poem line'>er...uh...sorry.##/li>
		##li class='poem line'>i just can't do it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>Why? because##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there are things known only to me##/li>
		##li class='poem line'>and maybe everybody else##/li>
		##li class='poem line'>for which science has no naming##/li>
		##li class='poem line'>there are things described only with poetry##/li>
		##li class='poem line'>the necessity of poetry is just one of them##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>there is no science to the meaning of life##/li>
		##li class='poem line'>or the subtle nature of reality##/li>
		##li class='poem line'>there is no clear logic##/li>
		##li class='poem line'>that holds the code of consciousness##/li>
		##li class='poem line'>this is the realm of art##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>I could rewrite the above thus:##/li>
		##li class='poem line'>There is no science to the meaning of life, no describable juxtaposition of elements or  mathematically legitimate concatenation of well-known linguistic axioms which will expose logically the subtle nature of reality.  Such things are best left to the creative imagination and intuition of the artist to explore and communicate;##/li>
		##li class='poem line'>but I won't, because it would lose meaning and effect.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>that there is ambiguity##/li>
		##li class='poem line'>is the key to understanding##/li>
		##li class='poem line'>that there is intuition##/li>
		##li class='poem line'>is the capstone of clarity##/li>
		##li class='poem line'>and freedom is their witness##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>when science is at its deepest##/li>
		##li class='poem line'>it is indistinguishable from art##/li>
		##li class='poem line'>to describe the deepest underpinnings of our Us##/li>
		##li class='poem line'>can only be done with picture and metaphor##/li>
		##li class='poem line'>let me give you an example:##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>where water meets air is the meeting of two oceans##/li>
		##li class='poem line'>neither of which is more or less real than anything you can imagine##/li>
		##li class='poem line'>and where consciousness meets substance##/li>
		##li class='poem line'>is the meeting of two oceans both of which are more real##/li>
		##li class='poem line'>than anything you can know##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the above is a poetic truth which describes a literal one##/li>
		##li class='poem line'>allow me a momentary departure:##/li>
		##li class='poem line'>we live in a soup of tiny strings##/li>
		##li class='poem line'>this is mathematically elegant##/li>
		##li class='poem line'>but means nothing to most of us##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but when i tell you that we live in an ocean##/li>
		##li class='poem line'>with neither surface nor bottom##/li>
		##li class='poem line'>where the swirling of infinitesimals##/li>
		##li class='poem line'>is the substance of the infinite##/li>
		##li class='poem line'>and the twist of consciousness##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it changes you, like it or not##/li>
		##li class='poem line'>you have learned no math##/li>
		##li class='poem line'>but you have leaned out of the window##/li>
		##li class='poem line'>glimpsed the impossible##/li>
		##li class='poem line'>and made it possible##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for in an infinite universe##/li>
		##li class='poem line'>among an infinite number of universes##/li>
		##li class='poem line'>whatever you can imagine##/li>
		##li class='poem line'>is out there somewhere##/li>
		##li class='poem line'>and you don't know the smallest fraction of it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i could have written all this as an essay##/li>
		##li class='poem line'>with unambiguous punctuation and unbroken lines##/li>
		##li class='poem line'>i could have capitalized and italicized##/li>
		##li class='poem line'>i could have made it square, and solid, and formal##/li>
		##li class='poem line'>and you would not have read it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>it is not for nothing##/li>
		##li class='poem line'>that the greatest poem in history##/li>
		##li class='poem line'>begins with the greatest contradiction in language##/li>
		##li class='poem line'>the way that can be named is not the way##/li>
		##li class='poem line'>nevertheless I have named it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i call it water (see Spring)##/li>
	##/ul>
##/article>";