<?php

namespace raingarden\rg_content\rg_poems\rg_a_to_f;
$the_html = "##article class='poem'>
	##ul class='poem body'>
		##li class='poem title'>##h2##article class='poem'>Fear##/h2>##/li>
		##li class='poem line'>1.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fear is in the belly##/li>
		##li class='poem line'>the grip of an unforgiving hand##/li>
		##li class='poem line'>squeezing the entrails##/li>
		##li class='poem line'>trying to push you out of yourself##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fear is in the brain##/li>
		##li class='poem line'>the clouds that wrap the hippocampus##/li>
		##li class='poem line'>in a night always waiting##/li>
		##li class='poem line'>to push back the dawn##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fear is in the chest##/li>
		##li class='poem line'>the weight of an ocean##/li>
		##li class='poem line'>crushing air from the lungs##/li>
		##li class='poem line'>an iron fist around the heart##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>2.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>two fears live in me##/li>
		##li class='poem line'>lodged in my soul##/li>
		##li class='poem line'>like a virus in the spine:##/li>
		##li class='poem line'>herpes of the mind##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>a darkened box##/li>
		##li class='poem line'>sets fire the medulla##/li>
		##li class='poem line'>in my reptilian core##/li>
		##li class='poem line'>i  know how a lizard feels in a concrete hole##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the other##/li>
		##li class='poem line'>binds me to the intangible##/li>
		##li class='poem line'>i am a victim of nothing##/li>
		##li class='poem line'>a sensual, palpable, nothing##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>3.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>my death##/li>
		##li class='poem line'>doesn't disturb me##/li>
		##li class='poem line'>a short passage from here to not##/li>
		##li class='poem line'>how could i care?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i could flee from life.##/li>
		##li class='poem line'>find a desert island##/li>
		##li class='poem line'>a last remnant, final##/li>
		##li class='poem line'>a dot on the barren horizon##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>but my island is here##/li>
		##li class='poem line'>between chair and table##/li>
		##li class='poem line'>i serve myself dinner##/li>
		##li class='poem line'>reheat coffee##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>4. ##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>i was king for ten minutes##/li>
		##li class='poem line'>and no one knew but me##/li>
		##li class='poem line'>i was a pauper without a song##/li>
		##li class='poem line'>and the crowds closed around me##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>for a brief time##/li>
		##li class='poem line'>all the flags were pointing##/li>
		##li class='poem line'>saying here's the guy##/li>
		##li class='poem line'>he has a voice, you know##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the wind has long since changed##/li>
		##li class='poem line'>i'm back in my chair##/li>
		##li class='poem line'>still, ten invisible minutes##/li>
		##li class='poem line'>is better than leftovers##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>5.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>ok, i woke up this morning##/li>
		##li class='poem line'>chose a head for the day##/li>
		##li class='poem line'>actually, it chose me##/li>
		##li class='poem line'>but that's a clich&eacute;, and i was avoiding it##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>this head is uncombed, unshaven##/li>
		##li class='poem line'>that's good enough, i don't##/li>
		##li class='poem line'>look at myself in mirrors##/li>
		##li class='poem line'>why bring up issues?##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>the sleeping dog##/li>
		##li class='poem line'>at the foot of the stairs##/li>
		##li class='poem line'>bit me on the ass yesterday##/li>
		##li class='poem line'>today i step over without waking him##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>6.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fear is in the hands##/li>
		##li class='poem line'>you raise them to your face##/li>
		##li class='poem line'>sacrificing touch for vision##/li>
		##li class='poem line'>turning away bullets with chips of bone##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fear is in the eyes##/li>
		##li class='poem line'>tight shut##/li>
		##li class='poem line'>against the brightness##/li>
		##li class='poem line'>that is the fire you loathe##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fear is in the gonads##/li>
		##li class='poem line'>the organs that cannot abide##/li>
		##li class='poem line'>the 10 000 nights##/li>
		##li class='poem line'>i spend alone##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>7.##/li>
		##li class='poem line'>&nbsp;##/li>
		##li class='poem line'>fear is in the mind##/li>
		##li class='poem line'>the future, stretching out unending##/li>
	##/ul>
##/article>";